import test from 'node:test';import assert from 'node:assert/strict';
import {ProjectStore} from '../store.js';import {starterProject} from '../authoring/starter.js';import {applyCommand} from '../fx/commands.js';import {validateProject} from '../runtime.js';
import {entityPacket,readEntityPacket,instantiateEntity,validateEntityLibrary} from './definitions.js';
const definition={id:'Motion',name:'Motion',schema:{type:'object',properties:{speed:{type:'number',minimum:0,maximum:20},enabled:{type:'boolean'},direction:{type:'array',items:{type:'number'},minItems:2,maxItems:2},mode:{type:'string',enum:['walk','fly']}},required:['speed','enabled','direction','mode'],additionalProperties:false},defaults:{speed:3,enabled:true,direction:[1,0],mode:'walk'}};
function setup(){const s=new ProjectStore(starterProject()),run=c=>s.edit(p=>applyCommand(p,c));run({op:'component.define',value:definition});run({op:'entity.create',id:'traveller',name:'Traveller'});run({op:'entity.assign',id:'traveller',component:'Motion'});return{s,run}}
test('generic components author, save and export without game or scene data',()=>{const {s,run}=setup();run({op:'entity.values',id:'traveller',component:'Motion',value:{...definition.defaults,speed:7}});const p=validateProject(JSON.parse(JSON.stringify(s.project)));assert.deepEqual(p.entityDefinitions,s.project.entityDefinitions);const packet=entityPacket(p);assert.equal(packet.format,'shapeshift-entities');assert.deepEqual(instantiateEntity(packet,'traveller'),{Motion:{...definition.defaults,speed:7}});assert.equal(packet.game,undefined)});
test('duplicate entities and runtime instances own their values',()=>{const {s,run}=setup();run({op:'entity.duplicate',id:'traveller',newId:'other'});run({op:'entity.values',id:'other',component:'Motion',value:{...definition.defaults,direction:[0,1]}});assert.deepEqual(s.project.entityDefinitions.entities[0].components.Motion.direction,[1,0]);const packet=entityPacket(s.project),a=instantiateEntity(packet,'traveller');a.Motion.direction[0]=99;assert.equal(instantiateEntity(packet,'traveller').Motion.direction[0],1)});
test('failed values/schema edits/imports are atomic and do not damage undo history',()=>{const {s,run}=setup(),before=JSON.stringify(s.project),n=s.undoStack.length;for(const value of [{...definition.defaults,speed:-1},{...definition.defaults,enabled:'yes'},{...definition.defaults,direction:[1]},{...definition.defaults,mode:'swim'}]){assert.throws(()=>run({op:'entity.values',id:'traveller',component:'Motion',value}));assert.equal(JSON.stringify(s.project),before)}assert.throws(()=>run({op:'component.define',value:{...definition,schema:{type:'string'},defaults:''}}));assert.throws(()=>run({op:'component.remove',id:'Motion'}));assert.throws(()=>run({op:'entity.import',value:{format:'shapeshift-entities',version:2,components:[],entities:[]}}));assert.equal(s.undoStack.length,n);assert.equal(JSON.stringify(s.project),before)});
test('detach/delete and imported libraries are undoable and redoable',()=>{const {s,run}=setup();run({op:'entity.detach',id:'traveller',component:'Motion'});assert.deepEqual(s.project.entityDefinitions.entities[0].components,{});s.undo();assert.ok(s.project.entityDefinitions.entities[0].components.Motion);s.redo();run({op:'entity.remove',id:'traveller'});s.undo();assert.equal(s.project.entityDefinitions.entities.length,1);const packet=entityPacket(s.project);run({op:'entity.import',value:{format:'shapeshift-entities',version:1,components:[],entities:[]}});s.undo();assert.deepEqual(entityPacket(s.project),packet)});
test('default edits apply only to subsequent assignments',()=>{const {s,run}=setup();run({op:'component.define',value:{...definition,defaults:{...definition.defaults,speed:9}}});assert.equal(s.project.entityDefinitions.entities[0].components.Motion.speed,3);run({op:'entity.create',id:'new'});run({op:'entity.assign',id:'new',component:'Motion'});assert.equal(s.project.entityDefinitions.entities[1].components.Motion.speed,9)});
test('legacy projects without definitions round trip and reject malicious or unsupported schemas',()=>{const old=starterProject();assert.equal(validateProject(old).entityDefinitions,undefined);assert.deepEqual(readEntityPacket(entityPacket(old)),{version:1,components:[],entities:[]});for(const schema of [{type:'object',$ref:'https://invalid.test'},{type:'number',minimum:5,maximum:1},{type:'array'},{type:'object',required:['missing']}])assert.throws(()=>validateEntityLibrary({version:1,components:[{id:'Test',schema,defaults:{}}],entities:[]}));const p=JSON.parse('{"format":"shapeshift-entities","version":1,"components":[],"entities":[],"__proto__":{"bad":true}}');assert.throws(()=>readEntityPacket(p));assert.equal({}.bad,undefined)});
