import {entityPacket} from './definitions.js';
import {referenceIssues} from '../references/catalog.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({version:1,components:[],entities:[]});
export function mountEntities({project,dispatch,revision,toast,download,references=()=>null}){
 const button=document.createElement('button');button.id='entities-open';button.textContent='Entities';document.querySelector('.top-actions').append(button);
 const panel=document.createElement('aside');panel.id='entities-panel';panel.className='author-panel';panel.hidden=true;panel.setAttribute('aria-label','Entity definitions');document.body.append(panel);
 const style=document.createElement('style');style.textContent='#entities-panel fieldset{display:block;margin:12px 0;padding:12px}#entities-panel .entity-field{margin:0 0 12px}#entities-panel .entity-field label{display:flex;flex-direction:column;gap:5px}#entities-panel details{margin:12px 0}#entities-panel textarea{width:100%;box-sizing:border-box}#entities-panel [type=checkbox]{align-self:flex-start;width:auto}#entities-panel [data-component]>.entity-field:last-of-type{margin-bottom:0}';document.head.append(style);
 let tab='entities',selected=null,component=null,stamp=-1;
 const library=()=>project().entityDefinitions??blank();
 const unique=(list,base)=>{let s=base,n=2;while(list.some(d=>d.id===s))s=base+'-'+n++;return s};
 const run=c=>{try{dispatch(c);stamp=-1;render();return true}catch(e){toast(e.message,true);return false}};
 const options=(list,value)=>list.map(d=>`<option value="${esc(d.id)}" ${d.id===value?'selected':''}>${esc(d.name??d.id)} (${esc(d.id)})</option>`).join('');
 function fields(value,s,path=[]){
  if(s.type==='object')return Object.entries(value).map(([key,v])=>{const def=s.properties?.[key]??{type:Array.isArray(v)?'array':v===null?'null':typeof v};return `<div class="entity-field"><label>${esc(def.title??key)}${def.description?`<small>${esc(def.description)}</small>`:''}${fields(v,def,[...path,key])}</label></div>`}).join('')||'<small>No fields. Edit component values JSON to add fields.</small>';
  const attr=`data-value-path="${esc(JSON.stringify(path))}" data-value-type="${s.type}"`;
  if(s.reference)return `<div class="button-row"><input ${attr} data-reference="${esc(JSON.stringify(s.reference))}" value="${esc(value)}" placeholder="Unassigned"><button data-pick-ref data-path="${esc(JSON.stringify(path))}" data-spec="${esc(JSON.stringify(s.reference))}">Choose…</button><button data-open-ref data-ref="${esc(JSON.stringify({...s.reference,id:value}))}" ${value?'':'disabled'}>Open</button></div>`;
  if(s.enum)return `<select ${attr} data-enum="${esc(JSON.stringify(s.enum))}">${s.enum.map((v,i)=>`<option value="${i}" ${JSON.stringify(v)===JSON.stringify(value)?'selected':''}>${esc(String(v))}</option>`).join('')}</select>`;
  if(s.type==='boolean')return `<input ${attr} type="checkbox" ${value?'checked':''}>`;
  if(s.type==='array'&&s.items?.reference)return value.map((v,i)=>`<div class="entity-field"><small>Item ${i+1}</small>${fields(v,s.items,[...path,i])}</div>`).join('');
  if(['array','null'].includes(s.type))return `<textarea ${attr} rows="3" spellcheck="false">${esc(JSON.stringify(value,null,2))}</textarea>`;
  return `<input ${attr} type="${['number','integer'].includes(s.type)?'number':'text'}" ${s.type==='integer'?'step="1"':'step="any"'} ${s.minimum!==undefined?`min="${s.minimum}"`:''} ${s.maximum!==undefined?`max="${s.maximum}"`:''} value="${esc(value)}">`;
 }
 function render(){
  if(panel.hidden||stamp===revision())return;stamp=revision();const l=library();selected=l.entities.some(d=>d.id===selected)?selected:l.entities[0]?.id;component=l.components.some(d=>d.id===component)?component:l.components[0]?.id;
  const e=l.entities.find(d=>d.id===selected),c=l.components.find(d=>d.id===component),available=l.components.filter(d=>!e||!Object.hasOwn(e.components,d.id));
  panel.innerHTML=`<header><strong>Entity definitions</strong><button data-close aria-label="Close entities">×</button></header><div class="button-row"><button data-tab="entities" aria-pressed="${tab==='entities'}">Entities</button><button data-tab="components" aria-pressed="${tab==='components'}">Components</button></div>
   <div class="button-row"><button data-export>Export JSON</button><button data-import>Import JSON</button><label>Import mode<select data-import-mode><option value="merge">Merge definitions</option><option value="replace">Replace library</option></select></label><input hidden data-file type="file" accept=".json,application/json"></div>
   ${tab==='entities'?`<label>Entity<select data-select>${options(l.entities,selected)}</select></label><div class="button-row"><input data-new-entity-id aria-label="New entity ID" placeholder="Entity ID (optional)"><button data-new-entity>New entity</button><button data-duplicate ${e?'':'disabled'}>Duplicate</button><button data-remove-entity ${e?'':'disabled'}>Delete</button></div>${e?`<label>Name<input data-name value="${esc(e.name)}"></label><small>ID: ${esc(e.id)}</small><h3>Components</h3><div class="button-row"><select data-assign-select aria-label="Component to assign">${options(available,null)}</select><button data-assign ${available.length?'':'disabled'}>Assign component</button></div>${!l.components.length?'<p>Define or import components in the Components tab first.</p>':''}${Object.entries(e.components).map(([id,value])=>{const d=l.components.find(c=>c.id===id);return `<fieldset data-component="${esc(id)}"><legend>${esc(d.name??id)} <button data-open-component="${esc(id)}">Edit definition</button></legend>${fields(value,d.schema)}<details><summary>Component values JSON</summary><textarea data-values-json rows="6" spellcheck="false">${esc(JSON.stringify(value,null,2))}</textarea><button data-apply-values>Apply values</button></details><button data-detach>Remove component</button></fieldset>`}).join('')}`:'<p>Create an entity, assign components and edit their values. The consuming game interprets the exported data.</p>'}`:
   `<p>Component definitions are plain JSON: a field schema and default values. No game behaviour runs here.</p><label>Component<select data-component-select>${options(l.components,component)}</select></label><div class="button-row"><input data-new-component-id aria-label="New component ID" placeholder="Component ID (optional)"><button data-new-component>New component</button><button data-remove-component ${c?'':'disabled'}>Delete</button></div>${c?`<label>Name<input data-component-name value="${esc(c.name??c.id)}"></label><small>ID: ${esc(c.id)}</small><label>Definition JSON<textarea data-definition rows="20" spellcheck="false">${esc(JSON.stringify(c,null,2))}</textarea></label><button data-apply-definition>Apply definition</button><small>Types: object, array, string, number, integer, boolean, null. Supports properties, required, enums and value/length limits. Schema edits must remain valid for assigned entities.</small>`:''}`}`;
 }
 function read(el){if(el.dataset.enum)return JSON.parse(el.dataset.enum)[+el.value];const type=el.dataset.valueType;if(type==='boolean')return el.checked;if(type==='number'||type==='integer'){if(el.value==='')throw Error('Enter a number');return Number(el.value)}if(type==='array'||type==='null')return JSON.parse(el.value);return el.value}
 panel.onchange=async event=>{const el=event.target;try{
  if(el.hasAttribute('data-file')){const file=el.files[0];if(file){if(file.size>5*1024*1024)throw Error('Entity library must be under 5 MB');if(run({op:'entity.import',mode:panel.querySelector('[data-import-mode]').value,value:JSON.parse(await file.text())})){const count=referenceIssues(project()).length;toast(count?'Imported; '+count+' references need assignment. Open References to review them.':'Definitions imported.')}}return}
  if(el.hasAttribute('data-select')){selected=el.value;stamp=-1;render()}
  else if(el.hasAttribute('data-component-select')){component=el.value;stamp=-1;render()}
  else if(el.hasAttribute('data-name'))run({op:'entity.rename',id:selected,name:el.value});
  else if(el.hasAttribute('data-component-name')){const c=structuredClone(library().components.find(c=>c.id===component));c.name=el.value;run({op:'component.define',value:c})}
  else if(el.hasAttribute('data-value-path')){const id=el.closest('[data-component]').dataset.component,e=library().entities.find(e=>e.id===selected),path=JSON.parse(el.dataset.valuePath);let value=structuredClone(e.components[id]);if(!path.length)value=read(el);else{let parent=value;for(const key of path.slice(0,-1))parent=parent[key];parent[path.at(-1)]=read(el)}if(!run({op:'entity.values',id:selected,component:id,value})){stamp=-1;render()}}
 }catch(e){toast(e.message,true)}};
 panel.onclick=event=>{const el=event.target.closest('button');if(!el)return;try{
  if(el.hasAttribute('data-open-ref')){references()?.open(JSON.parse(el.dataset.ref)).catch(e=>toast(e.message,true));return}
  if(el.hasAttribute('data-open-component')){references()?.open({kind:'component',id:el.dataset.openComponent}).catch(e=>toast(e.message,true));return}
  if(el.hasAttribute('data-pick-ref')){const id=el.closest('[data-component]').dataset.component,path=JSON.parse(el.dataset.path),spec=JSON.parse(el.dataset.spec),entityId=selected;references()?.pick(spec,'',value=>{const entity=library().entities.find(e=>e.id===entityId);if(!entity)throw Error('Entity was removed');let next=structuredClone(entity.components[id]);if(!path.length)next=value;else{let parent=next;for(const key of path.slice(0,-1))parent=parent[key];parent[path.at(-1)]=value}return run({op:'entity.values',id:entityId,component:id,value:next})});return}
  if(el.hasAttribute('data-close')){panel.hidden=true;button.setAttribute('aria-pressed','false');return}
  if(el.dataset.tab){tab=el.dataset.tab;stamp=-1;render()}
  if(el.hasAttribute('data-import'))panel.querySelector('[data-file]').click();
  if(el.hasAttribute('data-export'))download(JSON.stringify(entityPacket(project()),null,2),'entity-definitions.json');
  if(el.hasAttribute('data-new-entity')){selected=panel.querySelector('[data-new-entity-id]').value.trim()||unique(library().entities,'entity');run({op:'entity.create',id:selected,name:'New entity'})}
  if(el.hasAttribute('data-duplicate')){const id=selected;selected=unique(library().entities,id+'-copy');run({op:'entity.duplicate',id,newId:selected})}
  if(el.hasAttribute('data-remove-entity'))run({op:'entity.remove',id:selected});
  if(el.hasAttribute('data-new-component')){component=panel.querySelector('[data-new-component-id]').value.trim()||unique(library().components,'Component');if(library().components.some(c=>c.id===component))throw Error('Component ID already exists');run({op:'component.define',value:{id:component,name:'New component',schema:{type:'object',properties:{value:{type:'number'}},required:['value'],additionalProperties:false},defaults:{value:0}}})}
  if(el.hasAttribute('data-remove-component'))run({op:'component.remove',id:component});
  if(el.hasAttribute('data-apply-definition')){const value=JSON.parse(panel.querySelector('[data-definition]').value);if(value.id!==component)throw Error('Component IDs are stable; create another component to use a different ID');run({op:'component.define',value})}
  if(el.hasAttribute('data-assign'))run({op:'entity.assign',id:selected,component:panel.querySelector('[data-assign-select]').value});
  if(el.hasAttribute('data-detach'))run({op:'entity.detach',id:selected,component:el.closest('[data-component]').dataset.component});
  if(el.hasAttribute('data-apply-values'))run({op:'entity.values',id:selected,component:el.closest('[data-component]').dataset.component,value:JSON.parse(el.closest('details').querySelector('textarea').value)});
 }catch(e){toast(e.message,true)}};
 button.onclick=()=>{panel.hidden=!panel.hidden;button.setAttribute('aria-pressed',String(!panel.hidden));stamp=-1;render()};
 const timer=setInterval(render,120);
 return{hide(){panel.hidden=true;button.setAttribute('aria-pressed','false')},context:()=>({tab,selected,component,scroll:panel.scrollTop,visible:!panel.hidden}),restore(state){tab=state.tab;selected=state.selected;component=state.component;stamp=-1;panel.hidden=!state.visible;button.setAttribute('aria-pressed',String(state.visible));render();panel.scrollTop=state.scroll??0},show(target){if(target){tab=target.kind==='component'?'components':'entities';if(tab==='components')component=target.id;else selected=target.id}panel.hidden=false;button.setAttribute('aria-pressed','true');stamp=-1;render()},snapshot:()=>({tab,selected,component,library:structuredClone(library())}),dispose(){clearInterval(timer);panel.remove();button.remove();style.remove()}};
}
