import {abilityPacket,nativeAbilityBindings} from '../authoring/abilities.js';
import {RELIC_ART_KEYS} from '../integrations/little-gods/relic-art.js';
import {projectGrading} from '../authoring/appearance.js';
import {nativeProject,scenarioFor,RENDER_MODES,EFFECT_KINDS,NATIVE_ACTIONS} from './schema.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const option=(v,label=v)=>`<option value="${esc(v)}">${esc(label)}</option>`;
const defaults={performance:{scenario:'character',seed:1},pose:{motion:'walk',facing:'right',playing:true,carry:''},reaction:{id:'delight',intensity:1,voice:true},sound:{id:'chop'},voice:{variant:'female-v1',clip:'happy',pitch:1,intensity:1},hit:{target:'',kind:'tree',direction:1,shake:true},burst:{position:[0,1,0],count:12},shake:{strength:2,duration:.18},weather:{mode:'rain'},hour:{value:22},camera:{zoom:2.8,target:[0,1,2]},render:{target:'hero',mode:'billboard',kind:'character',scale:[.5,.5,.5]},call:{system:'economy',method:'',args:[]},wish:{index:0,targetData:{kind:'ground',x:0,z:0}},event:{value:{type:'',workerId:0}},freeze:{duration:.045},speed:{value:.5},flash:{target:'',duration:.15,strength:.85}};
export function mountNative({project,dispatch,toast}){
 const panel=document.createElement('section');panel.id='native-studio';panel.hidden=true;document.body.append(panel);
 panel.innerHTML=`<header><div><strong>Preview</strong><small>Integration · Little Gods</small></div><button id="ng-export">Export game data</button><button id="ng-json">Project JSON</button><button id="ng-close">Back to puppet</button></header><div class="ng-layout"><aside class="ng-library"><label>SCENARIO<select id="ng-scenario"></select></label><label>VARIATION<select id="ng-variation"></select></label><div class="ng-row"><button id="ng-new">＋ Scenario</button><button id="ng-new-variation">＋ Variation</button></div><div class="ng-tabs"><button data-ng-tab="assets">Assets</button><button data-ng-tab="reactions">Emotes</button><button data-ng-tab="audio">Audio</button><button data-ng-tab="data">Data</button></div><input id="ng-search" placeholder="Search the library…" aria-label="Search native library"><div id="ng-library-items"></div></aside><section class="ng-center"><div class="ng-settings"><label>Mode<select id="ng-mode"><option value="character">Character study</option><option value="village">Full village</option></select></label><label>Culture<select id="ng-culture"><option value="hearth">Hearth</option><option value="solis">Solis</option><option value="cryos">Cryos</option></select></label><label>Character<select id="ng-character"></select></label><label>Seconds<input id="ng-duration" type="number" min=".1" max="600" step=".1"></label><label>Seed<input id="ng-seed" type="number" min="1" step="1"></label><button id="ng-reload" class="primary">Apply & replay</button><button id="ng-select-artwork" aria-pressed="false">Select artwork</button></div><div id="ng-viewport"><div id="ng-status">Choose a scenario to preview.</div></div><div class="ng-transport"><button id="ng-play">▶ Play</button><button id="ng-restart">↶</button><input id="ng-time" type="range" min="0" max="5" step=".0166667" value="0" aria-label="Preview timeline"><output id="ng-time-label">0.00 s</output><label><input id="ng-audible" type="checkbox" checked> Audio</label></div><div class="ng-timeline-head"><strong>Action timeline</strong><select id="ng-action-type">${NATIVE_ACTIONS.map(v=>option(v)).join('')}</select><button id="ng-add-cue">＋ Add at playhead</button><button id="ng-binding">＋ Event binding</button><button id="ng-capture">Capture state</button></div><div id="ng-timeline"></div></section><aside class="ng-inspector"><h3 id="ng-inspector-title">Authoring</h3><p id="ng-inspector-help">Pick an asset, cue or game definition. Apply & replay rebuilds the same scene from its JSON and seed.</p><div id="ng-fields"></div><label id="ng-json-label">JSON data<textarea id="ng-values" spellcheck="false"></textarea></label><div class="ng-row"><button id="ng-apply" class="primary">Keep changes</button><button id="ng-audition">Audition</button><button id="ng-sound-edit">Sound recipe</button><button id="ng-remove">Remove</button></div><details><summary>Scene objects & integration methods</summary><div id="ng-catalog"></div></details></aside></div>`;
 const $=id=>panel.querySelector('#'+id);let artworkHost,selectedArtwork=null,selectingArtwork=false;let selectedScenario,variation='',tab='assets',selection=null,library,assets,catalog,frame,time=0,playing=false,last=0,loading=0,readyGeneration=0;
 const profile=()=>project().game?{...project().game,...(project().abilities?{abilityLibrary:abilityPacket(project()),abilityPresentation:nativeAbilityBindings(project())}:{}),grading:{...projectGrading(project()),preset:'neutral'}}:undefined,scenario=()=>scenarioFor(profile(),selectedScenario,variation);
 const guard=fn=>async(...args)=>{try{return await fn(...args);}catch(e){toast(e.message,true);$('ng-status')?.replaceChildren(document.createTextNode(e.message));}};
 function stop(){playing=false;$('ng-play').textContent='▶ Play';frame?.contentWindow.nativePreview?.stop();}
 function scenarioEdit(values){if(variation)dispatch({op:'game.variation.update',id:variation,values:{overrides:values}});else dispatch({op:'game.scenario.update',id:scenario().id,values});refresh();}
 function refresh(){if(!profile())return;if(variation&&!profile().variations.some(v=>v.id===variation))variation='';const s=scenario();selectedScenario=s.id;$('ng-scenario').innerHTML=profile().scenarios.map(s=>option(s.id,s.name??s.id)).join('');$('ng-scenario').value=s.id;$('ng-variation').innerHTML=option('','Base animation')+profile().variations.filter(v=>v.scenario===s.id).map(v=>option(v.id,v.name??v.id)).join('');$('ng-variation').value=variation;for(const key of ['mode','culture','character','duration','seed'])$('ng-'+key).value=s[key];$('ng-time').max=s.duration;$('ng-timeline').innerHTML=(s.events??[]).map((e,i)=>`<button data-ng-cue="${i}" style="--cue-time:${e.time/s.duration*100}%"><time>${e.time.toFixed(2)}</time><b>${esc(e.action.type)}</b><span>${esc(e.action.id??e.action.motion??e.action.method??e.action.target??'')}</span><i></i></button>`).join('')||'<p>Add motion, emotes, sound and gameplay actions at the playhead.</p>';}
 function showEditor(title,value,help='Changes are saved in the shared project JSON. Replay to apply them to a fresh scene.'){$('ng-inspector-title').textContent=title;$('ng-inspector-help').textContent=help;$('ng-values').value=JSON.stringify(value,null,2);fields(value);}
 function fields(v){let html='';const input=(key,value)=>{if(typeof value==='boolean')return `<label>${esc(key)}<input data-ng-field="${esc(key)}" type="checkbox" ${value?'checked':''}></label>`;const choices=key==='carry'?['',...RELIC_ART_KEYS]:key==='mode'&&selection?.kind==='node'?RENDER_MODES:key==='kind'&&selection?.kind==='node'?EFFECT_KINDS:key==='motion'?['idle','walk','work','chop','mine','till','fight','shoot','harvest']:key==='facing'?['front','back','left','right']:key==='id'&&v.type==='reaction'?library.reactions.map(r=>r.id):key==='id'&&v.type==='sound'?library.sounds:key==='variant'?[...new Set(library.voices.map(v=>v.variant))]:key==='clip'&&v.variant?library.voices.filter(a=>a.variant===v.variant).map(a=>a.clip):null;return `<label>${esc(key)}${choices?`<select data-ng-field="${esc(key)}">${choices.map(c=>`<option ${c===value?'selected':''}>${esc(c)}</option>`).join('')}</select>`:`<input data-ng-field="${esc(key)}" type="${typeof value==='number'?'number':'text'}" ${typeof value==='number'?'step="any"':''} value="${esc(value)}">`}</label>`;};for(const [k,x] of Object.entries(v))if(x!==null&&typeof x!=='object'&&k!=='type')html+=input(k,x);$('ng-fields').innerHTML=html;}
 function list(){if(!library)return;const q=$('ng-search').value.toLowerCase();let rows=[];if(tab==='assets'){rows=assets.assets.filter(a=>(a.id+' '+a.name).toLowerCase().includes(q)).map(a=>`<button data-ng-asset="${esc(a.id)}"><img loading="lazy" src="../${esc(a.path)}"><span>${esc(a.name)}</span></button>`);}if(tab==='reactions'){rows=library.reactions.filter(a=>(a.id+' '+a.label).toLowerCase().includes(q)).map(a=>`<button data-ng-reaction="${a.id}"><img src="../assets/vector/reacts/${a.id}.svg"><span>${esc(a.label)}</span></button>`);}if(tab==='audio'){rows=[...library.sounds.filter(id=>id.includes(q)).map(id=>`<button data-ng-sound="${id}"><span>♫ ${esc(id)}</span></button>`),...library.voices.filter(a=>(a.variant+' '+a.clip).includes(q)).map(a=>`<button data-ng-voice="${esc(a.variant+':'+a.clip)}"><span>◖ ${esc(a.clip)}<small>${esc(a.variant)}</small></span></button>`)];}if(tab==='data'){rows=Object.keys(catalog?.data??{}).filter(id=>id.toLowerCase().includes(q)).map(id=>`<button data-ng-data="${esc(id)}"><span>${esc(id)}</span></button>`);if(!catalog)rows=['<p>Load the native preview to inspect its data definitions.</p>'];}$('ng-library-items').className=['assets','reactions'].includes(tab)?'ng-thumbnails':'';$('ng-library-items').innerHTML=rows.join('');}
 async function load(at=0){stop();$('ng-play').disabled=true;const generation=++loading;frame?.remove();const f=frame=document.createElement('iframe');f.title='Shapeshift Studio · Little Gods preview';f.allow='autoplay';const response=await fetch('./native/preview.html');if(!response.ok)throw Error('Preview document unavailable');f.srcdoc=(await response.text()).replace(/\b(src|href)="([^"]*)"/g,(_,attribute,url)=>`${attribute}="${esc(new URL(url,new URL('./native/preview.html',document.baseURI)).href)}"`);$('ng-viewport').replaceChildren(f);await new Promise((resolve,reject)=>{f.onload=resolve;f.onerror=()=>reject(Error('Preview failed to load'));});while(!f.contentWindow.initializeNative)await new Promise(r=>setTimeout(r,30));const next=await f.contentWindow.initializeNative(structuredClone(profile()),selectedScenario,variation);if(generation!==loading)return;f.contentWindow.nativePreview.selectArtwork=selectingArtwork;f.contentWindow.onStudioArtworkSelected=picked=>{if(picked){stop();showArtwork(picked);}else toast('Select a visible character piece or scenery object.');};catalog=next;$('ng-play').disabled=false;time=0;await seek(at);list();$('ng-catalog').replaceChildren();for(const [system,methods] of Object.entries(catalog.systems)) {const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent=system+' · '+methods.length+' methods';detail.append(summary);for(const method of methods){const b=document.createElement('button');b.textContent=method;b.onclick=()=>selectAction({type:'call',system,method,args:[]});detail.append(b);}$('ng-catalog').append(detail);}for(const object of catalog.objects){const b=document.createElement('button');b.textContent=object.id+' · '+object.name;b.onclick=()=>{if(object.asset){showArtwork({asset:object.asset,name:object.name});return;}selection={kind:'node',id:'render-'+object.id};showEditor(object.name,{target:object.id,mode:'native',kind:object.id.startsWith('worker')?'character':'scenery',position:object.position??[0,0,0],rotation:[0,0,0],opacity:1,layer:0});};$('ng-catalog').append(b);}readyGeneration=generation;return catalog;}
 async function seek(t,{silent=true}={}){stop();t=Math.max(0,Math.min(scenario().duration,t));if(!frame?.contentWindow.nativePreview||t<time-1e-8)return load(t);await frame.contentWindow.nativePreview.advance(t,{silent});time=t;clock();return frame.contentWindow.nativePreview.state();}
 function clock(){$('ng-time').value=time;$('ng-time-label').textContent=time.toFixed(2)+' s';}
 function showArtwork(picked){selectedArtwork=picked;selection=null;showEditor(picked.name||picked.asset,{asset:picked.asset},'Shared SVG source. Editing it affects every use of this artwork; native animation and scene lighting remain active.');const open=document.createElement('button');open.id='ng-edit-artwork';open.textContent='Edit SVG source';open.onclick=guard(()=>openArtwork(picked.asset));$('ng-fields').prepend(open);}
 async function openArtwork(asset){if(!artworkHost)throw Error('Artwork workspace is not ready');stop();const saved=project().game?.artwork?.find(e=>e.id===asset),existing=project().assets.find(a=>a.id===saved?.source);let id=existing?.id;if(!id){const svg=await frame.contentWindow.nativePreview.artworkSource(asset);id='game-art-'+crypto.randomUUID().slice(0,8);dispatch({op:'game.artwork.import',nativeAsset:asset,id,svg,name:selectedArtwork?.name||asset});}await artworkHost.workspace.editArtwork(id);return id;}
 function bindArtwork(host){artworkHost=host;const bar=document.createElement('span');bar.id='game-artwork-actions';bar.hidden=true;bar.innerHTML='<button data-game-apply>Preview in village</button><button data-game-return>Return to village</button><button data-game-revert>Restore game original</button>';document.querySelector('#artwork-editor .av-bar').append(bar);bar.onclick=guard(async e=>{const asset=host.artwork.snapshot().asset,entry=project().game?.artwork?.find(a=>a.source===asset);if(!entry)return;const apply=e.target.hasAttribute('data-game-apply'),revert=e.target.hasAttribute('data-game-revert');if(apply||revert)dispatch({op:apply?'game.artwork.apply':'game.artwork.revert',nativeAsset:entry.id,time:host.artwork.snapshot().time});const at=time;await host.workspace.show('game');if(apply||revert)await load(at);showArtwork({asset:entry.id,name:project().assets.find(a=>a.id===asset)?.name});});setInterval(()=>{const asset=host.artwork.snapshot().asset;bar.hidden=!project().game?.artwork?.some(a=>a.source===asset);},150);}
 $('ng-select-artwork').onclick=()=>{selectingArtwork=!selectingArtwork;stop();$('ng-select-artwork').setAttribute('aria-pressed',String(selectingArtwork));if(frame?.contentWindow.nativePreview)frame.contentWindow.nativePreview.selectArtwork=selectingArtwork;};
 function selectAction(action,index){selection={kind:'cue',index};showEditor(index===undefined?'New '+action.type+' cue':'Edit '+action.type+' cue',action);$('ng-fields').insertAdjacentHTML('afterbegin',`<label>Cue time (seconds)<input id="ng-cue-at" type="number" min="0" max="${scenario().duration}" step=".016667" value="${index===undefined?time:scenario().events[index].time}"></label>`);}
 function addAction(action){const s=scenario(),events=structuredClone(s.events??[]);events.push({id:'cue-'+crypto.randomUUID().slice(0,8),time:Number($('ng-cue-at')?.value??time),action});scenarioEdit({events});}
 async function saveSelection(){const value=JSON.parse($('ng-values').value);if(selection?.kind==='profile'){dispatch({op:'game.replace',value});selectedScenario=value.scenarios[0].id;variation='';}
 else if(selection?.kind==='data')dispatch({op:'game.data',id:selection.id,values:value});
 else if(selection?.kind==='node'){const exists=profile().nodes.some(n=>n.id===selection.id);dispatch({op:exists?'game.node.update':'game.node.add',id:selection.id,values:value});}
 else if(selection?.kind==='cue'){if(selection.index===undefined)addAction(value);else{const events=structuredClone(scenario().events);events[selection.index].action=value;events[selection.index].time=Number($('ng-cue-at')?.value??events[selection.index].time);scenarioEdit({events});}}
 else if(selection?.kind==='binding'){const id=value.id??selection.id;dispatch({op:profile().bindings.some(b=>b.id===id)?'game.binding.update':'game.binding.add',id,values:value});}
 else if(selection?.kind==='variation')dispatch({op:'game.variation.update',id:variation,values:value});else throw Error('Select something to edit first');refresh();toast('Saved. Apply & replay to preview the changes.');}
 $('ng-apply').onclick=guard(saveSelection);$('ng-fields').onchange=e=>{if(!e.target.dataset.ngField)return;const v=JSON.parse($('ng-values').value),key=e.target.dataset.ngField;v[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;$('ng-values').value=JSON.stringify(v,null,2);if(key==='variant'){v.clip=library.voices.find(a=>a.variant===v.variant)?.clip??v.clip;$('ng-values').value=JSON.stringify(v,null,2);fields(v);}};
 $('ng-remove').onclick=guard(()=>{if(selection?.kind==='cue'&&selection.index!==undefined)scenarioEdit({events:scenario().events.filter((_,i)=>i!==selection.index)});else if(selection?.kind==='node')dispatch({op:'game.node.remove',id:selection.id});else if(selection?.kind==='data')dispatch({op:'game.data.reset',id:selection.id});refresh();});
 $('ng-audition').onclick=guard(async()=>{const a=JSON.parse($('ng-values').value);if(!frame?.contentWindow.nativePreview)await load();await frame.contentWindow.nativePreview.unlock();frame.contentWindow.nativePreview.session.step(0,{silent:false});frame.contentWindow.nativePreview.command(a);playing=true;$('ng-play').textContent='Ⅱ Pause';});
 $('ng-sound-edit').onclick=()=>{const a=JSON.parse($('ng-values').value);if(a.type!=='sound'||!catalog?.data['audio.recipes'])return toast('Select a sound cue first.');selection={kind:'data',id:'audio.recipes'};showEditor(a.id+' sound recipe',{[a.id]:catalog.data['audio.recipes'].value[a.id]},'Tone: start Hz, end Hz, seconds, gain, waveform, delay. Noise: seconds, gain, cutoff Hz, delay. Four variants preserve alternating feet and woodland/sand foley.');};
 $('ng-json').onclick=()=>{selection={kind:'profile'};showEditor('Game authoring JSON',profile(),'This is the same file the CLI reads and the published game consumes.');};
 $('ng-export').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(profile(),null,2)],{type:'application/json'}));a.href=url;a.download='game-authoring.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('ng-binding').onclick=()=>{selection={kind:'binding',id:'binding-'+crypto.randomUUID().slice(0,8)};showEditor('Gameplay event binding',{id:selection.id,event:'chopped',when:{},actions:[{type:'performance',scenario:selectedScenario,seed:1}]},'When the simulation emits this event, play this bundle. Use $event:workerId and other event fields in JSON arguments.');};
 $('ng-capture').onclick=guard(()=>{const initialState=frame.contentWindow.nativePreview.capture();scenarioEdit({initialState});toast('Captured the village as this scenario’s starting state.');});
 $('ng-close').onclick=()=>{stop();panel.hidden=true;document.body.classList.remove('native-open');};
 $('ng-reload').onclick=guard(()=>load());$('ng-restart').onclick=guard(()=>load());$('ng-time').onchange=guard(e=>seek(Number(e.target.value)));
 $('ng-play').onclick=guard(async()=>{if(playing){stop();return;}if(!frame?.contentWindow.nativePreview||time>=scenario().duration)await load();await frame.contentWindow.nativePreview.unlock();playing=true;last=performance.now();$('ng-play').textContent='Ⅱ Pause';});
 for(const key of ['mode','culture','character','duration','seed'])$('ng-'+key).onchange=guard(e=>scenarioEdit({[key]:['duration','seed'].includes(key)?Number(e.target.value):e.target.value}));
 $('ng-scenario').onchange=guard(async e=>{selectedScenario=e.target.value;variation='';time=0;refresh();await load();});$('ng-variation').onchange=guard(async e=>{variation=e.target.value;refresh();await load();});
 $('ng-new').onclick=guard(()=>{const id='scenario-'+crypto.randomUUID().slice(0,8);dispatch({op:'game.scenario.add',id,values:{...nativeProject().scenarios[0],id,name:'New scenario',mode:'village',events:[]}});selectedScenario=id;variation='';refresh();});
 $('ng-new-variation').onclick=guard(()=>{const id='variation-'+crypto.randomUUID().slice(0,8);dispatch({op:'game.variation.add',id,values:{scenario:selectedScenario,name:'Variation '+(profile().variations.length+1),weight:1,overrides:{seed:scenario().seed+1}}});variation=id;refresh();selection={kind:'variation'};showEditor('Variation',profile().variations.find(v=>v.id===id),'Edit this variation’s overrides or select timeline cues. The base animation remains available.');});
 $('ng-add-cue').onclick=()=>{const type=$('ng-action-type').value,a={type,...structuredClone(defaults[type])};if(['hit','flash'].includes(type))a.target=catalog?.objects.find(o=>o.name==='tree')?.id??'hero';selectAction(a);};
 $('ng-timeline').onclick=e=>{const b=e.target.closest('[data-ng-cue]');if(b)selectAction(scenario().events[Number(b.dataset.ngCue)].action,Number(b.dataset.ngCue));};
 panel.querySelectorAll('[data-ng-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.ngTab;list();});$('ng-search').oninput=list;
 $('ng-library-items').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.ngAsset){const id='art-'+crypto.randomUUID().slice(0,8);selection={kind:'node',id};showEditor('Add vector artwork',{asset:b.dataset.ngAsset,height:2,mode:'billboard',kind:'scenery',position:[0,0,2],rotation:[0,0,0],scale:[1,1,1],opacity:1,layer:10,lighting:true});}else if(b.dataset.ngReaction)selectAction({type:'reaction',id:b.dataset.ngReaction,intensity:1,voice:true});else if(b.dataset.ngSound)selectAction({type:'sound',id:b.dataset.ngSound});else if(b.dataset.ngVoice){const [variant,clip]=b.dataset.ngVoice.split(':');selectAction({type:'voice',variant,clip,pitch:1,intensity:1});}else if(b.dataset.ngData){selection={kind:'data',id:b.dataset.ngData};showEditor(selection.id,catalog.data[selection.id].value,'These are the actual values used by the game. Numbers, arrays, stages, sound layers and reaction mappings are editable JSON.');}};
 async function tick(now){const dt=Math.max(0,Math.min((now-last)/1000,1/15));last=now;if(playing&&frame?.contentWindow.nativePreview){try{time=Math.min(scenario().duration,time+dt);await frame.contentWindow.nativePreview.advance(time,{silent:!$('ng-audible').checked});clock();if(time>=scenario().duration)stop();}catch(e){stop();toast(e.message,true);}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 return {openArtwork,bindArtwork,artworkSelection:()=>selectedArtwork,hide(){stop();panel.hidden=true;document.body.classList.remove('native-open');},async show(){if(!profile())dispatch({op:'game.replace',value:nativeProject()});if(!library){[library,assets]=await Promise.all([fetch('./native/library.json').then(r=>r.json()),fetch('./catalog.json').then(r=>r.json())]);$('ng-character').innerHTML=library.characters.map(c=>option(c.id,c.label)).join('');}panel.hidden=false;document.body.classList.add('native-open');refresh();list();if(!frame)await load();},load,seek,stop,refresh,async grading(){if(frame?.contentWindow.nativePreview){frame.contentWindow.__littleGodsAuthoring.grading=structuredClone(profile().grading??{preset:'auto'});await frame.contentWindow.nativePreview.advance(time,{silent:true});}},async audition(a){const p=frame.contentWindow.nativePreview;await p.unlock();const result=p.command(a);await p.advance(time,{silent:false});return result;},command:a=>frame.contentWindow.nativePreview.command(a),catalog:()=>catalog,snapshot:()=>({time,loading:readyGeneration!==loading,scenario:selectedScenario,variation,profile:structuredClone(profile()),state:frame?.contentWindow?.nativePreview?.state()}),capture:()=>frame.contentWindow.nativePreview.capture()};
}
