import {boundVector} from './model.js';
import {poseAt} from '../runtime.js';
import {anchors,svgText} from '../vector/model.js';
import {renderVector} from '../vector/render.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountBoneBindings({project,context,revision,dispatch,pause,select,toast,example,download}){
 const button=document.createElement('button');button.id='bone-binding-open';button.textContent='Bind Bones';document.getElementById('motion-tools').before(button);
 const panel=document.createElement('aside');panel.id='bone-binding-panel';panel.className='author-panel';panel.hidden=true;panel.setAttribute('aria-label','Vector bone binding');document.body.append(panel);
 const style=document.createElement('style');style.textContent='#bone-binding-panel canvas{width:100%;background:#eee8df;border-radius:8px;cursor:crosshair}#bone-binding-panel .binding-bones{display:grid;grid-template-columns:1fr 1fr;max-height:150px;overflow:auto;gap:4px}#bone-binding-panel .binding-weights label{display:grid;grid-template-columns:1fr 90px;align-items:center}#bone-binding-panel .binding-bones label{display:flex;flex-direction:row;align-items:center;font-size:11px}#bone-binding-panel .binding-bones input{width:auto}#bone-binding-panel small{display:block}';document.head.append(style);
 let owner='',path='',selected=new Set([0]),stamp='',pick=[];
 const joint=()=>project().joints.find(j=>j.id===owner),asset=()=>project().assets.find(a=>a.id===joint()?.sprite?.asset);
 const options=(items,value)=>items.map(([id,name])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(name)}</option>`).join('');
 function run(command){try{pause();dispatch({joint:owner,clip:context().clip.id,time:context().time,...command});stamp='';refresh();}catch(e){toast(e.message,true);}}
 function draw(){const canvas=panel.querySelector('canvas'),j=joint(),v=asset()?.vector;if(!canvas||!v)return;const a=context(),pose=poseAt(project(),a.clip,a.time),sample=boundVector(v,j,pose,a.time)?.vector??v,ctx=canvas.getContext('2d'),[x,y,w,h]=sample.viewBox,k=Math.min((canvas.width-32)/w,(canvas.height-32)/h),dx=(canvas.width-w*k)/2-x*k,dy=(canvas.height-h*k)/2-y*k;ctx.resetTransform();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(dx,dy);ctx.scale(k,k);renderVector(ctx,sample,a.time);ctx.restore();const shape=sample.shapes.find(s=>s.id===path);pick=[];if(!shape)return;const vertices=new Set(anchors(shape).map(a=>a.index));ctx.lineWidth=1;ctx.strokeStyle='#809397';for(const anchor of anchors(shape))for(const index of [anchor.incoming,anchor.outgoing])if(index!=null){ctx.beginPath();ctx.moveTo(dx+anchor.x*k,dy+anchor.y*k);ctx.lineTo(dx+shape.points[index]*k,dy+shape.points[index+1]*k);ctx.stroke();}for(let i=0;i<shape.points.length;i+=2){const px=dx+shape.points[i]*k,py=dy+shape.points[i+1]*k,isVertex=vertices.has(i);pick.push({index:i/2,x:px,y:py});ctx.fillStyle=selected.has(i/2)?'#db5435':isVertex?'#176f78':'#a457b6';ctx.strokeStyle='white';ctx.beginPath();if(isVertex)ctx.rect(px-4,py-4,8,8);else ctx.arc(px,py,4,0,Math.PI*2);ctx.fill();ctx.stroke();}}
 function refresh(){if(panel.hidden)return;const a=context(),key=[revision(),a.dimension,owner,path,[...selected].join(',')].join(':');if(key===stamp){draw();return;}stamp=key;
 const sprites=project().joints.filter(j=>project().assets.find(v=>v.id===j.sprite?.asset)?.vector);if(!sprites.some(j=>j.id===owner))owner=sprites.find(j=>j.id===a.selected)?.id??sprites[0]?.id??'';const j=joint(),v=asset()?.vector,b=j?.sprite.boneBinding;if(!v?.shapes.some(s=>s.id===path))path=v?.shapes.find(s=>!s.hidden)?.id??v?.shapes[0]?.id??'';const shape=v?.shapes.find(s=>s.id===path),binding=b?.shapes.find(s=>s.shape===path);selected=new Set([...selected].filter(i=>i<(shape?.points.length??0)/2));const first=[...selected][0],weights=binding?.weights[first]??[];
 panel.innerHTML=`<header><div><strong>Bind vector bones</strong><small>Bend vertices and Bézier handles independently</small></div><button data-action="close" aria-label="Close bone binding">×</button></header><button data-action="example">Load animated book example</button>${a.dimension!==2?'<p>Open the 2D puppet workspace to author vector bindings. Bound puppets also render in 3D puppet layers.</p>':`<label>Artwork<select id="binding-owner">${options(sprites.map(j=>[j.id,j.name]),owner)}</select></label>${v?`<p>Pose your joints, then bind to capture their current position. Animate those joints to bend the artwork.</p><div class="binding-bones">${project().joints.map(n=>`<label><input type="checkbox" data-bone="${esc(n.id)}" ${b?.bones.some(x=>x.joint===n.id)?'checked':''}>${esc(n.name)}</label>`).join('')}</div><div class="button-row"><button data-action="bind">${b?'Rebind at current pose':'Bind selected bones'}</button>${b?'<button data-action="unbind">Unbind</button>':''}</div>${b?`<label><input id="binding-enabled" type="checkbox" ${b.enabled?'checked':''}> Deformation enabled</label>`:''}<label>Path<select id="binding-path">${options(v.shapes.map(s=>[s.id,s.name??s.id]),path)}</select></label><canvas width="640" height="440" aria-label="Select path vertices and Bézier handles"></canvas><small>Squares: vertices. Circles: handles. Click to select; Shift-click adds points.</small><label>Point<select id="binding-point">${options((shape?Array.from({length:shape.points.length/2},(_,i)=>[String(i),`${i+1} · ${anchors(shape).some(a=>a.index===i*2)?'vertex':'Bézier handle'}`]):[]),String(first))}</select></label><button data-action="all">Select all points</button>${binding?`<p>${selected.size} point${selected.size===1?'':'s'} selected. Weights below show the first selected point; Apply assigns the mix to every selected point.</p><div class="binding-weights">${b.bones.map(bone=>`<label>${esc(project().joints.find(j=>j.id===bone.joint)?.name)}<input type="number" min="0" max="100" step="1" data-weight="${esc(bone.joint)}" aria-label="${esc(bone.joint)} weight" value="${+((weights.find(w=>w.bone===bone.joint)?.weight??0)*100).toFixed(3)}"></label>`).join('')}</div><button data-action="weights" ${selected.size?'':'disabled'}>Apply weights · normalize to 100%</button>`:'<p>Bind this path to edit its bone weights.</p>'}<div class="button-row"><button data-action="select">Select artwork in rig</button><button data-action="svg">Export posed SVG</button></div>`:'<p>Add an editable SVG to the puppet, or load the book example.</p>'}`}`;draw();
 }
 panel.onclick=async e=>{const action=e.target.closest('button')?.dataset.action;if(!action)return;if(action==='close'){panel.hidden=true;return;}if(action==='example'){try{await example();owner='page';path='page-strip-8';selected=new Set([2]);stamp='';refresh();}catch(e){toast(e.message,true);}return;}if(action==='bind')run({op:'boneBinding.bind',bones:[...panel.querySelectorAll('[data-bone]:checked')].map(n=>n.dataset.bone)});if(action==='unbind')run({op:'boneBinding.unbind'});if(action==='weights')run({op:'boneBinding.weights',shape:path,points:[...selected],weights:[...panel.querySelectorAll('[data-weight]')].map(n=>({bone:n.dataset.weight,weight:Number(n.value)}))});if(action==='all'){selected=new Set(Array.from({length:asset().vector.shapes.find(s=>s.id===path).points.length/2},(_,i)=>i));stamp='';refresh();}if(action==='select')select(owner);if(action==='svg'){pause();const a=context(),v=asset().vector,posed=boundVector(v,joint(),poseAt(project(),a.clip,a.time),a.time)?.vector??v;download(svgText(posed,a.time),'bound-pose.svg','image/svg+xml');}};
 panel.onchange=e=>{const el=e.target;if(el.id==='binding-owner'){owner=el.value;path='';selected=new Set([0]);stamp='';refresh();}if(el.id==='binding-path'){path=el.value;selected=new Set([0]);stamp='';refresh();}if(el.id==='binding-point'){pause();selected=new Set([Number(el.value)]);stamp='';refresh();}if(el.id==='binding-enabled')run({op:'boneBinding.enabled',enabled:el.checked});};
 panel.addEventListener('pointerdown',e=>{if(e.target.tagName!=='CANVAS')return;pause();const rect=e.target.getBoundingClientRect(),x=(e.clientX-rect.left)*640/rect.width,y=(e.clientY-rect.top)*440/rect.height,hit=pick.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).sort((a,b)=>a.d-b.d)[0];if(!hit||hit.d>18)return;if(!e.shiftKey)selected=new Set();if(e.shiftKey&&selected.has(hit.index))selected.delete(hit.index);else selected.add(hit.index);stamp='';refresh();});
 function show(){owner=context().dimension===2&&project().joints.find(j=>j.id===context().selected)?.sprite?context().selected:owner;panel.hidden=false;stamp='';refresh();}
 button.onclick=()=>panel.hidden?show():panel.hidden=true;setInterval(refresh,100);return{show,hide(){panel.hidden=true;},example};
}
