import {villageWorld} from './ecs/village-world.js';
import * as systems from './ecs/systems/relics.js';
export {RELIC_TYPES,RELIC_RULES,RELIC_CULTURES,RELIC_ART_KEYS,relicArtPath,relicFeedbackEvents} from './ecs/systems/relics.js';
export function relicState(e,...args){return systems.relicState(villageWorld(e),...args);}
export function relicPeople(e,...args){return systems.relicPeople(villageWorld(e),...args);}
export function relicById(e,...args){return systems.relicById(villageWorld(e),...args);}
export function relicHolder(e,...args){return systems.relicHolder(villageWorld(e),...args);}
export function carriedRelic(e,...args){return systems.carriedRelic(villageWorld(e),...args);}
export function relicPoint(e,...args){return systems.relicPoint(villageWorld(e),...args);}
export function relicCarryKey(e,...args){return systems.relicCarryKey(villageWorld(e),...args);}
export function relicMemory(e,...args){return systems.relicMemory(villageWorld(e),...args);}
export function relicHistory(e,...args){return systems.relicHistory(villageWorld(e),...args);}
export function attachRelic(e,...args){return systems.attachRelic(villageWorld(e),...args);}
export function recordRelicOwner(e,...args){return systems.recordRelicOwner(villageWorld(e),...args);}
export function discoverRelic(e,...args){return systems.discoverRelic(villageWorld(e),...args);}
export function noticeRelicEvent(e,...args){return systems.noticeRelicEvent(villageWorld(e),...args);}
export function dropRelic(e,...args){return systems.dropRelic(villageWorld(e),...args);}
export function cancelRelicTask(e,...args){return systems.cancelRelicTask(villageWorld(e),...args);}
export function interruptRelic(e,...args){return systems.interruptRelic(villageWorld(e),...args);}
export function takeRelic(e,...args){return systems.takeRelic(villageWorld(e),...args);}
export function beginRelicFight(e,...args){return systems.beginRelicFight(villageWorld(e),...args);}
export function handleRelicTask(e,...args){return systems.handleRelicTask(villageWorld(e),...args);}
export function chooseRelicTask(e,...args){return systems.chooseRelicTask(villageWorld(e),...args);}
export function relicAirTemperature(e,...args){return systems.relicAirTemperature(villageWorld(e),...args);}
export function relicPersuasion(e,...args){return systems.relicPersuasion(villageWorld(e),...args);}
export function updateRelics(e,...args){return systems.updateRelics(villageWorld(e),...args);}
export function destroyRelic(e,...args){return systems.destroyRelic(villageWorld(e),...args);}
export function relicFireTarget(e,...args){return systems.relicFireTarget(villageWorld(e),...args);}
export function relicDescription(e,...args){return systems.relicDescription(villageWorld(e),...args);}
export function relicDetails(e,...args){return systems.relicDetails(villageWorld(e),...args);}
export function validRelics(e,...args){return systems.validRelics(villageWorld(e),...args);}
