import {vectorCardArtwork} from './card-art.js';
import {SKILL_WISHES} from './skill-wishes.js';
import {defineGameData} from './game-data.js';
import {BEAST_MIRACLES} from './beast-miracle-catalog.js';
export const WISHES=defineGameData('wish-catalog.WISHES',Object.freeze(vectorCardArtwork({
 poison:{name:'Poison',colour:'#94b64e',hint:'Poison a living villager for 90 seconds. It drains health and energy; an injured victim may die.'},
 purify:{name:'Purify',colour:'#86d9c7',hint:'Clear poison from a living villager immediately. Lost health recovers separately.'},
 acorn:{name:'Acorn',cultures:['hearth'],colour:'#d5ac65',art:'assets/vector/wishes/cards-v2/acorn.svg',hint:'Leave an acorn on clear Hearth ground. Villagers plant and tend it into an oak for future wood. Rain helps it grow.'},
 ...RELIC_MIRACLES,
 curse:{name:'Curse',colour:'#aa82cf',art:'assets/vector/wishes/cards/curse.svg',hint:'Bring three days of bad luck to a character. Life lifts the curse.'},
 ...BEAST_MIRACLES,
 ...SKILL_WISHES,
 rat:{name:'Rat',colour:'#c6aa91',art:'assets/vector/wishes/cards/rat.svg',hint:'Summon a rat on clear ground. It steals food from nearby stores or crops — including a neighbour’s camp.'},
 owl:{name:'Owl',colour:'#d8caa4',art:'assets/vector/wishes/cards/owl.svg',hint:'Summon a rare owl near a living tree. It hunts rats nearby. If its home tree falls, it flies away for good.'},
 'animal-bond':{name:'Animal Bond',colour:'#dfb680',art:'assets/vector/wishes/cards/animal-bond.svg',hint:'Bring a villager and nearby animal closer together'},
 'call-wild':{name:'Call of the Wild',colour:'#a4b98b',art:'assets/vector/wishes/cards/call-wild.svg',hint:'Invite nearby wildlife to linger on reachable ground'},
 dream:{name:'Dream',colour:'#b5a4d8',art:'assets/vector/wishes/cards/dream.svg',hint:'Give a sleeping adult a lasting ambition — choose their home'},
 uprising:{name:'Uprising',colour:'#e9ae69',art:'assets/vector/wishes/cards/uprising.svg',hint:'Make an adult villager rise against the current leader. Loyalists may defend them; the attempt can fail. Requires a leader.'},
 violence:{name:'Violence',colour:'#ef796c',art:'assets/vector/wishes/cards/violence.svg',hint:'Send a villager into a 20-second frenzy. They attack whoever is closest, including friends.'},
 sleep:{name:'Sleep',colour:'#c7bbed',art:'assets/vector/wishes/cards/sleep.svg',hint:'Calm a villager and send them to a safe bed for a nap. Danger can still wake them.'},
 ping:{name:'Explore here',colour:'#54c4d4',art:'assets/vector/wishes/cards/ping.svg',hint:'Suggest a spot to investigate for 30 seconds. An available villager may take a look; urgent needs come first.'},
 'leave-here':{name:'Leave here',colour:'#e88a65',art:'assets/vector/wishes/cards/leave-here.svg',hint:'Suggest that nearby villagers move away for now. Lasts 30 seconds; this does not forbid the area.'},
 wood:{name:'Wood',colour:'#d8b47e',art:'assets/vector/wishes/cards/wood.svg',hint:'Add 10 wood to the village’s shared stores for building, repairs and warmth.'},
 stone:{name:'Stone',colour:'#b5cbd6',art:'assets/vector/wishes/cards/stone.svg',hint:'Add 8 stone to the village’s shared stores for foundations and repairs.'},
 hot:{name:'Hot',colour:'#ffae73',art:'assets/vector/wishes/cards/hot.svg',hint:'Make the village hot at 35°C for 60 seconds, then ease back to normal. Replaces Cold; repeated casts refresh the effect.'},
 cold:{name:'Cold',colour:'#a5e4f4',art:'assets/vector/wishes/cards/cold.svg',hint:'Make the village cold at 5°C for 60 seconds, then ease back to normal. Replaces Hot; repeated casts refresh the effect.'},
 repair:{name:'Repair',colour:'#b5edaa',art:'assets/vector/wishes/cards/repair.svg',hint:'Restore a damaged standing house or chapel to full health. Does not rebuild ruins or extinguish fire.'},
 shield:{name:'Shield',colour:'#b7ebff',art:'assets/vector/wishes/cards/shield.svg',hint:'Protect a character from attacks, fire and lightning for 15 seconds.'},
 hand:{name:'Hand',colour:'#ead1ff',art:'assets/vector/wishes/cards/hand.svg',hint:'Lift a character, then click clear ground to put them down. Escape returns them to where you picked them up.'},
 friendship:{name:'Friendship',colour:'#f4d58c',art:'assets/vector/wishes/cards/friendship.svg',hint:'Make two nearby villagers friends without changing their romantic partners.'},
 enmity:{name:'Enmity',colour:'#db9bbb',art:'assets/vector/wishes/cards/enmity.svg',hint:'Turn two nearby villagers against one another without changing their romantic partners.'},
 love:{name:'Love',colour:'#ee9db0',hint:'Bring two nearby adults together, even if they already have sweethearts.'},
 resurrect:{name:'Resurrect',colour:'#e5dfaa',hint:'Bring a buried villager back to life. Only targets graves; requires a free population space and bed.'},
 life:{name:'Life',colour:'#b5edaa',hint:'Restore someone to full health, or advance a growing crop by half its growth cycle.'},
 fire:{name:'Fire',colour:'#ffc274',hint:'Set a house, character, plant or mushroom alight, or kindle the campfire.'},
 skull:{name:'Death',colour:'#d3b9ee',hint:'End a life. Villagers, raiders and Ink creatures can all be chosen.'},
 heartbreak:{name:'Breakup',colour:'#e7a4bd',hint:'Choose either sweetheart to end their relationship. Both will feel heartbroken.'},
 newcomer:{name:'Newcomer',colour:'#a6e5d8',hint:'Welcome a new adult with a random identity on clear ground. Requires a free population space and bed.'},
 food:{name:'Food',colour:'#efb974',art:'assets/vector/wishes/cards/food-supplies.svg',hint:'Add 8 food to the village’s shared stores. Villagers collect meals through their normal routines.'},
 energy:{name:'Energy',colour:'#b6f0dd',art:'assets/vector/wishes/cards/energy.svg',hint:'Restore a villager to full energy and cure fatigue. Can also be used when already rested.'},
 'age-adult':{name:'Adulthood',colour:'#bbd6a0',art:'assets/vector/wishes/cards/age-adult.svg',hint:'Make a villager a young adult. Their family and memories stay with them.'},
 'age-child':{name:'Childhood',colour:'#b9dcec',art:'assets/vector/wishes/cards/age-child.svg',hint:'Return a villager to childhood. They need care again and leave adult roles behind.'},
 'age-elder':{name:'Elderhood',colour:'#e8c78d',art:'assets/vector/wishes/cards/age-elder.svg',hint:'Make a villager an elder: slower, frailer, and cared for by the village.'},
 daybreak:{name:'Daybreak',colour:'#ffdc84',art:'assets/vector/wishes/cards/daybreak.svg',hint:'Bring daylight to the whole village.'},
 nightfall:{name:'Nightfall',colour:'#b9bcf4',art:'assets/vector/wishes/cards/nightfall.svg',hint:'Bring night to the whole village.'},
 'clear-skies':{name:'Clear Skies',colour:'#cae6f3',art:'assets/vector/wishes/cards/clear-skies.svg',hint:'End the rain and dry the campfire immediately. Any remaining fuel can burn again.'},
 rain:{name:'Rain',colour:'#a4ddeb',hint:'Call a passing shower over the village and put out fires.'},
})));
import {RELIC_MIRACLES} from './relic-miracle-catalog.js';
