import {DICE_SIDES,regularSolid} from './geometry.js';
import {diceParts} from './project.js';
import {spinClip} from './motion.js';
import {simulateDice,physicsRollClip} from './physics.js';
export function mountSolidTools(host){const open=document.createElement('button');open.id='s3-solid';open.textContent='+ Dice / solid';document.getElementById('s3-example').after(open);const dialog=document.createElement('dialog');dialog.className='solid-dialog';dialog.innerHTML=`<form method="dialog"><header><div><small>3D GEOMETRY</small><h2>Dice & solids</h2></div><button value="cancel" aria-label="Close solid tool">×</button></header><p>Beveled dice, regular polyhedra and prisms. SVG markings follow the mesh as it squashes and bends.</p><label>Geometry<select id="solid-kind"><option value="die">Dice / regular polyhedron</option><option value="prism">Equal-sided prism</option></select></label><label>Outcomes<select id="solid-sides">${DICE_SIDES.map(n=>`<option ${n===6?'selected':''}>${n}</option>`).join('')}</select></label><label id="prism-count" hidden>Prism sides<input id="solid-prism" type="number" min="3" max="20" value="5"></label><label>Edge softness<input id="solid-bevel" type="range" min=".015" max=".2" step=".005" value=".09"></label><label>Painted finish<select id="solid-theme"><option value="ivory">Ivory ceramic</option><option value="moss">Moss stone</option><option value="ember">Ember clay</option></select></label><label class="solid-check"><input id="solid-numbers" type="checkbox" checked>Add Inkwell numerals</label><label class="solid-check"><input id="solid-motion" type="checkbox" checked>Add squishy roll & idle-spin clips</label><label>Throw seed<input id="solid-result" type="number" min="0" max="4294967295" value="123"></label><small id="solid-note">D5: ten equal kite faces numbered 1–5 twice. Roll clips use rigid-body physics; the resting face determines the result.</small><p class="solid-error" role="alert"></p><footer><a href="./dice/index.html" target="_blank">Try Fable & Fortune ↗</a><button type="button" id="solid-apply">Add to scene</button></footer></form>`;document.body.append(dialog);const $=id=>dialog.querySelector('#solid-'+id);let editing;
 const kindChanged=()=>{dialog.querySelector('#prism-count').hidden=$('kind').value!=='prism';$('sides').parentElement.hidden=$('kind').value==='prism';};$('kind').onchange=kindChanged;
 open.onclick=()=>{host.pause();const n=host.node();editing=n?.regularSolid?n:null;const d=n?.regularSolid??{sides:6,kind:'die',bevel:.09,theme:'ivory',numbers:true};for(const k of ['kind','bevel','theme'])$(k).value=d[k];$('sides').value=DICE_SIDES.includes(d.sides)?d.sides:6;$('prism').value=d.sides;$('numbers').checked=d.numbers;$('result').value=123;$('apply').textContent=editing?'Update selected solid':'Add to scene';dialog.querySelector('.solid-error').textContent='';kindChanged();dialog.showModal();};
 $('apply').onclick=async()=>{const button=$('apply');button.disabled=true;try{const kind=$('kind').value,sides=+(kind==='prism'?$('prism').value:$('sides').value),bevel=+$('bevel').value,value=+$('result').value;const solid=regularSolid({kind,sides,bevel});if(!Number.isInteger(value)||value<0||value>4294967295)throw Error('Choose a whole-number seed from 0 to 4294967295');const id=editing?.id??'solid-'+crypto.randomUUID().slice(0,8),parts=await diceParts({id,sides,kind,bevel,theme:$('theme').value,numbers:$('numbers').checked}),p=host.project(),s=p.scene3d,commands=[];
 for(const [type,entry,list]of [['asset',parts.asset,p.assets],['material',parts.material,s.materials]]){const exists=list.some(v=>v.id===entry.id);commands.push(type==='asset'?{op:'scene3d.asset.'+(exists?'update':'add'),...entry}:{op:'scene3d.material.'+(exists?'update':'add'),id:entry.id,values:entry});}
 for(const n of parts.nodes){const old=s.nodes.find(v=>v.id===n.id);commands.push({op:'scene3d.node.'+(old?'update':'add'),id:n.id,type:n.type,values:old?{...n,position:old.position,rotation:old.rotation,parent:old.parent,name:old.name}:n});}
 const clipId=id+'-roll';if($('motion').checked)for(const c of [physicsRollClip(parts.solid,simulateDice(parts.solid,{seed:value}),{id:clipId,body:id,rig:parts.rig}),{...spinClip({body:id,rig:parts.rig}),id:id+'-spin'}])commands.push({op:'scene3d.clip.'+(s.clips.some(v=>v.id===c.id)?'update':'add'),id:c.id,values:c});host.dispatch(commands);await host.refresh();host.select(id);if($('motion').checked){host.clip(clipId);host.seek(0);}dialog.close();host.toast('Solid ready. Its paint, geometry and animation are editable.');}catch(e){dialog.querySelector('.solid-error').textContent=e.message;}finally{button.disabled=false;}};
}
