import * as T from '../scene3d/vendor.js';
// Small screen-space ink sparks; no per-frame DOM nodes or extra scene render.
export class DiceSparks {
 constructor(canvas,{reduced=false}={}){this.canvas=canvas;this.context=canvas.getContext('2d');this.reduced=reduced;this.particles=[];this.point=new T.Vector3();this.width=0;this.height=0;}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(w===this.width&&h===this.height)return;this.width=w;this.height=h;const ratio=Math.min(2,devicePixelRatio||1);this.canvas.width=Math.round(w*ratio);this.canvas.height=Math.round(h*ratio);this.context.setTransform(ratio,0,0,ratio,0,0);this.particles.length=0;}
 burst(scene,clock,{combo=0,kind='good',strength=1}={}){if(this.reduced)return;this.resize();const object=scene.objects.get('die-rig');if(!object)return;object.getWorldPosition(this.point);this.point.project(scene.camera);const x=(this.point.x+1)*this.width/2,y=(1-this.point.y)*this.height/2,energy=1+Math.min(2,Math.sqrt(combo)/5),count=Math.round((kind==='perfect'?20:kind==='miss'?25:11)*energy*strength);for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=(55+Math.random()*135)*energy;this.particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-45,at:clock,life:.24+Math.random()*.27,length:3+Math.random()*7,width:1+Math.random()*1.7,color:kind==='miss'?(i%2?'#b95037':'#6f3f32'):(i%3?'#dba52f':'#fff2af')});}if(this.particles.length>160)this.particles.splice(0,this.particles.length-160);}
 draw(clock){this.resize();const c=this.context;c.clearRect(0,0,this.width,this.height);let keep=0;for(const p of this.particles){const age=clock-p.at;if(age>=p.life)continue;this.particles[keep++]=p;const x=p.x+p.vx*age,y=p.y+p.vy*age+230*age*age,speed=Math.hypot(p.vx,p.vy),fade=1-age/p.life;c.globalAlpha=fade*fade;c.strokeStyle=p.color;c.lineWidth=p.width*fade;c.lineCap='round';c.beginPath();c.moveTo(x,y);c.lineTo(x-p.vx/speed*p.length,y-p.vy/speed*p.length);c.stroke();}this.particles.length=keep;c.globalAlpha=1;}
 dispose(){this.particles.length=0;this.context.clearRect(0,0,this.width,this.height);}
}
