import * as T from '../scene3d/vendor.js';
import {nodeDefaults,sceneDefaults,materialDefaults,littleGodsMaterialStyle} from '../scene3d/schema.js';
import {regularSolid,normalizeDiceSize} from './geometry.js';
import {diceAtlas} from './texture.js';
import {spinClip} from './motion.js';
import {simulateDice,physicsRollClip} from './physics.js';
export async function diceParts({sides=6,kind='die',bevel=.09,theme='ivory',numbers=true,id='die',position=[0,0,0],normalizeSize=false}={}){const shape=regularSolid({sides,kind,bevel}),solid=normalizeSize&&kind==='die'?normalizeDiceSize(shape):shape,asset=id+'-paint',material=id+'-ink',rig=id+'-rig',src=await diceAtlas(solid,{theme,numbers}),base=materialDefaults(material),definition={...base,...littleGodsMaterialStyle(base),name:'Painted '+theme,palette:['#ffffff','#d7b581','#fff4d9','#23392f'],map:asset,preservePaint:false,bands:8,creases:false,shadeContrast:.46,shadeSoftness:.015,strokeStyle:'hull',outlineUnits:'screen',ink:2.2,strokeVariation:.08,outlineWorldWidth:.025,roughness:.8,sheen:.12},simulation=simulateDice(solid,{seed:sides===5?1:123}),roll=physicsRollClip(solid,simulation,{body:id,rig}),rest={position:roll.tracks[1].keys.at(-1).value,rotation:roll.tracks[0].keys.at(-1).value},nodes=[{...nodeDefaults(rig,'group'),name:'Dice squash rig',position:rest.position.map((v,i)=>v+position[i]),dimensions:[2,2,2],material}, {...nodeDefaults(id,'mesh'),name:'D'+solid.count+' · '+(kind==='prism'?'prism':sides===5?'ten equal kite faces':'die'),parent:rig,position:[0,0,0],rotation:rest.rotation,dimensions:[1,1,1],material,mesh:solid.mesh,regularSolid:{sides,kind,bevel,theme,numbers}}];return{solid,simulation,roll,asset:{id:asset,name:'Inkwell numerals · editable SVG',src},material:definition,nodes,rig,body:id};}
export async function diceProject(options={}){const parts=await diceParts({normalizeSize:true,...options}),p={format:'inkwell-puppet',version:1,name:'Fable & Fortune · D'+parts.solid.count,assets:[parts.asset],joints:[{id:'root',name:'Stage',parent:null,layer:0,rest:{x:0,y:0,rotation:0,scaleX:1,scaleY:1}}],clips:[{id:'idle',name:'Idle',duration:3,fps:30,loop:true,tracks:{}}],scene3d:sceneDefaults()},s=p.scene3d;s.materials=[parts.material,{...materialDefaults('table'),name:'Warm tabletop',palette:['#e7dfce','#e7dfce','#fff5dc','#9b907b'],ink:0,shading:'lit',roughness:1,sheen:0}];s.nodes=[...parts.nodes,{...nodeDefaults('table','plane'),name:'Shadow catcher',rotation:[-90,0,0],position:[0,-.015,0],dimensions:[200,200,1],material:'table',castShadow:false}];s.camera={...s.camera,position:[3.6,4.8,6.6],target:[0,1,0],size:3.7};s.environment={...s.environment,background:'#f6f2e9',lightColor:'#fffaf0',intensity:2.5,ambient:2,lightPosition:[-5,7,-3],shadows:true};s.clips=[parts.roll,spinClip()];return{project:p,...parts};}

// A transparent shadow catcher leaves the cream background completely uniform.
export function configureDiceTable(host){host.objects.get('table')?.traverse(object=>{
 if(!object.isMesh)return;
 if(!object.material.isShadowMaterial){const previous=object.material;object.material=new T.ShadowMaterial({color:'#5e594a',opacity:.22,depthWrite:false});object.material.userData.uniforms=previous.userData.uniforms;previous.dispose();}
 object.renderOrder=-2;object.material.depthWrite=false;
});}
