const v=n=>['var',n],o=(n,...args)=>[n,...args],add=(...a)=>o('add',...a),sub=(a,b)=>o('sub',a,b),mul=(...a)=>o('mul',...a),div=(a,b)=>o('div',a,b),smooth=a=>o('smooth',a),sin=a=>o('sin',a),clamp=a=>o('clamp',a,0,1),branch=(condition,a,b)=>o('if',condition,a,b),before=t=>o('lt',v('time'),t);
// The launch/hover/slam equations remain authored tracks. The preparation now
// includes the requested eye-first pound: accelerating descent, a planted
// compression hold and recoil, then the downward propulsion beam.
export const launchTiming={faceImpact:.48,charge:1.45,rise:.55,hover:.65,fall:.22};
export function watcherLaunchTracks(){
 const t=v('time'),launch=sub(t,1.45),hover=sub(t,2),fall=sub(t,2.65),impactAge=o('max',0,sub(t,.535)),compression=sub(1,mul(.30,o('cos',mul(impactAge,20)),o('exp',mul(-9,impactAge)))),squash=branch(before(.48),1,branch(before(1.45),compression,1)),bounce=branch(before(.22),add(1.15,mul(.95,smooth(div(t,.22)))),branch(before(.48),sub(2.1,mul(.95,o('pow',clamp(div(sub(t,.22),.26)),2))),mul(1.15,squash))),rise=add(1.15,mul(2.1,sub(1,o('pow',sub(1,clamp(div(launch,.55))),3)))),hoverY=add(3.25,mul(sin(mul(hover,9)),.035)),fallStart=3.25+Math.sin(.65*9)*.035,fallY=sub(fallStart,mul(fallStart-1.15,o('pow',clamp(div(fall,.22)),2))),x=branch(before(2),0,mul(.7,smooth(div(hover,.5)))),y=branch(before(1.45),bounce,branch(before(2),rise,branch(before(2.65),hoverY,branch(before(2.87),fallY,1.15)))),rx=branch(before(2),mul(90,smooth(div(t,.38))),mul(90,sub(1,smooth(div(hover,.55)))));
 const track=(channel,values)=>({node:'watcher',channel,keys:[],program:{values}});
 return[track('scale',[div(1,o('sqrt',squash)),div(1,o('sqrt',squash)),squash]),track('position',[x,y,0]),track('rotation',[rx,0,0]),track('eye.gaze',[0,0]),track('eye.open',[branch(before(1.45),sub(1,mul(.25,clamp(div(t,1.45)))),branch(before(2),1.18,branch(before(2.87),.4,1)))]),track('deform.stretch',[branch(before(2.65),1,branch(before(2.87),1.22,sub(1,mul(.33,o('cos',mul(sub(t,2.87),20)),o('exp',mul(-8,sub(t,2.87)))))))]),track('deform.waist',[branch(before(2.65),0,branch(before(2.87),.17,mul(-.15,o('cos',mul(sub(t,2.87),20)),o('exp',mul(-8,sub(t,2.87))))))])];
}
