import {poseAt,sampleTrack,identity,point,setKey} from '../runtime.js';
import {sampleScene} from '../scene3d/animation.js';
import {FOLLOW_PRESETS} from './core.js';
const uid=(list,prefix)=>{let n=1;while(list.some(x=>x.id===prefix+'-'+n))n++;return prefix+'-'+n;};
export function applyMotionCommand(project,c){const scene=c.dimension===3,doc=scene?project.scene3d:project,clip=doc?.clips.find(x=>x.id===c.clip)??doc?.clips[0];if(!clip)throw Error('Choose an animation first');const nodes=scene?doc.nodes:project.joints,joint=nodes.find(n=>n.id===(c.joint??c.node)),time=c.time??0;clip.tools??={};const tools=clip.tools;
 if(c.op==='motion.targetKey'){const t=tools.constraints?.find(t=>t.id===c.id);if(!t)throw Error('Missing target');t.pointKeys??=[];t.pointKeys=t.pointKeys.filter(k=>Math.abs(k.time-time)>1e-6);if(!c.remove)t.pointKeys.push({time,value:structuredClone(c.value),easing:c.easing??'linear',...(c.bezier?{bezier:c.bezier}:{})});t.pointKeys.sort((a,b)=>a.time-b.time);return;}
 if(c.op==='motion.remove'){for(const key of ['constraints','follow','layers'])if(tools[key])tools[key]=tools[key].filter(x=>x.id!==c.id);return;}
 if(c.op==='motion.update'||c.op==='motion.weight'){const item=Object.values(tools).flat().find(x=>x.id===c.id);if(!item)throw Error('Missing motion layer');if(c.op==='motion.update'){for(const [k,v]of Object.entries(c.values??{})){if(['__proto__','prototype','constructor','id'].includes(k))throw Error('Reserved property');item[k]=structuredClone(v);}}else{const keys=Array.isArray(item.weight)?item.weight:[{time:0,value:item.weight??1,easing:'smooth'}],next=keys.filter(k=>Math.abs(k.time-time)>1e-6);next.push({time,value:c.value,easing:'smooth'});item.weight=next.sort((a,b)=>a.time-b.time);}return c.id;}
 if(c.op==='motion.pose'){const list=tools.layers??=[],id=uid(list,'pose'),values={};const ids=c.all?nodes.map(n=>n.id):[joint?.id];if(scene){const sampled=sampleScene(doc,clip.id,time);for(const id of ids){const n=sampled.byId.get(id),rest=nodes.find(x=>x.id===id);if(!n)continue;values[id]={position:n.position.map((v,i)=>v-rest.position[i]),rotation:n.rotation.map((v,i)=>v-rest.rotation[i]),scale:n.scale.map((v,i)=>v/rest.scale[i]),'deform.waist':n.deform.waist-rest.deform.waist,'deform.taper':n.deform.taper-rest.deform.taper,'deform.stretch':n.deform.stretch-rest.deform.stretch,'deform.bend':n.deform.bend.map((v,i)=>v-rest.deform.bend[i])};}}else{const pose=poseAt(project,clip,time);for(const id of ids){const p=pose.get(id);if(!p)continue;values[id]=Object.fromEntries(Object.entries(p.transform).map(([k,v])=>[k,k.startsWith('scale')?v/p.joint.rest[k]:v-p.joint.rest[k]]));}}
 list.push({id,name:c.name??'Pose morph',values,weight:0,enabled:true});return id;}
 if(c.op==='motion.clip'){if(!doc.clips.some(x=>x.id===c.sourceClip))throw Error('Choose a source animation');const list=tools.layers??=[],id=uid(list,'animation'),ids=new Set([joint?.id]);if(c.all)for(const n of nodes)ids.add(n.id);else{let grew=true;while(grew){grew=false;for(const n of nodes)if(ids.has(n.parent)&&!ids.has(n.id)){ids.add(n.id);grew=true;}}}if(ids.has(undefined))throw Error('Choose a branch');list.push({id,name:'Layer '+doc.clips.find(x=>x.id===c.sourceClip).name,values:{},sourceClip:c.sourceClip,joints:[...ids],speed:1,offset:0,start:time,end:clip.duration,weight:.5,loop:true,enabled:true});return id;}
 if(c.op==='motion.layer'){const list=tools.layers??=[],id=c.id??uid(list,'layer');list.push({id,name:c.name??'Pose layer',values:structuredClone(c.values),weight:c.weight??1,enabled:true});return id;}
 if(!joint)throw Error('Select a joint or scene object first');
 if(c.op==='motion.follow'){const list=tools.follow??=[],id=uid(list,'follow'),preset=FOLLOW_PRESETS[c.preset??'natural'];if(!preset)throw Error('Unknown follow-through preset');list.push({id,joint:joint.id,source:c.source??joint.parent??joint.id,...preset,limit:45,weight:1,enabled:true});return id;}
 if(c.op==='motion.contact'||c.op==='motion.look'){if(scene&&joint.controller)throw Error('This actor owns its contact and aim during actions. Select a child or a regular scene object.');const list=tools.constraints??=[],id=uid(list,c.op==='motion.look'?'look':'contact'),s=joint.sprite,origin=scene?[0,-joint.dimensions[1]/2,0]:s?[(.5-s.pivotX)*s.width,(1-s.pivotY)*s.height]:[0,0],at=scene?c.point:point(poseAt(project,clip,time).get(joint.id).world,{x:origin[0],y:origin[1]});if(scene&&!at&&c.op==='motion.contact')throw Error('Scene contact needs a world point');const look=c.op==='motion.look',target=look?(c.point??(scene?[0,1,3]:[180,-120])):(scene?at:[at.x,c.ground?c.height??0:at.y]);const entry={id,type:look?'look':c.ground?'ground':'pin',joint:joint.id,point:target,origin:look?(scene?[0,0,0]:[0,0]):origin,weight:1,start:time,end:clip.duration,blend:.1,enabled:true,...(c.target?{target:c.target}:{}),...(look?{limit:70,forward:0}:{})};const mid=nodes.find(n=>n.id===joint.parent),root=nodes.find(n=>n.id===mid?.parent);if(!look&&c.chain!==false&&mid&&root?.parent)entry.chain={mid:mid.id,root:root.id};list.push(entry);return id;}
 if(c.op==='motion.smear'){if(scene){joint.trail={enabled:true,seconds:.18,samples:4,alpha:.3,color:'#afdbf3',threshold:.05,start:time,end:clip.duration,...c.values};return joint.id;}joint.visual??={};joint.visual.smear={enabled:true,seconds:.12,samples:6,alpha:.35,decay:1.5,tint:.5,color:'#afdbf3',start:time,end:clip.duration,threshold:15,stretch:.2,preserveVolume:true,...c.values};return joint.id;}
 if(c.op==='motion.morph'){if(scene){const list=tools.layers??=[],id=uid(list,'shape');list.push({id,name:c.name??'Inflate / bend',weight:1,enabled:true,values:{[joint.id]:{'deform.waist':.2,'deform.bend':[.15,0]}}});return id;}joint.visual??={};joint.visual.morph={enabled:true,inflate:.25,taper:0,bend:0,weight:1,...c.values};return joint.id;}
 throw Error('Unknown motion command '+c.op);
}
