import * as T from '../scene3d/vendor.js';
// Bounded geometry echoes. Pool allocation happens only when authoring changes;
// play captures previous rendered poses, including controller motion.
export class SceneTrails{
 constructor(host){this.host=host;this.entries=new Map();}
 clear(){for(const e of this.entries.values()){for(const c of e.copies){c.root.removeFromParent();for(const m of c.materials)m.dispose();}}this.entries.clear();}
 configure(){this.clear();const h=this.host;for(const n of h.project.scene3d.nodes){const t=n.trail;if(!t?.enabled)continue;const source=h.objects.get(n.id);if(!source)continue;const copies=[];for(let i=0;i<Math.min(12,t.samples??4);i++){const root=source.clone(true),materials=[],pairs=[];function pair(a,b){if(a.isMesh){const map=a.material?.uniforms?.art?.value??a.material?.map,material=new T.MeshBasicMaterial({color:t.color??'#b2d2ee',map:map??null,transparent:true,opacity:0,depthWrite:false,depthTest:true,side:T.FrontSide,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:2,alphaTest:map?.isTexture ? .02 : 0});b.material=material;materials.push(material);}const skip=!!a.userData.helper||a.isLine||a.isPoints;b.userData={helper:true};b.castShadow=false;b.visible=a.visible&&!skip;pairs.push([a,b,skip]);for(let j=0;j<a.children.length;j++)pair(a.children[j],b.children[j]);}pair(source,root);root.visible=false;root.name=n.name+' motion echo';h.scene.add(root);copies.push({root,pairs,materials,time:-Infinity});}this.entries.set(n.id,{source,copies,index:0,lastTime:-Infinity,lastPosition:new T.Vector3(),clip:null});}}
 update(){const h=this.host,time=h.time;for(const [id,e]of this.entries){const config=h.project.scene3d.nodes.find(n=>n.id===id)?.trail;if(!config?.enabled)continue;const point=e.source.getWorldPosition(new T.Vector3()),dt=time-e.lastTime,reset=e.clip!==h.clipId||dt<0||dt>.2;if(reset){for(const c of e.copies)c.time=-Infinity;e.lastTime=time;e.lastPosition.copy(point);e.clip=h.clipId;}const speed=dt>0&&Number.isFinite(dt)?point.distanceTo(e.lastPosition)/dt:0,active=time>=(config.start??0)&&time<=(config.end??Infinity),spacing=(config.seconds??.18)/e.copies.length;for(const c of e.copies){const age=time-c.time;c.root.visible=active&&age>0&&age<(config.seconds??.18);for(const m of c.materials)m.opacity=(config.alpha??.3)*Math.max(0,1-age/(config.seconds??.18));}
 if(!reset&&active&&dt>=spacing&&speed>=(config.threshold??.05)){const c=e.copies[e.index];e.index=(e.index+1)%e.copies.length;for(const [a,b,skip]of c.pairs){b.position.copy(a.position);b.quaternion.copy(a.quaternion);b.scale.copy(a.scale);b.visible=a.visible&&!skip;}c.root.position.copy(point);c.root.quaternion.copy(e.source.getWorldQuaternion(new T.Quaternion()));c.root.scale.copy(e.source.getWorldScale(new T.Vector3()));c.time=time;c.root.visible=false;e.lastTime=time;e.lastPosition.copy(point);}else if(!active){e.lastTime=time;e.lastPosition.copy(point);}
 }}
}
