import {activeDrawOrder,drawOrderMembers,resolvedDrawOrder} from './model.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountDrawOrder({project,context,revision,dispatch,pause,select,seek,toast,example}){
 const button=document.createElement('button');button.id='draw-order-open';button.textContent='Draw order';document.getElementById('motion-tools').before(button);
 const panel=document.createElement('aside');panel.id='draw-order-panel';panel.className='author-panel';panel.setAttribute('aria-label','Animated draw order');panel.hidden=true;document.body.append(panel);const style=document.createElement('style');style.textContent='#draw-order-panel .rule-choice{display:flex;flex-direction:row;align-items:center;gap:8px}#draw-order-panel .rule-choice input{width:auto;flex:none;margin:0}';document.head.append(style);let stamp='';
 const options=(items,current)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===current?'selected':''}>${esc(label)}</option>`).join('');
 function run(c){try{pause();dispatch({node:context().selected,clip:context().clip.id,time:context().time,...c});stamp='';refresh();}catch(e){toast(e.message,true);stamp='';refresh();}}
 function refresh(){if(panel.hidden)return;const a=context(),key=[revision(),a.dimension,a.selected,a.clip?.id,a.time,a.mode].join(':');if(key===stamp)return;if(panel.contains(document.activeElement)&&document.activeElement.matches('input,select')&&stamp.split(':').slice(0,4).join(':')===key.split(':').slice(0,4).join(':'))return;stamp=key;
  const e=project().drawOrder?.find(e=>e.node===a.selected),members=drawOrderMembers(project(),a.selected),targets=project().joints.filter(j=>j.sprite&&!members.has(j.id)),active=e?activeDrawOrder(e,a.mode==='rig'?null:a.clip,a.time):null,keys=a.clip?.drawOrderTracks?.find(t=>t.node===a.selected)?.keys??[];
  panel.innerHTML=`<header><div><strong>Draw-order rules</strong><small>${a.mode==='rig'?'Rig defaults':'Hold keys · '+a.time.toFixed(2)+'s'}</small></div><button data-action="close" aria-label="Close draw order">×</button></header><button data-action="example">Load draw-order example</button>${a.dimension!==2?'<p>Edit these rules in the 2D rig. They also play in 3D puppet layers.</p>':`<label>Working on<select id="draw-order-owner">${options(project().joints.map(j=>[j.id,j.name]),a.selected)}</select></label><p>Move this piece and its descendants above or below a drawable target. Parenting and transforms stay unchanged.</p><label class="rule-choice"><input type="radio" name="draw-order-rule" data-rule="" ${active===null?'checked':''}> Normal · base order</label>${(e?.rules??[]).map(r=>`<article data-id="${esc(r.id)}"><label class="rule-choice"><input type="radio" name="draw-order-rule" data-rule="${esc(r.id)}" ${active===r.id?'checked':''}>${esc(r.name)}</label><label>Name<input data-field="name" value="${esc(r.name)}"></label><label>Placement<select data-field="placement">${options([['above','Above target'],['below','Below target']],r.placement)}</select></label><label>Target<select data-field="target">${options(targets.map(j=>[j.id,j.name]),r.target)}</select></label><button data-action="remove">Delete rule</button></article>`).join('')}<section><h3>New rule</h3><label>Placement<select id="draw-order-placement"><option value="above">Above target</option><option value="below">Below target</option></select></label><label>Target<select id="draw-order-target">${options(targets.map(j=>[j.id,j.name]),targets[0]?.id)}</select></label><button data-action="add" ${targets.length?'':'disabled'}>Add rule</button></section><p>${a.mode==='rig'?'Selecting a rule changes the rig default.':'Selecting a rule records a hold key at the playhead, including when you select Normal. Before the first key, the rig default applies.'}</p><section><h3>Keys in ${esc(a.clip.name)}</h3>${keys.length?keys.map(k=>`<div class="button-row"><button data-seek="${k.time}">${k.time.toFixed(3)}s · ${esc(e.rules.find(r=>r.id===k.value)?.name??'Normal')}</button><button data-delete-key="${k.time}" aria-label="Delete draw-order key">×</button></div>`).join(''):'<p>No draw-order keys in this clip.</p>'}<button data-action="timeline">Edit keys in Timeline</button></section><details><summary>Current order · back to front</summary><ol>${resolvedDrawOrder(project(),a.mode==='rig'?null:a.clip,a.time).map(id=>`<li>${esc(project().joints.find(j=>j.id===id)?.name)}</li>`).join('')}</ol></details>`}`;
 }
 panel.onchange=e=>{const el=e.target,a=context();if(el.id==='draw-order-owner'){pause();select(el.value);stamp='';refresh();return;}if(el.dataset.field)run({op:'drawOrder.update',id:el.closest('[data-id]').dataset.id,values:{[el.dataset.field]:el.value}});};
 panel.onclick=async e=>{const choice=e.target.closest('[data-rule]');if(choice){const a=context();if(project().drawOrder?.some(e=>e.node===a.selected))run({op:a.mode==='rig'?'drawOrder.default':'drawOrder.key',rule:choice.dataset.rule||null});return;}const b=e.target.closest('button');if(!b)return;const action=b.dataset.action;if(action==='close')panel.hidden=true;if(action==='example'){await example();stamp='';refresh();}if(action==='add')run({op:'drawOrder.add',placement:panel.querySelector('#draw-order-placement').value,target:panel.querySelector('#draw-order-target').value});if(action==='remove')run({op:'drawOrder.remove',id:b.closest('[data-id]').dataset.id});if(action==='timeline')document.getElementById('timeline-open').click();if(b.dataset.deleteKey!==undefined)run({op:'drawOrder.key',time:+b.dataset.deleteKey,remove:true});if(b.dataset.seek!==undefined){pause();seek(+b.dataset.seek);stamp='';refresh();}};
 const show=()=>{panel.hidden=false;stamp='';refresh();};button.onclick=()=>panel.hidden?show():panel.hidden=true;setInterval(refresh,120);return{show,hide(){panel.hidden=true;}};
}
