import * as T from './vendor.js';
import {loadImages} from '../runtime.js';
import {drawBackdrop} from '../authoring/backdrop-render.js';
export class SceneBackdrop{
 constructor(host){this.host=host;this.canvas=document.createElement('canvas');this.texture=new T.CanvasTexture(this.canvas);this.texture.colorSpace=T.SRGBColorSpace;this.texture.minFilter=T.LinearFilter;this.texture.generateMipmaps=false;this.images=new Map();this.signature='';this.frame='';this.revision=0;}
 async configure(project,baseURL=document.baseURI){const refs=new Set(project.backdrop?.layers.map(l=>l.asset)??[]),assets=project.assets.filter(a=>refs.has(a.id)).map(a=>({...a,src:new URL(a.src,baseURL).href})),signature=JSON.stringify([project.backdrop,assets]);if(signature===this.signature)return;const generation=++this.revision,images=await loadImages({assets});if(generation!==this.revision)return;this.images=images;this.signature=signature;this.frame='';}
 update(){const h=this.host,p=h.project,b=p?.backdrop;if(!b?.enabled||h.view!=='colour'){if(h.scene.background===this.texture)h.scene.background=new T.Color(p?.scene3d.environment.background??'#303034');return false;}const c=h.camera,def=p.scene3d.camera,anchor=def.target,target=h.controls?.target?.toArray()??anchor,span=c.isOrthographicCamera?(c.top-c.bottom):2*Math.tan(T.MathUtils.degToRad(c.fov/2))*c.position.distanceTo(new T.Vector3(...target)),direction=c.getWorldDirection(new T.Vector3()),yaw=Math.atan2(direction.x,-direction.z),initial=new T.Vector3(...def.target).sub(new T.Vector3(...def.position)),baseYaw=Math.atan2(initial.x,-initial.z),turn=Math.atan2(Math.sin(yaw-baseYaw),Math.cos(yaw-baseYaw)),view={x:(target[0]-anchor[0])/Math.max(.1,span)+turn/Math.PI,y:-(target[1]-anchor[1])/Math.max(.1,span),zoom:c.zoom/(def.zoom??1)},dpr=Math.min(2,h.renderer.getPixelRatio()),width=Math.max(1,Math.round(h.width*dpr)),height=Math.max(1,Math.round(h.height*dpr)),animated=b.tracks.length||b.layers.some(l=>l.tracks.length||l.drift.some(v=>v!==0)||this.images.get(l.asset)?.vectorModel?.tracks.length),time=animated?Math.round(h.time*60)/60:0,key=JSON.stringify([this.revision,width,height,view,time,p.appearance]);this.view=view;if(this.frame!==key){if(this.canvas.width!==width||this.canvas.height!==height)this.texture.dispose();if(this.canvas.width!==width)this.canvas.width=width;if(this.canvas.height!==height)this.canvas.height=height;const ctx=this.canvas.getContext('2d');ctx.clearRect(0,0,width,height);ctx.fillStyle=p.scene3d.environment.background;ctx.fillRect(0,0,width,height);drawBackdrop(ctx,p,this.images,time,view);this.texture.needsUpdate=true;this.frame=key;}const changed=h.scene.background!==this.texture||h.dirty||this.lastKey!==key;this.lastKey=key;h.scene.background=this.texture;return changed;}
 dispose(){++this.revision;this.texture.dispose();this.images.clear();}
}
