import * as T from './vendor.js';
import {deformPoint} from './effects.js';
// Ray tests use posed triangles too; GPU deformation must not leave an invisible
// undeformed collider behind. Cache by transform + pose, never by camera zoom.
export class SceneCollisions{
 constructor(){this.entries=new Map();}
 update(meshes,defs,objects){const live=new Set(meshes);for(const [mesh,entry]of this.entries)if(!live.has(mesh)){entry.mesh.geometry.dispose();this.entries.delete(mesh);}const result=[];for(const source of meshes){if(!source.visible)continue;const chain=[];let node=defs.get(source.userData.node);while(node){chain.push(node);node=defs.get(node.parent);}const signature=source.geometry.attributes.position.version+':'+source.matrixWorld.elements.join(',')+chain.map(n=>JSON.stringify(n.deform)+objects.get(n.id).matrixWorld.elements.join(',')).join(':');let entry=this.entries.get(source);if(!entry){const g=new T.BufferGeometry();g.setAttribute('position',source.geometry.attributes.position.clone());if(source.geometry.index)g.setIndex(source.geometry.index);for(const group of source.geometry.groups)g.addGroup(group.start,group.count,group.materialIndex);const mesh=new T.Mesh(g,new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.userData={...source.userData,source};entry={mesh,signature:null};this.entries.set(source,entry);}if(entry.signature!==signature){const p=source.geometry.attributes.position,out=entry.mesh.geometry.attributes.position,v=new T.Vector3(),transforms=chain.map(n=>({n,m:objects.get(n.id).matrixWorld,inverse:objects.get(n.id).matrixWorld.clone().invert()}));for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(source.matrixWorld);for(const {n,m,inverse}of transforms){v.applyMatrix4(inverse);deformPoint(v,n);v.applyMatrix4(m);}out.setXYZ(i,v.x,v.y,v.z);}out.needsUpdate=true;entry.mesh.geometry.computeVertexNormals();entry.mesh.geometry.computeBoundingSphere();entry.mesh.geometry.computeBoundingBox();entry.signature=signature;}result.push(entry.mesh);}return result;}
 dispose(){for(const e of this.entries.values()){e.mesh.geometry.dispose();e.mesh.material.dispose();}this.entries.clear();}
}
