import {AuthoredEffects} from './authored-effects.js';
import {SceneDecals} from './decals.js';
import * as T from './vendor.js';
const Z=new T.Vector3(0,0,1),Y=new T.Vector3(0,1,0),hash=x=>{const a=Math.sin(x*127.1+311.7)*43758.5453123;return a-Math.floor(a);};
export function deformPoint(p,node){const d=node.deform,h=node.dimensions[1]/2,u=T.MathUtils.clamp(p.y/h,-1,1),r=(1-d.waist*(1-u*u))*(1+d.taper*u)/Math.sqrt(d.stretch);p.x=p.x*r+d.bend[0]*h*((u+1)/2)**2;p.z=p.z*r+d.bend[1]*h*((u+1)/2)**2;p.y=(p.y+h)*d.stretch-h;return p;}
export function toWorld(p,node,objects,defs){p.applyMatrix4(objects.get(node.id).matrixWorld);let n=node;while(n){const matrix=objects.get(n.id).matrixWorld;p.applyMatrix4(matrix.clone().invert());deformPoint(p,n);p.applyMatrix4(matrix);n=defs.get(n.parent);}return p;}
const decalMaterial=map=>new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2,uniforms:{map:{value:map},color:{value:new T.Color()},alpha:{value:1},spread:{value:1},useMap:{value:map?1:0},age:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D map;uniform vec3 color;uniform float alpha,spread,useMap,age;varying vec2 vUv;void main(){vec2 uv=(vUv-.5)/max(.01,spread)+.5;if(any(lessThan(uv,vec2(0.)))||any(greaterThan(uv,vec2(1.))))discard;vec4 paint=texture2D(map,uv);float a=paint.a;vec3 c=mix(color,vec3(1.,.985,.93),clamp((paint.b-.025)/.85,0.,.97))*clamp(max(paint.r,max(paint.g,paint.b))/.72,.62,1.);if(useMap<.5){float r=length(uv-.5)*2.,wave=abs(sin(r*16.-age*7.));a=(1.-smoothstep(.88,1.,r))*smoothstep(.7,.9,wave);c=color;}gl_FragColor=vec4(c,a*alpha);\n#include <colorspace_fragment>\n}`});
export class SceneEffects{
 constructor(scene){this.scene=scene;this.root=new T.Group();this.root.renderOrder=15;scene.add(this.root);this.decals=new SceneDecals(this.root);this.authored=new AuthoredEffects(this.root);this.entries=new Map();this.maps=new Map();this.audio=null;this.lastTime=-1;this.lastClip='';this.muted=true;this.signature='';}
 async configure(project,asset){const signature=JSON.stringify(project.scene3d.clips.map(c=>({id:c.id,events:c.events})))+JSON.stringify([project.scene3d.effectLibraries,project.scene3d.audioLibraries])+project.assets.map(a=>a.id+a.src).join('|');if(signature===this.signature)return;const request=this.request=(this.request??0)+1,ids=new Set(project.scene3d.clips.flatMap(c=>c.events.flatMap(e=>e.type==='decal'||e.effect?[]:[e.asset,e.impactAsset].filter(Boolean)))),maps=new Map();try{await Promise.all([...ids].map(async id=>{const map=await new T.TextureLoader().loadAsync(asset(id));map.colorSpace=T.SRGBColorSpace;maps.set(id,map);}));}catch(e){maps.forEach(t=>t.dispose());throw e;}if(request!==this.request){maps.forEach(t=>t.dispose());return;}this.clear();this.maps=maps;for(const clip of project.scene3d.clips)for(const e of clip.events)if(!e.effect&&['beam','impact'].includes(e.type))this.make(e,clip.id+':'+e.id);await this.decals.configure(project,asset);await this.authored.configure(project,asset);this.signature=signature;}

 unlock(){this.audio??=new AudioContext();if(this.audio.state==='suspended'&&navigator.userActivation?.hasBeenActive===false)throw Error('Click the editor once to enable sound, or set audible:false for silent playback.');this.muted=false;this.onUnlock?.();this.authored.unlock();return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Click the editor once to enable sound, or set audible:false for silent playback.')),1500);this.audio.resume().then(()=>{clearTimeout(timer);resolve();},error=>{clearTimeout(timer);reject(error);});});}
 sound(e){if(this.muted||!this.audio)return;const a=this.audio,now=a.currentTime,pitch=(e.pitch??100)*(1+(Math.random()-.5)*.16),level=(e.volume??.12)*(.85+Math.random()*.3);for(let i=0;i<2;i++){const o=a.createOscillator(),g=a.createGain();o.type=e.wave??(i?'triangle':'sine');o.frequency.setValueAtTime(pitch*(i?2.01:1),now);o.frequency.exponentialRampToValueAtTime(Math.max(20,pitch*.25),now+.3);g.gain.setValueAtTime(level*(i?.22:1),now);g.gain.exponentialRampToValueAtTime(.0001,now+.4);o.connect(g).connect(a.destination);o.start(now);o.stop(now+.42);}this.noise??=(()=>{const b=a.createBuffer(1,a.sampleRate,a.sampleRate),v=b.getChannelData(0);for(let i=0;i<v.length;i++)v[i]=Math.random()*2-1;return b;})();const n=a.createBufferSource(),filter=a.createBiquadFilter(),g=a.createGain();n.buffer=this.noise;filter.type='lowpass';filter.frequency.setValueAtTime(pitch*8,now);filter.frequency.exponentialRampToValueAtTime(80,now+.25);g.gain.setValueAtTime(level*.4,now);g.gain.exponentialRampToValueAtTime(.0001,now+.25);n.connect(filter).connect(g).connect(a.destination);n.start(now,Math.random()*.4,.3);}
 make(e,key){const root=new T.Group(),mat=new T.MeshBasicMaterial({color:e.color??'#f5cb67',transparent:true,depthWrite:false}),core=new T.Mesh(new T.CylinderGeometry(1,1,1,16,1,true),mat),inner=new T.Mesh(core.geometry,new T.MeshBasicMaterial({color:'#fff2cc',transparent:true,depthWrite:false})),charge=new T.Group(),orb=new T.Mesh(new T.SphereGeometry(1,16,12),mat),swirls=[];charge.add(orb);for(let i=0;i<2;i++){const ring=new T.Mesh(new T.TorusGeometry(1,.045,5,48,Math.PI*1.65),mat);charge.add(ring);swirls.push(ring);}root.add(core,inner,charge);const stamp=new T.Mesh(new T.BufferGeometry(),decalMaterial(this.maps.get(e.asset??e.impactAsset))),sparks=new T.InstancedMesh(new T.SphereGeometry(1,5,3),mat,28);root.add(stamp,sparks);const light=new T.PointLight(e.color??'#f5cb67',0,7,2);this.scene.add(light);const entry={root,mat,core,inner,charge,orb,swirls,stamp,sparks,light,contact:null};this.root.add(root);this.entries.set(key,entry);return entry;}
 updateDecal(fx,hit,normal,size){if(!hit){fx.stamp.visible=false;return;}const last=fx.contact,version=hit.object.geometry.attributes.position.version;if(last&&last.object===hit.object&&last.point.distanceToSquared(hit.point)<.0004&&last.normal.dot(normal)>.999&&last.version===version&&last.size===size){fx.stamp.visible=true;return;}const orientation=new T.Euler().setFromQuaternion(new T.Quaternion().setFromUnitVectors(Z,normal)),g=new T.DecalGeometry(hit.object,hit.point,orientation,new T.Vector3(size*3,size*3,.10));fx.stamp.geometry.dispose();fx.stamp.geometry=g;fx.stamp.visible=true;fx.contact={object:hit.object,point:hit.point.clone(),normal:normal.clone(),version,size};}
 update(time,clip,objects,defs,targets,palettes,{audible=false,projectPoint=null}={}){const project=projectPoint??toWorld;for(const fx of this.entries.values()){fx.root.visible=false;fx.light.intensity=0;}let shake=0;for(const e of clip.events){const age=time-e.time,active=age>=0&&age<e.duration;if(e.effect)continue;if(e.type==='sound'){if(!e.audio&&audible&&this.lastClip===clip.id&&this.lastTime<e.time&&time>=e.time)this.sound(e);continue;}if(!active)continue;if(e.type==='shake')continue;if(e.type==='hitstop')continue;const node=defs.get(e.node),object=objects.get(e.node);if(!object||!node)continue;const fx=this.entries.get(clip.id+':'+e.id);if(!fx)continue;fx.root.visible=true;const color=e.color??node.effectColor??palettes.get(node.material)?.[1]??'#f5cb67';fx.mat.color.set(color);fx.light.color.set(color);fx.stamp.material.uniforms.color.value.set(color);let point,normal=new T.Vector3(0,1,0),strength=1,hit;const emitter=project(new T.Vector3(...(e.origin??[0,0,node.dimensions[2]/2+.03])),node,objects,defs);
 if(e.type==='beam'){const charge=e.charge??.6,fire=age>=charge,localDir=new T.Vector3(...(e.direction??[0,-.2,1])).normalize(),origin=new T.Vector3(...(e.origin??[0,0,node.dimensions[2]/2+.03])),near=project(origin.addScaledVector(localDir,.01),node,objects,defs),dir=near.sub(emitter).normalize();hit=new T.Raycaster(emitter,dir,.015,e.length??20).intersectObjects(targets.filter(m=>m.userData.node!==e.node),false)[0];point=hit?.point??emitter.clone().addScaledVector(dir,e.length??20);normal=hit?.face?hit.face.normal.clone().applyMatrix3(new T.Matrix3().getNormalMatrix(hit.object.matrixWorld)).normalize():dir.clone().negate();if(normal.dot(dir)>0)normal.negate();const length=point.distanceTo(emitter),envelope=fire?Math.min(1,(age-charge)*18)*Math.min(1,(e.duration-age)*8):0;for(const [i,mesh]of [fx.core,fx.inner].entries()){mesh.visible=fire;mesh.position.copy(emitter).addScaledVector(dir,length/2);mesh.quaternion.setFromUnitVectors(Y,dir);mesh.scale.set((e.width??.09)*envelope*(i?.32:1),length,(e.width??.09)*envelope*(i?.32:1));}fx.mat.opacity=fire?.85:.55;strength=fire?envelope:age/charge;fx.charge.visible=true;fx.charge.position.copy(emitter);fx.charge.quaternion.setFromUnitVectors(Z,dir);fx.orb.scale.setScalar((fire?.14:.05+.2*strength)*(1+.1*Math.sin(age*45)));for(let i=0;i<2;i++){const ring=fx.swirls[i];ring.scale.setScalar((fire?.2:.6*(1-strength)+.2)*(i?1.3:1));ring.rotation.z=age*(i?-4:5);ring.rotation.x=Math.sin(age*4+i)*.2;}fx.light.position.copy(emitter);fx.light.intensity=(fire?6:2)*strength;this.updateDecal(fx,fire?hit:null,normal,e.size??.8);if(!fire){point=emitter;normal.copy(dir);}fx.root.userData.contact=hit?{node:hit.object.userData.node,point:hit.point.toArray(),normal:normal.toArray()}:null;
 }else{const start=emitter.clone().addScaledVector(Y,.2);hit=new T.Raycaster(start,new T.Vector3(0,-1,0),0,1).intersectObjects(targets.filter(m=>m.userData.node!==e.node),false)[0];point=hit?.point??emitter;normal=hit?.face?.normal.clone()??Y.clone();strength=Math.sin(Math.min(1,age/e.duration)*Math.PI);fx.core.visible=fx.inner.visible=fx.charge.visible=false;this.updateDecal(fx,hit,normal,e.size??1);}
 const size=(e.size??.8)*strength,u=fx.stamp.material.uniforms;u.alpha.value=(e.type==='beam'?.75:1-age/e.duration)*strength;u.spread.value=e.type==='beam'?.65+.04*Math.sin(age*24):.35+.55*(1-(1-age/e.duration)**3);u.age.value=age;
 const tangent=new T.Vector3().crossVectors(normal,Math.abs(normal.y)>.9?Z:Y).normalize(),bitangent=new T.Vector3().crossVectors(normal,tangent),dummy=new T.Object3D();for(let i=0;i<28;i++){const p=(age*(1.6+hash(i)*1.2)+hash(i+41))%1,angle=hash(i+10)*Math.PI*2,travel=p*(.25+hash(i+31)*.9)*size;dummy.position.copy(point).addScaledVector(tangent,Math.cos(angle)*travel).addScaledVector(bitangent,Math.sin(angle)*travel).addScaledVector(normal,Math.sin(p*Math.PI)*size*.55+.02);dummy.scale.setScalar((1-p)*(.025+hash(i)*.05)*strength);dummy.updateMatrix();fx.sparks.setMatrixAt(i,dummy.matrix);}fx.sparks.instanceMatrix.needsUpdate=true;}
 this.decals.update(time,clip,objects,defs,targets,palettes,project);this.authored.update(time,clip,objects,defs,targets,palettes,project,audible&&!this.muted);this.lastTime=time;this.lastClip=clip.id;return shake;}
 pause(){this.onPause?.();this.authored.stopAudio();}
 clear(){this.decals.clear();this.authored.clear();for(const e of this.entries.values()){e.root.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});e.root.removeFromParent();e.light.removeFromParent();}this.entries.clear();for(const t of this.maps.values())t.dispose();this.maps.clear();this.lastTime=-1;this.lastClip='';}
 dispose(){this.request=(this.request??0)+1;this.clear();this.root.removeFromParent();this.audio?.close();}
}
