import {sliceGeometry,slicingSourceSize} from '../slicing/geometry.js';
import {subdivideIndexed} from './subdivision.js';
import * as T from './vendor.js';
const cache=new Map();
export function roleFor(color){const c=color.clone().convertLinearToSRGB(),max=Math.max(c.r,c.g,c.b);if(max<.12)return[3,1];if(c.r>.7&&c.g>.65&&c.b>.4)return[2,Math.min(1.1,max/.93)];if(c.r>c.b*1.4&&c.r>c.g*1.06)return[1,Math.min(1.1,max/.77)];return[0,Math.min(1.35,max/.29)];}
export async function parseSVG(src){if(!cache.has(src))cache.set(src,fetch(src).then(r=>{if(!r.ok)throw Error('SVG artwork unavailable');return r.text();}).then(text=>new T.SVGLoader().parse(text)).catch(e=>{cache.delete(src);throw e;}));return cache.get(src);}
function extrudedSVGGeometry(parsed,width=2,height=2,segments=12,depth=0){const box=(parsed.xml.getAttribute('viewBox')??`0 0 ${parsed.xml.getAttribute('width')} ${parsed.xml.getAttribute('height')}`).trim().split(/[ ,]+/).map(Number),geos=[];let layer=0;for(const path of parsed.paths){if(path.userData.style.fill==='none')continue;let [role,tone]=roleFor(path.color);const label=path.userData.node?.getAttribute('data-ink-role');if(label==='literal'){role=4;tone=1;}else if(['body','accent','paper','ink'].includes(label))role=['body','accent','paper','ink'].indexOf(label);for(const shape of T.SVGLoader.createShapes(path)){const g=depth?new T.ExtrudeGeometry(shape,{depth,bevelEnabled:false,steps:8,curveSegments:segments}):new T.ShapeGeometry(shape,segments);const p=g.attributes.position;for(let i=0;i<p.count;i++){p.setXYZ(i,((p.getX(i)-box[0])/box[2]-.5)*width,(.5-(p.getY(i)-box[1])/box[3])*height,depth?p.getZ(i)-depth/2:layer*.000003);}if(g.index){for(let i=0;i<g.index.count;i+=3){const a=g.index.getX(i);g.index.setX(i,g.index.getX(i+2));g.index.setX(i+2,a);}}else{for(const attr of Object.values(g.attributes))for(let i=0;i<attr.count;i+=3)for(let c=0;c<attr.itemSize;c++){const a=attr.array[i*attr.itemSize+c];attr.array[i*attr.itemSize+c]=attr.array[(i+2)*attr.itemSize+c];attr.array[(i+2)*attr.itemSize+c]=a;}}
 g.deleteAttribute('normal');g.computeVertexNormals();g.setAttribute('sourcePaint',new T.Float32BufferAttribute(Array.from({length:p.count*3},(_,i)=>[path.color.r,path.color.g,path.color.b][i%3]),3));g.setAttribute('paintRole',new T.Float32BufferAttribute(new Float32Array(p.count).fill(role),1));g.setAttribute('paintTone',new T.Float32BufferAttribute(new Float32Array(p.count).fill(tone),1));g.setAttribute('uv',new T.Float32BufferAttribute(Array.from({length:p.count*2},(_,i)=>i%2?p.getY(Math.floor(i/2))/height+.5:p.getX(Math.floor(i/2))/width+.5),2));geos.push(g.toNonIndexed());g.dispose();}layer++;}if(!geos.length)throw Error('SVG has no filled shapes');const merged=T.mergeGeometries(geos);geos.forEach(g=>g.dispose());merged.computeBoundingSphere();return merged;}
// Flatten curves by screen error instead of allocating the same number of
// vertices to every short segment in generated artwork.
function flatten(path,tolerance){const pts=[];for(const curve of path.curves){const a=curve.getPoint(0),b=curve.getPoint(1);if(!pts.length)pts.push(a);const visit=(t0,p0,t1,p1,depth)=>{const chord=p1.clone().sub(p0),len=chord.length(),error=p=>len?Math.abs(chord.x*(p0.y-p.y)-(p0.x-p.x)*chord.y)/len:p.distanceTo(p0),mid=curve.getPoint((t0+t1)/2);if(depth<12&&Math.max(error(mid),error(curve.getPoint(t0+(t1-t0)*.25)),error(curve.getPoint(t0+(t1-t0)*.75)))>tolerance){visit(t0,p0,(t0+t1)/2,mid,depth+1);visit((t0+t1)/2,mid,t1,p1,depth+1);}else pts.push(p1);};visit(0,a,1,b,0);}if(pts.length>1&&pts[0].distanceToSquared(pts.at(-1))<1e-10)pts.pop();return pts;}
export function svgGeometry(parsed,width=2,height=2,segments=12,depth=0){
 if(depth)return extrudedSVGGeometry(parsed,width,height,segments,depth);
 const box=(parsed.xml.getAttribute('viewBox')??`0 0 ${parsed.xml.getAttribute('width')} ${parsed.xml.getAttribute('height')}`).trim().split(/[ ,]+/).map(Number),pos=[],normal=[],uv=[],roles=[],tones=[],sourcePaint=[],index=[],tolerance=.48*12/segments;
 function append(vertices,triangles,color,label){let [role,tone]=roleFor(color);if(label==='literal'){role=4;tone=1;}else if(['body','accent','paper','ink'].includes(label))role=['body','accent','paper','ink'].indexOf(label);const base=pos.length/3;for(const v of vertices){const x=(v.x-box[0])/box[2],y=(v.y-box[1])/box[3];pos.push((x-.5)*width,(.5-y)*height,0);normal.push(0,0,1);uv.push(x,1-y);roles.push(role);tones.push(tone);sourcePaint.push(color.r,color.g,color.b);}for(const tri of triangles)index.push(...tri.slice().reverse().map(i=>i+base));}
 for(const path of parsed.paths){const label=path.userData.node?.getAttribute('data-ink-role'),style=path.userData.style;if(style.fill!=='none')for(const shape of T.SVGLoader.createShapes(path)){const contour=flatten(shape,tolerance),holes=shape.holes.map(h=>flatten(h,tolerance));if(contour.length<3)continue;append(contour.concat(...holes),T.ShapeUtils.triangulateShape(contour,holes),path.color,label);}if(style.stroke&&style.stroke!=='none'&&style.strokeWidth>0)for(const sub of path.subPaths){const points=flatten(sub,tolerance);if(sub.autoClose&&points.length)points.push(points[0]);if(points.length<2)continue;const stroke=T.SVGLoader.pointsToStroke(points,style,8);if(!stroke)continue;const p=stroke.attributes.position,verts=Array.from({length:p.count},(_,i)=>new T.Vector2(p.getX(i),p.getY(i))),tris=Array.from({length:p.count/3},(_,i)=>[i*3,i*3+1,i*3+2]);append(verts,tris,new T.Color(style.stroke),label);stroke.dispose();}}
 if(!index.length)throw Error('SVG has no filled shapes or strokes');const g=new T.BufferGeometry();for(const [name,values,size]of [['position',pos,3],['normal',normal,3],['uv',uv,2],['sourcePaint',sourcePaint,3],['paintRole',roles,1],['paintTone',tones,1]])g.setAttribute(name,new T.Float32BufferAttribute(values,size));g.setIndex(index);return subdivideIndexed(g,Math.max(width,height)/28);
}
export async function primitiveGeometry(n,asset){const [x,y,z]=slicingSourceSize(n),s=n.smoothOutline!==false&&['sphere','cylinder','cone','lathe'].includes(n.type)?Math.max(64,n.segments):n.segments;let g;switch(n.type){case'mesh':g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(n.mesh.positions,3));g.setAttribute('normal',new T.Float32BufferAttribute(n.mesh.normals,3));g.setAttribute('uv',new T.Float32BufferAttribute(n.mesh.uvs??n.mesh.positions.flatMap((v,i)=>i%3===0?[v+.5,n.mesh.positions[i+1]+.5]:[]),2));g.setIndex(n.mesh.indices);g.scale(x,y,z);break;case'box':g=new T.BoxGeometry(x,y,z,48,48,48);break;case'rounded-box':g=new T.RoundedBoxGeometry(x,y,z,Math.min(8,s),Math.min(n.radius,x/2,y/2,z/2));break;case'sphere':g=new T.SphereGeometry(x/2,s,Math.max(12,s/2));g.scale(1,y/x,z/x);break;case'cylinder':g=new T.CylinderGeometry(x/2,x/2,y,s,12);g.scale(1,1,z/x);break;case'cone':g=new T.ConeGeometry(x/2,y,s,12);g.scale(1,1,z/x);break;case'plane':g=new T.PlaneGeometry(x,y,Math.max(4,s),Math.max(4,s));break;case'lathe':g=new T.LatheGeometry(n.profile.map(p=>new T.Vector2(...p)),s);g.computeBoundingBox();{const size=g.boundingBox.getSize(new T.Vector3());g.center();g.scale(x/Math.max(size.x,.001),y/Math.max(size.y,.001),z/Math.max(size.z,.001));}break;case'extrude':case'svg':g=svgGeometry(await parseSVG(asset(n.svg)),x,y,s,n.type==='extrude'?z:0);break;default:return null;}if(!g.attributes.sourcePaint)g.setAttribute('sourcePaint',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count*3),3));if(!g.attributes.paintRole){g.setAttribute('paintRole',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count),1));g.setAttribute('paintTone',new T.Float32BufferAttribute(new Float32Array(g.attributes.position.count).fill(1),1));}return sliceGeometry(g,n.slicing,n.dimensions);}
export const faceTransform=(name,[x,y,z])=>({front:{position:[0,0,z/2+.006],rotation:[0,0,0],size:[x,y]},back:{position:[0,0,-z/2-.006],rotation:[0,Math.PI,0],size:[x,y]},right:{position:[x/2+.006,0,0],rotation:[0,Math.PI/2,0],size:[z,y]},left:{position:[-x/2-.006,0,0],rotation:[0,-Math.PI/2,0],size:[z,y]},top:{position:[0,y/2+.006,0],rotation:[-Math.PI/2,0,0],size:[x,z]},bottom:{position:[0,-y/2-.006,0],rotation:[Math.PI/2,0,0],size:[x,z]}}[name]);
export function disposeGroup(root){const geometries=new Set(),materials=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);if(m.userData.depth)materials.add(m.userData.depth);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}

// Only the outline hull shares normals across face/UV seams. The coloured mesh
// keeps intentional hard corners and paint islands, so smoothing cannot smear art.
export function smoothOutlineGeometry(geometry){
 const g=geometry.clone(),p=g.attributes.position,n=g.attributes.normal;if(!n)return g;
 const groups=new Map();
 for(let i=0;i<p.count;i++){const key=[p.getX(i),p.getY(i),p.getZ(i)].map(v=>Math.round(v*1e6)).join(','),entry=groups.get(key)??{ids:[],normal:new T.Vector3()};entry.ids.push(i);entry.normal.add(new T.Vector3(n.getX(i),n.getY(i),n.getZ(i)));groups.set(key,entry);}
 for(const {ids,normal}of groups.values()){if(normal.lengthSq()<1e-12)continue;normal.normalize();for(const i of ids)n.setXYZ(i,normal.x,normal.y,normal.z);}n.needsUpdate=true;return g;
}
