import {coloringDefaults} from './core/lighting-definition.js';
export const rgbHex=v=>'#'+v.map(x=>Math.round(Math.max(0,Math.min(1,x))*255).toString(16).padStart(2,'0')).join('');
export const hexRGB=v=>[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)/255);
export function lightingFields(n,field){
 const rgb=(label,path,v)=>`<label>${label}<input type="color" data-rgb="${path}" value="${rgbHex(v)}"></label>`;
 const check=(label,path,v)=>`<label><input type="checkbox" data-field="${path}" ${v?'checked':''}> ${label}</label>`;
 const select=(label,path,v,items)=>`<label>${label}<select data-field="${path}">${items.map(i=>`<option value="${i}" ${i===v?'selected':''}>${i}</option>`).join('')}</select></label>`;
 const vector=(title,path,values,labels=['X','Y','Z'])=>`<fieldset><legend>${title}</legend>${values.map((v,i)=>field(labels[i],path+'.'+i,v)).join('')}</fieldset>`;
 const l=n.light,c=n.coloring??coloringDefaults();
 return `<details open><summary>Light source</summary><div class="s3-palette">${['firefly','window','lantern'].map(p=>`<button data-light-preset="${p}">${p}</button>`).join('')}</div>${l?`${check('Enabled','light.enabled',l.enabled)}${select('Colour source','light.colorMode',l.colorMode,['custom','environment'])}${rgb('Light colour','light.color',l.color)}${field('Intensity','light.intensity',l.intensity)}${field('Reach (metres)','light.range',l.range)}${field('Falloff','light.falloff',l.falloff)}${vector('Attachment offset','light.offset',l.offset)}${check('Front-facing spill','light.frontOnly',l.frontOnly)}${vector('Local direction','light.direction',l.direction)}${check('Only at night','light.nightOnly',l.nightOnly)}${field('Flicker amount','light.pulse.amount',l.pulse.amount)}${field('Flicker speed','light.pulse.speed',l.pulse.speed)}${field('Flicker seed','light.pulse.seed',l.pulse.seed)}`:'<p>Attach a light to this object. It follows the animated pose.</p>'}</details><details ${n.coloring?'open':''}><summary>Tint & glowing artwork</summary>${n.coloring?`${rgb('Tint','coloring.tint',c.tint)}${field('Tint amount','coloring.strength',c.strength)}${select('Glow colour source','coloring.colorMode',c.colorMode,['custom','environment'])}${rgb('Glow colour','coloring.emissionColor',c.emissionColor)}${field('Glow strength','coloring.emission',c.emission)}${check('Glow only at night','coloring.nightOnly',c.nightOnly)}${select('Glow face','coloring.face',c.face,['all','front','back','left','right','top','bottom'])}${check('Limit glow to a region','coloring.regionOnly',c.regionOnly)}${vector('Artwork region (0–1, top-left origin)','coloring.region',c.region,['Centre X','Centre Y','Radius X','Radius Y'])}${select('Source colour mask','coloring.mask',c.mask,['all','warm','dark'])}`:'<button id="s3-coloring-enable">Enable tint & glow</button>'}</details>`;
}
