import * as T from './vendor.js';
// One rig per object. All associated geometry uses the same anchor transform.
export const deformationGLSL=`
uniform mat4 objectInverse;uniform vec3 rigHalf;uniform float rigCount;uniform mat4 rigMatrices[8],rigInverses[8];uniform vec3 rigHalves[8];uniform vec4 rigShapes[8];uniform vec2 rigBends[8];
vec3 deformAt(vec3 p,int i){float h=max(rigHalves[i].y,.001),u=clamp(p.y/h,-1.,1.);vec4 shape=rigShapes[i];float radial=inversesqrt(shape.x)*(1.-shape.y*(1.-u*u))*(1.+shape.z*u);p.xz*=radial;p.xz+=rigBends[i]*h*pow((u+1.)*.5,2.);p.y=(p.y+h)*shape.x-h;return p;}
vec3 localDeform(vec3 p){vec3 world=(modelMatrix*vec4(p,1.)).xyz;for(int i=0;i<8;i++){if(float(i)>=rigCount)break;world=(rigMatrices[i]*vec4(deformAt((rigInverses[i]*vec4(world,1.)).xyz,i),1.)).xyz;}return (objectInverse*vec4(world,1.)).xyz;}
`;
const eyeGLSL=`
uniform float eyeEnabled,iris,eyeOpen,eyeTilt,irisScale,eyeCount;uniform vec2 eyeCenter,gaze,eyeContour[64];varying vec2 eyePoint;attribute float paintRole;
vec2 eyeRange(float x){float lo=10000.,hi=-10000.;vec2 a=eyeContour[int(eyeCount)-1];for(int i=0;i<64;i++){if(float(i)>=eyeCount)break;vec2 b=eyeContour[i];if((a.x>x)!=(b.x>x)){float y=a.y+(b.y-a.y)*(x-a.x)/(b.x-a.x);lo=min(lo,y);hi=max(hi,y);}a=b;}return vec2(lo,hi);}
vec2 eyeWarp(vec2 p){vec2 r=eyeRange(p.x);if(r.x>r.y)return p;float y=p.y-eyeCenter.y,h=max(.001,y>=0.?r.y-eyeCenter.y:eyeCenter.y-r.x),amount=abs(y)<h?y:sign(y)*h*(1.-smoothstep(h,max(h+.001,rigHalf.y),abs(y)));p.y-=amount*(1.-eyeOpen);p.y+=eyeTilt*(p.x-eyeCenter.x)*(1.-smoothstep(h,max(h+.001,rigHalf.y),abs(y)));return p;}
`;
const eyeFragment=`uniform float eyeEnabled,iris,eyeOpen,eyeTilt,eyeCount;uniform vec2 eyeCenter,eyeContour[64];varying vec2 eyePoint;
bool inEye(vec2 p){p.y=eyeCenter.y+(p.y-eyeCenter.y-eyeTilt*(p.x-eyeCenter.x))/max(.001,eyeOpen);bool inside=false;vec2 a=eyeContour[int(eyeCount)-1];for(int i=0;i<64;i++){if(float(i)>=eyeCount)break;vec2 b=eyeContour[i];if((a.y>p.y)!=(b.y>p.y))if(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)inside=!inside;a=b;}return inside;}
`;
export function rigUniforms(){return{rigMatrix:{value:new T.Matrix4()},rigInverse:{value:new T.Matrix4()},rigHalf:{value:new T.Vector3(1,1,1)},shapeVector:{value:new T.Vector4(1,0,0,0)},stretch:{value:1},waist:{value:0},taper:{value:0},bend:{value:new T.Vector2()}};}
export function chainUniforms(chain){const pad=Array.from({length:8},(_,i)=>chain[i]??chain.at(-1));return{rigHalf:chain[0].rigHalf,rigCount:{value:chain.length},rigMatrices:{value:pad.map(r=>r.rigMatrix.value)},rigInverses:{value:pad.map(r=>r.rigInverse.value)},rigHalves:{value:pad.map(r=>r.rigHalf.value)},rigShapes:{value:pad.map(r=>r.shapeVector.value)},rigBends:{value:pad.map(r=>r.bend.value)}};}
export function eyeUniforms(e=null,iris=0){const u={eyeEnabled:{value:e?1:0},iris:{value:iris},eyeOpen:{value:e?.open??1},eyeTilt:{value:e?.tilt??0},irisScale:{value:e?.irisScale??1},eyeCount:{value:e?.contour.length??4},eyeCenter:{value:new T.Vector2(...(e?.center??[0,0]))},gaze:{value:new T.Vector2(...(e?.gaze??[0,0]))},eyeContour:{value:Array.from({length:64},(_,i)=>new T.Vector2(...(e?.contour[i]??[0,0])))}};return u;}
const moveVertex=`vec3 transformed=position;eyePoint=position.xy;if(eyeEnabled>.5){if(iris>.5){transformed.xy=transformed.xy*irisScale+eyeCenter+gaze;eyePoint=transformed.xy;}else{transformed.xy=eyeWarp(transformed.xy);eyePoint=transformed.xy;}}transformed=localDeform(transformed);`;
export function illustratedMaterial(def,rig,shared,{paint=false,eye=null,iris=0,maps={}}={}){
 const eyeU=eyeUniforms(eye,iris),u={objectInverse:{value:new T.Matrix4()},...rig,...eyeU,...shared,palette:{value:def.palette.map(c=>new T.Color(c))},bands:{value:def.bands},sourceColors:{value:def.paintMode==='source'?1:0},flash:{value:0},paint:{value:paint?1:0}};
 const m=new T.MeshPhysicalMaterial({clearcoat:Math.min(1,def.sheen*.5),clearcoatRoughness:def.roughness,color:paint?'#ffffff':def.palette[0],roughness:def.roughness,metalness:def.metalness,bumpMap:maps.heightMap??null,bumpScale:def.relief,roughnessMap:maps.roughnessMap??null,map:maps.map??null,side:T.DoubleSide});m.userData.uniforms=u;m.userData.materialId=def.id;
 m.onBeforeCompile=shader=>{Object.assign(shader.uniforms,u);shader.vertexShader=shader.vertexShader.replace('#include <common>',`#include <common>\n${deformationGLSL}${eyeGLSL}\nattribute float paintTone;attribute vec3 sourcePaint;varying vec3 vSourcePaint;varying float vRole,vTone;`).replace('#include <begin_vertex>',moveVertex+'\nvRole=paintRole;vTone=paintTone;vSourcePaint=sourcePaint;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\n${eyeFragment}\nuniform vec3 palette[4];uniform float bands,flash,paint,viewPass,sourceColors;varying vec3 vSourcePaint;varying float vRole,vTone;`).replace('#include <color_fragment>',`#include <color_fragment>\nif(paint>.5)diffuseColor.rgb=(sourceColors>.5||vRole>3.5)?vSourcePaint:palette[int(clamp(floor(vRole+.5),0.,3.))]*vTone;if(eyeEnabled>.5&&(iris>.5||(paint>.5&&vRole>1.5&&vRole<2.5))&&(eyeOpen<.01||!inEye(eyePoint)))discard;`).replace('#include <normal_fragment_begin>',`#include <normal_fragment_begin>\nnormal=normalize(cross(dFdx(vViewPosition),dFdy(vViewPosition)));if(!gl_FrontFacing)normal=-normal;`).replace('#include <opaque_fragment>',`float lum=dot(outgoingLight,vec3(.2126,.7152,.0722)),baseLum=max(.001,dot(diffuseColor.rgb,vec3(.2126,.7152,.0722)));float illumination=lum/baseLum;float stepped=floor(clamp(illumination,0.,2.)*bands+.5)/bands;outgoingLight*=mix(1.,stepped/max(.001,illumination),.65);outgoingLight=mix(outgoingLight,palette[2],flash);\n#include <opaque_fragment>\nif(viewPass>3.5){gl_FragColor=vec4(vec3(roughnessFactor),1.);return;}if(viewPass>2.5){float height=.5;
#ifdef USE_BUMPMAP
height=texture2D(bumpMap,vBumpMapUv).r;
#endif
gl_FragColor=vec4(vec3(height),1.);return;}if(viewPass>.5){gl_FragColor=vec4(normalize(normal)*.5+.5,1.);return;}`);};
 m.customProgramCacheKey=()=> 'illustrated-3d-v1';
 const depth=new T.MeshDepthMaterial({depthPacking:T.RGBADepthPacking,side:T.DoubleSide});depth.onBeforeCompile=s=>{Object.assign(s.uniforms,u);s.vertexShader=s.vertexShader.replace('#include <common>',`#include <common>\n${deformationGLSL}${eyeGLSL}`).replace('#include <begin_vertex>',moveVertex);s.fragmentShader=s.fragmentShader.replace('#include <common>',`#include <common>\n${eyeFragment}`).replace('#include <alphatest_fragment>',`#include <alphatest_fragment>\nif(iris>.5&&(eyeOpen<.01||!inEye(eyePoint)))discard;`);};depth.customProgramCacheKey=()=> 'illustrated-depth-v1';m.userData.depth=depth;return m;
}
// Inverted hull gives screen-space contour width; structural ribbons below use
// the same pressure/noise language as the cube's perfect-freehand-inspired ink.
export function outlineMaterial(def,rig,shared){const material=new T.ShaderMaterial({side:T.BackSide,uniforms:{objectInverse:{value:new T.Matrix4()},...rig,...shared,weight:{value:def.ink},scribble:{value:def.scribble},inkColor:{value:new T.Color(def.palette[3])}},vertexShader:deformationGLSL+`uniform vec2 resolution;uniform float weight,pixelRatio,inkWeight,scribble;void main(){vec3 p=localDeform(position),q=localDeform(position+normal*.002);vec4 clip=projectionMatrix*modelViewMatrix*vec4(p,1.),nearClip=projectionMatrix*modelViewMatrix*vec4(q,1.);vec2 d=nearClip.xy/nearClip.w-clip.xy/clip.w;d=normalize(d*resolution+vec2(.000001));float pressure=1.+scribble*(.2*sin(position.x*23.+position.y*13.)+.13*sin(position.z*31.));clip.xy+=d*weight*inkWeight*pixelRatio*pressure*2./resolution*clip.w;gl_Position=clip;}`,fragmentShader:`uniform vec3 inkColor;uniform float viewPass;void main(){if(viewPass>.5)discard;gl_FragColor=vec4(inkColor,1.);#include <colorspace_fragment>\n}`.replace(';#include',';\n#include')});material.userData.materialId=def.id;return material;}
export function strokeMesh(geometry,def,rig,shared){const edges=new T.EdgesGeometry(geometry,28),a=edges.attributes.position.array,starts=[],ends=[],seeds=[];for(let i=0;i<a.length;i+=6){starts.push(...a.slice(i,i+3));ends.push(...a.slice(i+3,i+6));seeds.push(i*.731);}edges.dispose();const g=new T.InstancedBufferGeometry(),points=[],params=[],index=[],detail=16;for(let i=0;i<=detail;i++){points.push(0,0,0,0,0,0);params.push(i/detail,-1,i/detail,1);if(i<detail){const n=i*2;index.push(n,n+1,n+2,n+1,n+3,n+2);}}g.setAttribute('position',new T.Float32BufferAttribute(points,3));g.setAttribute('param',new T.Float32BufferAttribute(params,2));for(const [name,value,size]of [['start',starts,3],['end',ends,3],['seed',seeds,1]])g.setAttribute(name,new T.InstancedBufferAttribute(new Float32Array(value),size));g.setIndex(index);g.instanceCount=seeds.length;const m=new T.ShaderMaterial({uniforms:{objectInverse:{value:new T.Matrix4()},...rig,...shared,weight:{value:def.ink},scribble:{value:def.scribble},inkColor:{value:new T.Color(def.palette[3])}},vertexShader:deformationGLSL+`attribute vec2 param;attribute vec3 start,end;attribute float seed;uniform vec2 resolution;uniform float weight,inkWeight,pixelRatio,scribble;varying float edge;void main(){float t=param.x;vec3 p=mix(start,end,t);vec4 clip=projectionMatrix*modelViewMatrix*vec4(localDeform(p),1.),a=projectionMatrix*modelViewMatrix*vec4(localDeform(mix(start,end,max(0.,t-.001))),1.),b=projectionMatrix*modelViewMatrix*vec4(localDeform(mix(start,end,min(1.,t+.001))),1.);vec2 d=(b.xy/b.w-a.xy/a.w)*resolution;vec2 side=vec2(-d.y,d.x)/max(length(d),.00001);float pressure=.9+.13*sin(t*13.+seed),wobble=scribble*(sin(t*17.+seed*12.)+.35*sin(t*43.+seed));clip.xy+=side*(param.y*weight*inkWeight*pressure+wobble)*pixelRatio*2./resolution*clip.w;clip.z-=.00001*clip.w;gl_Position=clip;edge=param.y;}`,fragmentShader:`uniform vec3 inkColor;uniform float viewPass;varying float edge;void main(){if(viewPass>.5)discard;float a=1.-smoothstep(1.-fwidth(edge),1.,abs(edge));gl_FragColor=vec4(inkColor,a);\n#include <colorspace_fragment>\n}`,transparent:true,depthWrite:false,side:T.DoubleSide});m.userData.materialId=def.id;const mesh=new T.Mesh(g,m);mesh.frustumCulled=false;mesh.renderOrder=3;return mesh;}

export function bindMeshTransform(mesh){const update=()=>{const u=mesh.material.uniforms??mesh.material.userData.uniforms;if(u?.objectInverse)u.objectInverse.value.copy(mesh.matrixWorld).invert();};mesh.onBeforeRender=update;mesh.onBeforeShadow=update;return mesh;}
