import {ClipAudio} from '../authoring/sound.js';
import * as T from './vendor.js';
import {loadImages,motionBounds,renderFrame,poseAt,animationTime} from '../runtime.js';
// A scene instance references the editable project rig, not a baked sprite sheet.
export {puppetSource} from '../puppet-sources.js';
import {puppetSource,puppetSourceKey} from '../puppet-sources.js';
export function puppetTime(binding,clip,time){const t=(Math.max(0,time-(binding.start??0))*(binding.speed??1)+(binding.offset??0));return binding.loop!==false?t%clip.duration:Math.min(t,clip.duration);}
const vertex=`varying vec2 vUv;varying vec3 vWorld,vNormal;void main(){vUv=uv;vec4 world=modelMatrix*vec4(position,1.);vWorld=world.xyz;vNormal=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*viewMatrix*world;}`;
const fragment=`uniform sampler2D art;uniform float pass;varying vec2 vUv;varying vec3 vWorld,vNormal;void main(){vec4 tex=texture2D(art,vUv);if(tex.a<.12)discard;if(pass>.5){gl_FragColor=pass<1.5?vec4(normalize(vNormal)*.5+.5,.7):vec4(vec3(.5),.7);return;}vec3 c=tex.rgb;float r=0.;gl_FragColor=vec4(c,1.);\n#include <colorspace_fragment>\n}`;
export class PuppetLayers{
 constructor(host){this.h=host;this.entries=new Map();this.sockets=new Map();this.signature='';this.source=null;this.images=null;this.variants=new Map();this.revision=0;}
 async configure(project){const source=puppetSource(project),signature=JSON.stringify(source);if(signature!==this.signature){const previous=this.images;this.images=await loadImages(source);for(const model of previous?.models?.values()??[])model.dispose?.();this.source=source;this.signature=signature;this.revision++;this.bounds=new Map();}const bindings=new Map(project.scene3d.nodes.filter(n=>n.type==='puppet'&&(n.puppet.source||n.variant||n.puppet.variant)).map(n=>[puppetSourceKey(n),n])),used=new Set(bindings.keys());for(const [id,node]of bindings){const source=puppetSource(project,node.variant??node.puppet.variant,node.puppet.source),signature=JSON.stringify(source),old=this.variants.get(id);if(old?.signature===signature)continue;const images=await loadImages(source);for(const model of old?.images?.models?.values()??[])model.dispose?.();this.variants.set(id,{source,images,signature,bounds:new Map()});this.revision++;}for(const [id,v]of this.variants)if(!used.has(id)){for(const model of v.images.models?.values()??[])model.dispose?.();this.variants.delete(id);}for(const e of this.entries.values()){e.last='';}this.syncSockets();}
 async attach(project){this.clear();if(!project.scene3d.nodes.some(n=>n.type==='puppet'))return;await this.configure(project);for(const node of project.scene3d.nodes.filter(n=>n.type==='puppet')){const canvas=document.createElement('canvas'),texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=T.LinearFilter;const material=new T.ShaderMaterial({uniforms:{art:{value:texture},pass:this.h.pipeline?.uniforms.pass??this.h.shared.viewPass},vertexShader:vertex,fragmentShader:fragment,side:T.DoubleSide,depthTest:true,depthWrite:true});const mesh=new T.Mesh(new T.PlaneGeometry(1,1),material);mesh.userData.node=node.id;mesh.userData.puppet=true;mesh.frustumCulled=false;mesh.customDepthMaterial=new T.MeshDepthMaterial({map:texture,alphaTest:.12,side:T.DoubleSide,depthPacking:T.RGBADepthPacking});mesh.castShadow=true;const facing=new T.Group();facing.add(mesh);this.h.objects.get(node.id).add(facing);this.h.pickables.push(mesh);this.h.lighting.bind(material,node.id);this.entries.set(node.id,{mesh,facing,canvas,texture,last:'',resolution:0,time:0,clip:null,audio:new ClipAudio(),audible:false,audioTime:0});}this.syncSockets();}
 update(time){if(!this.entries.size)return;const h=this.h;for(const [id,e]of this.entries){const node=h.sample?.byId.get(id)??h.project.scene3d.nodes.find(n=>n.id===id);if(!node||!node.visible)continue;const binding=node.puppet,variant=this.variants.get(puppetSourceKey(node)),source=variant?.source??this.source,images=variant?.images??this.images,bounds=variant?.bounds??this.bounds,clip=source.clips.find(c=>c.id===binding.clip)??source.clips[0],at=puppetTime(binding,clip,time),ppu=binding.pixelsPerUnit??150;let b=bounds.get(clip.id);if(!b){b=motionBounds(source,clip);const padding=24;b={minX:b.minX-padding,minY:b.minY-padding,maxX:b.maxX+padding,maxY:b.maxY+padding};bounds.set(clip.id,b);}const width=b.maxX-b.minX,height=b.maxY-b.minY;e.mesh.scale.set(width/ppu,height/ppu,1);e.mesh.position.set((b.minX+b.maxX)/2/ppu,-(b.minY+b.maxY)/2/ppu,0);
  if(binding.facing==='camera'){const parent=h.objects.get(id),world=parent.getWorldQuaternion(new T.Quaternion());e.facing.quaternion.copy(world.invert()).multiply(h.camera.quaternion);}else e.facing.quaternion.identity();e.facing.updateMatrixWorld(true);
  const size=e.mesh.getWorldScale(new T.Vector3()),distance=e.mesh.getWorldPosition(new T.Vector3()).distanceTo(h.camera.position),screenHeight=h.camera.isOrthographicCamera?size.y*h.height*h.camera.zoom/(h.camera.top-h.camera.bottom):size.y*h.height/(2*Math.tan(h.camera.fov*Math.PI/360)*Math.max(.01,distance));const resolution=Math.max(256,Math.min(1024,2**Math.ceil(Math.log2(Math.max(1,screenHeight*h.renderer.getPixelRatio()))))),frame=Math.round(at*60),key=[this.revision,clip.id,frame,resolution,width,height].join(':');e.time=at;e.clip=clip.id;
  if(key!==e.last){const ratio=resolution/Math.max(width,height),w=Math.max(1,Math.round(width*ratio)),ht=Math.max(1,Math.round(height*ratio)),rendered=renderFrame(source,images,clip,frame/60,{width:w,height:ht,camera:[ratio,0,0,ratio,-b.minX*ratio,-b.minY*ratio],background:'transparent'});if(e.canvas.width!==w||e.canvas.height!==ht){e.texture.dispose();e.canvas.width=w;e.canvas.height=ht;}const ctx=e.canvas.getContext('2d');ctx.clearRect(0,0,w,ht);ctx.drawImage(rendered,0,0,w,ht);e.texture.needsUpdate=true;e.last=key;e.resolution=resolution;h.invalidate();}
 }for(const [id,socket]of this.sockets){const n=h.sample.byId.get(id),matrix=this.jointMatrix(n.parent,n.attachment);socket.matrix.copy(matrix??new T.Matrix4());socket.matrixWorldNeedsUpdate=true;socket.updateMatrixWorld(true);}}
 updateAudio(time,{audible=false}={}){for(const [id,e]of this.entries){const n=this.h.sample?.byId.get(id);if(!n)continue;const source=this.variants.get(puppetSourceKey(n))?.source??this.source,clip=source.clips.find(c=>c.id===n.puppet.clip)??source.clips[0],at=puppetTime(n.puppet,clip,time),hear=audible&&n.visible;if(hear&&!e.audible)e.audio.begin(clip,e.audioTime<=at?e.audioTime:at);e.audio.sync(source,clip,at,{audible:hear});e.audible=hear;e.audioTime=at;}}
 pauseAudio(){for(const e of this.entries.values()){e.audio.stop();e.audible=false;}}
 syncSockets(){const h=this.h;if(!this.entries.size)return;for(const [id,socket]of this.sockets){const n=h.project.scene3d.nodes.find(n=>n.id===id);if(!n?.attachment||socket.parent!==h.objects.get(n.parent)){const object=h.objects.get(id);if(object)(h.objects.get(n?.parent)??h.world).add(object);socket.removeFromParent();this.sockets.delete(id);}}for(const n of h.project.scene3d.nodes){if(!n.attachment||!this.entries.has(n.parent)||this.sockets.has(n.id))continue;const socket=new T.Group();socket.name=n.attachment+' attachment';socket.matrixAutoUpdate=false;h.objects.get(n.parent).add(socket);socket.add(h.objects.get(n.id));this.sockets.set(n.id,socket);}}
 authoredPosition(id){return this.h.objects.get(id).position.toArray();}
 jointMatrix(id,joint){const e=this.entries.get(id);if(!e)return null;const node=this.h.sample.byId.get(id),source=this.variants.get(puppetSourceKey(node))?.source??this.source,clip=source.clips.find(c=>c.id===e.clip)??source.clips[0],pose=poseAt(source,clip,animationTime(clip,e.time)).get(joint);if(!pose)return null;const m=pose.world,ppu=node.puppet.pixelsPerUnit;return new T.Matrix4().makeRotationFromQuaternion(e.facing.quaternion).multiply(new T.Matrix4().set(m[0],-m[2],0,m[4]/ppu,-m[1],m[3],0,-m[5]/ppu,0,0,1,0,0,0,0,1));}
 snapshot(){return [...this.entries].map(([id,e])=>({id,clip:e.clip,time:e.time,resolution:e.resolution,width:e.canvas.width,height:e.canvas.height}));}
 clear(){this.sockets.clear();for(const e of this.entries.values()){e.audio.dispose();e.facing.removeFromParent();e.mesh.geometry.dispose();e.mesh.material.dispose();e.mesh.customDepthMaterial.dispose();e.texture.dispose();}this.entries.clear();}
 dispose(){this.clear();for(const v of this.variants.values())for(const model of v.images.models?.values()??[])model.dispose?.();this.variants.clear();for(const model of this.images?.models?.values()??[])model.dispose?.();this.images=null;}
}
