import {applySceneResolved,readSceneChannel} from './resolved-channels.js';
import {SceneBackdrop} from './backdrop.js';
import {projectAppearance,projectGrading} from '../authoring/appearance.js';
import {animatedPlaneGeometry,bindAnimatedPlane,updateAnimatedPlanes} from '../vector/scene-plane.js';
import {validateGrading} from '../../rendering/color-grading.js';
import {SceneTrails} from '../motion-tools/scene-trails.js';
import {solveSceneTools} from '../motion-tools/scene.js';
import {PuppetLayers} from './puppet-layer.js';
import {mirroredScale} from './core/mirroring.js';
import {sceneNavigation} from './canvas-navigation.js';
import {SceneLighting} from './lighting.js';
import {IllustratedPipeline} from './illustrated-pipeline.js';
import {CameraMotion,cameraMotionDefaults} from './core/camera-motion.js';
import {SceneFacials} from './facials.js';
import {sampleSequence} from './sequence.js';
import {SceneCollisions} from './collision.js';
import {SceneCompositor} from './compositor.js';
import {vectorGeometry,detailBucket} from './vector-cache.js';
import * as T from './vendor.js';
import {validateScene} from './schema.js';
import {createSceneSampler} from './animation.js';
import {primitiveGeometry,parseSVG,svgGeometry,faceTransform,disposeGroup} from './geometry.js';
import {rigUniforms,chainUniforms,bindMeshTransform,illustratedMaterial,outlineMaterial,strokeMesh} from './material.js';
import {SceneEffects,deformPoint,toWorld} from './effects.js';
const geometrySignature=p=>JSON.stringify({assets:p.assets.map(a=>[a.id,a.src,!!a.vector?.tracks.length]),nodes:p.scene3d.nodes.map(n=>({id:n.id,type:n.type,parent:n.parent,dimensions:n.dimensions,radius:n.radius,segments:n.segments,material:n.material,svg:n.svg,profile:n.profile,castShadow:n.castShadow,receiveShadow:n.receiveShadow,surfaces:Object.fromEntries(Object.entries(n.surfaces).map(([k,v])=>[k,{...v,eye:v.eye?{...v.eye,open:0,gaze:[0,0],tilt:0}:undefined}]))})),materials:p.scene3d.materials.map(m=>[m.id,m.map,m.heightMap,m.roughnessMap,m.repeat,m.flat])});
const textureCache=new Map();
async function loadTexture(src,color=false){const key=src+color;if(!textureCache.has(key))textureCache.set(key,new T.TextureLoader().loadAsync(src).then(t=>{if(color)t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;return t;}).catch(e=>{textureCache.delete(key);throw e;}));return textureCache.get(key);}
export class IllustratedScene{
 constructor(canvas,{controls=false}={}){this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.compositor=new SceneCompositor(this.renderer);this.scene=new T.Scene();this.backdrop=new SceneBackdrop(this);this.world=new T.Group();this.scene.add(this.world);this.light=new T.DirectionalLight('#ffe5b5',3);this.light.castShadow=true;this.light.shadow.mapSize.set(2048,2048);Object.assign(this.light.shadow.camera,{left:-15,right:15,top:15,bottom:-15,near:.1,far:60});this.light.shadow.bias=-.0003;this.light.shadow.normalBias=.015;this.scene.add(this.light,this.light.target);this.ambient=new T.HemisphereLight('#fff8e8','#455656',.9);this.scene.add(this.ambient);this.effects=new SceneEffects(this.scene);this.effects.onPause=()=>this.puppets?.pauseAudio();this.facials=new SceneFacials(this);this.cameraMotion=new CameraMotion();this.lighting=new SceneLighting();this.collisions=new SceneCollisions();this.puppets=new PuppetLayers(this);this.trails=new SceneTrails(this);this.objects=new Map();this.rigs=new Map();this.materials=[];this.pickables=[];this.shared={resolution:{value:new T.Vector2(1,1)},pixelRatio:{value:this.renderer.getPixelRatio()},inkWeight:{value:1},viewPass:{value:0}};this.camera=new T.OrthographicCamera(-4,4,4,-4,.05,160);this.controls=controls?new T.OrbitControls(this.camera,canvas):null;if(this.controls){this.controls.enableDamping=true;this.controls.dampingFactor=.1;this.navigation=sceneNavigation(this);}this.generation=0;this.time=0;this.clipId=null;this.view='colour';this.disposed=false;this.zoomTimer=0;this.lastZoomSignature='';this.stats={loads:0,updates:0,seeks:0,renders:0};this.dirty=true;this.lastCameraState=[];}
 asset(id){const a=this.project.assets.find(a=>a.id===id);if(!a)throw Error('Missing asset '+id);return new URL(a.src,this.baseURL??document.baseURI).href;}
 async load(project,{baseURL=document.baseURI,preserveCamera=false}={}){project=projectAppearance(project);await this.backdrop.configure(project,baseURL);validateGrading(project.grading);this.trails.clear();if(project.scene3d.rendering?.pipeline==='illustrated'){validateScene(project.scene3d,project.assets);if(!this.pipeline){this.effects.dispose();this.facials.dispose();this.pipeline=new IllustratedPipeline(this);preserveCamera=false;}return this.pipeline.load(project,{baseURL,preserveCamera});}if(this.pipeline){this.pipeline.dispose();this.pipeline=null;this.effects=new SceneEffects(this.scene);this.effects.onPause=()=>this.puppets?.pauseAudio();this.facials=new SceneFacials(this);this.compositor.dispose();this.compositor=new SceneCompositor(this.renderer);delete this.scene.userData.inkEffects;delete this.scene.userData.groundDecals;delete this.scene.userData.shapeShadow;}this.stats.loads++;validateScene(project.scene3d,project.assets);const generation=++this.generation;const nextProject=structuredClone(project),signature=geometrySignature(nextProject);if(this.project&&this.geometrySignature===signature){this.project=nextProject;this.baseURL=baseURL;this.preparePose();await this.puppets.configure(nextProject);this.applyAppearance();await this.effects.configure(nextProject,id=>this.asset(id));if(generation!==this.generation||this.disposed)return;this.clipId=nextProject.scene3d.clips.some(c=>c.id===this.clipId)?this.clipId:nextProject.scene3d.clips[0].id;if(!preserveCamera)this.setCamera(nextProject.scene3d.camera);this.seek(this.time,this.clipId);this.render();return this;}const s=nextProject.scene3d,world=new T.Group(),objects=new Map(),rigs=new Map(),materials=[],pickables=[],defs=new Map(s.nodes.map(n=>[n.id,n]));const asset=id=>{const a=nextProject.assets.find(a=>a.id===id);if(!a)throw Error('Missing asset '+id);return new URL(a.src,baseURL).href;};const maps=new Map(),ownedTextures=[];for(const m of s.materials){const textures={};for(const k of ['heightMap','roughnessMap','map'])if(m[k]){textures[k]=await loadTexture(asset(m[k]),k==='map');if(m.repeat){textures[k]=textures[k].clone();ownedTextures.push(textures[k]);textures[k].repeat.fromArray(m.repeat);}}maps.set(m.id,textures);}
 const makeMat=(def,rig,opts)=>{const m=illustratedMaterial(def,rig,this.shared,{...opts,maps:opts?.maps??maps.get(def.id)});materials.push(m);return m;};
 for(const n of s.nodes){const object=new T.Group();object.name=n.name;object.userData.node=n.id;objects.set(n.id,object);rigs.set(n.id,rigUniforms());}
 for(const n of s.nodes){const object=objects.get(n.id);(objects.get(n.parent)??world).add(object);object.position.fromArray(n.position);object.rotation.set(...n.rotation.map(T.MathUtils.degToRad));object.scale.fromArray(mirroredScale(n));object.visible=n.visible;}
 world.updateMatrixWorld(true);
 for(const n of s.nodes){const object=objects.get(n.id),def=s.materials.find(m=>m.id===n.material);let owner=n;const chain=[];while(owner){chain.push(rigs.get(owner.id));owner=defs.get(owner.parent);}const rig=chainUniforms(chain);object.userData.rigOwner=n.id;const animatedArt=n.type==='svg'&&nextProject.assets.find(a=>a.id===n.svg)?.vector?.tracks.length,geometry=animatedArt?animatedPlaneGeometry(...n.dimensions.slice(0,2)):n.type==='svg'?await vectorGeometry(asset(n.svg),n.dimensions[0],n.dimensions[1],0):await primitiveGeometry(n,asset);if(geometry){const material=makeMat(def,rig,{paint:['svg','extrude'].includes(n.type)}),mesh=new T.Mesh(geometry,material);mesh.name=n.name;mesh.userData.node=n.id;if(n.type==='svg'&&!animatedArt){mesh.userData.vector={src:asset(n.svg),size:n.dimensions.slice(0,2),bucket:0};
 // SVG layers share a plane. Paint in document order without letting their
 // coplanar triangles overwrite one another's depth. A silhouette prepass
 // still contributes real deformed depth and occludes other scene objects.
 const depthMaterial=material.userData.depth.clone();depthMaterial.onBeforeCompile=material.userData.depth.onBeforeCompile;depthMaterial.customProgramCacheKey=material.userData.depth.customProgramCacheKey;depthMaterial.userData.uniforms=material.userData.uniforms;depthMaterial.colorWrite=false;const depthMesh=new T.Mesh(geometry,depthMaterial);depthMesh.name=n.name+' depth';depthMesh.userData.helper=true;depthMesh.renderOrder=-1;object.add(bindMeshTransform(depthMesh));mesh.depthPrepass=depthMesh;material.depthWrite=false;material.polygonOffset=true;material.polygonOffsetFactor=-1;material.polygonOffsetUnits=-2;mesh.renderOrder=1;
 }mesh.castShadow=n.castShadow;mesh.receiveShadow=n.receiveShadow;mesh.customDepthMaterial=material.userData.depth;if(animatedArt)ownedTextures.push(bindAnimatedPlane(mesh,n.svg,n.dimensions.slice(0,2)));object.add(bindMeshTransform(mesh));pickables.push(mesh);if(n.type!=='plane'&&n.type!=='svg'){const outline=new T.Mesh(geometry,outlineMaterial(def,rig,this.shared));outline.name='Ink contour';outline.userData.helper=true;object.add(bindMeshTransform(outline));const strokes=strokeMesh(geometry,def,rig,this.shared);strokes.userData.helper=true;object.add(bindMeshTransform(strokes));}}
 for(const [face,surface]of Object.entries(n.surfaces)){const surfaceMaps={...maps.get(def.id)},irisMaps={};for(const k of ['heightMap','roughnessMap']){if(surface[k])surfaceMaps[k]=await loadTexture(asset(surface[k]));const ik='iris'+k[0].toUpperCase()+k.slice(1);if(surface[ik])irisMaps[k]=await loadTexture(asset(surface[ik]));}const frame=faceTransform(face,n.dimensions),group=new T.Group();group.position.fromArray(frame.position);group.rotation.set(...frame.rotation);object.add(group);const geo=await vectorGeometry(asset(surface.asset),...frame.size,0),mat=makeMat(def,rig,{paint:true,eye:surface.eye,maps:surfaceMaps}),paint=new T.Mesh(geo,mat);paint.frustumCulled=false;paint.userData={node:n.id,face,vector:{src:asset(surface.asset),size:frame.size,bucket:0}};paint.renderOrder=1;mat.depthWrite=false;paint.receiveShadow=true;group.add(bindMeshTransform(paint));pickables.push(paint);if(surface.iris){const irisGeo=await vectorGeometry(asset(surface.iris),...frame.size,0),irisMat=makeMat(def,rig,{paint:true,eye:surface.eye,iris:1,maps:irisMaps}),iris=new T.Mesh(irisGeo,irisMat);iris.frustumCulled=false;iris.position.z=.025;iris.userData={node:n.id,face,iris:true,vector:{src:asset(surface.iris),size:frame.size,bucket:0}};iris.renderOrder=2;irisMat.depthWrite=false;group.add(bindMeshTransform(iris));pickables.push(iris);}}
 }
 if(generation!==this.generation||this.disposed){disposeGroup(world);ownedTextures.forEach(t=>t.dispose());return;}
 disposeGroup(this.world);this.ownedTextures?.forEach(t=>t.dispose());this.ownedTextures=ownedTextures;this.geometrySignature=signature;this.project=nextProject;this.palettes=new Map(s.materials.map(m=>[m.id,m.palette]));this.baseURL=baseURL;this.scene.remove(this.world);this.world=world;this.scene.add(world);this.objects=objects;this.lighting.reset();world.traverse(mesh=>{if(mesh.userData.node&&mesh.material?.isMeshPhysicalMaterial)this.lighting.bind(mesh.material,mesh.userData.node,mesh.userData.face);});this.rigs=rigs;this.materials=materials;this.pickables=pickables;await this.puppets.attach(nextProject);this.preparePose();this.scene.background=new T.Color(s.environment.background);this.light.color.set(s.environment.lightColor);this.light.position.fromArray(s.environment.lightPosition);this.light.intensity=s.environment.intensity;this.ambient.intensity=s.environment.ambient;this.renderer.shadowMap.enabled=s.environment.shadows;this.shared.inkWeight.value=s.environment.inkWeight;this.compositor.setGrading(projectGrading(nextProject));if(!preserveCamera)this.setCamera(s.camera);await this.effects.configure(nextProject,asset);if(generation!==this.generation||this.disposed)return;this.clipId=s.clips.some(c=>c.id===this.clipId)?this.clipId:s.clips[0].id;this.seek(Math.min(this.time,s.clips.find(c=>c.id===this.clipId).duration));this.renderer.compile(this.scene,this.camera);this.render();return this;
 }
 // Validated store changes enter here. Geometry work keeps the existing load path.
 async sync(project,change){project=projectAppearance(project);await this.backdrop.configure(project,this.baseURL);
   if(this.pipeline&&project.scene3d.rendering?.pipeline==='illustrated')return this.pipeline.sync(project,change);
   if(!this.project||!change||change.full||change.geometry)return this.load(project,{preserveCamera:!!this.project});
   const generation=++this.generation;this.stats.updates++;
   this.project=structuredClone(project);if(this.puppets.entries.size)await this.puppets.configure(this.project);
   this.preparePose();if(change.appearance)this.applyAppearance();
   if(change.effects)await this.effects.configure(this.project,id=>this.asset(id));
   if(generation!==this.generation||this.disposed)return this;
   const s=this.project.scene3d;this.clipId=s.clips.some(c=>c.id===this.clipId)?this.clipId:s.clips[0].id;
   if(change.camera)this.setCamera(s.camera);
   this.trails.configure();this.seek(Math.min(this.time,s.clips.find(c=>c.id===this.clipId).duration),this.clipId);return this;
 }
 preparePose(){
   this.trails.configure();
   this.cameraMotion.configure(this.project.scene3d.cameraMotion??cameraMotionDefaults());this.sampler=createSceneSampler(this.project.scene3d);this.facials.configure(this.project.scene3d.nodes);
   this.materialDefinitions=new Map(this.project.scene3d.materials.map(m=>[m.id,m]));
   this.uniformTargets=new Map();
   for(const [id,o]of this.objects){const targets=[];o.traverse(mesh=>{if(mesh.userData.node===id&&mesh.material?.userData.uniforms)targets.push(mesh);});this.uniformTargets.set(id,targets);o.name=this.sampler.byId.get(id)?.name??id;}
   this.collisionSources=this.pickables.filter(p=>!p.userData.face);
 }
 applyAppearance(){this.compositor.setGrading(projectGrading(this.project));const s=this.project.scene3d,defs=new Map(s.materials.map(m=>[m.id,m]));this.palettes=new Map(s.materials.map(m=>[m.id,m.palette]));this.scene.background=new T.Color(s.environment.background);this.light.color.set(s.environment.lightColor);this.light.position.fromArray(s.environment.lightPosition);this.light.intensity=s.environment.intensity;this.ambient.intensity=s.environment.ambient;this.renderer.shadowMap.enabled=s.environment.shadows;this.shared.inkWeight.value=s.environment.inkWeight;this.world.traverse(o=>{const m=o.material,def=defs.get(m?.userData.materialId);if(!def)return;const u=m.uniforms??m.userData.uniforms;if(u.palette)def.palette.forEach((c,i)=>u.palette.value[i].set(c));if(u.bands)u.bands.value=def.bands;if(u.sourceColors)u.sourceColors.value=def.paintMode==='source'?1:0;if(u.weight)u.weight.value=def.ink;if(u.scribble)u.scribble.value=def.scribble;if(u.inkColor)u.inkColor.value.set(def.palette[3]);if(m.isMeshStandardMaterial){m.color.set(u.paint.value||m.userData.animatedVector?'#ffffff':def.palette[0]);m.roughness=def.roughness;m.metalness=def.metalness;m.bumpScale=def.relief;m.clearcoat=Math.min(1,def.sheen*.5);m.clearcoatRoughness=def.roughness;}});}

 invalidate(){this.dirty=true;}
 setCamera(def){this.invalidate();const aspect=this.width/this.height||1,old=this.camera;this.camera=def.type==='perspective'?new T.PerspectiveCamera(def.fov,aspect,def.near,def.far):new T.OrthographicCamera(-def.size*aspect/2,def.size*aspect/2,def.size/2,-def.size/2,def.near,def.far);this.camera.zoom=def.zoom??1;this.camera.updateProjectionMatrix();this.camera.position.fromArray(def.position);this.camera.lookAt(new T.Vector3(...def.target));if(this.controls){this.controls.object=this.camera;this.controls.target.fromArray(def.target);this.controls.update();}this.camera.updateMatrixWorld();return old;}
 cameraDefinition(){const c=this.camera,def=this.project?.scene3d.camera??{target:[0,0,0],size:8};return{...def,type:c.isPerspectiveCamera?'perspective':'orthographic',position:c.position.toArray(),zoom:c.zoom,target:this.controls?.target.toArray()??def.target,size:c.isOrthographicCamera?(c.top-c.bottom):def.size,fov:c.fov??40,near:c.near,far:c.far};}

 resize(width,height){if(!width||!height)return;this.invalidate();this.width=width;this.height=height;this.renderer.setSize(width,height,false);this.compositor.resize(Math.round(width*this.renderer.getPixelRatio()),Math.round(height*this.renderer.getPixelRatio()));this.shared.resolution.value.set(width*this.renderer.getPixelRatio(),height*this.renderer.getPixelRatio());const c=this.camera;if(c.isPerspectiveCamera)c.aspect=width/height;else{const h=c.top-c.bottom;c.left=-h*width/height/2;c.right=-c.left;}c.updateProjectionMatrix();}
 seek(time,clipId=this.clipId,{audible=false,parameters={},clock=time,continuous=false}={}){if(this.pipeline)return this.pipeline.seek(time,clipId,{audible,parameters,clock,continuous});if(!this.project)return;this.time=time;this.clipId=clipId;this.stats.seeks++;this.invalidate();const sample=this.sampler.sample(clipId,time,{parameters}),defs=sample.byId;this.sample=sample;for(const n of new Set([...sample.transformNodes,...[...(this.resolvedNodes??[])].map(id=>sample.byId.get(id)).filter(Boolean)])){const o=this.objects.get(n.id);if(!o)continue;o.position.fromArray(n.position);o.rotation.set(n.rotation[0]*Math.PI/180,n.rotation[1]*Math.PI/180,n.rotation[2]*Math.PI/180);o.scale.fromArray(mirroredScale(n));o.visible=n.visible;}for(const n of sample.nodes)if(n.ground!==undefined)this.objects.get(n.id).position.fromArray(n.position);
 this.world.updateMatrixWorld(true);for(const n of sample.nodes){if(n.ground===undefined)continue;const o=this.objects.get(n.id),v=new T.Vector3();let bottom=Infinity;for(const x of [-.5,.5])for(const z of [-.5,.5])for(let i=0;i<=24;i++){v.set(n.dimensions[0]*x,n.dimensions[1]*(i/24-.5),n.dimensions[2]*z);deformPoint(v,n);v.applyMatrix4(o.matrixWorld);bottom=Math.min(bottom,v.y);}if(bottom<n.ground){o.position.y+=n.ground-bottom;o.updateMatrixWorld(true);}}solveSceneTools(this);this.world.updateMatrixWorld(true);applySceneResolved(this);for(const n of this.sample.nodes){const o=this.objects.get(n.id),rig=this.rigs.get(n.id);rig.rigMatrix.value.copy(o.matrixWorld);rig.rigInverse.value.copy(o.matrixWorld).invert();rig.rigHalf.value.fromArray(n.dimensions).multiplyScalar(.5);rig.stretch.value=T.MathUtils.clamp(n.deform.stretch,.15,4);rig.waist.value=T.MathUtils.clamp(n.deform.waist,-.65,.8);rig.taper.value=T.MathUtils.clamp(n.deform.taper,-.8,.8);rig.bend.value.fromArray(n.deform.bend);rig.shapeVector.value.set(rig.stretch.value,rig.waist.value,rig.taper.value,0);for(const mesh of this.uniformTargets.get(n.id)??[]){const u=mesh.material.userData.uniforms;u.flash.value=n.flash??this.materialDefinitions.get(n.material)?.flash??0;if(mesh.userData.face){const eye=n.surfaces[mesh.userData.face]?.eye;if(eye){u.eyeOpen.value=eye.open;u.eyeTilt.value=eye.tilt;u.gaze.value.fromArray(eye.gaze);}}}}
 this.puppets.update(time);this.puppets.updateAudio(time,{audible:audible&&!this.effects.muted});this.lighting.update(this.sample,this.project.scene3d.environment,time,this.objects,(p,n)=>toWorld(p,n,this.objects,this.sample.byId));
 this.effects.update(time,sample.clip,this.objects,this.sample.byId,sample.clip.events.some(e=>['beam','impact','decal'].includes(e.type)&&time>=e.time&&time<e.time+e.duration)?this.collisions.update(this.collisionSources,this.sample.byId,this.objects):[],this.palettes,{audible});this.cameraMotion.sample(sample.clip,time,{clock,continuous});this.shake=this.cameraMotion.amplitude;return sample;
 }
 setChannelOverrides(values){this.channelOverrides=structuredClone(values);if(this.project){this.seek(this.time,this.clipId);this.render(true);}return this;}
 readChannel(id,channel){return readSceneChannel(this,id,channel);}
 authoredTransform(id){const o=this.objects.get(id);return this.pipeline?this.pipeline.authoredTransform(id):{position:this.puppets.authoredPosition(id),rotation:[o.rotation.x,o.rotation.y,o.rotation.z].map(T.MathUtils.radToDeg),scale:mirroredScale(this.project.scene3d.nodes.find(n=>n.id===id),o.scale.toArray())};}
 updateRigTransforms(id){if(this.pipeline)return this.pipeline.updateRigTransforms(id);this.invalidate();this.world.updateMatrixWorld(true);for(const [id,rig]of this.rigs){const o=this.objects.get(id);rig.rigMatrix.value.copy(o.matrixWorld);rig.rigInverse.value.copy(o.matrixWorld).invert();}}
 render(force=false){if(this.disposed)return;if(this.pipeline)return this.pipeline.render(force);this.puppets.update(this.time);this.trails.update();if(this.facials.update(performance.now()))this.dirty=true;applySceneResolved(this,{eyesOnly:true});if(this.backdrop.update())this.dirty=true;const moved=this.controls?.update(),c=this.camera,p=c.position,q=c.quaternion;
 const cameraState=[p.x,p.y,p.z,q.x,q.y,q.z,q.w,c.zoom,c.fov,c.aspect,c.left,c.right,c.top,c.bottom,c.near,c.far],cameraChanged=cameraState.some((v,i)=>!Object.is(v,this.lastCameraState[i]));
 if(!force&&!this.dirty&&!moved&&!cameraChanged&&this.lastView===this.view)return false;
 this.lastCameraState=cameraState;this.lastView=this.view;this.dirty=false;this.stats.renders++;updateAnimatedPlanes(this);
 const signature=this.camera.zoom+':'+this.camera.position.distanceTo(this.controls?.target??new T.Vector3());if(signature!==this.lastZoomSignature){this.lastZoomSignature=signature;clearTimeout(this.zoomTimer);this.zoomTimer=setTimeout(()=>this.updateVectorDetail().catch(e=>console.error(e)),180);}const view={colour:0,normal:1,depth:2,height:3,roughness:4}[this.view]??0;this.shared.viewPass.value=view===2?0:view;const position=this.camera.position.clone(),offset=this.cameraMotion.offset;this.camera.position.x+=offset[0];this.camera.position.y+=offset[1];this.camera.position.z+=offset[2];this.camera.updateMatrixWorld();this.effects.root.visible=view===0;try{this.compositor.render(this.scene,this.camera,view);}finally{this.camera.position.copy(position);this.camera.updateMatrixWorld();}}

 async updateVectorDetail(){if(this.pipeline)return this.pipeline.updateVectorDetail();if(!this.project||this.disposed)return;const generation=this.generation;for(const mesh of this.pickables){const v=mesh.userData.vector;if(!v)continue;const distance=this.camera.position.distanceTo(mesh.getWorldPosition(new T.Vector3())),pixels=this.camera.isOrthographicCamera?v.size[0]*this.height*this.camera.zoom/(this.camera.top-this.camera.bottom):v.size[0]*this.height/(2*Math.tan(T.MathUtils.degToRad(this.camera.fov/2))*distance),bucket=detailBucket(pixels,this.renderer.getPixelRatio());if(bucket===v.bucket)continue;const geometry=await vectorGeometry(v.src,...v.size,bucket);if(generation!==this.generation||this.disposed){geometry.dispose();return;}const previous=mesh.geometry;mesh.geometry=geometry;if(mesh.depthPrepass)mesh.depthPrepass.geometry=geometry;v.bucket=bucket;previous.dispose();this.invalidate();}}

 pick(x,y){if(this.pipeline)return this.pipeline.pick(x,y);const rect=this.canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((x-rect.left)/rect.width*2-1,-(y-rect.top)/rect.height*2+1),this.camera);const hit=ray.intersectObjects(this.collisions.update(this.collisionSources,this.sample.byId,this.objects),false).find(h=>h.object.visible);if(hit){const source=hit.object.userData.source,node=this.sample.nodes.find(n=>n.id===hit.object.userData.node);if(['box','rounded-box'].includes(node?.type)){const group=source.geometry.groups.find(g=>hit.faceIndex*3>=g.start&&hit.faceIndex*3<g.start+g.count);hit.faceName=['right','left','top','bottom','front','back'][group?.materialIndex??0];}}return hit;}

 capture(){this.render(true);return this.canvas.toDataURL('image/png');}
 snapshot(){if(this.pipeline)return this.pipeline.snapshot();return{puppets:this.puppets.snapshot(),stats:{...this.stats},time:this.time,clip:this.clipId,nodes:[...this.objects].map(([id,o])=>({id,position:o.position.toArray(),rotation:o.rotation.toArray().slice(0,3),scale:o.scale.toArray(),rig:o.userData.rigOwner})),camera:this.cameraDefinition(),cameraMotion:this.cameraMotion.snapshot(),lights:this.lighting.snapshot(),drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,decals:[...this.effects.decals.entries].filter(([,e])=>e.effect.root.visible).map(([id,e])=>({id,contact:e.contact,layers:e.effect.layers.length})),effects:[...this.effects.entries].filter(([,e])=>e.root.visible).map(([id,e])=>({id,contact:e.root.userData.contact??null}))};}
 startComposition(){return this.pipeline?.startComposition()??false;}
 stepControllers(dt,options){return this.pipeline?.step(dt,options);}
 preparePlayback(options){return this.pipeline?.preparePlayback(options);}
 dispose(){this.backdrop.dispose();this.trails.clear();this.puppets.dispose();this.pipeline?.dispose();this.disposed=true;clearTimeout(this.zoomTimer);++this.generation;this.navigation?.dispose();this.controls?.dispose();this.effects.dispose();this.facials.dispose?.();this.collisions.dispose();disposeGroup(this.world);this.light.shadow.map?.dispose();this.ownedTextures?.forEach(t=>t.dispose());this.compositor.dispose();this.renderer.dispose();}
}
export async function createScenePlayer(canvas,project,options={}){
 const scene=new IllustratedScene(canvas,options);scene.resize(options.width??canvas.clientWidth??800,options.height??canvas.clientHeight??600);await scene.load(project,options);let raf=0,last=0,playing=false,sequenceTime=0,sequenceIndex=-1;
 const api={scene,seek(time,clip){api.stop();scene.seek(time,clip);scene.render();},
 play(clip=scene.clipId){start(clip,false);},playAll(){sequenceTime=0;sequenceIndex=-1;start(null,true);},
 stop(){playing=false;cancelAnimationFrame(raf);scene.effects.pause();},dispose(){api.stop();scene.dispose();}};
 function start(clip,all){api.stop();if(!all&&clip!==scene.clipId)scene.seek(0,clip);playing=true;let playbackClock=all?0:scene.time;scene.cameraMotion.reset(playbackClock);if(all&&scene.pipeline)scene.startComposition();else scene.preparePlayback({audible:true});last=performance.now();const tick=now=>{if(!playing)return;const dt=Math.max(0,Math.min((now-last)/1000,.05));last=now;playbackClock+=dt;if(all&&scene.pipeline){scene.stepControllers(dt,{audible:true});}else if(all){sequenceTime+=dt;const next=sampleSequence(project.scene3d,sequenceTime);if(next.index!==sequenceIndex){scene.effects.pause();sequenceIndex=next.index;}scene.seek(next.time,next.clip,{audible:true,parameters:next.parameters,clock:playbackClock,continuous:true});if(next.done)playing=false;}else{const c=project.scene3d.clips.find(c=>c.id===clip),next=scene.time+dt;scene.seek(c.loop?next%c.duration:Math.min(next,c.duration),clip,{audible:true,clock:playbackClock,continuous:true});if(!c.loop&&next>=c.duration)playing=false;}scene.render();if(playing)raf=requestAnimationFrame(tick);else scene.effects.pause();};raf=requestAnimationFrame(tick);}
 return api;
}
