const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),finite=v=>Number.isFinite(v)&&v>=0,point=v=>record(v)&&Number.isFinite(v.x)&&Number.isFinite(v.z),identity=v=>Number.isSafeInteger(v)||typeof v==='string';
export class VillageAttachments {}
export class VillageOccasions {}
export const occasionKinds=['house','birth','memorial','welcome','recovery','singing','stories','quiet'];
export const validOccasion=o=>record(o)&&typeof o.key==='string'&&occasionKinds.includes(o.kind)&&identity(o.source)&&finite(o.at)&&['readyAt','expires'].every(k=>o[k]===undefined||finite(o[k]));
export const PlaceAttachmentsState={name:'PlaceAttachmentsState',replaceable:false,validate:s=>s instanceof VillageAttachments&&record(s.economy)&&finite(s.nextCheck)&&Array.isArray(s.gardens)&&s.gardens.every(g=>point(g)&&identity(g.id)&&Array.isArray(g.contributors)&&g.contributors.every(Number.isSafeInteger))};
export const OccasionsState={name:'OccasionsState',replaceable:false,validate:s=>s instanceof VillageOccasions&&record(s.economy)&&Array.isArray(s.queue)&&s.queue.length<=8&&s.queue.every(validOccasion)&&Array.isArray(s.recent)&&s.recent.length<=64&&s.recent.every(k=>typeof k==='string')&&record(s.completed)&&Object.values(s.completed).every(finite)&&['nextCheck','after','meals'].every(k=>finite(s[k]))};
export const OccasionSession={name:'OccasionSession',validate:r=>record(r)&&r.occasions instanceof VillageOccasions&&record(r.value)&&validOccasion(r.value.occasion)&&point(r.value.center)&&['deadline','inviteAt','until'].every(k=>finite(r.value[k]))&&(r.value.startedAt===null||finite(r.value.startedAt))&&Array.isArray(r.value.members)&&r.value.members.length<=6&&r.value.members.every(m=>record(m)&&record(m.worker)&&point(m.spot)&&typeof m.arrived==='boolean'&&typeof m.cued==='boolean'&&(m.enjoyment===undefined||Number.isFinite(m.enjoyment)))&&new Set(r.value.members.map(m=>m.worker)).size===r.value.members.length};
const optional=(r,k,test)=>r[k]===undefined||test(r[k]);
export const validPlaces=p=>p==null||record(p)&&
 (p.tree==null||point(p.tree)&&identity(p.tree.id)&&finite(p.tree.born)&&typeof p.tree.lost==='boolean'&&optional(p.tree,'lostAt',finite))&&
 (p.rest==null||point(p.rest)&&Number.isSafeInteger(p.rest.visits)&&p.rest.visits>=1&&optional(p.rest,'lost',v=>typeof v==='boolean'))&&
 (p.garden==null||point(p.garden)&&identity(p.garden.id)&&(p.garden.partnerId===null||Number.isSafeInteger(p.garden.partnerId)));
export const ActorPlaces={name:'ActorPlaces',validate:r=>record(r)&&record(r.person)&&optional(r,'places',validPlaces)&&['cueAt','gardenCueAt','restDeadline'].every(k=>optional(r,k,finite))};
export const ActorOccasion={name:'ActorOccasion',validate:r=>record(r)&&record(r.person)&&optional(r,'id',v=>v===null||typeof v==='string')&&optional(r,'kind',v=>v===null||occasionKinds.includes(v))&&['food','after'].every(k=>optional(r,k,finite))};
export const communityActors=[{definition:ActorPlaces,key:'actorPlaces',fields:{attachments:'places',placeCueAt:'cueAt',gardenCueAt:'gardenCueAt',restDeadline:'restDeadline'}},{definition:ActorOccasion,key:'actorOccasions',fields:{occasionId:'id',occasionKind:'kind',occasionFood:'food',occasionAfter:'after'}}];
export function communityActorInput(person){return communityActors.flatMap(({definition,fields})=>{const keys=Object.keys(fields).filter(k=>Object.hasOwn(person,k));if(!keys.length)return [];const row={person};for(const key of keys)row[fields[key]]=person[key];if(!definition.validate(row))throw Error('Invalid '+definition.name+' input');return [{definition,row,keys}];});}
