import {SKILLS} from './development-rules.js';
const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),finite=v=>Number.isFinite(v)&&v>=0,identity=v=>Number.isSafeInteger(v)||typeof v==='string',optional=(r,k,test)=>r[k]===undefined||test(r[k]),nullable=test=>v=>v===null||test(v),skill=v=>Object.hasOwn(SKILLS,v);
export const validSkillValues=v=>record(v)&&Object.entries(v).every(([id,r])=>skill(id)&&record(r)&&['xp','practised','taught'].every(k=>finite(r[k])&&r[k]<=500));
export const validLesson=a=>record(a)&&Number.isSafeInteger(a.mentorId)&&skill(a.skill)&&finite(a.until)&&finite(a.learned)&&a.learned<=500&&optional(a,'stage',v=>['watch','try','fumble','encourage','retry','success'].includes(v))&&['stageAt','startedAt'].every(k=>optional(a,k,finite));
export const validAmbition=a=>record(a)&&finite(a.at)&&['mastery','family','explore','reconcile'].includes(a.kind)&&(a.kind!=='mastery'||skill(a.skill)&&Number.isInteger(a.goal)&&a.goal>=1&&a.goal<=5)&&(a.kind!=='reconcile'||Number.isSafeInteger(a.targetId))&&(!['explore','reconcile'].includes(a.kind)||finite(a.baseline));
const causes=['fire','wish','lightning','raid','revolt'];
export const ActorSkills={name:'ActorSkills',validate:r=>record(r)&&record(r.person)&&optional(r,'values',validSkillValues)&&optional(r,'celebration',nullable(c=>record(c)&&skill(c.skill)&&Number.isInteger(c.level)&&c.level>=1&&c.level<=5&&finite(c.at)))};
export const ActorLearning={name:'ActorLearning',validate:r=>record(r)&&record(r.person)&&optional(r,'lesson',nullable(validLesson))&&optional(r,'after',finite)&&optional(r,'history',v=>Array.isArray(v)&&v.length<=8&&v.every(h=>record(h)&&skill(h.skill)&&Number.isSafeInteger(h.mentorId)&&typeof h.mentorName==='string'&&finite(h.at)&&finite(h.amount)&&optional(h,'completed',v=>typeof v==='boolean')))};
export const ActorAmbitions={name:'ActorAmbitions',validate:r=>record(r)&&record(r.person)&&optional(r,'current',nullable(validAmbition))&&optional(r,'history',v=>Array.isArray(v)&&v.length<=8&&v.every(a=>validAmbition(a)&&finite(a.endedAt)&&['fulfilled','lost-opportunity'].includes(a.outcome)))&&['after','tryAt','fulfilledUntil','dreamUntil','explorationVisits'].every(k=>optional(r,k,finite))};
export const ActorRecovery={name:'ActorRecovery',validate:r=>record(r)&&record(r.person)&&optional(r,'disaster',nullable(v=>record(v)&&Number.isSafeInteger(v.episodeId)&&identity(v.homeId)&&finite(v.at)&&finite(v.until)&&causes.includes(v.cause)))&&optional(r,'guest',nullable(v=>record(v)&&Number.isSafeInteger(v.hostId)&&identity(v.homeId)&&identity(v.originHomeId)&&finite(v.at)&&finite(v.until)&&typeof v.slept==='boolean'&&typeof v.strained==='boolean'))&&optional(r,'thanks',v=>Array.isArray(v)&&v.length<=24&&v.every(s=>typeof s==='string'))};
export const developmentDomains=[
 {definition:ActorSkills,key:'actorSkills',access:'actorSkills',fields:{skills:'values',skillCelebration:'celebration'}},
 {definition:ActorLearning,key:'actorLearning',access:'actorLearning',fields:{apprenticeship:'lesson',apprenticeAfter:'after',learningHistory:'history'}},
 {definition:ActorAmbitions,key:'actorAmbitions',access:'actorAmbitions',fields:{ambition:'current',ambitionHistory:'history',ambitionAfter:'after',ambitionTryAt:'tryAt',fulfilledUntil:'fulfilledUntil',dreamInspiredUntil:'dreamUntil',explorationVisits:'explorationVisits'}},
 {definition:ActorRecovery,key:'actorRecovery',access:'actorRecovery',fields:{disaster:'disaster',recoveryGuest:'guest',recoveryThanks:'thanks'}}
];
export function developmentInput(person){return developmentDomains.flatMap(({definition,fields})=>{const keys=Object.keys(fields).filter(k=>Object.hasOwn(person,k));if(!keys.length)return [];const row={person};for(const key of keys)row[fields[key]]=person[key];if(!definition.validate(row))throw Error('Invalid '+definition.name+' input');return [{definition,row,keys}];});}
export const DevelopmentSchedule={name:'DevelopmentSchedule',replaceable:false,validate:r=>record(r)&&['apprenticeAt','ambitionAt'].every(k=>optional(r,k,finite))};
export const CommunityRecoveryState={name:'CommunityRecoveryState',replaceable:false,validate:s=>record(s)&&Number.isSafeInteger(s.nextId)&&s.nextId>=0&&finite(s.nextCheck)&&Array.isArray(s.incidents)&&s.incidents.length<=16&&s.incidents.every(i=>record(i)&&Number.isSafeInteger(i.id)&&i.id>=0&&identity(i.homeId)&&causes.includes(i.cause)&&finite(i.at)&&finite(i.lastAt)&&typeof i.gathered==='boolean')};
