import {DevelopmentSchedule,CommunityRecoveryState} from './development-data.js';import {villageWorld} from './village-world.js';
const bindings=new WeakMap(),specs=[{definition:DevelopmentSchedule,key:'developmentSchedule'},{definition:CommunityRecoveryState,key:'communityRecovery'}];
export function developmentStateEntity(state){const b=bindings.get(state);if(!b||!b.world.alive(b.id)||b.world.get(b.id,b.name)!==state||b.world.resources.get(b.name)!==state)throw Error('Development state is not active');return b.id;}
function check(e,spec,state){if(state==null)return;if(!spec.definition.validate(state))throw Error('Invalid '+spec.definition.name);const b=bindings.get(state);if(b){developmentStateEntity(state);if(b.world!==villageWorld(e)||b.name!==spec.definition.name)throw Error('Foreign development state');}}
function install(e,spec,state){const world=villageWorld(e),name=spec.definition.name,old=world.resources.get(name);if(!world.stores.has(name))world.define(spec.definition);if(old&&old!==state){const b=bindings.get(old);if(b)world.destroy(b.id);world.resources.delete(name);}if(state==null)return state;let b=bindings.get(state);if(!b){const id=world.create({[name]:state});b={world,id,name};bindings.set(state,b);world.setResource(name,state);}Object.defineProperty(e,spec.key,{enumerable:true,configurable:true,get(){const current=world.resources.get(name),bound=current&&bindings.get(current);return bound&&world.alive(bound.id)&&world.get(bound.id,name)===current?current:undefined;}});return state;}
export const developmentSchedule=e=>{const state=e.developmentSchedule;if(!state)throw Error('Missing development schedule');developmentStateEntity(state);return state;};
export function createCommunityRecovery(e){if(e.communityRecovery!=null){developmentStateEntity(e.communityRecovery);return e.communityRecovery;}return install(e,specs[1],{nextId:0,nextCheck:0,incidents:[]});}
export function restoreDevelopmentState(e){
 const oldFields={apprenticeCheckAt:'apprenticeAt',ambitionCheckAt:'ambitionAt'},keys=Object.keys(oldFields).filter(k=>Object.hasOwn(e,k));if(e.developmentSchedule!=null&&keys.length)throw Error('Ambiguous development schedule');const schedule=e.developmentSchedule??{};for(const key of keys)schedule[oldFields[key]]=e[key];
 check(e,specs[0],schedule);check(e,specs[1],e.communityRecovery);const recovery=e.communityRecovery;install(e,specs[0],schedule);install(e,specs[1],recovery);for(const key of keys)delete e[key];
}
function set(state,values,spec){developmentStateEntity(state);const b=bindings.get(state);if(b.name!==spec.definition.name||!spec.definition.validate({...state,...values})||Object.keys(values).some(k=>!(spec.key==='developmentSchedule'?['apprenticeAt','ambitionAt']:['nextId','nextCheck','incidents']).includes(k)))throw Error('Invalid '+spec.definition.name);Object.assign(state,values);return state;}
export const setDevelopmentSchedule=(state,values)=>set(state,values,specs[0]);
export const setCommunityRecoveryState=(state,values)=>set(state,values,specs[1]);
