const record=r=>r!==null&&typeof r==='object'&&!Array.isArray(r);
const optional=(r,k,test)=>!Object.hasOwn(r,k)||r[k]===undefined||test(r[k]);
const nonnegative=n=>Number.isFinite(n)&&n>=0,integer=n=>Number.isSafeInteger(n)&&n>=0;
const numberFields=(r,keys)=>keys.every(k=>optional(r,k,nonnegative));
const point=r=>['x','z'].every(k=>optional(r,k,Number.isFinite));
const reservation=r=>optional(r,'reservedBy',v=>v===null||integer(v));
const stateIn=(r,states)=>optional(r,'state',s=>states.includes(s));
const named=r=>record(r)&&typeof r.id==='string'&&point(r);
export const FarmPlot={name:'FarmPlot',replaceable:false,validate:r=>named(r)&&reservation(r)&&optional(r,'passes',integer)&&optional(r,'visible',v=>typeof v==='boolean')&&stateIn(r,['ready','planned','preparing','planting'])};
export const ConstructionProject={name:'ConstructionProject',replaceable:false,validate:r=>named(r)&&reservation(r)&&optional(r,'state',v=>typeof v==='string')&&['stage','strikes'].every(k=>optional(r,k,integer))&&numberFields(r,['delivered'])&&optional(r,'spent',s=>record(s)&&numberFields(s,['wood','stone']))};
export const Mushroom={name:'Mushroom',replaceable:false,validate:r=>record(r)&&integer(r.id)&&point(r)&&stateIn(r,['growing','ready','fading','dormant','burning'])&&numberFields(r,['age','height'])&&optional(r,'growth',v=>Number.isFinite(v)&&v>=0&&v<=1)};
export const DiscoveryChest={name:'DiscoveryChest',replaceable:false,validate:r=>named(r)&&reservation(r)&&numberFields(r,['createdAt','retryAt'])&&optional(r,'openedAt',v=>v===null||nonnegative(v))&&optional(r,'locked',v=>typeof v==='boolean')};
const domain=(name,fields)=>({name,replaceable:false,validate:r=>record(r)&&record(r.economy)&&numberFields(r,fields)});
export const Farming=domain('Farming',['shortage','nextCheck','completed']);
export const Housing=domain('Housing',['completed','nextCheck','nextMove']);
export const Ecology=domain('Ecology',['moisture','nextSeed','nextMushroom','nextTree','nextFungus','seeded','bloomed','treeLimit']);
export const Discovery=domain('Discovery',['nextId','nextSpawn','opened','nextKeySpawn']);
export const EnvironmentMember={name:'EnvironmentMember',validate:r=>record(r)&&Number.isSafeInteger(r.domain)&&integer(r.order)};
export const ENVIRONMENT_DOMAINS=Object.freeze({Farming:{key:'farming',collection:'plots',component:'FarmPlot'},Housing:{key:'housing',collection:'projects',component:'ConstructionProject'},Ecology:{key:'ecology',collection:'mushrooms',component:'Mushroom'},Discovery:{key:'discovery',collection:'chests',component:'DiscoveryChest'}});
export const environmentDefinitions={Farming,Housing,Ecology,Discovery,FarmPlot,ConstructionProject,Mushroom,DiscoveryChest,EnvironmentMember};
