const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),time=v=>Number.isFinite(v)&&v>=0,id=v=>Number.isSafeInteger(v)&&v>=0,point=v=>record(v)&&Number.isFinite(v.x)&&Number.isFinite(v.z)&&Object.keys(v).every(k=>['x','z'].includes(k)),optional=(r,k,test)=>r[k]===undefined||test(r[k]);
const strict=(owner,fields,test)=>r=>record(r)&&record(r[owner])&&Object.keys(r).every(k=>k===owner||fields.includes(k))&&test(r);
const specialty=v=>record(v)&&time(v.since)&&id(v.shows)&&id(v.encouraged)&&Array.isArray(v.favourites)&&v.favourites.length<=8&&v.favourites.every(id)&&new Set(v.favourites).size===v.favourites.length&&Object.keys(v).every(k=>['since','shows','encouraged','favourites'].includes(k));
export const ActorPerformanceCareer={name:'ActorPerformanceCareer',validate:strict('person',['specialization','shows','conversations'],r=>optional(r,'specialization',specialty)&&['shows','conversations'].every(k=>optional(r,k,id)))};
export const ActorPerformanceParticipation={name:'ActorPerformanceParticipation',validate:strict('person',['sessionId','seat','after','entertainedUntil'],r=>optional(r,'sessionId',id)&&optional(r,'seat',point)&&['after','entertainedUntil'].every(k=>optional(r,k,time)))};
export const performanceActorDomains=[
 {definition:ActorPerformanceCareer,key:'actorPerformanceCareers',fields:{actor:'specialization',actorShows:'shows',storyConversations:'conversations'}},
 {definition:ActorPerformanceParticipation,key:'actorPerformanceParticipations',fields:{performanceId:'sessionId',performanceSeat:'seat',performanceAfter:'after',entertainedUntil:'entertainedUntil'}}
];
export function performanceActorInput(person){return performanceActorDomains.flatMap(({definition,fields})=>{const keys=Object.keys(fields).filter(k=>Object.hasOwn(person,k));if(!keys.length)return [];const row={person};for(const k of keys)row[fields[k]]=person[k];if(!definition.validate(row))throw Error('Invalid '+definition.name+' input');return [{definition,row,keys}];});}
const kind=v=>['comfort','story','play'].includes(v);
export const validPerformance=s=>record(s)&&id(s.id)&&id(s.hostId)&&kind(s.kind)&&time(s.at)&&(s.startedAt===null||time(s.startedAt)&&s.startedAt>=s.at)&&Number.isInteger(s.beat)&&s.beat>=-1&&s.beat<=2&&typeof s.cancelled==='boolean'&&Array.isArray(s.members)&&s.members.length<=6&&new Set(s.members.map(m=>m.id)).size===s.members.length&&s.members.every(m=>record(m)&&id(m.id)&&point(m.spot)&&typeof m.arrived==='boolean'&&Object.keys(m).every(k=>['id','spot','arrived'].includes(k)))&&Object.keys(s).every(k=>['id','hostId','kind','members','at','startedAt','beat','cancelled'].includes(k));
export const TheatreIdentity={name:'TheatreIdentity',replaceable:false,validate:s=>record(s)&&record(s.economy)&&Object.keys(s).every(k=>k==='economy')};
export const TheatreSchedule={name:'TheatreSchedule',validate:strict('theatre',['nextAt','nextId'],r=>time(r.nextAt)&&id(r.nextId))};
export const TheatrePerformance={name:'TheatrePerformance',validate:strict('theatre',['session'],r=>r.session===null||validPerformance(r.session))};
export const TheatreHistory={name:'TheatreHistory',validate:strict('theatre',['entries'],r=>Array.isArray(r.entries)&&r.entries.length<=12&&r.entries.every(h=>record(h)&&time(h.at)&&id(h.hostId)&&kind(h.kind)&&id(h.audience)&&h.audience<=5&&Object.keys(h).every(k=>['at','hostId','kind','audience'].includes(k))))};
export const theatreDomains=[{definition:TheatreSchedule,key:'theatreSchedules',fields:{nextAt:'nextAt',nextId:'nextId'}},{definition:TheatrePerformance,key:'theatrePerformances',fields:{session:'session'}},{definition:TheatreHistory,key:'theatreHistories',fields:{history:'entries'}}];
