import {defineGameData} from '../game-data.js';
export const POISON_RULES=defineGameData('village-poison.RULES',{duration:90,damagePerSecond:.48,energyPerSecond:.22,speed:.68,workRate:.7,symptomEvery:13,treatmentSeconds:5,treatmentReduction:35,treatmentCooldown:22,careRadius:10});
const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),time=v=>Number.isFinite(v)&&v>=0,id=v=>Number.isSafeInteger(v)&&v>=0;
const strict=(r,keys)=>record(r)&&Object.keys(r).every(k=>keys.includes(k));
export const validPoisonEffect=p=>strict(p,['since','until','lastAt','nextSymptom','severity','source','treatments'])&&['since','until','lastAt','nextSymptom'].every(k=>time(p[k]))&&p.until>=p.since&&p.lastAt>=p.since&&p.lastAt<=p.until&&p.nextSymptom>=p.since&&Number.isFinite(p.severity)&&p.severity>0&&p.severity<=1&&id(p.treatments)&&['snake','miracle'].includes(p.source);
const validCare=p=>strict(p,['targetId','deadline','startedAt'])&&id(p.targetId)&&time(p.deadline)&&(p.startedAt===null||time(p.startedAt)&&p.startedAt<=p.deadline);
export const ActorPoison={name:'ActorPoison',validate:r=>strict(r,['person','effect'])&&record(r.person)&&(r.effect===undefined||validPoisonEffect(r.effect))};
export const ActorPoisonCare={name:'ActorPoisonCare',validate:r=>strict(r,['person','job','carerId','after'])&&record(r.person)&&(r.job===undefined||validCare(r.job))&&(r.carerId===undefined||id(r.carerId))&&(r.after===undefined||time(r.after))};
export const poisonActorDomains=[{definition:ActorPoison,key:'actorPoisons',fields:{poison:'effect'}},{definition:ActorPoisonCare,key:'actorPoisonCare',fields:{poisonCare:'job',poisonCarerId:'carerId',poisonCareAfter:'after'}}];
export function poisonActorInput(person){return poisonActorDomains.flatMap(({definition,fields})=>{const keys=Object.keys(fields).filter(k=>Object.hasOwn(person,k));if(!keys.length)return [];const row={person};for(const k of keys)row[fields[k]]=person[k];if(!definition.validate(row))throw Error('Invalid '+definition.name+' input');return [{definition,row,keys}];});}
