const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),finite=v=>Number.isFinite(v)&&v>=0,signed=v=>Number.isFinite(v)||v===-Infinity,unit=v=>finite(v)&&v<=1,identity=v=>Number.isSafeInteger(v)||typeof v==='string',point=v=>record(v)&&Number.isFinite(v.x)&&Number.isFinite(v.z),optional=(r,k,test)=>r[k]===undefined||test(r[k]),nullable=test=>v=>v===null||test(v),textMemory=v=>record(v)&&typeof v.text==='string'&&finite(v.at);
export class VillageFaith {}
export const FaithState={name:'FaithState',replaceable:false,validate:s=>s instanceof VillageFaith&&record(s.economy)&&optional(s,'shrine',nullable(point))&&typeof s.offeringsEnabled==='boolean'&&['wishes','offerings','nextCheck','rain','dryFor'].every(k=>finite(s[k]))&&signed(s.lastOfferingAt)};
export const PrayersState={name:'PrayersState',replaceable:false,validate:s=>record(s)&&optional(s,'shrine',nullable(point))};
export const validBelief=f=>record(f)&&['value','gratitude','complacency'].every(k=>optional(f,k,unit))&&['lastOfferedAt','lastHarmAt'].every(k=>optional(f,k,signed))&&['offerAfter','nextHardshipAt','cueAt'].every(k=>optional(f,k,finite))&&optional(f,'blessings',v=>Array.isArray(v)&&v.length<=8&&v.every(finite))&&!Object.hasOwn(f,'favorSeen')&&!Object.hasOwn(f,'jealousy');
export const ActorFaith={name:'ActorFaith',validate:r=>record(r)&&record(r.person)&&optional(r,'belief',nullable(validBelief))&&['handAfter','witnessAfter'].every(k=>optional(r,k,finite))};
export const ActorOffering={name:'ActorOffering',validate:r=>record(r)&&record(r.person)&&optional(r,'kind',v=>['wood','stone','food'].includes(v))&&optional(r,'cargo',nullable(v=>record(v)&&['wood','stone','food'].includes(v.kind)&&finite(v.amount)))&&['deadline','until'].every(k=>optional(r,k,finite))};
const prayerKinds=['rain','repair','shelter','return','food','company'];
const prayer=p=>record(p)&&prayerKinds.includes(p.kind)&&point(p.point)&&finite(p.askedAt)&&finite(p.deadline)&&optional(p,'targetId',identity)&&['answeredAt','health','growth','population'].every(k=>optional(p,k,nullable(finite)));
export const ActorPrayer={name:'ActorPrayer',validate:r=>record(r)&&record(r.person)&&optional(r,'request',nullable(prayer))&&['after','until','reliefUntil'].every(k=>optional(r,k,finite))&&optional(r,'memories',v=>Array.isArray(v)&&v.length<=4&&v.every(m=>record(m)&&prayerKinds.includes(m.kind)&&finite(m.at)))};
export const divineKinds=['work','replant','chest','drop','building','repair','campfire','farm'],divineStatuses=['pending','accepted','refused','deferred','unavailable'];
export const validDivineIntent=r=>record(r)&&divineKinds.includes(r.kind)&&divineStatuses.includes(r.status)&&identity(r.targetId)&&typeof r.task==='string'&&finite(r.askedAt)&&unit(r.roll)&&(r.status==='pending'||finite(r.decidedAt)&&typeof r.reason==='string');
export const ActorDivineIntent={name:'ActorDivineIntent',validate:r=>record(r)&&record(r.person)&&optional(r,'request',nullable(validDivineIntent))&&optional(r,'choice',v=>record(v)&&record(v.previous)&&finite(v.readyAt)&&finite(v.until))};
export const ActorDivineResponse={name:'ActorDivineResponse',validate:r=>record(r)&&record(r.person)&&optional(r,'mood',nullable(v=>record(v)&&typeof v.kind==='string'&&finite(v.until)))&&optional(r,'memories',v=>Array.isArray(v)&&v.length<=6&&v.every(textMemory))};
export const religionDomains=[
 {definition:ActorFaith,key:'actorFaith',access:'actorFaith',fields:{faith:'belief',divineFaithAfter:'handAfter',divineWitnessAfter:'witnessAfter'}},
 {definition:ActorOffering,key:'actorOfferings',access:'actorOffering',fields:{offeringKind:'kind',offeringCargo:'cargo',offeringDeadline:'deadline',offeringUntil:'until'}},
 {definition:ActorPrayer,key:'actorPrayers',access:'actorPrayer',fields:{prayer:'request',prayerAfter:'after',prayerUntil:'until',prayerMemories:'memories',reliefUntil:'reliefUntil'}},
 {definition:ActorDivineIntent,key:'actorDivineIntents',access:'actorDivineIntent',fields:{divineRequest:'request',placementChoice:'choice'}},
 {definition:ActorDivineResponse,key:'actorDivineResponses',access:'actorDivineResponse',fields:{divineMemories:'memories',divineMood:'mood'}}
];
export function religionInput(person){return religionDomains.flatMap(({definition,fields})=>{const keys=Object.keys(fields).filter(k=>Object.hasOwn(person,k));if(!keys.length)return [];const row={person};for(const key of keys)row[fields[key]]=person[key];if(!definition.validate(row))throw Error('Invalid '+definition.name+' input');return [{definition,row,keys}];});}
