import {villageWorld} from './village-world.js';import {FaithState,PrayersState} from './religion-data.js';
const specs={faith:FaithState,prayers:PrayersState},bindings=new WeakMap();
export function religionBinding(state,name){const b=bindings.get(state);if(!b||b.name!==name||!b.world.alive(b.id)||b.world.get(b.id,name)!==state||b.world.resources.get(name)!==state)throw Error(name+' is not a live entity');return b;}
function validate(e,key,state){const d=specs[key];if(!d||!d.validate(state)||key==='faith'&&state.economy!==e)throw Error('Invalid '+d?.name);const b=bindings.get(state);if(b&&religionBinding(state,d.name).world!==villageWorld(e))throw Error('Foreign '+d.name);}
export function bindReligion(e,key,state){validate(e,key,state);const world=villageWorld(e),d=specs[key],bound=bindings.get(state);if(bound){e[key]=state;return state;}if(!world.stores.has(d.name))world.define(d);const old=world.resources.get(d.name),b=old&&bindings.get(old);if(b)world.destroy(b.id);const id=world.create({[d.name]:state});bindings.set(state,{world,id,name:d.name});world.setResource(d.name,state);e[key]=state;return state;}
export function restoreReligion(e){for(const [key,d]of Object.entries(specs))if(e[key]!=null)validate(e,key,e[key]);const world=villageWorld(e);for(const [key,d]of Object.entries(specs)){if(!world.stores.has(d.name))world.define(d);for(const id of [...world.query([d.name])])if(world.get(id,d.name)!==e[key])world.destroy(id);if(e[key]!=null)bindReligion(e,key,e[key]);else world.resources.delete(d.name);}}
export const createPrayers=(e,options)=>bindReligion(e,'prayers',{shrine:options.shrine});
export function setFaithState(state,values){religionBinding(state,'FaithState');if(Object.keys(values).some(k=>!['shrine','offeringsEnabled','wishes','offerings','nextCheck','lastOfferingAt','rain','dryFor'].includes(k))||!FaithState.validate(Object.assign(Object.create(Object.getPrototypeOf(state)),state,values)))throw Error('Invalid FaithState');Object.assign(state,values);return state;}
export function setPrayersState(state,values){religionBinding(state,'PrayersState');if(Object.keys(values).some(k=>k!=='shrine')||!PrayersState.validate({...state,...values}))throw Error('Invalid PrayersState');Object.assign(state,values);return state;}
