const record=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),optional=(r,k,test)=>r[k]===undefined||test(r[k]);
// Both numeric villager IDs and string beast IDs can own a harvest reservation.
export const ResourceHarvest={name:'ResourceHarvest',validate:r=>record(r)&&record(r.node)&&optional(r,'reservedBy',v=>v===null||id(v))&&optional(r,'hits',v=>Number.isSafeInteger(v)&&v>=0)&&optional(r,'retryAt',Number.isFinite)&&optional(r,'raidRetryAt',Number.isFinite)&&Object.keys(r).every(k=>['node','reservedBy','hits','retryAt','raidRetryAt'].includes(k))};
export const ResourceGrowth={name:'ResourceGrowth',validate:r=>record(r)&&record(r.node)&&optional(r,'state',v=>['ready','depleted','growing'].includes(v))&&optional(r,'growth',v=>Number.isFinite(v)&&v>=0&&v<=1)&&optional(r,'readyAt',v=>v===null||Number.isFinite(v))&&optional(r,'initialGrow',v=>Number.isFinite(v)&&v>0)&&Object.keys(r).every(k=>['node','state','growth','readyAt','initialGrow'].includes(k))};
const bool=v=>typeof v==='boolean',nonnegative=v=>Number.isFinite(v)&&v>=0,id=v=>typeof v==='string'&&v.length>0||Number.isSafeInteger(v)&&v>=0;
function component(name,fields){return {name,validate:r=>record(r)&&record(r.node)&&Object.entries(fields).every(([k,test])=>optional(r,k,test))&&Object.keys(r).every(k=>k==='node'||Object.hasOwn(fields,k))};}
export const ResourceCultivation=component('ResourceCultivation',{plotId:id,needsPlanting:bool,unplanted:bool});
export const ResourceWoodland=component('ResourceWoodland',{woodland:bool,parentId:id,ecoBornAt:nonnegative,felledAt:v=>v===null||nonnegative(v),growSeconds:v=>Number.isFinite(v)&&v>0,age:nonnegative});
export const ResourceOak=component('ResourceOak',{oakSeedAt:nonnegative,oakPlantedAt:v=>v===null||nonnegative(v),oakTended:bool,oakPlantContactAt:nonnegative,oakPlanterId:id});
export const ResourceCondition=component('ResourceCondition',{burningUntil:Number.isFinite,burntPlant:bool,removed:bool});
export const resourceDomains=[{definition:ResourceOak,key:'resourceOaks',fields:['oakSeedAt','oakPlantedAt','oakTended','oakPlantContactAt','oakPlanterId'],access:'resourceOak'},{definition:ResourceHarvest,key:'resourceHarvests',fields:['reservedBy','hits','retryAt','raidRetryAt'],access:'resourceHarvest'},{definition:ResourceGrowth,key:'resourceGrowths',fields:['state','growth','readyAt','initialGrow'],access:'resourceGrowth'},{definition:ResourceCultivation,key:'resourceCultivations',fields:['plotId','needsPlanting','unplanted'],access:'resourceCultivation'},{definition:ResourceWoodland,key:'resourceWoodlands',fields:['woodland','parentId','ecoBornAt','felledAt','growSeconds','age'],access:'resourceWoodland'},{definition:ResourceCondition,key:'resourceConditions',fields:['burningUntil','burntPlant','removed'],access:'resourceCondition'}];
export const ResourceNode={name:'ResourceNode',replaceable:false,validate:n=>record(n)&&resourceDomains.every(s=>s.fields.every(k=>!Object.hasOwn(n,k)))};
