import {villageWorld} from './village-world.js';
import {ShelterIdentity,HouseFire,ShelterSchedule,ShelterWeather,shelterDomains} from './shelter-data.js';
export {shelterDomains} from './shelter-data.js';
const bindings=new WeakMap(),fires=new WeakMap();
const HouseFireOrder={name:'HouseFireOrder',validate:r=>Number.isSafeInteger(r?.order)&&r.order>=0};
function define(world){for(const def of [ShelterIdentity,HouseFire,HouseFireOrder,ShelterSchedule,ShelterWeather])if(!world.stores.has(def.name))world.define(def);}
export function shelterBinding(state){const b=bindings.get(state);if(!b||!b.world.alive(b.id)||b.world.get(b.id,'ShelterIdentity')!==state||b.world.resources.get('Shelter')!==state||b.e.shelter!==state)throw Error('Shelter state is no longer active');return b;}
const get=(s,name)=>{if(s==null)return undefined;const {world,id}=shelterBinding(s);return world.get(id,name);};
export const shelterSchedule=s=>get(s,'ShelterSchedule'),shelterWeather=s=>get(s,'ShelterWeather');
function set(s,values,definition){const {world,id}=shelterBinding(s);return world.add(id,definition.name,{...values,shelter:s});}
export const setShelterSchedule=(s,v)=>set(s,v,ShelterSchedule),setShelterWeather=(s,v)=>set(s,v,ShelterWeather);
function list(b){const store=b.world.store('HouseFire'),order=b.world.store('HouseFireOrder');if(b.revision!==store.valueRevision||b.orderRevision!==order.valueRevision){b.cached=Object.freeze(b.world.query(['HouseFire','HouseFireOrder']).filter(id=>b.world.owner(id)===b.id).sort((a,c)=>order.get(a).order-order.get(c).order).map(id=>{const row=store.get(id);fires.set(row,{world:b.world,id,owner:b.id});return row;}));b.revision=store.valueRevision;b.orderRevision=order.valueRevision;}return b.cached;}
function checkFires(b,rows){if(!Array.isArray(rows)||new Set(rows.map(r=>r?.id)).size!==rows.length)throw Error('Invalid house fires');for(const row of rows){b.world.validate('HouseFire',row);const old=fires.get(row);if(old&&old.world.alive(old.id)&&(old.world!==b.world||old.owner!==b.id))throw Error('Foreign house fire');}}
export function replaceHouseFires(s,rows){const b=shelterBinding(s);checkFires(b,rows);const previous=new Map(list(b).map(row=>[row,fires.get(row).id]));for(const [row,id]of previous)if(!rows.includes(row))b.world.destroy(id);for(const [order,row]of rows.entries()){let id=previous.get(row);if(id===undefined){id=b.world.create({HouseFire:row,HouseFireOrder:{order}});b.world.own(b.id,id,{component:'ShelterIdentity'});fires.set(row,{world:b.world,id,owner:b.id});}else b.world.add(id,'HouseFireOrder',{order});}b.revision=-1;const current=list(b);if(rows.length===current.length&&rows.every((r,i)=>r===current[i]))b.cached=Object.freeze(rows);return b.cached;}
export function addHouseFire(s,input){const row={...input};replaceHouseFires(s,[...s.fires,row]);return row;}
export function setHouseFire(s,id,values){const b=shelterBinding(s),row=s.fires.find(r=>r.id===id);if(!row)throw Error('Unknown house fire');if(values.id!==undefined&&values.id!==id)throw Error('House fire home cannot change');const next={...row,...values,id};b.world.validate('HouseFire',next);const fire=fires.get(row);b.world.add(fire.id,'HouseFire',next);fires.set(next,fire);return next;}
function project(e,spec,world,incoming){const store=world.store(spec.definition.name);let revision=-1,cached;Object.defineProperty(e,spec.key,{enumerable:true,configurable:true,get(){if(revision!==store.valueRevision){const current=store.values.slice();cached=Object.freeze(incoming.length===current.length&&incoming.every((r,i)=>r===current[i])?incoming:current);revision=store.valueRevision;}return cached;}});}
export function bindShelterState(e,s){const world=villageWorld(e);define(world);const oldBinding=bindings.get(s);if(oldBinding){if(oldBinding.e!==e)throw Error('Foreign shelter state');shelterBinding(s);return s;}world.validate('ShelterIdentity',s);const plans=shelterDomains.map(spec=>{const incoming=e[spec.key]??[],keys=spec.fields.filter(k=>Object.hasOwn(s,k));if(!Array.isArray(incoming)||incoming.length>1||incoming.some(r=>r.shelter!==s)||incoming.length&&keys.length)throw Error('Invalid or ambiguous '+spec.definition.name);const row=incoming[0]??Object.fromEntries([['shelter',s],...keys.map(k=>[k,s[k]])]);world.validate(spec.definition.name,row);return {spec,incoming,row,keys};});const rows=s.fires;checkFires({world,id:undefined},rows);
 const old=world.resources.get('Shelter'),oldId=old&&bindings.get(old)?.id;if(oldId!==undefined)world.destroy(oldId);const id=world.create({ShelterIdentity:s}),b={world,id,e,revision:-1,orderRevision:-1,cached:Object.freeze([])};bindings.set(s,b);e.shelter=s;world.setResource('Shelter',s);for(const {spec,row,keys,incoming}of plans){for(const key of keys)delete s[key];world.add(id,spec.definition.name,row);project(e,spec,world,incoming);}Object.defineProperty(s,'fires',{enumerable:true,configurable:true,get(){return list(b)}});replaceHouseFires(s,rows);return s;}
export function restoreShelterState(e){const world=villageWorld(e);define(world);if(e.shelter)return bindShelterState(e,e.shelter);for(const spec of shelterDomains)if(e[spec.key]?.length)throw Error('Shelter components without shelter state');const old=world.resources.get('Shelter'),id=old&&bindings.get(old)?.id;if(id!==undefined)world.destroy(id);world.resources.delete('Shelter');for(const spec of shelterDomains)project(e,spec,world,[]);}

export function createShelterState(e){if(e.shelter){shelterBinding(e.shelter);return e.shelter;}return bindShelterState(e,{fires:[],nextBeds:0});}
