import {renderFrame,motionBounds} from '../runtime.js';
import {surface} from './filters.js';
import {GIFEncoder,quantize,applyPalette,zipSync,strToU8,parseGIF,decompressFrames} from './media-vendor.js';
export async function decodeGIF(buffer){const gif=parseGIF(buffer),frames=decompressFrames(gif,true),canvas=surface(gif.lsd.width,gif.lsd.height),ctx=canvas.getContext('2d'),images=[];let previous=null,last=null;for(const f of frames){if(last?.disposalType===2)ctx.clearRect(last.dims.left,last.dims.top,last.dims.width,last.dims.height);else if(last?.disposalType===3&&previous)ctx.putImageData(previous,0,0);previous=ctx.getImageData(0,0,canvas.width,canvas.height);const patch=surface(f.dims.width,f.dims.height);patch.getContext('2d').putImageData(new ImageData(f.patch,f.dims.width,f.dims.height),0,0);ctx.drawImage(patch,f.dims.left,f.dims.top);const copy=surface(canvas.width,canvas.height);copy.getContext('2d').drawImage(canvas,0,0);images.push({canvas:copy,delay:f.delay||100});last=f;}return images;}
export function frameTimes(clip,{fps=clip.fps,skip=0,reverse=false}={}){const count=Math.max(1,Math.ceil(clip.duration*fps)),times=[];for(let i=0;i<count;i+=Math.max(1,Math.floor(skip)+1))times.push(i/fps);if(reverse)times.reverse();return times;}
export async function pngBytes(canvas){const blob=canvas.convertToBlob?await canvas.convertToBlob({type:'image/png'}):await new Promise(r=>canvas.toBlob(r,'image/png'));return new Uint8Array(await blob.arrayBuffer());}
export function contentBounds(canvas){const {width:w,height:h}=canvas,d=canvas.getContext('2d').getImageData(0,0,w,h).data;let x=w,y=h,r=0,b=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(d[(yy*w+xx)*4+3]){x=Math.min(x,xx);y=Math.min(y,yy);r=Math.max(r,xx+1);b=Math.max(b,yy+1);}return r?{x,y,width:r-x,height:b-y}:{x:0,y:0,width:1,height:1};}
export async function renderExport(project,images,clip,options={},progress=()=>{}){
 if(options.fps!==undefined&&(!Number.isInteger(options.fps)||options.fps<1||options.fps>120))throw Error('FPS must be 1–120');if(options.skip!==undefined&&(!Number.isInteger(options.skip)||options.skip<0||options.skip>1000))throw Error('Frame skip must be 0–1000');
 const width=options.width??project.fx?.settings.width??512,height=options.height??project.fx?.settings.height??512,format=options.format??'sheet',times=options.time!==undefined?[options.time]:frameTimes(clip,options),fps=options.fps??clip.fps,frames=[],files={},metadata={format:'puppet-studio-frames',version:1,clip:clip.id,width,height,fps,skip:options.skip??0,reverse:!!options.reverse,frames:[]},framing=motionBounds(project,clip);if(times.length*width*height>200000000)throw Error('Export exceeds 200 million pixels. Lower size, FPS, or increase frame skip.');
 if(!['sheet','frames','gif','png'].includes(format))throw Error('Unknown export format');
 const gif=format==='gif'?GIFEncoder():null;
 for(let i=0;i<times.length;i++){const canvas=renderFrame(project,images,clip,times[i],{width,height,framing}),trim=options.trim?contentBounds(canvas):{x:0,y:0,width,height},name=String(i).padStart(5,'0')+'.png';metadata.frames.push({index:i,time:times[i],source:trim,name});
  if(format==='gif'){const rgba=canvas.getContext('2d').getImageData(0,0,width,height).data,palette=quantize(rgba,255,{format:'rgb444'});palette.unshift([0,0,0]);const pixels=applyPalette(rgba,palette,'rgb444');for(let k=0;k<pixels.length;k++)if(rgba[k*4+3]<128)pixels[k]=0;else if(pixels[k]===0)pixels[k]=1;gif.writeFrame(pixels,width,height,{palette,transparent:true,transparentIndex:0,delay:1000/fps*((options.skip??0)+1),dispose:2,repeat:clip.loop?0:-1});}
  else if(format==='frames'||format==='png'){const crop=surface(trim.width,trim.height);crop.getContext('2d').drawImage(canvas,trim.x,trim.y,trim.width,trim.height,0,0,trim.width,trim.height);files[name]=await pngBytes(crop);}
  else frames.push({canvas,trim});progress((i+1)/times.length);await new Promise(r=>setTimeout(r,0));
 }
 if(gif){gif.finish();return{bytes:gif.bytes(),type:'image/gif',extension:'gif',metadata};}
 if(format==='png')return{bytes:files[Object.keys(files)[0]],type:'image/png',extension:'png',metadata};
 if(format==='sheet'){const cols=Math.max(1,Math.ceil(Math.sqrt(frames.length))),cellW=Math.max(...frames.map(f=>f.trim.width)),cellH=Math.max(...frames.map(f=>f.trim.height)),sheet=surface(cols*cellW,Math.ceil(frames.length/cols)*cellH);if(sheet.width>16384||sheet.height>16384)throw Error('Sheet exceeds 16384 pixels. Use PNG frames or smaller dimensions.');const ctx=sheet.getContext('2d');for(let i=0;i<frames.length;i++){const {canvas,trim}=frames[i],x=i%cols*cellW,y=Math.floor(i/cols)*cellH;ctx.drawImage(canvas,trim.x,trim.y,trim.width,trim.height,x,y,trim.width,trim.height);metadata.frames[i].frame={x,y,width:trim.width,height:trim.height};}files['spritesheet.png']=await pngBytes(sheet);metadata.sheet={width:sheet.width,height:sheet.height};}
 files['animation.json']=strToU8(JSON.stringify(metadata,null,2));return{bytes:zipSync(files),type:'application/zip',extension:'zip',metadata};
}
