import * as T from './models-vendor.js';
import {parameter} from './math.js';
export async function loadModels(models=[]){const result=new Map();for(const model of models){if(!model.src)continue;const renderer=new T.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});renderer.setSize(model.width??256,model.height??256);renderer.setClearColor(0,0);let object;
 if(model.format==='glb'||model.format==='gltf'){object=(await new T.GLTFLoader().loadAsync(model.src)).scene;}
 else{const text=await (await fetch(model.src)).text(),loader=new T.OBJLoader();if(model.mtl){const materials=new T.MTLLoader().parse(model.mtl,'');materials.preload();loader.setMaterials(materials);}object=loader.parse(text);}
 const box=new T.Box3().setFromObject(object),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3());object.position.sub(center);const pivot=new T.Group();pivot.add(object);pivot.scale.setScalar(2/Math.max(size.x,size.y,size.z,.001));const scene=new T.Scene();scene.add(pivot);const ambient=new T.AmbientLight('#ffffff',model.ambient??.8),light=new T.PointLight(model.lightColor??'#ffffff',model.lightIntensity??3,0,0);scene.add(ambient,light);
 const materials=[];object.traverse(child=>{if(child.isMesh){if(!model.mtl&&model.format==='obj')child.material=new T.MeshStandardMaterial({color:model.color??'#d2eab0',roughness:.6});materials.push(...(Array.isArray(child.material)?child.material:[child.material]));}});
 const draw=(time,m)=>{const aspect=(m.width??256)/(m.height??256),camera=m.camera==='perspective'?new T.PerspectiveCamera(m.fov??40,aspect,.01,100):new T.OrthographicCamera(-1.5*aspect,1.5*aspect,1.5,-1.5,.01,100);camera.position.set(0,0,m.distance??5);camera.lookAt(0,0,0);pivot.rotation.set(parameter(m.rotationX,time)*Math.PI/180,(parameter(m.rotationY,time)+parameter(m.spin,time)*time)*Math.PI/180,parameter(m.rotationZ,time)*Math.PI/180);pivot.scale.setScalar(2/Math.max(size.x,size.y,size.z,.001)*parameter(m.scale,time,1));ambient.intensity=m.ambient??.8;light.position.set(m.lightX??3,m.lightY??5,m.lightZ??5);light.color.set(m.lightColor??'#ffffff');light.intensity=m.lightIntensity??3;for(const material of materials){material.wireframe=!!m.wireframe;if(model.format==='obj'&&!model.mtl)material.color.set(m.color??'#d2eab0');}renderer.render(scene,camera);return renderer.domElement;};draw.dispose=()=>{renderer.dispose();for(const m of materials)m.dispose();object.traverse(c=>c.geometry?.dispose());};result.set(model.id,draw);
 }return result;}
