import {prepareBodyJoinProfiles} from '../body-join-profiles.js';
import {drawBodyJoinSeam} from '../body-join-seams.js';
import {bodyJoinFrame} from '../body-joins.js';
import {joinedArtwork} from '../body-join-render.js';
import {drawBackdrop,backdropView2D} from '../authoring/backdrop-render.js';
import {styledJoints,projectGrading,styledLighting} from '../authoring/appearance.js';
import {vectorCanvas} from '../vector/render.js';
import {gradeCanvas} from '../grading-2d.js';
import {point} from '../joint-transforms.js';
import {lightingFrame,illuminateSprite} from '../lighting-2d.js';
import {imageFrame} from './frames.js';
import {dynamicMotion} from './motion.js';
import {surface,filterImage,composite} from './filters.js';
import {sampleParticleSystem,drawParticles} from './particles.js';
import {fluidAt,fluidPixels} from './fluids.js';
import {presentationAt} from './presentation.js';
import {random,hash,clamp,parameter} from './math.js';
const artCache=new WeakMap(),maskCache=new WeakMap(),morphCache=new WeakMap();
function imageMask(image,n){if(!image)return null;let cache=maskCache.get(image);if(!cache){cache=new Map();maskCache.set(image,cache);}if(cache.has(n))return cache.get(n);const c=surface(n,n),ctx=c.getContext('2d');ctx.drawImage(image,0,0,n,n);const data=ctx.getImageData(0,0,n,n).data,result=Array.from({length:n*n},(_,i)=>data[i*4+3]/255);cache.set(n,result);return result;}
function artwork(j,images,time,scale=1){const s=j.sprite,original=images.get(s.asset);if(!original)return null;const crop=s.crop??[0,0,1,1],v=j.visual??{},vector=original.vectorModel,dynamic=!!vector?.tracks.length,img=vector?vectorCanvas(vector,time,Math.max(1,Math.round(Math.min(2048,s.width*scale/crop[2]))),Math.max(1,Math.round(Math.min(2048,s.height*scale/crop[3])))):imageFrame(original,time,s.fps??12);if(vector&&crop.every((n,i)=>n===[0,0,1,1][i])&&!v.tintAmount)return img;const key=JSON.stringify([s,v.tint,v.tintAmount,v.smear?.inline,scale]),bucket=artCache.get(img)??new Map();artCache.set(img,bucket);if(!dynamic&&bucket.has(key))return bucket.get(key);const c=surface(Math.max(1,Math.min(2048,s.width*scale)),Math.max(1,Math.min(2048,s.height*scale))),ctx=c.getContext('2d'),iw=img.naturalWidth??img.width,ih=img.naturalHeight??img.height;ctx.drawImage(img,crop[0]*iw,crop[1]*ih,crop[2]*iw,crop[3]*ih,0,0,c.width,c.height);const result=v.tintAmount?filterImage('tint',c,{color:v.tint,amount:v.tintAmount}):c;if(!dynamic){bucket.set(key,result);if(bucket.size>16)bucket.delete(bucket.keys().next().value);}return result;}
function sprite(ctx,j,images,world,time,{alpha=1,trail=false,lighting,velocity,joins}={}){let s=j.sprite;const v=j.visual??{},m=ctx.getTransform(),scale=Math.max(.25,2**Math.ceil(Math.log2(Math.max(Math.hypot(m.a*world[0]+m.c*world[1],m.b*world[0]+m.d*world[1]),Math.hypot(m.a*world[2]+m.c*world[3],m.b*world[2]+m.d*world[3]))))),art=artwork(j,images,time,scale);if(!art)return;ctx.save();if(velocity&&v.smear?.stretch){const speed=Math.hypot(velocity.x,velocity.y),gain=1+Math.min(1.5,speed/600*v.smear.stretch),angle=Math.atan2(velocity.y,velocity.x),cx=world[4],cy=world[5];ctx.translate(cx,cy);ctx.rotate(angle);ctx.scale(gain,v.smear.preserveVolume===false?1:1/gain);ctx.rotate(-angle);ctx.translate(-cx,-cy);}ctx.transform(...world);ctx.transform(1,Math.tan((parameter(v.skewY,time)+dynamicMotion(v.motion,time).skewY)*Math.PI/180),Math.tan((parameter(v.skewX,time)+dynamicMotion(v.motion,time).skewX)*Math.PI/180),1,0,0);ctx.globalAlpha*=clamp(parameter(v.opacity,time,1))*alpha;ctx.globalCompositeOperation=v.blend??'source-over';let source=art;
 if(trail&&v.smear?.inline>0){source=surface(art.width,art.height);const q=source.getContext('2d');q.drawImage(art,0,0);q.globalCompositeOperation='destination-in';const n=Math.min(16,v.smear.inline);for(const [x,y]of [[n,0],[-n,0],[0,n],[0,-n]])q.drawImage(art,x,y);}
 if(trail&&v.smear?.tint)source=filterImage('tint',source,{color:v.smear.color,amount:v.smear.tint});
 if(trail&&v.smear?.outline)source=filterImage('outline',source,{color:v.smear.outlineColor,width:v.smear.outline});
 source=illuminateSprite(source,j,world,lighting);if(joins?.length){const warped=joinedArtwork(source,s,joins,scale);source=warped.canvas;s=warped.sprite;}const x=-s.width*s.pivotX,y=-s.height*s.pivotY;
 if(v.break?.enabled&&!trail&&time>=v.break.delay){const b=v.break,age=time-b.delay,step=Math.max(2,b.pieceSize),cols=Math.ceil(s.width/step),rows=Math.ceil(s.height/step);if(cols*rows>12000){ctx.restore();return;}
  for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const r=random(hash(b.seed,j.id,row,col)),delay=r()*(b.gradual??0),t=Math.max(0,age-delay),progress=clamp(t/b.duration),a=(b.direction+(r()-.5)*b.spread)*Math.PI/180,speed=b.speed*(.5+r()),spin=(r()-.5)*b.spin*2,sx=col*step,sy=row*step,w=Math.min(step,s.width-sx),h=Math.min(step,s.height-sy);ctx.save();ctx.translate(x+sx+w/2+Math.cos(a)*speed*t,y+sy+h/2+Math.sin(a)*speed*t+b.gravity*t*t/2);ctx.rotate(spin*t*Math.PI/180);const size=Math.max(0,1-progress*b.shrink);ctx.scale(size,size);ctx.globalAlpha*=Math.max(0,1-progress*b.fade);ctx.drawImage(source,sx/s.width*source.width,sy/s.height*source.height,w/s.width*source.width,h/s.height*source.height,-w/2,-h/2,w,h);ctx.restore();}
 }else if(v.morph?.enabled){const a=v.morph,w=clamp(parameter(a.weight,time,1)),inflate=parameter(a.inflate,time)*w,taper=parameter(a.taper,time)*w,bend=parameter(a.bend,time)*w,padRatio=(Math.abs(inflate)+Math.abs(taper)+2*Math.abs(bend))/2+.002,total=1+padRatio*2,res=Math.min(1,2048/(source.width*total)),sw=source.width*res,sh=Math.max(1,Math.round(source.height*res)),padding=sw*padRatio,key=[inflate,taper,bend,sw,sh,source.vectorFrame].join(':');let cached=morphCache.get(source);if(!cached){cached={canvas:surface(Math.ceil(sw*total),sh)};morphCache.set(source,cached);}const warped=cached.canvas;if(cached.key!==key){if(warped.width!==Math.ceil(sw*total)||warped.height!==sh){warped.width=Math.ceil(sw*total);warped.height=sh;}const wc=warped.getContext('2d');wc.clearRect(0,0,warped.width,warped.height);for(let row=0;row<sh;row++){const u=(row+.5)/sh,shape=Math.max(.1,1+inflate*Math.sin(u*Math.PI)+taper*(u-.5)),offset=bend*Math.sin(u*Math.PI)*sw;wc.drawImage(source,0,row/sh*source.height,source.width,source.height/sh,padding+sw*(1-shape)/2+offset,row,sw*shape,1);}cached.key=key;}ctx.drawImage(warped,x-padRatio*s.width,y,s.width*total,s.height);}else if(v.wave?.enabled){const a=v.wave,horizontal=a.axis!=='y',length=horizontal?s.height:s.width,strip=Math.max(1,length/128);for(let pos=0;pos<length;pos+=strip){const end=Math.min(strip,length-pos),u=pos/length,offset=Math.sin(u*a.frequency*Math.PI*2+time*a.speed*Math.PI*2)*a.amplitude*(a.anchor?u:1);if(horizontal)ctx.drawImage(source,0,pos/s.height*source.height,source.width,end/s.height*source.height,x+offset,y+pos,s.width,end);else ctx.drawImage(source,pos/s.width*source.width,0,end/s.width*source.width,source.height,x+pos,y+offset,end,s.height);}}
 else ctx.drawImage(source,x,y,s.width,s.height);ctx.restore();}
export function drawScene(ctx,project,images,clip,time,poseAt,overrides=[]){if(clip?.fx)project={...project,fx:clip.fx};
 const profiles=prepareBodyJoinProfiles(project,images),joinCache=new Map(),joinsAt=t=>{if(!joinCache.has(t))joinCache.set(t,bodyJoinFrame(project,sample(t),profiles));return joinCache.get(t);},poseCache=new Map(),sample=t=>{if(!poseCache.has(t))poseCache.set(t,poseAt(project,clip,t));return poseCache.get(t);};
 const state=presentationAt(clip,time),at=state.animationTime,pose=sample(at),lighting=lightingFrame({...project,lighting:styledLighting(project)},clip,at,pose,overrides),layers=[];
 for(const j of styledJoints(project)){if(j.hidden||!j.sprite)continue;layers.push({layer:j.layer,draw(){const smear=j.visual?.smear,previous=Math.max(0,at-1/(clip?.fps??30)),center=p=>point(p.get(j.id).world,{x:(.5-j.sprite.pivotX)*j.sprite.width,y:(.5-j.sprite.pivotY)*j.sprite.height}),a=center(pose),b=smear?.enabled?center(sample(previous)):a,dt=Math.max(1e-6,at-previous),velocity={x:(a.x-b.x)/dt,y:(a.y-b.y)/dt},moving=Math.hypot(velocity.x,velocity.y)>=(smear?.threshold??0),active=smear?.enabled&&at>=(smear.start??0)&&at<=(smear.end??Infinity)&&moving;function trail(){if(!active)return;const count=Math.max(1,Math.min(64,Math.round(smear.samples)));for(let n=count;n>=1;n--){const t=Math.max(0,at-n/count*smear.seconds),old=sample(t);sprite(ctx,j,images,old.get(j.id).world,t,{alpha:smear.alpha*(1-n/(count+1))**smear.decay,trail:true,lighting,joins:joinsAt(t).get(j.id)});}}if(!smear?.front)trail();sprite(ctx,j,images,pose.get(j.id).world,at,{lighting,velocity:active?velocity:null,joins:joinsAt(at).get(j.id)});for(const flash of clip?.cues??[]){if(flash.enabled===false||flash.type!=='sprite-flash'||flash.joint!==j.id||time<flash.time||time>=flash.time+flash.duration)continue;const age=time-flash.time,fade=flash.profile==='contact'?age<.05?1:1-((age-.05)/.13)**2*(3-2*(age-.05)/.13):1-age/flash.duration;sprite(ctx,{...j,visual:{...j.visual,tint:flash.color,tintAmount:clamp(flash.amount*fade)}},images,pose.get(j.id).world,at,{lighting,joins:joinsAt(at).get(j.id)});}if(smear?.front)trail();}});}
 for(const part of styledJoints(project)){const join=part.bodyJoin;if(!join?.enabled||join.matchEdges===false||part.hidden)continue;const body=styledJoints(project).find(j=>j.id===join.targetNode);if(!body||body.hidden)continue;const frame=joinsAt(at).get(body.id)?.find(j=>j.partId===part.id);if(!frame?.profile)continue;const paint=(target,j)=>sprite(target,j,images,pose.get(j.id).world,at,{lighting,joins:joinsAt(at).get(j.id)});layers.push({layer:Math.max(body.layer,part.layer)+.001,draw:()=>drawBodyJoinSeam(ctx,frame,pose.get(body.id).world,target=>paint(target,body.layer>part.layer?part:body),target=>paint(target,body.layer>part.layer?body:part))});}
 for(const system of sampleParticleSystem(project.fx?.emitters??[],at,{loopDuration:clip?.loop?clip.duration:0,contours:images.contours??new Map()}))layers.push({layer:system.emitter.layer,draw:()=>drawParticles(ctx,system.particles,images)});
 for(const f of project.fx?.fluids??[]){if(f.enabled===false||at<f.delay)continue;layers.push({layer:f.layer,draw(){const config={...f,sourceMask:imageMask(images.get(f.sourceImage),f.resolution),solidMask:imageMask(images.get(f.obstacleImage),f.resolution)}, {pixels,width:n}=fluidPixels(config,at),c=surface(n,n);c.getContext('2d').putImageData(new ImageData(pixels,n,n),0,0);ctx.drawImage(c,f.x-f.width/2,f.y-f.height/2,f.width,f.height);}});}
 for(const model of project.fx?.models??[]){const renderer=images.models?.get(clip?.fx?clip.id+':'+model.id:model.id);if(renderer&&model.enabled!==false)layers.push({layer:model.layer??0,draw(){const image=renderer(at,model);ctx.drawImage(image,(model.x??0)-image.width/2,(model.y??0)-image.height/2);}});}
 layers.sort((a,b)=>a.layer-b.layer);for(const layer of layers)layer.draw();return state;
}
export function frameCamera(camera,state,width,height){const [a,b,c,d,x,y]=camera,angle=state.rotation*Math.PI/180,co=Math.cos(angle)*state.scale,si=Math.sin(angle)*state.scale;return[co*a-si*b,si*a+co*b,co*c-si*d,si*c+co*d,width/2+co*(x-width/2)-si*(y-height/2)+state.x,height/2+si*(x-width/2)+co*(y-height/2)+state.y];}
export function renderSceneFrame(project,images,clip,time,{width=512,height=512,camera=[1,0,0,1,width/2,height/2],background='transparent',presentation=true,underlay,overrides=[]}={},poseAt){
 const canvas=surface(width,height),ctx=canvas.getContext('2d'),state=presentation?presentationAt(clip,time):{x:0,y:0,rotation:0,scale:1,overlays:[],letterbox:0},cam=frameCamera(camera,state,width,height);
 if(background!=='transparent'){ctx.fillStyle=background;ctx.fillRect(0,0,width,height);}drawBackdrop(ctx,project,images,time,backdropView2D(cam,width,height));ctx.save();ctx.transform(...cam);underlay?.(ctx);drawScene(ctx,project,images,presentation?clip:clip?{...clip,cues:[]}:null,time,poseAt,overrides);ctx.restore();let result=composite(canvas,project.fx,images,time);
 // Camera and post effects run on presentation time even while the animation is frozen.
 const final=surface(width,height),fc=final.getContext('2d');fc.drawImage(result,0,0);
 for(const overlay of state.overlays){fc.globalCompositeOperation=overlay.blend;fc.globalAlpha=clamp(overlay.opacity);fc.fillStyle=overlay.color;fc.fillRect(0,0,width,height);}fc.globalAlpha=1;fc.globalCompositeOperation='source-over';if(state.letterbox){fc.fillStyle='#000';fc.fillRect(0,0,width,height*state.letterbox);fc.fillRect(0,height*(1-state.letterbox),width,height*state.letterbox);}
 gradeCanvas(final,projectGrading(project));const pixelSize=project.fx?.settings.pixelSize??1;return pixelSize>1?filterImage('pixelate',final,{size:pixelSize}):final;
}
