import {finiteTree,validateCurve} from './validate.js';
export const NODE_TYPES={
 scene:{label:'Scene',group:'Input',params:{}},image:{label:'Image',group:'Input',params:{asset:''}},solid:{label:'Solid colour',group:'Input',params:{color:'#f29b57'}},noise:{label:'Noise',group:'Generate',params:{scale:12,speed:1,seed:1}},gradient:{label:'Gradient',group:'Generate',params:{color:'#faac65',color2:'#715bd5',angle:90}},checker:{label:'Checker',group:'Generate',params:{size:16,color:'#ffffff',color2:'#272737'}},
 blend:{label:'Blend',group:'Composite',params:{mode:'screen',amount:1}},mask:{label:'Alpha mask',group:'Composite',params:{invert:false}},transform:{label:'Transform',group:'Transform',params:{x:0,y:0,rotation:0,scale:1}},crop:{label:'Crop',group:'Transform',params:{x:0,y:0,width:256,height:256}},tile:{label:'Tile',group:'Transform',params:{count:2}},mirror:{label:'Mirror',group:'Transform',params:{x:true,y:false}},
 glow:{label:'Glow',group:'Lighting',params:{radius:8,strength:1.5,color:'#ffba71'}},outline:{label:'Outline',group:'Lighting',params:{width:2,color:'#151927'}},shadow:{label:'Shadow',group:'Lighting',params:{x:6,y:8,blur:6,color:'#101021'}},blur:{label:'Blur',group:'Filter',params:{radius:3}},sharpen:{label:'Sharpen',group:'Filter',params:{amount:1}},denoise:{label:'Denoise',group:'Filter',params:{amount:1}},
 tint:{label:'Tint',group:'Colour',params:{color:'#ff9659',amount:.5}},hue:{label:'Hue shift',group:'Colour',params:{degrees:90}},saturation:{label:'Saturation',group:'Colour',params:{amount:1.5}},brightness:{label:'Brightness',group:'Colour',params:{amount:1.2}},contrast:{label:'Contrast',group:'Colour',params:{amount:1.5}},gamma:{label:'Gamma',group:'Colour',params:{amount:1.5}},grayscale:{label:'Grayscale',group:'Colour',params:{}},sepia:{label:'Sepia',group:'Colour',params:{amount:1}},invert:{label:'Invert',group:'Colour',params:{}},posterize:{label:'Posterize',group:'Pixel',params:{levels:4}},threshold:{label:'Threshold',group:'Pixel',params:{level:.5}},pixelate:{label:'Pixelate',group:'Pixel',params:{size:4}},palette:{label:'Palette & dither',group:'Pixel',params:{colors:['#171c2b','#64458b','#ce688a','#f3c779','#ffffff'],excluded:[],dither:.4,pattern:'bayer',patternAsset:''}},
 wave:{label:'Wave distortion',group:'Distort',params:{amplitude:8,frequency:3,speed:1,axis:'x'}},displace:{label:'Displacement map',group:'Distort',params:{amount:14}},ripple:{label:'Ripple',group:'Distort',params:{amplitude:6,frequency:10,speed:2}},twirl:{label:'Twirl',group:'Distort',params:{amount:2,radius:.6}},chromatic:{label:'Chromatic aberration',group:'Distort',params:{offset:3}},glitch:{label:'Glitch',group:'Distort',params:{amount:12,lines:8,speed:8,seed:1}},dissolve:{label:'Dissolve',group:'Reveal',params:{progress:.4,scale:6,edge:.04,color:'#ffcc7a',seed:1}},vignette:{label:'Vignette',group:'Filter',params:{amount:.6}},opacity:{label:'Opacity',group:'Composite',params:{amount:.6}},output:{label:'Output',group:'Output',params:{}}
};
export const PARTICLE_SHAPES=['circle','soft','square','star','spark','ring','triangle','diamond','cross','heart','image'];
export function defaultEmitter(id='emitter'){return{id,name:'Sparks',enabled:true,layer:50,seed:1,x:0,y:-100,rate:45,burst:0,delay:0,duration:2,loop:true,shape:'point',distribution:'linear',width:40,height:40,path:[],pathClosed:false,pathDuration:2,pathEasing:'linear',orbit:0,orbitSpeed:1,chance:1,life:[.4,1.2],speed:[40,130],direction:[-110,-70],angle:[0,360],spin:[-80,80],size:[3,9],sizeEnd:.05,scaleX:1,scaleY:1,gravityX:0,gravityY:80,drag:.1,turbulence:0,wiggle:0,wiggleSpeed:4,attractor:{x:0,y:0,strength:0},repel:0,collision:{enabled:false,y:0,bounce:.5},colors:['#fff4c4','#ffa559','#bb4755'],alpha:[0,1,0],blend:'lighter',particleShape:'spark',asset:null,frameRate:12,orientToVelocity:true,stepEmit:null,deathEmit:null,contour:null,overLife:{size:[{time:0,value:1,easing:'linear'},{time:1,value:1,easing:'linear'}],alpha:[{time:0,value:1,easing:'linear'},{time:1,value:1,easing:'linear'}],speed:[{time:0,value:1,easing:'linear'},{time:1,value:1,easing:'linear'}],rotation:[{time:0,value:0,easing:'linear'},{time:1,value:0,easing:'linear'}]}};}
export function defaultFluid(id='fluid'){return{id,name:'Smoke',enabled:true,layer:45,seed:1,x:0,y:-70,width:180,height:240,resolution:48,rate:1,density:1,velocityX:0,velocityY:-35,buoyancy:1,vorticity:12,viscosity:.0002,dissipation:.3,temperature:1,sourceRadius:.1,sourceImage:null,obstacleImage:null,colors:['#292b4700','#797395','#d3bdcc'],gradient:true,fade:true,delay:0,duration:3,obstacles:[]};}
export function ensureFX(p){return p.fx??={settings:{width:512,height:512,background:'transparent',padding:50,pixelSize:1,seed:1},emitters:[],fluids:[],models:[],nodes:[{id:'scene',type:'scene',inputs:[],params:{},x:40,y:80}],output:'scene'};}
export function defaultVisual(){return{opacity:1,tint:'#ffffff',tintAmount:0,blend:'source-over',smear:{enabled:false,seconds:.16,samples:14,alpha:.6,decay:1.5,front:false,color:'#ffbe71',tint:0,inline:0,outline:0,outlineColor:'#171c2b'},wave:{enabled:false,amplitude:8,frequency:2,speed:1,axis:'x',anchor:true},break:{enabled:false,delay:.2,duration:1.2,pieceSize:12,speed:80,direction:-90,spread:180,gravity:140,spin:90,shrink:.5,fade:1,gradual:.3,seed:1},skewX:0,skewY:0,motion:{enabled:false,mode:'burst',delay:0,duration:1,speed:5,damping:5,easing:'smooth',pingpong:false,x:0,y:0,rotation:12,scaleX:.15,scaleY:-.15,skewX:0,skewY:0}};}
export function validateFX(p){
 const f=p.fx;if(!f)return;const bad=msg=>{throw Error('FX: '+msg);},finite=(v,name,min=-1e6,max=1e6)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max)bad('invalid '+name);};
 if(!f.settings)bad('missing canvas settings');finite(f.settings.width,'width',1,8192);finite(f.settings.height,'height',1,8192);if(f.settings.padding!==undefined)finite(f.settings.padding,'padding',0,4096);if(f.settings.pixelSize!==undefined)finite(f.settings.pixelSize,'pixel size',1,256);
 for(const key of ['emitters','fluids','models','nodes'])if(!Array.isArray(f[key])||f[key].length>128)bad('invalid '+key);
 const emitterIds=new Set();for(const e of f.emitters){if(!e.id||emitterIds.has(e.id))bad('emitter IDs must be unique');emitterIds.add(e.id);for(const k of ['x','y','layer','seed','rate','burst','delay','duration','chance','width','height','gravityX','gravityY','drag','turbulence','sizeEnd','scaleX','scaleY'])finite(e[k],k);if(e.chance<0||e.chance>1||e.scaleX<0||e.scaleY<0||e.width<0||e.height<0)bad('invalid emitter dimensions or chance');for(const points of Object.values(e.overLife??{}))validateCurve(points);if(e.rate<0||e.rate>2000||e.burst<0||e.burst>4000||e.duration<=0)bad('emitter capacity exceeded');for(const k of ['life','speed','direction','angle','spin','size']){if(!Array.isArray(e[k])||e[k].length!==2)bad('invalid '+k+' range');e[k].forEach(v=>finite(v,k));if(e[k][0]>e[k][1])bad('range minimum exceeds maximum');}if(e.life[0]<=0||e.life[1]>30||e.size[0]<0)bad('invalid particle lifetime or size');if(!PARTICLE_SHAPES.includes(e.particleShape))bad('unknown particle shape');if(!['point','rectangle','ellipse','diamond','line','contour'].includes(e.shape))bad('unknown emission shape');if(!Array.isArray(e.path)||e.path.length>2000)bad('invalid path');for(const pt of e.path){finite(pt.x,'path x');finite(pt.y,'path y');}}
 for(const e of f.emitters)for(const key of ['stepEmit','deathEmit'])if(e[key]&&!emitterIds.has(e[key]))bad('missing child emitter');
 for(const fluid of f.fluids){finite(fluid.resolution,'fluid resolution',16,128);finite(fluid.width,'fluid width',1,4096);finite(fluid.height,'fluid height',1,4096);finite(fluid.duration,'duration',.01,120);finite(fluid.sourceRadius,'source radius',.001,1);for(const key of ['rate','density','dissipation','viscosity'])finite(fluid[key],key,0,100);for(const o of fluid.obstacles??[])for(const key of ['x','y','width','height'])finite(o[key],key,-1,2);}
 const ids=new Set();for(const n of f.nodes){if(!n.id||ids.has(n.id)||!NODE_TYPES[n.type])bad('invalid node');ids.add(n.id);if(!Array.isArray(n.inputs)||n.inputs.length>2)bad('invalid node inputs');}
 if(!ids.has(f.output))bad('missing output node');const visited=new Set(),visiting=new Set(),map=new Map(f.nodes.map(n=>[n.id,n]));function visit(id){if(visited.has(id))return;if(visiting.has(id))bad('graph contains a cycle');const n=map.get(id);if(!n)bad('missing input node '+id);visiting.add(id);for(const input of n.inputs)if(input)visit(input);visiting.delete(id);visited.add(id);}for(const n of f.nodes)visit(n.id);
 for(const model of f.models){if(!['obj','glb','gltf'].includes(model.format)||typeof model.src!=='string')bad('invalid model');for(const key of ['width','height'])finite(model[key],key,1,2048);}
 for(const node of f.nodes)for(const value of Object.values(node.params??{}))if(Array.isArray(value)&&value[0]?.time!==undefined)validateCurve(value);
 finiteTree(f);
 function numbers(obj,depth=0){if(depth>25)bad('parameters are too deeply nested');if(typeof obj==='number'&&!Number.isFinite(obj))bad('non-finite parameter');if(obj&&typeof obj==='object')for(const v of Object.values(obj))numbers(v,depth+1);}numbers(f);
}
