import test from 'node:test';
import assert from 'node:assert/strict';
import {poseAt,validateProject,identity,removeJoint} from '../runtime.js';
import {ProjectStore} from '../store.js';
import {applyCommand} from '../fx/commands.js';
import {constraintDefaults} from './model.js';
import {timelineRows,applyTimelineCommand} from '../authoring/timeline.js';
import {puppetSource} from '../puppet-sources.js';
import {libraryPacket} from '../authoring/library-transfer.js';
import {libraryPreviewProject} from '../authoring/library.js';
import {constraintExample} from './example.js';
const joint=(id,parent=null,x=0,y=0,rotation=0,scale=1)=>({id,name:id,parent,layer:0,rest:{x,y,rotation,scaleX:scale,scaleY:scale}});
function fixture(){return{format:'inkwell-puppet',version:1,name:'Constraints',assets:[],joints:[joint('parent',null,10,0,90,2),joint('owner','parent'),joint('target',null,10,6)],clips:[{id:'idle',name:'Idle',duration:2,fps:30,loop:false,tracks:{}}]};}
const close=(actual,expected)=>actual.forEach((v,i)=>assert.ok(Math.abs(v-expected[i])<1e-6,`${actual} ≠ ${expected}`));
test('2D world/local conversion resolves parent transforms and all five types',()=>{const p=fixture();for(const type of ['translation','rotation','scale','transform','distance']){const c=constraintDefaults('c','owner',type,2,'target');p.constraints=[c];validateProject(p);const pose=poseAt(p,p.clips[0],0);assert.ok([...pose.get('owner').world].every(Number.isFinite));if(type==='translation'){close([pose.get('owner').transform.x,pose.get('owner').transform.y],[3,0]);close(pose.get('owner').world.slice(4),[10,6]);}}});
test('limits-only, rotation multipliers, offsets and partial strength do not drift while scrubbing',()=>{const p=fixture();p.joints[1].parent=null;p.joints[1].rest.x=30;let c=constraintDefaults('c','owner','translation',2,null);c.channels.position.max[0]=10;c.strength=.5;p.constraints=[c];for(let i=0;i<10;i++)assert.equal(poseAt(p,p.clips[0],i/10).get('owner').transform.x,20);c=constraintDefaults('c','owner','rotation',2,'target');c.sourceSpace=c.destinationSpace=c.limitSpace='local';c.channels.rotation.multiplier[0]=2;c.channels.rotation.offset[0]=5;p.joints[2].rest.rotation=45;p.constraints=[c];assert.equal(poseAt(p,p.clips[0],0).get('owner').transform.rotation,95);});
test('final state-machine overrides are constrained against the final blended target',()=>{const p=fixture();p.joints[1].parent=null;p.constraints=[constraintDefaults('c','owner','translation',2,'target')];const pose=poseAt(p,p.clips[0],0,{finalOverrides:true,overrides:[{node:'target',channel:'x',value:50},{node:'owner',channel:'x',value:0}]});assert.equal(pose.get('owner').transform.x,50);assert.equal(poseAt(p,p.clips[0],0,{constraints:false}).get('owner').transform.x,0);});
test('commands round-trip, undo/redo, reject cycles, and remove dangling constraints and weight tracks',()=>{const store=new ProjectStore(fixture());store.edit(p=>applyCommand(p,{op:'constraint.add',id:'c',node:'owner',type:'translation',target:'target'}));store.edit(p=>applyCommand(p,{op:'constraint.key',id:'c',clip:'idle',time:0,value:.5}));const saved=JSON.parse(JSON.stringify(store.project));assert.deepEqual(validateProject(saved).constraints,store.project.constraints);assert.throws(()=>store.edit(p=>applyCommand(p,{op:'constraint.add',node:'target',type:'translation',target:'owner'})),/cyclic/);store.edit(p=>removeJoint(p,'target'));assert.equal(store.project.constraints.length,0);assert.equal(store.project.clips[0].constraintWeights.length,0);store.undo();assert.equal(store.project.constraints.length,1);store.redo();assert.equal(store.project.constraints.length,0);});
test('strength keys appear in the shared timeline and can be retimed and deleted',()=>{const p=fixture();applyCommand(p,{op:'constraint.add',id:'c',node:'owner',type:'translation',target:'target'});applyCommand(p,{op:'constraint.key',id:'c',clip:'idle',time:1,value:.5});const row=timelineRows(p,{clip:'idle'}).find(r=>r.id==='constraint:c');assert.equal(row.keys.length,1);applyTimelineCommand(p,{op:'timeline.edit',clip:'idle',keys:[{row:row.id,time:1}],delta:.2});validateProject(p);assert.equal(row.keys[0].time,1.2);applyTimelineCommand(p,{op:'timeline.edit',clip:'idle',keys:[{row:row.id,time:1.2}],remove:true});validateProject(p);});

function chainFixture(count=2){
 const p=fixture();p.joints=[joint('base'),...Array.from({length:count+1},(_,i)=>joint('b'+i,i?'b'+(i-1):'base',i?60:0)),joint('goal',null,60,40)];
 p.constraints=[{...constraintDefaults('reach','b'+count,'ik',2,'goal'),boneCount:count}];return p;
}
const error=(pose,a,b)=>Math.hypot(...pose.get(a).world.slice(4).map((v,i)=>v-pose.get(b).world[i+4]));
test('IK reaches targets with one, two and longer chains without stretching or mutating input',()=>{
 for(const count of [1,2,3,5,12,32]){const p=chainFixture(count);if(count===1)Object.assign(p.joints.at(-1).rest,{x:0,y:60});const before=JSON.stringify(p);validateProject(p);const pose=poseAt(p,p.clips[0],0);assert.ok(error(pose,'b'+count,'goal')<.001,`count ${count}: ${error(pose,'b'+count,'goal')}`);for(let i=1;i<=count;i++){assert.ok(Math.abs(error(pose,'b'+i,'b'+(i-1))-60)<1e-6);assert.equal(pose.get('b'+i).transform.x,60);}assert.equal(JSON.stringify(p),before);}
});
test('IK inversion chooses opposite bends and works through transformed and mirrored parents',()=>{
 for(const mirrored of [false,true]){const p=chainFixture();Object.assign(p.joints[0].rest,{x:30,y:-20,rotation:37,scaleX:mirrored?-2:2,scaleY:2});const root=poseAt(p,p.clips[0],0,{constraints:false}).get('b0').world;Object.assign(p.joints.at(-1).rest,{x:root[0]*60+root[2]*40+root[4],y:root[1]*60+root[3]*40+root[5]});const bends=[];for(const invert of [false,true]){p.constraints[0].invertDirection=invert;const pose=poseAt(p,p.clips[0],0);assert.ok(error(pose,'b2','goal')<.001);bends.push(pose.get('b1').world.slice(4));}assert.ok(Math.hypot(...bends[0].map((v,i)=>v-bends[1][i]))>100);}
});
test('IK strength blends rotations from FK and scrubbing has no accumulated state',()=>{
 const p=chainFixture(3);applyCommand(p,{op:'constraint.key',id:'reach',clip:'idle',time:0,value:0});applyCommand(p,{op:'constraint.key',id:'reach',clip:'idle',time:2,value:1});const fk=poseAt(p,p.clips[0],0),full=poseAt(p,p.clips[0],2),half=poseAt(p,p.clips[0],1);assert.equal(fk.get('b3').world[4],180);for(const id of ['b0','b1','b2'])assert.ok(Math.abs(half.get(id).transform.rotation-full.get(id).transform.rotation/2)<1e-6);for(const t of [2,1,0,1,2,1]){const pose=poseAt(p,p.clips[0],t);if(t===1)close(pose.get('b3').world,half.get('b3').world);}p.constraints[0].enabled=false;assert.equal(poseAt(p,p.clips[0],2).get('b3').world[4],180);
});
test('IK stacks respect order and downstream constraints read the solved endpoint',()=>{
 const p=chainFixture();p.joints.push(joint('other',null,30,-80),joint('follower'));const second={...p.constraints[0],id:'second',target:'other'},follow=constraintDefaults('follow','follower','translation',2,'b2');p.constraints.unshift(follow);p.constraints.push(second);validateProject(p);let pose=poseAt(p,p.clips[0],0);assert.ok(error(pose,'b2','other')<.001);close(pose.get('follower').world.slice(4),pose.get('b2').world.slice(4));applyCommand(p,{op:'constraint.order',id:'reach',index:2});pose=poseAt(p,p.clips[0],0);assert.ok(error(pose,'b2','goal')<.001);
});
test('IK handles unreachable, coincident and zero-length chains without NaNs',()=>{
 for(const count of [1,2,4])for(const [x,y]of [[0,0],[10000,-10000]]){const p=chainFixture(count);Object.assign(p.joints.at(-1).rest,{x,y});const pose=poseAt(p,p.clips[0],0);for(const v of pose.values())assert.ok(v.world.every(Number.isFinite));for(let i=1;i<=count;i++)assert.ok(Math.abs(error(pose,'b'+i,'b'+(i-1))-60)<1e-6);}const p=chainFixture();p.joints.forEach(j=>j.rest.x=j.rest.y=0);assert.ok([...poseAt(p,p.clips[0],0).values()].every(v=>v.world.every(Number.isFinite)));
});
test('IK validation rejects driven-branch targets, dependency cycles and invalid bone counts transactionally',()=>{
 const p=chainFixture(),before=JSON.stringify(p);for(const values of [{boneCount:0},{boneCount:33},{boneCount:1.5},{boneCount:4},{target:'b1'},{target:'b0'}]){assert.throws(()=>applyCommand(p,{op:'constraint.update',id:'reach',values}));assert.equal(JSON.stringify(p),before);}assert.throws(()=>applyCommand(p,{op:'constraint.add',id:'cycle',node:'goal',target:'b1',type:'translation'}),/cyclic/);const store=new ProjectStore(p);store.edit(p=>applyCommand(p,{op:'constraint.update',id:'reach',values:{invertDirection:true,boneCount:1}}));assert.equal(store.project.constraints[0].boneCount,1);store.undo();assert.equal(store.project.constraints[0].boneCount,2);store.redo();assert.equal(store.project.constraints[0].invertDirection,true);validateProject(JSON.parse(JSON.stringify(store.project)));
});
test('authored offsets preserve animated owner channels and apply before independent limits',()=>{
 const p=fixture();p.joints[1].parent=null;p.joints[1].rest={x:3,y:4,rotation:10,scaleX:2,scaleY:3};p.joints[2].rest={x:20,y:30,rotation:40,scaleX:4,scaleY:5};p.clips[0].tracks.owner=[{time:0,value:{...identity(),x:2,rotation:5,scaleX:2},easing:'linear'}];const c=constraintDefaults('offset','owner','transform',2,'target');c.sourceSpace=c.destinationSpace=c.limitSpace='local';c.ownerOffset=true;p.constraints=[c];let v=poseAt(p,p.clips[0],0).get('owner').transform;close([v.x,v.y,v.rotation,v.scaleX,v.scaleY],[25,34,55,16,15]);c.channels.position.max[0]=23;assert.equal(poseAt(p,p.clips[0],0).get('owner').transform.x,23);c.ownerOffset=false;assert.equal(poseAt(p,p.clips[0],0).get('owner').transform.x,20);
});
test('3D puppet sources retain rig constraints and isolate linked source definitions',()=>{
 const p=chainFixture();let source=puppetSource(p);assert.deepEqual(source.constraints,p.constraints);assert.ok(error(poseAt(source,source.clips[0],0),'b2','goal')<.001);p.puppetSources=[{id:'rig',name:'Rig',roots:['base','goal'],clips:['idle']}];source=puppetSource(p,undefined,'rig');validateProject(p);assert.equal(source.constraints[0].type,'ik');p.puppetSources[0].roots=['base'];assert.throws(()=>validateProject(p),/target/);
});
test('library characters preserve constraints, targets and strength keys across placement and publishing',()=>{
 const p=constraintExample();applyCommand(p,{op:'constraint.key',id:'arm-ik',clip:'reach',time:0,value:1});const source=new ProjectStore(p),edit=(s,c)=>s.edit(p=>applyCommand(p,c));edit(source,{op:'library.capture',id:'arm',name:'Arm',category:'characters',dimension:2,node:'base'});const preview=libraryPreviewProject(source.project,source.project.library.items[0]);validateProject(preview.project);assert.equal(preview.project.constraints[0].type,'ik');
 const dest=new ProjectStore(fixture());edit(dest,{op:'library.import',value:JSON.parse(JSON.stringify(libraryPacket(source.project,source.project.library.items[0])))});for(const instance of ['first','second'])edit(dest,{op:'library.place',id:'arm',instance,position:[200,40]});
 for(const name of ['first','second']){const root=dest.project.joints.find(j=>j.id===name),link=root.librarySource,id=link.motion.constraintBindings['arm-ik'],c=dest.project.constraints.find(c=>c.id===id),clip=dest.project.clips.find(c=>c.id===link.motion.bindings.reach);assert.equal(c.node,link.bindings.tip);assert.equal(c.target,link.bindings.goal);assert.equal(clip.constraintWeights[0].constraint,id);const pose=poseAt(dest.project,clip,0);assert.ok(error(pose,c.node,c.target)<.001);}
 const id=dest.project.joints.find(j=>j.id==='first').librarySource.motion.constraintBindings['arm-ik'];edit(dest,{op:'constraint.update',id,values:{invertDirection:true}});edit(dest,{op:'library.updateSource',id:'arm',instance:'first'});assert.ok(dest.project.constraints.every(c=>c.invertDirection));validateProject(JSON.parse(JSON.stringify(dest.project)));dest.undo();assert.equal(dest.project.constraints.filter(c=>c.invertDirection).length,1);dest.redo();assert.ok(dest.project.constraints.every(c=>c.invertDirection));
});
