import {applyNoodleCommand} from './model.js';
import {noodleArtwork} from './render2d.js';
import {poseAt,identity} from '../runtime.js';
import {svgText,validateVector} from '../vector/model.js';
const unique=(base,list)=>{let id=base,i=2;while(list.some(v=>v.id===id))id=base+'-'+i++;return id;};
export function bakeNoodleVector(project,node,clip,time,animation=false,fps=12){const j=project.joints.find(j=>j.id===node);if(!j?.noodle?.enabled||!project.assets.find(a=>a.id===j.sprite?.asset)?.vector)throw Error('Select editable SVG artwork with an enabled Noodle deformer');if(j.sprite.mesh?.enabled)throw Error('SVG baking requires point deformation; artwork meshes can use the normal rendered export');const intervals=Math.ceil(clip.duration*fps);if(animation&&intervals>96)throw Error('Use 96 or fewer intervals (shorter clip or lower FPS)');const times=animation?Array.from({length:intervals+1},(_,i)=>i*clip.duration/intervals):[time],images=new Map(project.assets.map(a=>[a.id,{vectorModel:a.vector}])),shapes=[],tracks=[];let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
 for(let frame=0;frame<times.length;frame++){const pose=poseAt(project,clip,times[frame]),out=noodleArtwork(j,images,pose,times[frame]);if(!out)throw Error('Every turning drawing must be editable SVG artwork');const vector=out.images.get(out.joint.sprite.asset).vectorModel,world=pose.get(j.id).world,ids=new Map(vector.shapes.map(s=>[s.id,s.id+'-f'+frame]));for(const shape of vector.shapes){const s=structuredClone(shape),opacity=s.opacity;for(const key of ['fill','stroke'])if(s[key]?.swatch)s[key]=vector.swatches.find(v=>v.id===s[key].swatch)?.color??'#000000';s.id=ids.get(s.id);s.name+=' · '+frame;s.points=s.points.map((_,i)=>{const k=i-i%2,x=s.points[k],y=s.points[k+1];return i%2?world[1]*x+world[3]*y+world[5]:world[0]*x+world[2]*y+world[4];});if(s.clips)s.clips=s.clips.map(c=>({...c,source:ids.get(c.source)??c.source}));s.strokeWidth*=Math.sqrt(Math.abs(world[0]*world[3]-world[1]*world[2]));s.opacity=frame===0?opacity:0;shapes.push(s);for(let i=0;i<s.points.length;i+=2){minX=Math.min(minX,s.points[i]-s.strokeWidth-1);minY=Math.min(minY,s.points[i+1]-s.strokeWidth-1);maxX=Math.max(maxX,s.points[i]+s.strokeWidth+1);maxY=Math.max(maxY,s.points[i+1]+s.strokeWidth+1);}if(animation){const keys=new Map([[0,frame===0?opacity:0],[times[frame],opacity]]);if(frame+1<times.length)keys.set(times[frame+1],0);tracks.push({shape:s.id,channel:'opacity',keys:[...keys].sort((a,b)=>a[0]-b[0]).map(([time,value])=>({time,value,easing:'step'}))});}}
 }
 const vector={version:1,viewBox:[minX,minY,Math.max(1,maxX-minX),Math.max(1,maxY-minY)],duration:clip.duration,loop:clip.loop,shapes,tracks,swatches:[]};validateVector(vector);return vector;
}
export function noodleCommand(project,c){if(c.op!=='noodle.bake')return applyNoodleCommand(project,c);if(c.dimension===3)throw Error('Use the 3D mesh download or portable player export');const clip=project.clips.find(v=>v.id===c.clip),vector=bakeNoodleVector(project,c.node,clip,c.time??0,c.animation,c.fps??12),asset=unique('noodle-baked',project.assets),node=unique(asset,project.joints),clipId=unique(asset,project.clips),[x,y,width,height]=vector.viewBox;project.assets.push({id:asset,src:'data:image/svg+xml,'+encodeURIComponent(svgText(vector)),vector});project.joints.push({id:node,name:'Baked noodle',parent:null,layer:Math.max(0,...project.joints.map(j=>j.layer))+1,rest:identity(),sprite:{asset,width,height,pivotX:-x/width,pivotY:-y/height}});project.clips.push({id:clipId,name:'Baked noodle',duration:clip.duration,fps:c.fps??12,loop:clip.loop,tracks:{}});return {dimension:2,node,clip:clipId,asset};}
