import {noodleDefaults,noodlePose} from './model.js';
import {svgText} from '../vector/model.js';
import {sceneDefaults,nodeDefaults} from '../scene3d/schema.js';
import {shapeMaterial} from '../shape-lab/style.js';
const rest=()=>({x:0,y:0,rotation:0,scaleX:1,scaleY:1}),path=(id,points,fill)=>({id,name:id,commands:['M',...Array(points.length/2-1).fill('L'),'Z'],points,fill,stroke:'none',strokeWidth:0,opacity:1,hidden:false,locked:false,fillRule:'nonzero',lineCap:'round',lineJoin:'round'});
export function noodleExample(dimension=2){const n=noodleDefaults();n.lag=.13;n.spring=.45;const keys=[];for(const [time,bend,stretch,twist]of [[0,0,1,0],[.5,-.3,.68,-25],[1,.35,1.35,60],[1.5,-.2,.85,-35],[2,0,1,0]]){const pose=noodlePose(n);pose.points=pose.points.map((p,i)=>[bend*(i/3)**2,p[1],dimension===3?.16*Math.sin(i/3*Math.PI)*bend:0]);pose.stretch=stretch;pose.twists=pose.twists.map((_,i)=>twist*i/3);keys.push({time,value:pose,easing:'smooth'});}
 const vector={version:1,viewBox:[-65,-180,130,360],duration:2,loop:true,tracks:[],swatches:[],shapes:[path('body',[-46,-168,38,-168,54,-145,48,165,-45,165,-55,140],'#e4ad58'),path('shade',[24,-168,38,-168,54,-145,48,165,22,165],'#ca8546'),...[[-30,-110],[4,-65],[-25,-10],[5,45],[-27,100]].map(([x,y],i)=>path('spot'+i,[x,y,x+22,y-5,x+26,y+22,x+2,y+30],'#8b563c')),path('eye-white',[-32,-155,-7,-155,-7,-130,-32,-130],'#fff7d8'),path('eye',[-19,-151,-9,-151,-9,-134,-19,-134],'#28383a')]},asset={id:'noodle-art',src:'data:image/svg+xml,'+encodeURIComponent(svgText(vector)),vector},p={format:'inkwell-puppet',version:1,name:dimension===2?'Noodle · native 2D rubber animal':'Noodle · 3D rubber animal',assets:[asset],joints:[{id:'root',name:'Stage',parent:null,layer:0,rest:rest()},{id:'noodle',name:'Rubber animal',parent:'root',layer:1,rest:rest(),sprite:{asset:asset.id,width:130,height:360,pivotX:.5,pivotY:.5},noodle:n}],clips:[{id:'bounce',name:'Squash, bend & twist',duration:2,fps:30,loop:true,tracks:{},noodleTracks:[{node:'noodle',keys}]}]};
 if(dimension===3){const s=p.scene3d=sceneDefaults();s.materials=[shapeMaterial('ink','#e4ad58','Warm rubber')];s.environment.background='#edf0dc';s.environment.shadows=false;s.camera={...s.camera,position:[4,2,7],target:[0,0,0],size:4.8};const body={...nodeDefaults('noodle','rounded-box'),name:'Rubber animal',position:[0,0,0],dimensions:[1,3,.8],radius:.16,noodle:structuredClone(n)};body.surfaces.front={asset:asset.id};s.nodes=[body];s.clips=[{id:'bounce',name:'Squash, bend & twist',duration:2,loop:true,tracks:[],events:[],noodleTracks:[{node:'noodle',keys:structuredClone(keys)}]}];}
 return p;
}
