import {surface} from '../fx/filters.js';
import {sampleNoodle,noodleDeformer} from './model.js';
import {deformVector,turningArtwork} from './vector.js';
import {boundVector} from '../bone-binding/model.js';
import {meshArtwork} from '../mesh/render.js';
const grid={vertices:[],triangles:[]};for(let y=0;y<=48;y++)for(let x=0;x<=12;x++)grid.vertices.push(x/12,y/48);for(let y=0;y<48;y++)for(let x=0;x<12;x++){const a=y*13+x;grid.triangles.push(a,a+1,a+14,a,a+14,a+13);}
export function noodleArtwork(j,images,pose,time){if(!j.noodle?.enabled||!j.sprite)return null;const n=pose?.noodles?.get(j.id)??j.noodle,{asset,definition}=turningArtwork(n),original=images.get(asset||j.sprite.asset);if(!original)return null;let source=original.vectorModel,sprite={...j.sprite,asset:asset||j.sprite.asset};if(source&&!sprite.mesh?.enabled){const bound=!asset&&boundVector(source,j,pose,time);if(bound){source=bound.vector;sprite=bound.sprite;}const warped=deformVector(source,sprite,definition,time,j.sprite),nextImages=new Map(images);nextImages.set(sprite.asset,{vectorModel:warped.vector});return{joint:{...j,noodle:undefined,sprite:warped.sprite},images:nextImages};}return{joint:{...j,sprite,noodleResolved:definition},images};}
export function noodleRaster(source,sprite,reference,definition,scale){if(sprite.mesh?.enabled){const copy=surface(source.width,source.height);copy.getContext('2d').drawImage(source,0,0);source=copy;}const map=noodleDeformer(definition,2).point,h=reference.height,positions=grid.vertices.map((_,i)=>{const k=i-i%2,x=(grid.vertices[k]-sprite.pivotX)*sprite.width,y=(grid.vertices[k+1]-sprite.pivotY)*sprite.height,q=map([(x+(reference.pivotX-.5)*reference.width)/h,-(y+(reference.pivotY-.5)*h)/h,0]);return i%2?(-q[1]*h-(reference.pivotY-.5)*h)/sprite.height+sprite.pivotY:(q[0]*h-(reference.pivotX-.5)*reference.width)/sprite.width+sprite.pivotX;});return meshArtwork(source,{...sprite,mesh:grid},positions,scale);}
export function sampleNoodles(project,clip,time){return new Map(project.joints.filter(j=>j.noodle?.enabled).map(j=>[j.id,sampleNoodle(j.noodle,clip,j.id,time)]));}
