import {newStateMachine,machineClips} from './model.js';
import {loadImages} from '../runtime.js';
import {createStateMachinePlayer} from './player2d.js';
import {createSceneStateMachinePlayer} from './player3d.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=prefix=>prefix+'-'+crypto.randomUUID().slice(0,8);
const options=(items,value)=>items.map(([id,name])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(name)}</option>`).join('');
const select=(field,label,items,value)=>`<label>${label}<select data-edit="${field}">${options(items,value)}</select></label>`;
const number=(field,label,value,min=-100000,max=100000)=>`<label>${label}<input data-edit="${field}" type="number" step="any" min="${min}" max="${max}" value="${value}"></label>`;
export function mountStateMachines({project,context,dispatch,revision,toast}){
 const button=document.createElement('button');button.id='state-machines-open';button.textContent='State Machines';document.getElementById('save').before(button);
 const panel=document.createElement('dialog');panel.id='state-machines-panel';panel.setAttribute('aria-label','Animation state machines');panel.innerHTML=`<header><div><strong>State Machines</strong><small>Connect animations with inputs and transitions</small></div><button data-action="close" aria-label="Close state machines">×</button></header><div class="sm-toolbar"></div><div class="sm-layout"><aside class="sm-layers"></aside><main><div class="sm-graph-tools"></div><div class="sm-graph-scroll"><svg class="sm-graph" aria-label="State graph"></svg></div><p class="sm-hint">Drag states to arrange. Click an arrow to edit its conditions. Transitions run in listed order; all conditions on an arrow must match.</p></main><aside class="sm-inspector"></aside></div><footer><section class="sm-inputs"></section><section class="sm-preview"><div class="sm-preview-buttons"><button data-action="preview">Start preview</button><button data-action="pause">Pause</button><button data-action="reset">Reset</button><span class="sm-status" role="status">Preview stopped</span></div><div class="sm-preview-surface"></div><small>Pose blending. Clip visuals use the dominant animation; preview is silent.</small></section></footer>`;document.body.append(panel);
 let selected='',layerId='',selection=null,stamp='',player=null,ticket=0,previewKey='',drag=null;
 const find=()=>{const m=project().stateMachines?.find(m=>m.id===selected);return{m,l:m?.layers.find(l=>l.id===layerId)??m?.layers[0]};};
 const stop=()=>{ticket++;player?.dispose();player=null;previewKey='';panel.querySelector('.sm-preview-surface').replaceChildren();panel.querySelector('.sm-status').textContent='Preview stopped';};
 function run(command){try{dispatch(command);stamp='';refresh();return true;}catch(error){toast(error.message,true);stamp='';refresh();return false;}}
 function edit(fn){const {m}=find();if(!m)return;const copy=structuredClone(m),layer=copy.layers.find(l=>l.id===layerId)??copy.layers[0];fn(copy,layer);run({op:'stateMachine.put',value:copy});}
 function refresh(){if(!panel.open)return;const dimension=context().dimension,key=revision()+':'+dimension+':'+selected+':'+layerId+':'+selection?.id;if(key===stamp)return;const list=(project().stateMachines??[]).filter(m=>m.dimension===dimension);if(!list.some(m=>m.id===selected)){selected=list[0]?.id??'';layerId='';selection=null;}const {m,l}=find();layerId=l?.id??'';if(player&&previewKey!==revision()+':'+selected)stop();stamp=revision()+':'+dimension+':'+selected+':'+layerId+':'+selection?.id;
  panel.querySelector('.sm-toolbar').innerHTML=`<b>${dimension}D</b><label>Machine<select id="sm-machine">${options(list.map(m=>[m.id,m.name]),selected)}</select></label><button data-action="new">New machine</button>${m?`<label>Name<input data-edit="machine.name" value="${esc(m.name)}"></label><button data-action="delete-machine">Delete machine</button>`:''}`;
  panel.querySelector('.sm-layers').innerHTML=m?`<h3>Layers</h3><p>Lower layers take priority on shared properties.</p>${m.layers.map(x=>`<button data-layer="${x.id}" class="${x.id===layerId?'selected':''}">${x.enabled?'●':'○'} ${esc(x.name)}</button>`).join('')}<button data-action="add-layer">+ Layer</button><label>Layer name<input data-edit="layer.name" value="${esc(l.name)}"></label><label><input data-edit="layer.enabled" type="checkbox" ${l.enabled?'checked':''}> Enabled</label><div class="button-row"><button data-action="layer-up">↑</button><button data-action="layer-down">↓</button><button data-action="delete-layer" ${m.layers.length<2?'disabled':''}>Delete</button></div>${select('layer.entry','Entry state',l.states.map(s=>[s.id,s.name]),l.entry)}<h3>Transitions</h3>${l.transitions.map((t,i)=>`<button data-edge="${t.id}" class="${selection?.id===t.id?'selected':''}">${i+1}. ${esc(l.states.find(s=>s.id===t.from)?.name??'Any')} → ${esc(l.states.find(s=>s.id===t.to)?.name??'Exit')}</button>`).join('')}`:'<p>Create a machine to connect your animation clips.</p>';
  panel.querySelector('.sm-graph-tools').innerHTML=m?'<button data-action="add-state">+ Animation state</button><button data-action="add-blank">+ Blank state</button><button data-action="add-transition">+ Transition</button>':'';
  graph(l);inspector(m,l);inputs(m);
 }
 function graph(l){const svg=panel.querySelector('.sm-graph');if(!l){svg.innerHTML='';return;}const virtual=[{id:'any',name:'Any state',x:10,y:12},{id:'exit',name:'Exit',x:480,y:12}],states=[...virtual,...l.states],width=Math.max(720,...states.map(s=>s.x+190)),height=Math.max(300,...states.map(s=>s.y+100));svg.setAttribute('width',width);svg.setAttribute('height',height);svg.setAttribute('viewBox',`0 0 ${width} ${height}`);
  svg.innerHTML=`<defs><marker id="sm-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>${l.transitions.map((t,i)=>{const a=states.find(s=>s.id===t.from),b=states.find(s=>s.id===t.to);if(!a||!b)return'';const x=a.x+80,y=a.y+52,bx=b.x+80,by=b.y,d=a===b?`M ${x+40} ${y} C ${x+150} ${y+90},${x+150} ${by-50},${bx+20} ${by}`:`M ${x} ${y} C ${x} ${y+45+i*6},${bx} ${by-45-i*6},${bx} ${by}`;return`<g data-edge="${t.id}" class="sm-edge ${selection?.id===t.id?'selected':''} ${t.enabled?'':'disabled'}"><path d="${d}" class="sm-edge-hit"/><path d="${d}" class="sm-edge-line" marker-end="url(#sm-arrow)"/><text x="${(x+bx)/2+8}" y="${(y+by)/2}">${i+1}</text></g>`;}).join('')}${states.map(s=>`<g data-state="${s.id}" transform="translate(${s.x},${s.y})" class="sm-state ${selection?.id===s.id?'selected':''} ${['any','exit'].includes(s.id)?'virtual':''}" role="button" tabindex="0" aria-label="${esc(s.name)}"><rect width="160" height="52" rx="9"/><text x="12" y="21">${esc(s.name.slice(0,23))}</text><text x="12" y="40" class="sm-state-detail">${s.id===l.entry?'Entry · ':''}${s.type==='animation'?esc(machineClips(project(),find().m.dimension).find(c=>c.id===s.clip)?.name?.slice(0,22)):s.type??'special'}</text></g>`).join('')}`;
 }
 function inspector(m,l){const el=panel.querySelector('.sm-inspector');if(!m){el.innerHTML='';return;}const s=l.states.find(s=>s.id===selection?.id),t=l.transitions.find(t=>t.id===selection?.id);if(s)el.innerHTML=`<h3>State</h3><label>Name<input data-edit="state.name" value="${esc(s.name)}"></label>${s.type==='animation'?select('state.clip','Animation',machineClips(project(),m.dimension).map(c=>[c.id,c.name]),s.clip)+number('state.speed','Speed',s.speed,-20,20)+select('state.playback','Playback',[['clip','Use clip setting'],['loop','Loop'],['once','Play once']],s.playback):'<p>A blank state contributes no animation.</p>'}<button data-action="set-entry">Use as entry</button><button data-action="delete-state" ${l.states.length===1?'disabled':''}>Delete state</button>`;
  else if(t)el.innerHTML=`<h3>Transition</h3>${select('transition.from','From',[['any','Any state'],...l.states.map(s=>[s.id,s.name])],t.from)}${select('transition.to','To',[...l.states.map(s=>[s.id,s.name]),['exit','Exit']],t.to)}<label><input data-edit="transition.enabled" type="checkbox" ${t.enabled?'checked':''}> Enabled</label>${number('transition.duration','Blend seconds',t.duration,0,60)}${select('transition.easing','Blend easing',[['smooth','Smooth'],['linear','Linear']],t.easing)}<label>Exit time (cycles; empty = immediate)<input data-edit="transition.exitTime" type="number" min="0" max="100" step=".1" value="${t.exitTime??''}"></label><h4>Conditions · all must match</h4>${t.conditions.map((c,i)=>{const input=m.inputs.find(x=>x.id===c.input),ops=input.type==='number'?['eq','ne','gt','ge','lt','le']:input.type==='boolean'?['eq','ne']:['fired'];return`<div class="sm-condition" data-condition="${i}"><select data-cond="input" aria-label="Condition input">${options(m.inputs.map(x=>[x.id,x.name]),c.input)}</select><select data-cond="op" aria-label="Condition comparison">${options(ops.map(o=>[o,({eq:'=',ne:'≠',gt:'>',ge:'≥',lt:'<',le:'≤',fired:'fired'})[o]]),c.op)}</select>${input.type==='number'?`<input data-cond="value" aria-label="Condition value" type="number" step="any" value="${c.value}">`:input.type==='boolean'?`<select data-cond="value" aria-label="Condition value">${options([['true','True'],['false','False']],String(c.value))}</select>`:''}<button data-remove-condition="${i}" aria-label="Remove condition">×</button></div>`;}).join('')}<button data-action="add-condition" ${m.inputs.length?'':'disabled'}>+ Condition</button><p>Separate arrows provide alternative (OR) conditions. Empty conditions always match.</p><div class="button-row"><button data-action="edge-up">Priority ↑</button><button data-action="edge-down">↓</button></div><button data-action="delete-transition">Delete transition</button>`;
  else el.innerHTML='<h3>State graph</h3><p>Select a state or transition to edit it. Any state can interrupt a settled state; transitions finish their blend before another transition starts. Exit ends this layer.</p>';
 }
 function inputs(m){panel.querySelector('.sm-inputs').innerHTML=m?`<h3>Inputs <small>Defaults save with the project. Test values are temporary.</small></h3>${m.inputs.map(i=>`<div class="sm-input" data-input="${i.id}"><input data-input-name value="${esc(i.name)}" aria-label="Input name"><small>${i.type}</small>${i.type==='trigger'?`<button data-fire="${i.id}">Fire</button>`:i.type==='boolean'?`<label>Default <input data-input-default type="checkbox" ${i.value?'checked':''}></label><label>Test <input data-test="${i.id}" type="checkbox" ${i.value?'checked':''}></label>`:`<label>Default <input data-input-default type="number" step="any" value="${i.value}"></label><label>Test <input data-test="${i.id}" type="number" step="any" value="${i.value}"></label>`}<button data-remove-input="${i.id}" aria-label="Delete input">×</button></div>`).join('')}<div class="button-row"><select id="sm-input-type" aria-label="New input type">${options([['boolean','Boolean'],['number','Number'],['trigger','Trigger']],'boolean')}</select><button data-action="add-input">+ Input</button></div>`:'';}
 function live(frame){for(const el of panel.querySelectorAll('[data-state]'))el.classList.toggle('active',frame.layers.some(l=>l.id===layerId&&l.state===el.dataset.state));for(const el of panel.querySelectorAll('.sm-edge'))el.classList.toggle('active',frame.layers.some(l=>l.id===layerId&&l.transition===el.dataset.edge));const {m}=find();panel.querySelector('.sm-status').textContent=frame.layers.map(l=>`${l.name}: ${m?.layers.find(x=>x.id===l.id)?.states.find(s=>s.id===l.state)?.name??l.state}`).join(' · ');}
 async function preview(){const {m}=find();if(!m)return;if(player){player.play();return;}stop();const own=++ticket,key=revision()+':'+selected,p=structuredClone(project()),canvas=document.createElement('canvas');canvas.width=480;canvas.height=260;panel.querySelector('.sm-preview-surface').append(canvas);panel.querySelector('.sm-status').textContent='Loading preview…';try{const created=m.dimension===3?await createSceneStateMachinePlayer(canvas,p,m.id,{width:480,height:260,onFrame:live}):createStateMachinePlayer(canvas,p,await loadImages(p),m.id,{onFrame:live});if(own!==ticket||!panel.open||key!==revision()+':'+selected){created.dispose();canvas.remove();return;}player=created;previewKey=key;for(const el of panel.querySelectorAll('[data-test]'))player.setInput(el.dataset.test,el.type==='checkbox'?el.checked:+el.value);player.play();}catch(e){if(own===ticket){stop();toast(e.message,true);}}}
 panel.onclick=e=>{const target=e.target.closest('button,[data-edge],[data-state]');if(!target)return;if(target.dataset.layer){layerId=target.dataset.layer;selection=null;stamp='';refresh();return;}if(target.dataset.edge||target.dataset.state){selection={id:target.dataset.edge??target.dataset.state};stamp='';refresh();return;}if(target.dataset.fire){if(player){player.fire(target.dataset.fire);player.advance(0);}else toast('Start the preview to test inputs.');return;}if(target.dataset.removeInput){edit(m=>{m.inputs=m.inputs.filter(i=>i.id!==target.dataset.removeInput);for(const l of m.layers)for(const t of l.transitions){if(t.conditions.some(c=>c.input===target.dataset.removeInput))t.enabled=false;t.conditions=t.conditions.filter(c=>c.input!==target.dataset.removeInput);}});return;}if(target.dataset.removeCondition!==undefined){edit((m,l)=>l.transitions.find(t=>t.id===selection.id).conditions.splice(+target.dataset.removeCondition,1));return;}
  const a=target.dataset.action,{m,l}=find();if(a==='close'){panel.close();return;}if(a==='preview'){preview();return;}if(a==='pause'){player?.pause();return;}if(a==='reset'){player?.reset();inputs(m);return;}if(a==='new'){const value=newStateMachine(uid('machine'),context().dimension,machineClips(project(),context().dimension)[0]);selected=value.id;layerId='';selection=null;run({op:'stateMachine.put',value});return;}if(!m)return;if(a==='delete-machine'){run({op:'stateMachine.remove',id:m.id});return;}
  edit((m,l)=>{const state=l.states.find(s=>s.id===selection?.id),transition=l.transitions.find(t=>t.id===selection?.id);
   if(a==='add-layer'){const n=newStateMachine(uid('layer'),m.dimension,machineClips(project(),m.dimension)[0]).layers[0];n.name='Layer '+(m.layers.length+1);m.layers.push(n);layerId=n.id;selection=null;}
   if(a==='delete-layer'&&m.layers.length>1){m.layers=m.layers.filter(x=>x.id!==l.id);layerId=m.layers[0].id;selection=null;}
   if(a==='layer-up'||a==='layer-down'){const i=m.layers.indexOf(l),to=i+(a==='layer-up'?-1:1);if(to>=0&&to<m.layers.length)[m.layers[i],m.layers[to]]=[m.layers[to],m.layers[i]];}
   if(a==='add-state'||a==='add-blank'){const clip=machineClips(project(),m.dimension)[0],s={id:uid('state'),name:a==='add-blank'?'Blank':clip?.name??'Blank',type:a==='add-blank'||!clip?'blank':'animation',x:100+(l.states.length%3)*210,y:100+Math.floor(l.states.length/3)*130,...(clip?{clip:clip.id,speed:1,playback:'clip'}:{})};l.states.push(s);selection={id:s.id};}
   if(a==='set-entry'&&state)l.entry=state.id;
   if(a==='delete-state'&&state&&l.states.length>1){l.states=l.states.filter(s=>s!==state);l.transitions=l.transitions.filter(t=>t.from!==state.id&&t.to!==state.id);if(l.entry===state.id)l.entry=l.states[0].id;selection=null;}
   if(a==='add-transition'){const t={id:uid('transition'),from:state?.id??l.entry,to:l.states.find(s=>s.id!==(state?.id??l.entry))?.id??'exit',enabled:true,duration:.2,easing:'smooth',exitTime:1,conditions:[]};l.transitions.push(t);selection={id:t.id};}
   if(a==='delete-transition'&&transition){l.transitions=l.transitions.filter(t=>t!==transition);selection=null;}
   if(a==='edge-up'||a==='edge-down'){const i=l.transitions.indexOf(transition),to=i+(a==='edge-up'?-1:1);if(i>=0&&to>=0&&to<l.transitions.length)[l.transitions[i],l.transitions[to]]=[l.transitions[to],l.transitions[i]];}
   if(a==='add-input'){const type=panel.querySelector('#sm-input-type').value;m.inputs.push({id:uid('input'),name:type+' '+(m.inputs.length+1),type,...(type!=='trigger'?{value:type==='number'?0:false}:{})});}
   if(a==='add-condition'&&transition&&m.inputs.length){const i=m.inputs[0];transition.conditions.push({input:i.id,op:i.type==='trigger'?'fired':'eq',...(i.type!=='trigger'?{value:i.value}:{})});}
  });
 };
 panel.onchange=e=>{const el=e.target;if(el.id==='sm-input-type')return;if(el.id==='sm-machine'){stop();selected=el.value;layerId='';selection=null;stamp='';refresh();return;}if(el.dataset.test){try{player?.setInput(el.dataset.test,el.type==='checkbox'?el.checked:+el.value);player?.advance(0);}catch(e){toast(e.message,true);}return;}
  edit((m,l)=>{if(el.dataset.edit){const [scope,key]=el.dataset.edit.split('.'),owner=scope==='machine'?m:scope==='layer'?l:scope==='state'?l.states.find(s=>s.id===selection?.id):l.transitions.find(t=>t.id===selection?.id);if(owner)owner[key]=el.type==='checkbox'?el.checked:el.type==='number'?(key==='exitTime'&&el.value===''?null:+el.value):el.value;}
   const input=m.inputs.find(i=>i.id===el.closest('[data-input]')?.dataset.input);if(el.hasAttribute('data-input-name'))input.name=el.value;if(el.hasAttribute('data-input-default'))input.value=el.type==='checkbox'?el.checked:+el.value;
   if(el.dataset.cond){const c=l.transitions.find(t=>t.id===selection.id).conditions[+el.closest('[data-condition]').dataset.condition];if(el.dataset.cond==='input'){const input=m.inputs.find(i=>i.id===el.value);c.input=input.id;c.op=input.type==='trigger'?'fired':'eq';if(input.type==='trigger')delete c.value;else c.value=input.value;}else if(el.dataset.cond==='value'){const input=m.inputs.find(i=>i.id===c.input);c.value=input.type==='boolean'?el.value==='true':+el.value;}else c.op=el.value;}
  });
 };
 panel.onpointerdown=e=>{const g=e.target.closest('g[data-state]'),{l}=find(),s=l?.states.find(s=>s.id===g?.dataset.state);if(!s||e.button!==0)return;drag={id:s.id,x:s.x,y:s.y,startX:e.clientX,startY:e.clientY,g,moved:false};g.setPointerCapture(e.pointerId);};
 panel.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;drag.moved ||= Math.hypot(dx,dy)>3;drag.g.setAttribute('transform',`translate(${Math.max(0,Math.min(10000,drag.x+dx))},${Math.max(70,Math.min(10000,drag.y+dy))})`);};
 panel.onpointerup=e=>{if(!drag)return;const d=drag;drag=null;if(d.moved){edit((m,l)=>{const s=l.states.find(s=>s.id===d.id);s.x=Math.max(0,Math.min(10000,d.x+e.clientX-d.startX));s.y=Math.max(70,Math.min(10000,d.y+e.clientY-d.startY));});}};
 panel.onpointercancel=()=>{drag=null;stamp='';refresh();};panel.onclose=stop;panel.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.state){selection={id:e.target.dataset.state};stamp='';refresh();e.preventDefault();}});
 const show=()=>{if(!panel.open)panel.showModal();stamp='';refresh();};button.onclick=show;setInterval(refresh,200);return{show,snapshot:()=>player?.snapshot()??null,preview};
}
