import test from 'node:test';
import assert from 'node:assert/strict';
import {ProjectStore} from '../store.js';
import {applyCommand} from '../fx/commands.js';
import {validateProject,identity,poseAt} from '../runtime.js';
import {sceneDefaults,nodeDefaults} from '../scene3d/schema.js';
import {newStateMachine} from './model.js';
import {createMachinePose2D} from './player2d.js';
import {createMachinePose3D} from './player3d.js';
function fixture(dimension=2){const project={format:'inkwell-puppet',version:1,name:'State machines',assets:[],joints:[{id:'root',name:'Root',parent:null,layer:0,rest:identity()},{id:'hand',name:'Hand',parent:'root',layer:1,rest:{...identity(),x:5}}],clips:[{id:'idle',name:'Idle',duration:2,fps:30,loop:true,tracks:{root:[{time:0,value:{...identity(),x:10},easing:'linear'}]}},{id:'run',name:'Run',duration:2,fps:30,loop:true,tracks:{root:[{time:0,value:{...identity(),x:30},easing:'linear'}]}}]};if(dimension===3){project.scene3d=sceneDefaults();project.scene3d.nodes=[nodeDefaults('root','box'),nodeDefaults('hand','box')];project.scene3d.clips=project.clips.map((c,i)=>({...c,events:[],tracks:[{node:'root',channel:'position',keys:[{time:0,value:[i?30:10,0,0],easing:'linear'}]}]}));}const m=newStateMachine('m',dimension,project.clips[0]),l=m.layers[0];l.states.push({...l.states[0],id:'run',clip:'run',name:'Run',x:300});m.inputs=[{id:'go',name:'Go',type:'trigger'}];l.transitions=[{id:'next',from:l.entry,to:'run',enabled:true,duration:1,easing:'linear',exitTime:null,conditions:[{input:'go',op:'fired'}]}];project.stateMachines=[m];return validateProject(project);}
test('document commands persist through validation, JSON and undo/redo; missing referenced clips are rejected',()=>{const p=fixture(),store=new ProjectStore(p),before=structuredClone(store.project),value=structuredClone(p.stateMachines[0]);value.name='Renamed';store.edit(p=>applyCommand(p,{op:'stateMachine.put',value}));assert.equal(store.project.stateMachines[0].name,'Renamed');store.undo();assert.deepEqual(store.project,before);store.redo();assert.equal(validateProject(JSON.parse(JSON.stringify(store.project))).stateMachines[0].name,'Renamed');assert.throws(()=>store.edit(p=>{p.clips=p.clips.filter(c=>c.id!=='run');}),/State machine/);assert.equal(store.project.clips.length,2);});
test('2D samples blend local poses while untouched joints retain rest transforms',()=>{const pose=createMachinePose2D(fixture(),'m');pose.machine.fire('go');const values=pose.resolve(pose.machine.advance(.5));assert.equal(values.find(v=>v.node==='root'&&v.channel==='x').value,20);assert.equal(values.find(v=>v.node==='hand'&&v.channel==='x').value,5);});
test('3D samples blend position arrays, and disabled layers contribute nothing',()=>{const p=fixture(3),pose=createMachinePose3D(p,'m');pose.machine.fire('go');assert.deepEqual(pose.resolve(pose.machine.advance(.5)).find(v=>v.node==='root'&&v.channel==='position').value,[20,0,0]);pose.dispose();p.stateMachines[0].layers[0].enabled=false;const off=createMachinePose3D(p,'m');assert.deepEqual(off.resolve().find(v=>v.node==='root'&&v.channel==='position').value,p.scene3d.nodes[0].position);off.dispose();});
test('upper 3D layer affects only its keyed channel, preserving lower-layer movement',()=>{const p=fixture(3),m=p.stateMachines[0],l=structuredClone(m.layers[0]);p.scene3d.clips.push({...p.scene3d.clips[0],id:'turn',tracks:[{node:'root',channel:'rotation',keys:[{time:0,value:[0,45,0],easing:'linear'}]}]});l.id='upper';l.states=[{...l.states[0],clip:'turn'}];l.transitions=[];m.layers.push(l);const pose=createMachinePose3D(p,'m'),v=pose.resolve();assert.deepEqual(v.find(v=>v.node==='root'&&v.channel==='position').value,[10,0,0]);assert.deepEqual(v.find(v=>v.node==='root'&&v.channel==='rotation').value,[0,45,0]);pose.dispose();});
export {fixture};
test('an upper-layer pose correction does not reset another joint',()=>{const p=fixture(),m=p.stateMachines[0],l=structuredClone(m.layers[0]);p.clips.push({...p.clips[0],id:'hand-correction',tracks:{},tools:{layers:[{id:'pose',values:{hand:{rotation:45}},weight:1}]}});l.id='upper';l.states=[{...l.states[0],clip:'hand-correction'}];l.transitions=[];m.layers.push(l);const pose=createMachinePose2D(p,'m'),v=pose.resolve();assert.equal(v.find(v=>v.node==='root'&&v.channel==='x').value,10);assert.equal(v.find(v=>v.node==='hand'&&v.channel==='rotation').value,45);});

test('final machine overrides take precedence after corrective pose evaluation',()=>{const p=fixture(),c=p.clips[0];c.tools={layers:[{id:'correction',values:{hand:{rotation:45}},weight:1}]};const result=poseAt(p,c,0,{overrides:[{node:'hand',channel:'rotation',value:20}],finalOverrides:true});assert.equal(result.get('hand').transform.rotation,20);assert.ok(Math.abs(result.get('hand').world[0]-Math.cos(20*Math.PI/180))<1e-9);});
