// Trace the largest alpha island. Transparent holes remain transparent in the source.
export function traceAlpha(data,width,height,{alpha=32,detail=.006,padding=0}={}){
 const mask=new Uint8Array(width*height);for(let i=0;i<mask.length;i++)mask[i]=data[i*4+3]>=alpha?1:0;const radius=Math.max(0,Math.min(8,Math.round(padding)));let filled=mask;if(radius){filled=new Uint8Array(mask.length);for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(mask[y*width+x])for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++)if(dx*dx+dy*dy<=radius*radius&&x+dx>=0&&x+dx<width&&y+dy>=0&&y+dy<height)filled[(y+dy)*width+x+dx]=1;}
 const edges=new Map(),on=(x,y)=>x>=0&&y>=0&&x<width&&y<height&&filled[y*width+x],add=(a,b)=>{const key=a.join(',');if(!edges.has(key))edges.set(key,[]);edges.get(key).push(b);};
 for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(on(x,y)){if(!on(x,y-1))add([x,y],[x+1,y]);if(!on(x+1,y))add([x+1,y],[x+1,y+1]);if(!on(x,y+1))add([x+1,y+1],[x,y+1]);if(!on(x-1,y))add([x,y+1],[x,y]);}
 const loops=[];while(edges.size){const first=[...edges.keys()][0],start=first.split(',').map(Number),loop=[start];let next=start;for(let i=0;i<width*height*4;i++){const key=next.join(','),list=edges.get(key);if(!list?.length)break;next=list.pop();if(!list.length)edges.delete(key);if(next[0]===start[0]&&next[1]===start[1])break;loop.push(next);}if(loop.length>=3)loops.push(loop);}
 if(!loops.length)throw Error('Mesh: no opaque contour at this alpha threshold');const area=p=>Math.abs(p.reduce((sum,a,i)=>{const b=p[(i+1)%p.length];return sum+a[0]*b[1]-a[1]*b[0];},0));let loop=loops.sort((a,b)=>area(b)-area(a))[0].map(([x,y])=>[x/width,y/height]);const distance=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);};
 function simplify(points,tol){if(points.length<=2)return points;let d=0,index=0;for(let i=1;i<points.length-1;i++){const next=distance(points[i],points[0],points.at(-1));if(next>d){d=next;index=i;}}return d>tol?[...simplify(points.slice(0,index+1),tol).slice(0,-1),...simplify(points.slice(index),tol)]:[points[0],points.at(-1)];}
 let far=1;for(let i=2;i<loop.length;i++)if(Math.hypot(...loop[i].map((n,k)=>n-loop[0][k]))>Math.hypot(...loop[far].map((n,k)=>n-loop[0][k])))far=i;let result,tol=Math.max(.001,detail);do{result=[...simplify(loop.slice(0,far+1),tol).slice(0,-1),...simplify([...loop.slice(far),loop[0]],tol).slice(0,-1)];tol*=1.5;}while(result.length>128);if(result.length<3)throw Error('Mesh: use more detail for this contour');return result.flat();
}
