import {pruneAppearanceTargets} from '../authoring/appearance.js';
import {validateVector,svgText,sampleVector,VECTOR_CHANNELS,transformShape,shapeBounds,paintColor} from './model.js';
function applyVectorCommandImpl(project,c){if(c.op==='vector.create'){if(project.assets.some(a=>a.id===c.id))throw Error('Duplicate artwork asset');if(typeof c.id!=='string'||!/^[\w-]+$/.test(c.id)||typeof c.src!=='string'||!c.src.startsWith('data:image/svg+xml'))throw Error('New artwork needs an SVG source and id');project.assets.push({id:c.id,src:c.src});return c.id;}const asset=project.assets.find(a=>a.id===c.asset);if(!asset)throw Error('Select an artwork asset');if(c.op==='vector.init'){validateVector(c.value);asset.originalSrc??=asset.src;asset.vector=structuredClone(c.value);}else{const v=asset.vector;if(!v)throw Error('Open this SVG in Artwork first');const ids=new Set(c.ids??[c.shape]),shapes=v.shapes.filter(s=>ids.has(s.id));if(c.op==='vector.settings'){if(Object.keys(c.values).some(k=>!['duration','loop','viewBox'].includes(k)))throw Error('Unknown artwork setting');if(c.values.duration!==undefined){const ratio=c.values.duration/v.duration;for(const t of v.tracks)for(const k of t.keys)k.time*=ratio;}Object.assign(v,c.values);}
 else if(c.op==='vector.update'){for(const s of shapes){if(c.values.commands||c.values.points&&c.values.points.length!==s.points.length){if(v.tracks.some(t=>t.shape===s.id&&t.channel==='points'))throw Error('Remove morph keys before changing path topology');}Object.assign(s,structuredClone(c.values));}}
 else if(c.op==='vector.key'){if(!shapes.length||!VECTOR_CHANNELS.includes(c.channel))throw Error('Select a shape and an animatable property');for(const s of shapes){let track=v.tracks.find(t=>t.shape===s.id&&t.channel===c.channel);if(!track&&c.remove)continue;if(!track){if(['fill','stroke'].includes(c.channel)&&s[c.channel]?.type)throw Error('Gradient stops are not colour-keyable; use a solid fill for recolour tracks');track={shape:s.id,channel:c.channel,keys:[]};v.tracks.push(track);if(c.time>0){const base=['fill','stroke'].includes(c.channel)?paintColor(s[c.channel],v):s[c.channel];track.keys.push({time:0,value:structuredClone(base),easing:c.easing??'smooth'});}}const sampled=c.value??sampleVector(v,c.time).find(x=>x.id===s.id)[c.channel],value=['fill','stroke'].includes(c.channel)?paintColor(sampled,v):sampled;track.keys=track.keys.filter(k=>Math.abs(k.time-c.time)>1e-6);if(!c.remove)track.keys.push({time:c.time,value:structuredClone(value),easing:c.easing??'smooth'});track.keys.sort((a,b)=>a.time-b.time);if(!track.keys.length)v.tracks=v.tracks.filter(t=>t!==track);}}
 else if(c.op==='vector.delete'){v.shapes=v.shapes.filter(s=>!ids.has(s.id));v.tracks=v.tracks.filter(t=>!ids.has(t.shape));}
 else if(c.op==='vector.duplicate'){for(const s of shapes){const id=s.id+'-'+crypto.randomUUID().slice(0,6),copy=transformShape(structuredClone(s),{dx:12,dy:12});copy.id=id;copy.name=s.name+' copy';v.shapes.splice(v.shapes.indexOf(s)+1,0,copy);for(const t of [...v.tracks].filter(t=>t.shape===s.id)){const clone=structuredClone(t);clone.shape=id;if(clone.channel==='points')clone.keys.forEach(k=>k.value=k.value.map((n,i)=>n+12));v.tracks.push(clone);}}}
 else if(c.op==='vector.order'){const chosen=v.shapes.filter(s=>ids.has(s.id)),other=v.shapes.filter(s=>!ids.has(s.id));v.shapes=c.front?[...other,...chosen]:[...chosen,...other];}
 else if(c.op==='vector.add'){v.shapes.push(structuredClone(c.value));}
 else if(c.op==='vector.swatch'){const s=v.swatches.find(s=>s.id===c.id);if(s)Object.assign(s,c.values);else v.swatches.push({id:c.id,...c.values});}
 else if(c.op==='vector.boolean'){for(const s of shapes)if(v.tracks.some(t=>t.shape===s.id))throw Error('Bake or remove animation keys before combining shapes');v.shapes=v.shapes.filter(s=>!ids.has(s.id));v.shapes.push(structuredClone(c.value));}
 else throw Error('Unknown artwork command');}validateVector(asset.vector);asset.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svgText(asset.vector,0));return asset.id;}

export function applyVectorCommand(project,command){const result=applyVectorCommandImpl(project,command);if(['vector.delete','vector.init','vector.boolean'].includes(command.op))pruneAppearanceTargets(project);return result;}
