import {SVGLoader} from '../scene3d/vendor.js';
import {validateVector,svgText,rgbHex} from './model.js';
export async function importVector(asset){const response=await fetch(asset.src);if(!response.ok)throw Error('Artwork could not be opened');const text=await response.text(),doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.localName!=='svg')throw Error('Choose SVG artwork to edit its paths');if(doc.querySelector('mask,filter,image,text,use,pattern,script,foreignObject'))throw Error('This SVG contains masks, filters, text, linked shapes or images. Expand those objects to paths first; the original artwork has been kept.');for(const e of doc.querySelectorAll('*')){for(const a of e.attributes)if(/^on/i.test(a.name))throw Error('Active SVG content cannot be edited');if(e.localName==='style')throw Error('Expand SVG styles into attributes before editing.');if(e.localName==='g'&&Number(e.getAttribute('opacity')??1)!==1)throw Error('Expand group transparency before editing paths.');}
 const root=doc.documentElement,viewBox=(root.getAttribute('viewBox')??`0 0 ${root.getAttribute('width')} ${root.getAttribute('height')}`).trim().split(/[ ,]+/).map(Number);if(viewBox.length!==4||viewBox.some(x=>!Number.isFinite(x)))throw Error('SVG needs a numeric viewBox');const parsed=new SVGLoader().parse(text),model={version:1,viewBox,duration:5,loop:false,swatches:[],shapes:[],tracks:[]};
 const color=(value,fallback='#000000')=>{if(!value||value==='none')return value==='none'?'none':fallback;const ref=/^url\(#([^)]*)\)/.exec(value);if(ref){const g=doc.getElementById(ref[1]);if(!g||!['linearGradient','radialGradient'].includes(g.localName)||g.hasAttribute('gradientTransform')||g.hasAttribute('href')||g.hasAttribute('xlink:href'))throw Error('Expand transformed or linked gradients before editing.');const percent=(key,f)=>{const v=g.getAttribute(key);return v?parseFloat(v)/(v.endsWith('%')?100:1):f;};return{type:g.localName==='radialGradient'?'radial':'linear',units:g.getAttribute('gradientUnits')??'objectBoundingBox',x1:percent(g.localName==='radialGradient'?'cx':'x1',g.localName==='radialGradient'?.5:0),y1:percent(g.localName==='radialGradient'?'cy':'y1',g.localName==='radialGradient'?.5:0),x2:percent(g.localName==='radialGradient'?'r':'x2',g.localName==='radialGradient'?.5:1),y2:percent('y2',0),stops:[...g.querySelectorAll('stop')].map(s=>({offset:parseFloat(s.getAttribute('offset')??0)/(String(s.getAttribute('offset')).endsWith('%')?100:1),color:color(s.getAttribute('stop-color')??s.style?.stopColor??'#000000'),opacity:Number(s.getAttribute('stop-opacity')??1)}))};}const c=document.createElement('canvas').getContext('2d');c.fillStyle=value;const result=c.fillStyle;if(/^#[\da-f]{6}$/i.test(result))return result;if(/^#[\da-f]{3}$/i.test(result))return '#'+[...result.slice(1)].map(x=>x+x).join('');const nums=result.match(/[\d.]+/g);return nums?rgbHex(nums.slice(0,3).map(Number)):fallback;};
 function appendPaths(paths){const added=[];for(const path of paths){const i=model.shapes.length;const commands=[],points=[];for(const sub of path.subPaths){if(!sub.curves.length)continue;const start=sub.curves[0].getPoint(0);commands.push('M');points.push(start.x,start.y);for(const curve of sub.curves){if(curve.isLineCurve){commands.push('L');points.push(curve.v2.x,curve.v2.y);}else if(curve.isCubicBezierCurve){commands.push('C');points.push(curve.v1.x,curve.v1.y,curve.v2.x,curve.v2.y,curve.v3.x,curve.v3.y);}else if(curve.isQuadraticBezierCurve){commands.push('C');points.push(curve.v0.x+2/3*(curve.v1.x-curve.v0.x),curve.v0.y+2/3*(curve.v1.y-curve.v0.y),curve.v2.x+2/3*(curve.v1.x-curve.v2.x),curve.v2.y+2/3*(curve.v1.y-curve.v2.y),curve.v2.x,curve.v2.y);}else{const n=8;for(let j=0;j<n;j++){const a=j/n,b=(j+1)/n,p=curve.getPoint(a),q=curve.getPoint(b),epsilon=1e-5,pa=curve.getPoint(Math.min(1,a+epsilon)),qb=curve.getPoint(Math.max(0,b-epsilon)),factor=(b-a)/epsilon/3;commands.push('C');points.push(p.x+(pa.x-p.x)*factor,p.y+(pa.y-p.y)*factor,q.x-(q.x-qb.x)*factor,q.y-(q.y-qb.y)*factor,q.x,q.y);}}}if(sub.autoClose||['rect','circle','ellipse','polygon'].includes(path.userData.node?.localName))commands.push('Z');}if(!commands.length)continue;const style=path.userData.style,fill=color(style.fill),stroke=color(path.userData.node?.getAttribute('data-trim-stroke')??style.stroke,'none');if(style.fillOpacity!==undefined&&style.strokeOpacity!==undefined&&style.fillOpacity!==style.strokeOpacity&&fill!=='none'&&stroke!=='none')throw Error('Expand separate fill/stroke transparency first.');model.shapes.push({id:'path-'+i,name:path.userData.node?.getAttribute('data-name')||path.userData.node?.id||'Path '+(i+1),commands,points,fill,stroke,strokeWidth:Number(style.strokeWidth??0),opacity:Number(style.opacity??1)*Number(fill==='none'?style.strokeOpacity??1:style.fillOpacity??1),fillRule:style.fillRule??'nonzero',lineCap:style.strokeLineCap??'butt',lineJoin:style.strokeLineJoin??'miter',role:path.userData.node?.getAttribute('data-ink-role')??'literal',hidden:false,locked:false});added.push({shape:model.shapes.at(-1),node:path.userData.node});}return added;}
 const entries=appendPaths(parsed.paths.filter(p=>!p.userData.node.closest('clipPath')&&!p.userData.node.hasAttribute('data-trim-rendered'))),sources=new Map(),svgNS='http://www.w3.org/2000/svg';
 const attr=(node,key)=>node.style?.getPropertyValue(key)||node.getAttribute(key);
 const ancestors=node=>{const out=[];for(let n=node;n?.nodeType===1;n=n.parentElement)out.unshift(n);return out;};
 for(const {shape,node} of entries){
  if(node.hasAttribute('data-trim-mode')){shape.trimMode=node.getAttribute('data-trim-mode');for(const [field,attr,fallback] of [['trimStart','start',0],['trimEnd','end',1],['trimOffset','offset',0]])shape[field]=Number(node.getAttribute('data-trim-'+attr)??fallback);}

  shape.hidden=ancestors(node).some(n=>attr(n,'display')==='none')||attr(node,'visibility')==='hidden';
  for(const owner of ancestors(node)){
   const value=attr(owner,'clip-path');if(!value||value==='none')continue;
   const match=/^url\(\s*['"]?#([^)'"\s]+)['"]?\s*\)$/.exec(value);if(!match)throw Error('Clipping must reference a local SVG shape');
   const definition=doc.getElementById(match[1]);if(definition?.localName!=='clipPath')throw Error('Missing SVG clipping path');
   if((definition.getAttribute('clipPathUnits')||'userSpaceOnUse')!=='userSpaceOnUse')throw Error('Expand object-bounding-box clipping to user-space paths before editing.');
   if(definition.querySelector('[clip-path]'))throw Error('Expand nested clipping sources before editing.');
   const transforms=ancestors(owner).map(n=>n.getAttribute('transform')).filter(Boolean),key=JSON.stringify([match[1],transforms]);
   let source=sources.get(key);
   if(!source){
    const root=doc.createElementNS(svgNS,'svg');root.setAttribute('viewBox',viewBox.join(' '));let group=root;
    for(const transform of [...transforms,definition.getAttribute('transform')].filter(Boolean)){const g=doc.createElementNS(svgNS,'g');g.setAttribute('transform',transform);group.append(g);group=g;}
    const original=definition.getAttribute('data-source-d');
    if(original){const path=doc.createElementNS(svgNS,'path');path.setAttribute('d',original);group.append(path);}else for(const child of definition.children)group.append(child.cloneNode(true));
    const paths=new SVGLoader().parse(new XMLSerializer().serializeToString(root)).paths;
    if(paths.length!==1)throw Error('Combine each clipping source into one compound path before editing.');
    const exportedId=definition.getAttribute('data-source');
    const existing=!transforms.length&&entries.find(e=>e.node.getAttribute('data-vector-id')===exportedId);
    const clipped=paths[0].userData.node;
    let rule=definition.getAttribute('clip-rule')||'nonzero';for(const n of ancestors(clipped)){rule=attr(n,'clip-rule')||rule;}
    source={shape:existing?.shape??appendPaths(paths)[0]?.shape,rule,inverse:!!original&&definition.getAttribute('data-inverse')==='true'};
    if(!source.shape)throw Error('Clipping source has no geometry');
    if(!existing){source.shape.hidden=true;source.shape.name=definition.getAttribute('data-name')||'Clip '+match[1];source.shape.fillRule=definition.getAttribute('data-source-rule')||rule;}
    if(original)source.rule=definition.querySelector('path')?.getAttribute('clip-rule')||rule;
    sources.set(key,source);
   }
   shape.clips??=[];if(!shape.clips.some(c=>c.source===source.shape.id))shape.clips.push({source:source.shape.id,rule:source.rule,inverse:source.inverse});
  }
 }
 validateVector(model);return model;
}
