import {validateEffectBindings} from '@shapeshift-labs/studio-core/illustration/effect-state';
import {colorShiftDefaults,validateColorShift} from '@shapeshift-labs/studio-core/illustration/color-shift';
import {putIllustrationKey,validateIllustrationTracks} from '@shapeshift-labs/studio-core/illustration/tracks';
import {liquidSoundPreset} from '@shapeshift-labs/studio-core/illustration/liquid-audio';
import {soundDefaults} from '../authoring/sound.js';
import {liquidDefaults,validateLiquid} from '@shapeshift-labs/studio-core/illustration/container-liquid';
import {applySceneCommand} from '../scene3d/schema.js';
import {applyMotionCommand} from '../motion-tools/commands.js';
const merge=(a,b)=>{for(const [k,v]of Object.entries(b??{})){if(['__proto__','constructor','prototype','id'].includes(k))throw Error('Reserved illustration property');if(v&&typeof v==='object'&&!Array.isArray(v))merge(a[k]??={},v);else a[k]=structuredClone(v);}return a;};
export function applyIllustrationCommand(project,c){const doc=c.dimension===3?project.scene3d:project,nodes=doc?.nodes??doc?.joints,clip=doc?.clips.find(x=>x.id===c.clip)??doc?.clips[0],node=nodes?.find(n=>n.id===c.joint);if(!node||!clip)throw Error('Select artwork and an animation');
 if(c.op==='illustration.bindings'){if(c.dimension===3||!Array.isArray(c.bindings))throw Error('Provide 2D effect bindings as an array');const next=[...(project.illustrationBindings??[]).filter(b=>b.joint!==node.id),...c.bindings.map(b=>({...structuredClone(b),joint:node.id}))];validateEffectBindings(next,project.joints);project.illustrationBindings=next;return node.id;}
 if(c.op==='illustration.binding'){if(c.dimension===3)throw Error('Illustration bindings currently target 2D artwork');const next=(project.illustrationBindings??[]).filter(b=>b.joint!==node.id||b.channel!==c.channel);if(!c.remove)next.push({joint:node.id,channel:c.channel,...structuredClone(c.values)});validateEffectBindings(next,project.joints);project.illustrationBindings=next;return node.id;}
 if(c.op==='illustration.colorShift'){if(c.dimension===3)throw Error('Colour shift currently targets 2D artwork');const next=merge(structuredClone(node.visual?.colorShift??colorShiftDefaults()),c.values);validateColorShift(next);node.visual??={};node.visual.colorShift=next;return node.id;}
 if(c.op==='illustration.key'){if(c.dimension===3)throw Error('Illustration keys currently target 2D artwork');const next=putIllustrationKey(clip.illustrationTracks,node.id,c.channel,c.time,c.value,c.easing);validateIllustrationTracks(next,project.joints);clip.illustrationTracks=next;return node.id;}
 if(c.op==='illustration.removeKeys'){clip.illustrationTracks=(clip.illustrationTracks??[]).filter(t=>t.joint!==node.id||!t.channel.startsWith(c.prefix+'.'));return node.id;}
 if(c.op==='illustration.soundPreset'){project.audioLibraries??={};let id='liquid';for(let i=2;project.audioLibraries[id];i++)id='liquid-'+i;project.audioLibraries[id]=liquidSoundPreset(soundDefaults({frequency:520,duration:.14,volume:.1,spread:1.3}));return id;}
 if(c.op==='illustration.corrective'){let layer=clip.tools?.layers?.find(l=>l.id===c.id);if(!layer){const id=applyMotionCommand(project,{op:'motion.layer',dimension:c.dimension,clip:clip.id,values:{},name:'Pose-driven drawing',weight:1});layer=clip.tools.layers.find(l=>l.id===id);layer.driver={joint:node.id,channel:c.dimension===3?'rotation.z':'rotation',from:0,to:60,easing:'smooth'};}layer.driver??={joint:node.id,channel:c.dimension===3?'rotation.z':'rotation',from:0,to:60,easing:'smooth'};merge(layer,c.values);return layer.id;}
 if(c.op==='illustration.liquid'){if(c.dimension===3)throw Error('Attach container liquid to a 2D puppet joint');if(c.remove){delete node.liquid;project.illustrationBindings=(project.illustrationBindings??[]).filter(b=>b.joint!==node.id||!b.channel.startsWith('liquid.'));for(const c of project.clips)c.illustrationTracks=(c.illustrationTracks??[]).filter(t=>t.joint!==node.id||!t.channel.startsWith('liquid.'));return node.id;}const next=merge(structuredClone(node.liquid??liquidDefaults()),c.values);validateLiquid(next);node.liquid=next;return node.id;}
 if(c.op==='illustration.edge'){node.visual??={};merge(node.visual.edge??={enabled:true,width:2,color:'#211e1a'},c.values);return node.id;}
 if(c.op==='illustration.boil'){const asset=project.assets.find(a=>a.id===(node.sprite?.asset??node.svg));if(!asset?.vector)throw Error('Open this SVG as editable artwork first');merge(asset.vector.boil??={enabled:true,amount:.6,rate:8,variants:3,seed:1,scale:60},c.values);return asset.id;}
 if(c.op==='illustration.fold'){if(c.dimension!==3)throw Error('Bend regions need a 3D object');if(c.time!==undefined){for(const [key,value]of Object.entries(c.values))applySceneCommand(project,{op:'scene3d.key',clip:clip.id,node:node.id,channel:'deform.'+key,time:c.time,value});}else{node.deform??={};merge(node.deform,c.values);}return node.id;}
 if(c.op==='illustration.field'){doc.motionFields??=[];let f=doc.motionFields.find(f=>f.id===c.id);if(c.remove){doc.motionFields=doc.motionFields.filter(f=>f.id!==c.id);return c.id;}if(!f){f={id:'field-'+crypto.randomUUID().slice(0,8),kind:'gust',enabled:true,center:c.dimension===3?[0,0,0]:[0,-100],direction:c.dimension===3?[1,0,0]:[1,0],velocity:c.dimension===3?[.6,0,0]:[40,0],radius:c.dimension===3?4:250,strength:c.dimension===3?1:35,start:0,duration:6,frequency:.8,speed:c.dimension===3?4:200,decay:4};doc.motionFields.push(f);}merge(f,c.values);return f.id;}
 if(c.op==='illustration.receiver'){merge(node.fieldReceiver??={enabled:true,lag:.2,strength:1,rotation:.15,translation:0,bend:.1},c.values);return node.id;}
 throw Error('Unknown illustration command');
}
