import {liquidDefaults} from '@shapeshift-labs/studio-core/illustration/container-liquid';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const numeric={fill:[0,1,.01],frequency:[.2,8,.05],damping:[.03,2,.01],agitation:[0,3,.05],lineWidth:[0,20,.1],surfaceDepth:[0,.2,.01],meniscus:[0,12,.1],bubbles:[0,24,1],layerOffset:[-100,100,.01]};
export function mountLiquidTools({project,context,dispatch,toast,pause,revision}){
 const button=document.createElement('button');button.id='liquid-open';button.textContent='Liquid';document.getElementById('sound-open').after(button);
 const panel=document.createElement('aside');panel.id='illustration-panel';panel.className='author-panel';panel.hidden=true;document.body.append(panel);
 let signature='',target=null;
 function render(){const p=project(),c=context(),joint=p.joints.find(j=>j.id===c.selected);target={joint:joint?.id,clip:c.clip,dimension:c.dimension};signature=JSON.stringify([revision(),target]);
  panel.innerHTML=`<header><strong>Container liquid</strong><button data-close aria-label="Close liquid">×</button></header>${c.dimension===3?'<p>Select artwork in the 2D Puppet workspace.</p>':!joint?'<p>Select a bottle or container joint.</p>':`<p>${esc(joint.name)} · draw a liquid surface inside its local boundary.</p>${!joint.liquid?'<button data-add>Add liquid container</button>':`<label><span>Enabled</span><input data-property="enabled" type="checkbox" ${joint.liquid.enabled?'checked':''}></label>${Object.entries(numeric).map(([key,[min,max,step]])=>`<label>${esc(key)}<input data-property="${key}" aria-label="Liquid ${key}" type="number" min="${min}" max="${max}" step="${step}" value="${joint.liquid[key]}"></label>${key==='fill'?'<button data-key="fill">Key fill at playhead</button>':''}`).join('')}${['color','shadow','highlight','ink'].map(key=>`<label>${key}<input data-property="${key}" aria-label="Liquid ${key}" type="color" value="${joint.liquid[key]}"></label>${key!=='ink'?`<button data-key="${key}">Key ${key} at playhead</button>`:''}`).join('')}<label>Boundary · local [x,y] points<textarea id="liquid-boundary" rows="7">${esc(JSON.stringify(joint.liquid.boundary))}</textarea></label><button data-boundary>Apply boundary</button><p>The surface responds to the joint’s motion. Key fill and colours on the shared timeline.</p><button data-sound>Add liquid sound library</button><button data-clear-keys>Remove liquid keys</button><button data-remove>Remove liquid container</button>`}`}`;
 }
 function run(command){const c=context();if(c.selected!==target?.joint||c.clip!==target?.clip||c.dimension!==target?.dimension)throw Error('Selection changed. Reopen Liquid before editing.');pause();const result=dispatch({...target,...command});return result;}
 panel.onchange=e=>{const key=e.target.dataset.property;if(!key)return;try{run({op:'illustration.liquid',values:{[key]:e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value}});}catch(error){toast(error.message,true);render();}};
 panel.onclick=e=>{const b=e.target.closest('button');if(!b)return;try{if(b.hasAttribute('data-close')){panel.hidden=true;return;}if(b.hasAttribute('data-add'))run({op:'illustration.liquid',values:liquidDefaults()});if(b.hasAttribute('data-remove'))run({op:'illustration.liquid',remove:true});if(b.hasAttribute('data-boundary'))run({op:'illustration.liquid',values:{boundary:JSON.parse(panel.querySelector('#liquid-boundary').value)}});if(b.dataset.key){const joint=project().joints.find(j=>j.id===target.joint);run({op:'illustration.key',channel:'liquid.'+b.dataset.key,time:context().time,value:joint.liquid[b.dataset.key]});}if(b.hasAttribute('data-clear-keys'))run({op:'illustration.removeKeys',prefix:'liquid'});if(b.hasAttribute('data-sound')){run({op:'illustration.soundPreset'});toast('Liquid cues added. Open Sound to audition and place them.');}render();}catch(error){toast(error.message,true);}};
 const show=()=>{panel.hidden=false;render();};button.onclick=()=>panel.hidden?show():panel.hidden=true;
 const timer=setInterval(()=>{if(panel.hidden||panel.contains(document.activeElement))return;const c=context();if(signature!==JSON.stringify([revision(),{joint:c.selected,clip:c.clip,dimension:c.dimension}]))render();},200);
 return{show,hide(){panel.hidden=true;},snapshot(){const c=context();return structuredClone(project().joints.find(j=>j.id===c.selected)?.liquid??null);},dispose(){clearInterval(timer);panel.remove();button.remove();}};
}
