import test from 'node:test';import assert from 'node:assert/strict';
import {shiftColor,colorShiftDefaults} from '@shapeshift-labs/studio-core/illustration/color-shift';
import {createEffectState,resolveEffectBindings,resolveEffectProperties} from '@shapeshift-labs/studio-core/illustration/effect-state';
import {ProceduralTimeline} from '@shapeshift-labs/studio-core/procedural/simulation';
import {emptyProcedural,validateProcedural} from '@shapeshift-labs/studio-core/procedural/model';
import {emptyProject,applyCommand} from '../fx/commands.js';import {validateProject,removeJoint} from '../runtime.js';import {ProjectStore} from '../store.js';
test('colour shift preserves dark ink and hue rotation retains neutral colours',()=>{const c={...colorShiftDefaults(),amount:1,mode:'hue',hue:120};assert.equal(shiftColor('#201b25',c),'#201b25');assert.equal(shiftColor('#aaaaaa',c),'#aaaaaa');assert.equal(shiftColor('#ff0000',{...c,preserveInk:false}),'#00ff00');assert.equal(shiftColor('#123456',{...c,amount:0}),'#123456');});
test('runtime data/state bindings and event transitions override keys without mutating authored data',()=>{const base={amount:0,color:'#000000'},before=JSON.stringify(base),bindings=[{joint:'root',channel:'colorShift.amount',source:'data',path:'health',min:0,max:100,from:1,to:0},{joint:'root',channel:'colorShift.color',source:'state',path:'status',equals:'poisoned',from:'#ffffff',to:'#008800'}];const values=resolveEffectBindings(bindings,{health:25},{status:'poisoned'});assert.deepEqual(resolveEffectProperties(base,[],'root','colorShift',0,values),{amount:.75,color:'#008800'});assert.equal(JSON.stringify(base),before);
 const state=createEffectState();state.dispatch({joint:'root',channel:'colorShift.amount',from:0,value:1,duration:1});state.advance(.5);assert.equal(state.snapshot()[0].value,.5);state.dispatch({joint:'root',channel:'colorShift.amount',value:0,duration:.5});state.advance(.5);assert.equal(state.snapshot()[0].value,0);state.clear('root','colorShift.amount');assert.deepEqual(state.snapshot(),[]);assert.throws(()=>state.set('root','__proto__.x',1));
});
test('colour and fill authoring commands validate, serialize and undo atomically',()=>{const store=new ProjectStore(emptyProject()),clip=store.project.clips[0].id;store.edit(p=>applyCommand(p,{op:'illustration.liquid',joint:'root',clip,values:{fill:0}}));store.edit(p=>applyCommand(p,{op:'illustration.key',joint:'root',clip,channel:'liquid.fill',time:0,value:0}));store.edit(p=>applyCommand(p,{op:'illustration.key',joint:'root',clip,channel:'liquid.fill',time:1,value:1}));assert.equal(resolveEffectProperties({fill:0},store.project.clips[0].illustrationTracks,'root','liquid',.5).fill,.5);store.undo();assert.equal(store.project.clips[0].illustrationTracks[0].keys.length,1);store.redo();const before=JSON.stringify(store.project);assert.throws(()=>store.edit(p=>applyCommand(p,{op:'illustration.binding',joint:'root',clip,channel:'colorShift.amount',values:{source:'data',path:'__proto__.bad'}})));assert.equal(JSON.stringify(store.project),before);validateProject(JSON.parse(before));});
test('authored impulse is applied once, obeys gravity and repeats identically after rewind',()=>{const p=emptyProcedural();p.gravity=[0,60];p.damping=0;p.particles=[{id:'ball',mass:1,radius:2,position:[0,0]}];p.impulses=[{id:'kick',time:.2,particles:['ball'],velocity:[120,-60]}];validateProcedural(p);const t=new ProceduralTimeline(p);assert.equal(t.sample(.2).points.get('ball')[0],0);const first=t.sample(.7).points.get('ball');assert.ok(Math.abs(first[0]-60)<.001);t.sample(.1);assert.deepEqual(t.sample(.7).points.get('ball'),first);p.particles[0].mass=0;assert.throws(()=>validateProcedural(p),/free dynamic/);});
test('deleting a joint removes its effect tracks and data bindings',()=>{const p=emptyProject(),clip=p.clips[0].id;p.joints.push({id:'piece',name:'Piece',parent:'root',layer:1,rest:{x:0,y:0,rotation:0,scaleX:1,scaleY:1}});applyCommand(p,{op:'illustration.colorShift',joint:'piece',clip,values:{amount:.5}});applyCommand(p,{op:'illustration.key',joint:'piece',clip,channel:'colorShift.amount',time:0,value:.5});applyCommand(p,{op:'illustration.binding',joint:'piece',clip,channel:'colorShift.amount',values:{source:'data',path:'health',from:1,to:0,min:0,max:100}});removeJoint(p,'piece');validateProject(p);assert.deepEqual(p.illustrationBindings,[]);assert.deepEqual(p.clips[0].illustrationTracks,[]);});

import {timelineRows,applyTimelineCommand} from '../authoring/timeline.js';
test('shared timeline retimes and deletes illustration keys',()=>{const p=emptyProject(),clip=p.clips[0];applyCommand(p,{op:'illustration.key',joint:'root',clip:clip.id,channel:'colorShift.amount',time:0,value:0});const row=timelineRows(p,{clip:clip.id}).find(r=>r.illustration);assert.ok(row);applyTimelineCommand(p,{op:'timeline.edit',clip:clip.id,keys:[{row:row.id,time:0}],delta:.1});assert.equal(clip.illustrationTracks[0].keys[0].time,.1);applyTimelineCommand(p,{op:'timeline.edit',clip:clip.id,keys:[{row:row.id,time:.1}],remove:true});assert.deepEqual(clip.illustrationTracks,[]);validateProject(p);});
