import {resolveEffectProperties} from '@shapeshift-labs/studio-core/illustration/effect-state';
import {LiquidTimeline,liquidSurface,liquidBubbles} from '@shapeshift-labs/studio-core/illustration/container-liquid';
const cache=new Map();
export function drawContainerLiquid(ctx,config,state,motion){const s=liquidSurface(config,state,motion);if(!s.fill)return s;ctx.save();ctx.clip(new Path2D(s.boundary));const a=s.local(s.range.umin,s.level),b=s.local(s.range.umax,s.range.vmax),gradient=ctx.createLinearGradient(...a,...b);gradient.addColorStop(0,config.color);gradient.addColorStop(1,config.shadow);ctx.fillStyle=gradient;ctx.fill(new Path2D(s.fill));ctx.save();ctx.clip(new Path2D(s.fill));ctx.fillStyle=config.shadow;ctx.globalAlpha=.3;ctx.fill(new Path2D(s.shade));ctx.fillStyle=config.highlight;for(const b of liquidBubbles(config,state,s)){ctx.globalAlpha=b.opacity;ctx.beginPath();ctx.arc(...b.center,b.radius,0,Math.PI*2);ctx.fill();}ctx.restore();ctx.fillStyle=config.highlight;ctx.globalAlpha=.65;ctx.fill(new Path2D(s.cap));ctx.globalAlpha=.8;ctx.fill(new Path2D(s.ribbon));ctx.globalAlpha=1;if(config.lineWidth>0){ctx.strokeStyle=config.ink;ctx.lineWidth=config.lineWidth;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke(new Path2D(s.surface));}ctx.restore();return s;}
export function liquidLayers(project,clip,time,pose,poseAt,values=[]){const layers=[];for(const joint of project.joints){const config=joint.liquid;if(!config||config.enabled===false||joint.hidden)continue;
 const signature=JSON.stringify([config,project.joints.map(j=>[j.id,j.parent,j.rest,j.visual?.motion]),clip?.tracks,clip?.effects,clip?.tools,project.motionFields,project.procedural]),key=(clip?.id??'rest')+':'+joint.id;
 let entry=cache.get(key);if(!entry||entry.signature!==signature){const motion=t=>{const m=poseAt(project,clip,t).get(joint.id).world;return{angle:Math.atan2(m[1],m[0]),x:m[4],y:m[5]};};entry={signature,timeline:new LiquidTimeline(config,motion)};cache.set(key,entry);if(cache.size>24)cache.delete(cache.keys().next().value);}
 const state=entry.timeline.sample(time),matrix=pose.get(joint.id).world,motion={angle:Math.atan2(matrix[1],matrix[0]),x:matrix[4],y:matrix[5]};layers.push({layer:joint.layer+config.layerOffset,draw(ctx){ctx.save();ctx.transform(...matrix);drawContainerLiquid(ctx,resolveEffectProperties(config,clip?.illustrationTracks,joint.id,'liquid',time,values),state,motion);ctx.restore();}});
 }return layers;}
export function clearContainerLiquidCache(){cache.clear();}
