import {parameter} from '../fx/math.js';
import {surface} from '../fx/filters.js';
import {rewriteEdgePixels} from './edges.js';
const cache=new WeakMap(),shadeCache=new WeakMap();
export function shadeArtwork(source,shade,images){if(!shade||!shade.opacity)return source;const shadeKey=JSON.stringify([shade,source.vectorFrame]),bucket=shadeCache.get(source)??new Map();shadeCache.set(source,bucket);if(bucket.has(shadeKey))return bucket.get(shadeKey);const out=surface(source.width,source.height),ctx=out.getContext('2d');ctx.drawImage(source,0,0);const overlay=surface(out.width,out.height),q=overlay.getContext('2d');q.fillStyle=shade.color??'#49392f';q.strokeStyle=q.fillStyle;
 if(shade.asset&&images.get(shade.asset))q.drawImage(images.get(shade.asset),0,0,out.width,out.height);
 else{q.translate(out.width*(shade.x??.5),out.height*(shade.y??.5));q.rotate((shade.angle??-30)*Math.PI/180);const d=Math.hypot(out.width,out.height);if(shade.kind==='hatch'){q.lineWidth=shade.lineWidth??2;const step=Math.max(4,shade.spacing??14);for(let x=0;x<d;x+=step){q.beginPath();q.moveTo(x,-d);q.lineTo(x,d);q.stroke();}}else q.fillRect(0,-d,d,d*2);}
 q.resetTransform();q.globalCompositeOperation='destination-in';q.drawImage(source,0,0);if(shade.protectInk!==false){const pixels=q.getImageData(0,0,out.width,out.height),base=ctx.getImageData(0,0,out.width,out.height).data;for(let i=0;i<base.length;i+=4){const luminance=(base[i]*.2126+base[i+1]*.7152+base[i+2]*.0722)/255;pixels.data[i+3]*=Math.max(0,Math.min(1,(luminance-.12)/.22));}q.putImageData(pixels,0,0);}ctx.globalAlpha=shade.opacity;ctx.drawImage(overlay,0,0);bucket.set(shadeKey,out);if(bucket.size>12)bucket.delete(bucket.keys().next().value);return out;}
// Recolour both sides of every alpha boundary (including holes) in the baked
// result. Geometry never grows a separate shadow-like offset silhouette.
export function rewriteEdges(canvas,width,color){const ctx=canvas.getContext('2d'),{width:w,height:h}=canvas,data=ctx.getImageData(0,0,w,h);rewriteEdgePixels(data.data,w,h,width,color);ctx.putImageData(data,0,0);return canvas;}
export function outlinedSprite(ctx,j,images,world,time,options,draw){const image=images.get(j.sprite.asset);if(!image)return;const s=j.sprite,v=j.visual,e=v.edge,transform=ctx.getTransform(),zoom=Math.max(.1,Math.hypot(transform.a*world[0]+transform.c*world[1],transform.b*world[0]+transform.d*world[1])),ratio=Math.min(2,Math.max(.5,zoom),512/Math.max(s.width,s.height)),pad=Math.ceil(Math.max(s.width,s.height)*Math.max(.12,(Math.abs(parameter(v.morph?.inflate,time))+Math.abs(parameter(v.morph?.taper,time))+2*Math.abs(parameter(v.morph?.bend,time)))/2)+(v.wave?.amplitude??0)+e.width/zoom),w=Math.ceil((s.width+2*pad)*ratio),h=Math.ceil((s.height+2*pad)*ratio),animated=!!image.frames?.length||!!v.motion?.enabled||!!image.vectorModel?.tracks.length||!!image.vectorModel?.boil?.enabled||!!options.soft||!!options.joins?.length||!!options.lighting?.lights?.length||!!v.wave?.enabled||!!v.break?.enabled||JSON.stringify(v).includes('time'),key=JSON.stringify([s,v,animated?Math.floor(time*30):0,Math.round(zoom*100),image.vectorFrame,options.soft?time:0,options.joins??null,options.lighting?.active?[world,options.lighting.environment,options.lighting.night,options.lighting.lights]:null,options.soft?[world,options.soft,options.soft.particles.map(id=>options.procedural?.points.get(id))]:null]);let entries=cache.get(image);if(!entries){entries=new Map();cache.set(image,entries);}let out=entries.get(key);if(!out){out=surface(w,h);const q=out.getContext('2d');q.scale(ratio,ratio);q.translate(pad+s.width*s.pivotX,pad+s.height*s.pivotY);draw(q,{...j,visual:{...v,edge:undefined,opacity:1,blend:'source-over'}},images,[1,0,0,1,0,0],time,{...options,alpha:1,sourceWorld:world});rewriteEdges(out,e.width/zoom*ratio,e.color??'#211e1a');entries.set(key,out);if(entries.size>12)entries.delete(entries.keys().next().value);}ctx.save();ctx.globalAlpha*=Math.max(0,Math.min(1,parameter(v.opacity,time,1)))*(options.alpha??1);ctx.globalCompositeOperation=v.blend??'source-over';ctx.transform(...world);ctx.drawImage(out,-pad-s.width*s.pivotX,-pad-s.height*s.pivotY,w/ratio,h/ratio);ctx.restore();}
