import {projectGrading} from './authoring/appearance.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {GRADING_CONTROLS,GRADING_PRESETS,resolveGrading} from '../rendering/color-grading.js';
export function mountGrading({project,dispatch,revision,toast}){
 const button=document.createElement('button');button.id='grading-open';button.textContent='Colour grade';document.querySelector('#fx-open').before(button);
 const panel=document.createElement('aside');panel.id='grading-panel';panel.hidden=true;panel.setAttribute('aria-label','Scene colour grading');document.body.append(panel);let last=-1;
 const labels={amount:'Strength',exposure:'Exposure · stops',contrast:'Contrast',saturation:'Saturation',temperature:'Warmth',tint:'Magenta / green',split:'Split toning',inkProtection:'Protect ink'};
 const run=command=>{try{dispatch(command);}catch(e){toast(e.message,true);}};
 function refresh(){if(panel.hidden||last===revision())return;last=revision();const g=projectGrading(project()),preset=project().grading?.preset??'neutral',choices=[{id:'auto',name:'Active style'},{id:'neutral',name:'Neutral'},...(project().appearance?.grades??[])];panel.innerHTML=`<header><div><strong>Colour grading</strong><small>Final scene · lighting, shadows & effects</small></div><button data-close aria-label="Close colour grading">×</button></header><label class="grade-enabled"><input id="grade-enabled" type="checkbox" ${g.enabled?'checked':''}> Apply grade <span>Uncheck to compare</span></label><label class="field">Palette<select id="grade-preset">${choices.map(p=>`<option value="${esc(p.id)}" ${p.id===preset?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label>${Object.entries(GRADING_CONTROLS).map(([k,[min,max,step]])=>`<label class="grade-control"><span>${labels[k]}<output>${g[k].toFixed(2)}</output></span><input data-grade="${k}" aria-label="${labels[k]}" type="range" min="${min}" max="${max}" step="${step}" value="${g[k]}"></label>`).join('')}<div class="grade-colours">${['shadows','highlights'].map(k=>`<label>${k}<input aria-label="${k} tint" data-grade="${k}" type="color" value="${g[k]}"></label>`).join('')}</div><p>Applied after light, shadows, ink and effects. Your UI and depth views keep their original colours.</p><button id="grade-reset">Reset this grade</button><label class="field">Save as a reusable grade<input id="grade-name" placeholder="Grade name"></label><button id="grade-save">Save grade</button>`;}
 panel.onclick=e=>{if(e.target.id==='grade-save'){const name=panel.querySelector('#grade-name').value.trim();if(!name){toast('Enter a grade name',true);return;}const id='grade-'+crypto.randomUUID().slice(0,8);run([{op:'appearance.grade',id,name,values:{...projectGrading(project()),preset:'neutral'}},{op:'grading.reset',preset:id}]);refresh();}if(e.target.closest('[data-close]'))panel.hidden=true;if(e.target.id==='grade-reset'){run({op:'grading.reset',preset:project().grading?.preset??'neutral'});refresh();}};
 // The local range thumb is immediate; one durable, undoable edit per gesture.
 panel.oninput=e=>{if(e.target.type==='range')e.target.previousElementSibling.querySelector('output').textContent=Number(e.target.value).toFixed(2);};
 panel.onchange=e=>{if(e.target.id==='grade-preset')run({op:'grading.reset',preset:e.target.value});else if(e.target.id==='grade-enabled')run({op:'grading.set',values:{enabled:e.target.checked}});else if(e.target.dataset.grade)run({op:'grading.set',values:{[e.target.dataset.grade]:e.target.type==='color'?e.target.value:Number(e.target.value)}});refresh();};
 button.onclick=()=>{panel.hidden=!panel.hidden;last=-1;refresh();};setInterval(refresh,180);
}
