import {parameter} from './fx/math.js';
import {dynamicMotion} from './fx/motion.js';
import {lightingGLSL} from './scene3d/core/lighting-glsl.js';
import {MAX_LIGHTS,lightPower,nightActivation,coloringDefaults} from './scene3d/core/lighting-definition.js';
import {sampleLighting2D} from './lighting-state.js';
import {point,multiply} from './joint-transforms.js';
const linear=v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4;
const hex=v=>[1,3,5].map(i=>parseInt(v.slice(i,i+2),16)/255);
function spriteLightMatrix(j,world,time){const v=j.visual;if(!v)return world;const motion=dynamicMotion(v.motion,time),x=parameter(v.skewX,time)+motion.skewX,y=parameter(v.skewY,time)+motion.skewY;return x||y?multiply(world,[1,Math.tan(y*Math.PI/180),Math.tan(x*Math.PI/180),1,0,0]):world;}
export function lightingFrame(project,clip,time,pose,overrides=[]){
 if(!(project.lighting?.night>0)&&!clip?.lightingTracks?.length&&!project.joints.some(j=>j.light||j.coloring))return {active:false};
 const nodes=sampleLighting2D(project,clip,time,overrides),e=project.lighting??{night:0,lightColor:'#f0bf4b'},night=e.night??0,lights=[];
 const shown=j=>{if(pose.soloHidden?.has(j.id))return false;for(let p=j;p;p=nodes.get(p.parent))if(p.hidden)return false;return true;};
 for(const j of nodes.values()){const l=j.light;if(!l||!shown(j))continue;const power=lightPower(l,time,night);if(!power)continue;const m=spriteLightMatrix(j,pose.get(j.id).world,time),origin=point(m,{x:l.offset[0],y:l.offset[1]}),tip=point(m,{x:l.offset[0]+l.direction[0],y:l.offset[1]+l.direction[1]}),direction=[tip.x-origin.x,tip.y-origin.y,l.direction[2]],len=Math.hypot(...direction)||1;lights.push({position:[origin.x,origin.y,l.offset[2],l.range],color:[...(l.colorMode==='environment'?hex(e.lightColor):l.color).map(linear),power],direction:[...direction.map(v=>v/len),l.frontOnly?1:0],falloff:l.falloff});}
 return {nodes,lights,environment:e,night,time,active:lights.length>0||night>0||[...nodes.values()].some(j=>j.coloring&&(j.coloring.strength>0||j.coloring.emission>0))};
}
let renderer;
class Lighting2D{
 constructor(){this.canvas=typeof OffscreenCanvas==='function'?new OffscreenCanvas(1,1):document.createElement('canvas');const gl=this.gl=this.canvas.getContext('webgl2',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)throw Error('Puppet lights require WebGL 2');
  const compile=(type,text)=>{const s=gl.createShader(type);gl.shaderSource(s,text);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;};
  const vertex=compile(gl.VERTEX_SHADER,`#version 300 es\nprecision highp float;out vec2 uv;out vec3 world;uniform mat3 pose;uniform vec4 sprite;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));uv=vec2(p.x,1.-p.y);world=vec3((pose*vec3(sprite.xy+uv*sprite.zw,1.)).xy,0.);gl_Position=vec4(p*2.-1.,0.,1.);}`);
  const frag=compile(gl.FRAGMENT_SHADER,`#version 300 es\nprecision highp float;in vec2 uv;in vec3 world;out vec4 outputColor;uniform sampler2D art;${lightingGLSL}\nvec3 linear(vec3 c){return mix(c/12.92,pow((c+.055)/1.055,vec3(2.4)),step(vec3(.04045),c));}vec3 srgb(vec3 c){return mix(c*12.92,1.055*pow(max(c,vec3(0.)),vec3(1./2.4))-.055,step(vec3(.0031308),c));}void main(){vec4 tex=texture(art,uv);vec3 c=linear(tex.rgb);float ink=1.-step(.012,max(c.r,max(c.g,c.b)));outputColor=vec4(srgb(puppetLighting(c,c,world,uv,ink)),tex.a);}`);
  const p=this.program=gl.createProgram();gl.attachShader(p,vertex);gl.attachShader(p,frag);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));gl.deleteShader(vertex);gl.deleteShader(frag);this.uniforms=new Map();this.textures=new Map();this.texturePixels=0;this.positions=new Float32Array(MAX_LIGHTS*4);this.colors=new Float32Array(MAX_LIGHTS*4);this.directions=new Float32Array(MAX_LIGHTS*4);this.falloffs=new Float32Array(MAX_LIGHTS);this.defaultColoring=coloringDefaults();
 }
 uniform(name){if(!this.uniforms.has(name))this.uniforms.set(name,this.gl.getUniformLocation(this.program,name));return this.uniforms.get(name);}
 draw(art,j,world,state){const gl=this.gl,c=j.coloring??this.defaultColoring,e=state.environment,night=state.night;if(this.canvas.width!==art.width)this.canvas.width=art.width;if(this.canvas.height!==art.height)this.canvas.height=art.height;gl.viewport(0,0,art.width,art.height);gl.useProgram(this.program);
  let texture=this.textures.get(art);if(!texture){texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,art);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);this.textures.set(art,texture);this.texturePixels+=art.width*art.height;while(this.textures.size>64||this.texturePixels>16777216){const [old,t]=this.textures.entries().next().value;gl.deleteTexture(t);this.texturePixels-=old.width*old.height;this.textures.delete(old);}}else{gl.bindTexture(gl.TEXTURE_2D,texture);if(art.vectorFrame!==undefined)gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,art);}
  const u=(name,v)=>gl.uniform1f(this.uniform(name),v),rgb=(name,v)=>gl.uniform3fv(this.uniform(name),v);for(let i=0;i<state.lights.length;i++){const l=state.lights[i];this.positions.set(l.position,i*4);this.colors.set(l.color,i*4);this.directions.set(l.direction,i*4);this.falloffs[i]=l.falloff;}
  gl.uniform1i(this.uniform('puppetLightCount'),state.lights.length);gl.uniform4fv(this.uniform('puppetLightPosition[0]'),this.positions);gl.uniform4fv(this.uniform('puppetLightColor[0]'),this.colors);gl.uniform4fv(this.uniform('puppetLightDirection[0]'),this.directions);gl.uniform1fv(this.uniform('puppetLightFalloff[0]'),this.falloffs);
  rgb('puppetWorldTint',(e.nightTint??[.28,.34,.5]).map(v=>1-night+linear(v)*night));rgb('puppetTint',c.tint.map(linear));u('puppetTintStrength',c.strength);rgb('puppetEmissionColor',(c.colorMode==='environment'?hex(e.lightColor):c.emissionColor).map(linear));u('puppetEmission',c.emission*(c.nightOnly?nightActivation(night):1));u('puppetRegionOnly',c.regionOnly?1:0);gl.uniform4fv(this.uniform('puppetRegion'),c.region);u('puppetMask',['all','warm','dark'].indexOf(c.mask));
  gl.uniformMatrix3fv(this.uniform('pose'),false,[world[0],world[1],0,world[2],world[3],0,world[4],world[5],1]);const s=j.sprite;gl.uniform4f(this.uniform('sprite'),-s.width*s.pivotX,-s.height*s.pivotY,s.width,s.height);gl.drawArrays(gl.TRIANGLES,0,3);this.canvas.vectorFrame=(this.outputFrame=(this.outputFrame??0)+1);return this.canvas;
 }
}
export function illuminateSprite(art,j,world,state){if(!state?.active)return art;renderer??=new Lighting2D();return renderer.draw(art,state.nodes.get(j.id)??j,spriteLightMatrix(j,world,state.time),state);}
