// Navigation context is session state. It never writes sampled poses to the project.
export function mountWorkspace({scene,native,pause,fx,project,puppetState,restorePuppet,fitPuppet=()=>{}}){
 const header=document.querySelector('.topbar'),nav=document.createElement('nav');nav.className='workspace-tabs';nav.setAttribute('aria-label','Workspace views');const puppet=document.createElement('button');puppet.id='workspace-puppet';puppet.textContent='Rig';const sceneButton=document.getElementById('scene3d-open'),gameButton=document.getElementById('native-open');sceneButton.textContent='Scene';gameButton.textContent='Little Gods integration';gameButton.hidden=true;nav.append(puppet,sceneButton,gameButton);header.querySelector('.project-title').after(nav);
 const breadcrumbs=document.createElement('nav');breadcrumbs.id='workspace-context';breadcrumbs.setAttribute('aria-label','Editing context');header.after(breadcrumbs);const preview=document.createElement('aside');preview.id='workspace-scene-context';preview.hidden=true;preview.innerHTML='<header>Scene context <span>Source changes update every instance</span></header><div></div>';document.body.append(preview);
 const back=document.createElement('button');back.id='workspace-return';back.textContent='← Return to scene';back.hidden=true;document.querySelector('.stage-toolbar').append(back);const extras=new Map();let view='puppet',editingInstance=null,transition=Promise.resolve(),stack=[],canvasHome=null;
 const label=v=>({scene:'Scene',puppet:'Rig source',artwork:'Artwork source',game:'Little Gods integration',preview:'Preview'}[v]??v);
 function capture(){if(view==='scene')return{view,...scene.selection(),face:scene.snapshot().face};if(view==='puppet')return{view,...puppetState()};return{view,...extras.get(view)?.api.snapshot?.()};}
 function context(){breadcrumbs.replaceChildren();for(const [i,c]of stack.entries()){const button=document.createElement('button');button.textContent=label(c.view)+(c.selected?' / '+(project().scene3d?.nodes.find(n=>n.id===c.selected)?.name??project().joints.find(j=>j.id===c.selected)?.name??c.selected):'');button.onclick=()=>returnTo(i);breadcrumbs.append(button,document.createTextNode(' › '));}const current=document.createElement('strong');current.textContent=label(view);breadcrumbs.append(current);const description=document.createElement('span'),state=puppetState();description.textContent=view==='puppet'?(state.mode==='rig'?'Rest pose · shared rig':'Animation · '+(project().clips.find(c=>c.id===state.clip)?.name??state.clip)):view==='scene'?(document.getElementById('s3-autokey')?.checked?'Animation key · selected instance':'Placement · selected instance'):view==='artwork'?'Shared source artwork · affects every reference':view==='game'?'Scenario playback':'';breadcrumbs.append(description);back.hidden=view!=='puppet'||!stack.length;
  const retain=stack.some(c=>c.view==='scene')&&view!=='scene',canvas=scene.runtime()?.canvas;if(retain&&canvas){if(!canvasHome){canvasHome=canvas.parentElement;preview.querySelector('div').append(canvas);canvas.style.pointerEvents='none';}preview.hidden=false;scene.contextPreview(true);}else if(canvasHome&&canvas){canvasHome.prepend(canvas);canvasHome=null;canvas.style.pointerEvents='';preview.hidden=true;scene.contextPreview(false);}document.documentElement.style.setProperty('--studio-header-height',header.getBoundingClientRect().height+breadcrumbs.getBoundingClientRect().height+'px');}
 function show(next,{drill=false}={}){if(!['puppet','scene','game'].includes(next)&&!extras.has(next))return Promise.reject(Error('Unknown workspace '+next));transition=transition.catch(()=>{}).then(async()=>{if(!drill){stack=[];editingInstance=null;}pause();if(next==='scene'&&canvasHome){const canvas=scene.runtime().canvas;canvasHome.prepend(canvas);canvasHome=null;canvas.style.pointerEvents='';preview.hidden=true;scene.contextPreview(false);}for(const [id,extra]of extras)if(id!==next)extra.api.hide();if(next!=='scene')scene.hide();if(next!=='game')native.hide();if(next==='scene')await scene.show();else if(next==='game')await native.show();if(extras.has(next))await extras.get(next).api.show();view=next;document.body.dataset.workspace=next;for(const [id,b]of [['puppet',puppet],['scene',sceneButton],['game',gameButton],...[...extras].map(([id,e])=>[id,e.button])]){b.classList.toggle('active',id===view);b.setAttribute('aria-pressed',String(id===view));}context();}).catch(error=>{console.error(error);throw error;});return transition;}
 async function restoreContext(target){
  stack=structuredClone(target.breadcrumbs??stack);editingInstance=target.editingInstance??null;await show(target.view,{drill:true});
  if(target.view==='scene'){const s=project().scene3d;if(s?.clips.some(c=>c.id===target.clip)&&target.clip!==scene.selection().clip)scene.setClip(target.clip);scene.seek(target.time??0);scene.select(s?.nodes.some(n=>n.id===target.selected)?target.selected:(s?.nodes[0]?.id??null),target.face);if(target.camera&&scene.runtime())scene.runtime().setCamera(target.camera);}
  else if(target.view==='puppet')restorePuppet(target);
  else if(target.view==='artwork')await extras.get('artwork').api.restore(target);
  context();
 }
 async function returnTo(index){const target=stack[index];if(target)await restoreContext({...target,breadcrumbs:stack.slice(0,index)})}

 puppet.onclick=()=>show('puppet');sceneButton.onclick=()=>show('scene');gameButton.onclick=()=>show('game');back.onclick=()=>returnTo(stack.length-1);document.getElementById('ng-close').addEventListener('click',()=>show('puppet'));
 document.addEventListener('keydown',e=>{if(view==='puppet'||e.target.matches('input,select,textarea')||e.target.isContentEditable)return;const key=e.key.toLowerCase();if((e.metaKey||e.ctrlKey)&&['z','s'].includes(key)){e.preventDefault();e.stopImmediatePropagation();document.getElementById(key==='s'?'save':e.shiftKey?'redo':'undo').click();}else if(view==='scene'&&!e.metaKey&&!e.ctrlKey&&!e.target.closest('button,[role=button]')){const tool={v:'translate',r:'rotate',s:'scale'}[key];if(tool){e.preventDefault();document.querySelector('#scene3d-editor [data-tool="'+tool+'"]').click();}else if(e.code==='Space'){e.preventDefault();document.getElementById('s3-play').click();}}},true);
 new ResizeObserver(()=>{document.documentElement.style.setProperty('--studio-header-height',header.getBoundingClientRect().height+breadcrumbs.getBoundingClientRect().height+'px');}).observe(header);new ResizeObserver(()=>{if(!preview.hidden){const r=preview.querySelector('div').getBoundingClientRect();scene.runtime()?.resize(r.width,r.height);}}).observe(preview);document.body.dataset.workspace=view;puppet.classList.add('active');let last='';setInterval(()=>{const key=JSON.stringify([view,puppetState().mode,puppetState().clip,project().name,document.getElementById('s3-autokey')?.checked]);if(key!==last){last=key;context();}},200);
 return{show,capture:()=>({...capture(),breadcrumbs:structuredClone(stack),editingInstance,...(view==='scene'&&scene.runtime()?{camera:scene.runtime().cameraDefinition()}:{} )}),restore:restoreContext,register(id,name,api){const button=document.createElement('button');button.id='workspace-'+id;button.textContent=name;button.onclick=()=>show(id);nav.append(button);extras.set(id,{button,api});},async editPuppet(id,clip){stack.push(capture());editingInstance=id;const instance=project().scene3d.nodes.find(n=>n.id===id),sceneTime=scene.selection().time,source=project().clips.find(c=>c.id===clip),t=Math.max(0,sceneTime-(instance?.puppet.start??0))*(instance?.puppet.speed??1)+(instance?.puppet.offset??0);restorePuppet({...puppetState(),selected:project().puppetSources?.find(s=>s.id===instance?.puppet.source)?.roots[0]??puppetState().selected,clip,time:instance?.puppet.loop!==false?t%source.duration:Math.min(source.duration,t)});await show('puppet',{drill:true});fitPuppet();},async editArtwork(id){stack.push(capture());await show('artwork',{drill:true});await extras.get('artwork').api.openAsset(id);context();},back:()=>returnTo(stack.length-1),snapshot:()=>({view,editingInstance,breadcrumbs:structuredClone(stack)})};
}
