import {actionDocument,actionTargets,actionNumericFields} from './actions.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountActions({project,context,dispatch,revision,openClip,toast}){
 const button=document.createElement('button');button.id='actions-open';button.textContent='Actions';document.getElementById('save').before(button);const panel=document.createElement('aside');panel.id='actions-panel';panel.className='author-panel';panel.hidden=true;document.body.append(panel);let selected='',stamp='';
 const run=c=>{try{const result=dispatch(c);stamp='';refresh();return result;}catch(e){toast(e.message,true);}};
 function refresh(){if(panel.hidden)return;const c=context(),p=project(),key=revision()+':'+selected+':'+c.dimension+':'+c.clip;if(key===stamp)return;stamp=key;const doc=actionDocument(p,c.dimension),clip=doc?.clips.find(x=>x.id===c.clip),list=(p.actions??[]).filter(a=>a.dimension===c.dimension);if(!list.some(a=>a.id===selected))selected=list[0]?.id??'';const a=list.find(a=>a.id===selected),fields=a?actionNumericFields(a.template):[],nodes=c.dimension===3?doc?.nodes:p.joints;
 panel.innerHTML=`<header><div><strong>Actions</strong><small>Reusable motion, effects and sound</small></div><button data-close>×</button></header><label>Name<input id="act-capture-name" value="${esc(clip?.name??'Action')}"></label><button id="act-capture" ${clip?'':'disabled'}>Capture current clip</button><h3>Action library</h3><select id="act-library">${list.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}</select>${a?`<label>Action name<input id="act-name" value="${esc(a.name)}"></label><h3>New instance</h3>${actionTargets(a).map(id=>`<label>${esc(id)}<select data-act-binding="${esc(id)}">${(nodes??[]).map(n=>`<option value="${esc(n.id)}" ${n.id===id?'selected':''}>${esc(n.name)}</option>`).join('')}</select></label>`).join('')}<button id="act-use">Add to clips</button><h3>Expose a control</h3><label>Property<select id="act-field">${fields.map((f,i)=>`<option value="${i}">${esc(f.label)}</option>`).join('')}</select></label><label>Control name<input id="act-control-name" placeholder="For example, recoil strength"></label><div class="button-row"><label>Minimum<input id="act-min" type="number" value="0"></label><label>Maximum<input id="act-max" type="number" value="10"></label></div><button id="act-expose">Expose selected property</button><p>${a.parameters.map(x=>esc(x.name)).join(' · ')}</p><button id="act-remove">Remove recipe; keep clips</button>`:''}${clip?.actionSource?`<h3>Selected clip · action controls</h3>${(p.actions.find(x=>x.id===clip.actionSource.id)?.parameters??[]).map(param=>`<label>${esc(param.name)}<input type="number" data-act-value="${esc(param.id)}" min="${param.min}" max="${param.max}" step=".01" value="${clip.actionSource.values[param.id]??param.default}"></label>`).join('')}<p>Timing 1 is the original speed. Hand-edited keys remain editable and take precedence when a control changes.</p>`:''}`;
 }
 panel.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))panel.hidden=true;const c=context(),a=project().actions?.find(x=>x.id===selected);if(b.id==='act-capture'){const id='action-'+crypto.randomUUID().slice(0,8);run({op:'action.capture',id,dimension:c.dimension,clip:c.clip,name:panel.querySelector('#act-capture-name').value});selected=id;stamp='';refresh();}if(b.id==='act-use'){const clip='action-clip-'+crypto.randomUUID().slice(0,8),bindings=Object.fromEntries([...panel.querySelectorAll('[data-act-binding]')].map(i=>[i.dataset.actBinding,i.value]));if(run({op:'action.instantiate',id:selected,clip,bindings}))openClip(clip);}if(b.id==='act-remove')run({op:'action.remove',id:selected});if(b.id==='act-expose'){const field=actionNumericFields(a.template)[+panel.querySelector('#act-field').value];run({op:'action.parameter',id:selected,value:{id:'control-'+crypto.randomUUID().slice(0,8),name:panel.querySelector('#act-control-name').value||field.label.slice(-80),kind:'number',path:field.path,default:field.value,min:+panel.querySelector('#act-min').value,max:+panel.querySelector('#act-max').value}});}};
 panel.onchange=e=>{const el=e.target,c=context();if(el.id==='act-library'){selected=el.value;stamp='';refresh();}if(el.id==='act-name')run({op:'action.rename',id:selected,name:el.value});if(el.dataset.actValue)run({op:'action.values',dimension:c.dimension,clip:c.clip,values:{[el.dataset.actValue]:+el.value}});if(el.id==='act-field'){const a=project().actions.find(x=>x.id===selected),f=actionNumericFields(a.template)[+el.value],v=f.value;panel.querySelector('#act-min').value=Math.min(0,v*2);panel.querySelector('#act-max').value=Math.max(1,v*2);}};
 button.onclick=()=>{panel.hidden=!panel.hidden;stamp='';refresh();};setInterval(refresh,200);return{show(){panel.hidden=false;stamp='';refresh();}};
}
