import {sampleKeys} from '../vector/model.js';
import {validateBezier} from './easing.js';
const hex=v=>/^#[\da-f]{6}$/i.test(v),check=(v,m)=>{if(!v)throw Error('Backdrop: '+m);};
export const backdropDefaults=()=>({version:1,enabled:true,duration:12,loop:true,sky:{enabled:true,top:'#4d6078',bottom:'#c1c3c9',horizon:.72},layers:[],tracks:[]});
export const backdropLayer=(id,asset)=>({id,name:'Image layer',asset,visible:true,opacity:1,tint:'#ffffff',position:[0,0],scale:[1,1],parallax:[.25,.1],zoom:0,drift:[0,0],repeat:[true,false],fit:'cover',blend:'source-over',tracks:[]});
const channels=['opacity','tint','position','scale','parallax','drift','zoom'];
export function validateBackdrop(p){const b=p.backdrop;if(!b)return;check(b.version===1&&typeof b.enabled==='boolean'&&typeof b.loop==='boolean','invalid settings');check(Number.isFinite(b.duration)&&b.duration>=.1&&b.duration<=600,'invalid duration');check(b.sky&&typeof b.sky.enabled==='boolean'&&hex(b.sky.top)&&hex(b.sky.bottom)&&Number.isFinite(b.sky.horizon)&&b.sky.horizon>=.05&&b.sky.horizon<=1,'invalid sky');check(Array.isArray(b.layers)&&b.layers.length<=32,'maximum 32 image layers');const ids=new Set();function value(channel,v){if(['tint','top','bottom'].includes(channel)){check(typeof v==='string'&&hex(v),'invalid colour');return;}if(['opacity','zoom','horizon'].includes(channel)){check(Number.isFinite(v)&&v>=0&&v<=1,'invalid '+channel);return;}check(Array.isArray(v)&&v.length===2&&v.every(n=>Number.isFinite(n)&&Math.abs(n)<=100),'invalid '+channel);if(channel==='scale')check(v.every(n=>n>=.01),'scale must be positive');}function tracks(list,allowed){check(Array.isArray(list)&&list.length<=16,'invalid tracks');const seen=new Set();for(const t of list){check(allowed.includes(t.channel)&&!seen.has(t.channel),'invalid or duplicate track');seen.add(t.channel);check(Array.isArray(t.keys)&&t.keys.length<=1000,'too many keys');let prev=-1;for(const k of t.keys){check(Number.isFinite(k.time)&&k.time>=0&&k.time<=b.duration&&k.time>prev,'invalid key time');prev=k.time;check(['linear','smooth','step','in-quad','out-quad','out-back','out-elastic','bezier'].includes(k.easing),'invalid easing');validateBezier(k);value(t.channel,k.value);}}}tracks(b.tracks,['top','bottom','horizon']);for(const l of b.layers){check(typeof l.id==='string'&&/^[\w.-]{1,80}$/.test(l.id)&&!ids.has(l.id),'invalid layer id');ids.add(l.id);check(typeof l.name==='string'&&l.name.length<=160&&typeof l.visible==='boolean','invalid layer');check(p.assets.some(a=>a.id===l.asset),'missing image');check(['cover','contain','stretch'].includes(l.fit)&&['source-over','screen','multiply','lighter'].includes(l.blend),'invalid fit or blend');check(Array.isArray(l.repeat)&&l.repeat.length===2&&l.repeat.every(x=>typeof x==='boolean'),'invalid repetition');for(const k of channels)value(k,l[k]);tracks(l.tracks,channels);}}
export function sampleBackdrop(b,time){if(!b?.enabled)return null;const at=b.loop?((time%b.duration)+b.duration)%b.duration:Math.max(0,Math.min(b.duration,time)),sample=(o,tracks)=>{const out={...o};for(const t of tracks)out[t.channel]=sampleKeys(t.keys,at,o[t.channel]);return out;};return{...b,sky:sample(b.sky,b.tracks),layers:b.layers.map(l=>sample(l,l.tracks))};}
export function applyBackdropCommand(p,c){const b=p.backdrop??=backdropDefaults();if(c.op==='backdrop.settings'){Object.assign(b,structuredClone(c.values));}else if(c.op==='backdrop.add'){check(!b.layers.some(l=>l.id===c.id),'duplicate layer');b.layers.push({...backdropLayer(c.id,c.asset),...structuredClone(c.values??{})});}else if(c.op==='backdrop.update'){const l=b.layers.find(l=>l.id===c.id);check(l,'missing layer');Object.assign(l,structuredClone(c.values));}else if(c.op==='backdrop.remove'){b.layers=b.layers.filter(l=>l.id!==c.id);if(p.appearance)p.appearance.bindings=p.appearance.bindings.filter(x=>x.target.kind!=='backdrop'||x.target.id!==c.id);}else if(c.op==='backdrop.order'){check(c.ids.length===b.layers.length&&new Set(c.ids).size===b.layers.length&&c.ids.every(id=>b.layers.some(l=>l.id===id)),'order must contain every layer once');b.layers=c.ids.map(id=>b.layers.find(l=>l.id===id));}else if(c.op==='backdrop.key'){const l=c.id?b.layers.find(l=>l.id===c.id):b.sky;check(l,'missing layer');const list=c.id?l.tracks:b.tracks;let t=list.find(t=>t.channel===c.channel);if(!t){t={channel:c.channel,keys:[]};list.push(t);if(c.time>0)t.keys.push({time:0,value:structuredClone(l[c.channel]),easing:'smooth'});}t.keys=t.keys.filter(k=>Math.abs(k.time-c.time)>1e-6);if(!c.remove)t.keys.push({time:c.time,value:structuredClone(c.value),easing:c.easing??'smooth',...(c.bezier?{bezier:c.bezier}:{})});t.keys.sort((a,b)=>a.time-b.time);}else throw Error('Unknown backdrop command');validateBackdrop(p);}
