import {animationTime} from '../fx/presentation.js';
import {sampleBackdrop} from './backdrop.js';
import {gestureRecorder} from './recording.js';
import {toolPoint} from '../motion-tools/core.js';
import {backdropView2D} from './backdrop-render.js';
import {canvasEditCommands,canvasValues} from './canvas-controls.js';
import {point,inverse} from '../joint-transforms.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
// Handles are DOM overlay controls. No editor adornments enter artwork or exports.
export function mountCanvasControls(host){
 const {project,context,stage,pose,camera,scene,select,pause,gesture,environment,toast}=host;
 const overlay=document.createElement('div');overlay.id='canvas-controls';overlay.className='canvas-controls';overlay.setAttribute('aria-label','Canvas property controls');document.body.append(overlay);
 const tools=document.createElement('div');tools.className='canvas-control-bar';const toggle=document.createElement('button');toggle.textContent='Canvas controls';toggle.id='canvas-controls-toggle';toggle.setAttribute('aria-pressed','true');document.querySelector('.workspace-tabs').after(toggle);
 let enabled=true,descriptors=[],drag=null,chosen=null,lastStamp='',size={width:1,height:1},sampleCache=null;
 toggle.onclick=()=>{enabled=!enabled;toggle.setAttribute('aria-pressed',String(enabled));lastStamp='';};
 function projection(c,element){const r=element.getBoundingClientRect();size=r;if(c.dimension===2){const cam=camera(),poses=pose(),local=(id,p)=>id?point(poses.get(id).world,{x:p[0],y:p[1]}):{x:p[0],y:p[1]};return{screen:(id,p)=>{const q=point(cam,local(id,p));return[q.x,q.y];},unproject:(id,xy,base)=>{const w=point(inverse(cam),{x:xy[0],y:xy[1]}),q=id?point(inverse(poses.get(id).world),w):w;return[q.x,q.y,base?.[2]??0];}};}
  const runtime=scene(),cam=runtime.camera,objects=runtime.objects;return{world:(id,xyz)=>{const v=cam.position.clone().fromArray(xyz);if(id)objects.get(id)?.localToWorld(v);return v.toArray();},local:(id,xyz)=>{const v=cam.position.clone().fromArray(xyz);if(id)objects.get(id)?.worldToLocal(v);return v.toArray();},onPlane:(xy,origin,normal)=>{const a=cam.position.clone().set(xy[0]/r.width*2-1,1-xy[1]/r.height*2,-1).unproject(cam),b=a.clone().set(xy[0]/r.width*2-1,1-xy[1]/r.height*2,1).unproject(cam),direction=b.sub(a),n=cam.position.clone().fromArray(normal),den=direction.dot(n);if(Math.abs(den)<1e-8)return origin;return a.addScaledVector(direction,cam.position.clone().fromArray(origin).sub(a).dot(n)/den).toArray();},screen:(id,p)=>{const v=cam.position.clone().fromArray(p);if(id)objects.get(id)?.localToWorld(v);v.project(cam);return[(v.x+1)*r.width/2,(1-v.y)*r.height/2,v.z];},unproject:(id,xy,base,ground=false)=>{const a=cam.position.clone().set(xy[0]/r.width*2-1,1-xy[1]/r.height*2,-1).unproject(cam),b=a.clone().set(xy[0]/r.width*2-1,1-xy[1]/r.height*2,1).unproject(cam);if(id){objects.get(id)?.worldToLocal(a);objects.get(id)?.worldToLocal(b);}const axis=ground?'y':'z',target=ground?base[1]:base[2],delta=b[axis]-a[axis];if(Math.abs(delta)<1e-8)return base;return a.add(b.sub(a).multiplyScalar((target-a[axis])/delta)).toArray();}};
 }
 function build(c,element){const key=[c.dimension,c.clip,c.time,c.mode,host.overrideRevision?.()].join(':');if(sampleCache?.project!==project()||sampleCache?.key!==key)sampleCache={project:project(),key,values:c.dimension===3?{nodes:[],backdrop:sampleBackdrop(project().backdrop,c.time)}:canvasValues(project(),c,host.overrides?.()??[])};const values=c.dimension===3?{...sampleCache.values,nodes:scene().sample?.nodes??sampleCache.values.nodes}:sampleCache.values,p=projection(c,element),out=[],add=d=>{if(d.xy.every(Number.isFinite)&&Math.abs(d.xy[0])<size.width*3&&Math.abs(d.xy[1])<size.height*3)out.push(d);};
  for(const n of values.nodes){if(n.hidden||n.visible===false)continue;const isSelected=c.selected===n.id;
   if(n.light?.enabled){const origin=n.light.offset,xy=p.screen(n.id,origin);add({id:n.id+':light',label:n.name+' · light position',glyph:'✦',xy,kind:'light',node:n.id,channel:'light.offset',value:origin,move:at=>p.unproject(n.id,at,origin)});if(isSelected){const edge=[origin[0]+n.light.range,origin[1],origin[2]],ex=p.screen(n.id,edge);add({id:n.id+':radius',label:'Light reach',glyph:'↔',xy:ex,origin:xy,ring:Array.from({length:49},(_,i)=>p.screen(n.id,[origin[0]+Math.cos(i*Math.PI/24)*n.light.range,origin[1]+Math.sin(i*Math.PI/24)*n.light.range,origin[2]])),kind:'light',node:n.id,channel:'light.range',value:n.light.range,move:at=>clamp(Math.hypot(...p.unproject(n.id,at,origin).map((v,i)=>v-origin[i])),.01,1000)});}}
   if(isSelected&&c.dimension===3)for(const [face,surface]of Object.entries(n.surfaces??{})){if(!surface.eye)continue;const e=surface.eye,[w,h,d]=n.dimensions,xy=e.center??[0,0],g=e.gaze??[0,0];const toLocal=(u,v)=>({front:[u,v,d/2],back:[-u,v,-d/2],left:[-w/2,v,u],right:[w/2,v,-u],top:[u,h/2,-v],bottom:[u,-h/2,v]}[face]);const base=toLocal(xy[0]+g[0],xy[1]+g[1]),center=p.screen(n.id,toLocal(...xy)),screen=p.screen(n.id,base),right=p.screen(n.id,toLocal(xy[0]+1,xy[1])),up=p.screen(n.id,toLocal(xy[0],xy[1]+1)),ax=[right[0]-center[0],right[1]-center[1]],ay=[up[0]-center[0],up[1]-center[1]],det=ax[0]*ay[1]-ax[1]*ay[0];if(Math.abs(det)<5)continue;
    add({id:n.id+':eye:'+face,label:'Eye gaze · '+face,glyph:'◉',xy:screen,origin:center,kind:'eye',node:n.id,face,value:g,move:at=>{const x=at[0]-center[0],y=at[1]-center[1];return[clamp((x*ay[1]-y*ay[0])/det,-2,2),clamp((y*ax[0]-x*ax[1])/det,-2,2)];}});
   }
  }
  const doc=c.dimension===3?project().scene3d:project(),clip=doc.clips.find(x=>x.id===c.clip);
  for(const t of clip?.tools?.constraints??[]){if(t.type!=='look'||t.enabled===false||t.joint!==c.selected)continue;const targetPoint=toolPoint(t,c.dimension===2?animationTime(clip,c.time):c.time),base=targetPoint.length===3?targetPoint:[...targetPoint,0],xy=p.screen(t.target,base);add({id:'target:'+t.id,label:'Look target',glyph:'◎',xy,kind:'target',targetId:t.id,node:t.joint,value:targetPoint,move:at=>p.unproject(t.target,at,base).slice(0,c.dimension)});}
  for(const e of clip?.events??[]){if(e.type!=='decal'||e.controllerOwned||c.time<e.time||c.time>=e.time+e.duration)continue;
   const base=e.origin??[0,0,0],emitter=p.world(e.node,base),contact=(scene().pipeline?.timeline??scene().effects).decals.entries.get(clip.id+':'+e.id)?.contact,center=contact?.point??emitter,normal=contact?.normal??[0,1,0],xy=p.screen(null,center),atPlane=at=>p.onPlane(at,center,normal);
   add({id:'decal:'+e.id,label:'Decal · '+(e.name??e.id)+(contact?'':' · projector (no surface hit)'),glyph:'▱',xy,kind:'decal',targetId:e.id,node:e.node,channel:'origin',value:base,move:at=>{const hit=atPlane(at);return p.local(e.node,emitter.map((v,i)=>v+hit[i]-center[i]));}});
   if(chosen==='decal:'+e.id){const seed=Math.abs(normal[0])<.8?[1,0,0]:[0,0,1],dot=seed.reduce((v,n,i)=>v+n*normal[i],0),tangent=seed.map((n,i)=>n-dot*normal[i]),len=Math.hypot(...tangent),edge=center.map((v,i)=>v+tangent[i]/len*(e.size??1)/2);
    add({id:'decal-size:'+e.id,label:'Decal size',glyph:'↔',xy:p.screen(null,edge),origin:xy,kind:'decal',targetId:e.id,node:e.node,channel:'size',value:e.size??1,move:at=>clamp(Math.hypot(...atPlane(at).map((v,i)=>v-center[i]))*2,.01,100)});
   }
  }
  const layer=values.backdrop?.layers.find(l=>chosen==='backdrop:'+l.id||environment.snapshot().visible&&environment.snapshot().selected===l.id);
  if(layer){const view=c.dimension===2?backdropView2D(camera(),size.width,size.height):(scene().backdrop?.view??{x:0,y:0}),xy=[size.width*(.5+layer.position[0]+layer.drift[0]*c.time-view.x*layer.parallax[0]),size.height*(.5+layer.position[1]+layer.drift[1]*c.time-view.y*layer.parallax[1])];add({id:'backdrop:'+layer.id,label:layer.name+' · position',glyph:'▧',xy,kind:'backdrop',targetId:layer.id,channel:'position',value:layer.position,move:at=>[layer.position[0]+(at[0]-xy[0])/size.width,layer.position[1]+(at[1]-xy[1])/size.height]});add({id:'parallax:'+layer.id,label:layer.name+' · parallax depth',glyph:'⇆',xy:[xy[0]+80+layer.parallax[0]*80,xy[1]+45],origin:xy,kind:'backdrop',targetId:layer.id,channel:'parallax',value:layer.parallax,move:at=>[clamp((at[0]-xy[0]-80)/80,0,2),clamp((at[1]-xy[1]-45)/80+layer.parallax[1],0,2)]});}
  return out;
 }
 function refresh(){const c=context(),element=stage();overlay.hidden=!enabled||!element||!['puppet','scene'].includes(c.view);if(overlay.hidden||drag)return;const r=element.getBoundingClientRect();Object.assign(overlay.style,{left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px'});try{descriptors=build(c,element);}catch{return;}const layers=project().backdrop?.layers??[],stamp=JSON.stringify([descriptors.map(d=>[d.id,d.xy.map(v=>Math.round(v)),d.value]),layers.map(l=>[l.id,l.name]),chosen]);if(stamp===lastStamp)return;lastStamp=stamp;overlay.replaceChildren();
  for(const d of descriptors){if(d.ring){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),path=document.createElementNS(svg.namespaceURI,'polyline');svg.classList.add('canvas-radius-ring');path.setAttribute('points',d.ring.map(p=>p.slice(0,2).join(',')).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#8cbbff80');path.setAttribute('stroke-dasharray','4 4');svg.append(path);overlay.append(svg);}if(d.origin){const line=document.createElement('div'),dx=d.xy[0]-d.origin[0],dy=d.xy[1]-d.origin[1];line.className='canvas-control-line';Object.assign(line.style,{left:d.origin[0]+'px',top:d.origin[1]+'px',width:Math.hypot(dx,dy)+'px',transform:`rotate(${Math.atan2(dy,dx)}rad)`});overlay.append(line);}const b=document.createElement('button');b.className='canvas-property-handle';b.dataset.handle=d.id;b.setAttribute('aria-label',d.label);b.title=d.label+' · drag to edit · Escape cancels';b.textContent=d.glyph;Object.assign(b.style,{left:d.xy[0]+'px',top:d.xy[1]+'px'});overlay.append(b);}
  if(layers.length){tools.replaceChildren();for(const l of layers){const b=document.createElement('button');b.textContent=l.name;b.dataset.background=l.id;b.title='Select background layer';b.classList.toggle('active',chosen==='backdrop:'+l.id);tools.append(b);}overlay.append(tools);}
 }
 function finish(cancel=false){if(!drag)return;const d=drag;drag=null;try{if(d.override){if(cancel||!d.moved)host.resolved.cancelGesture(d.override);else host.resolved.show(d.override.channel);}else if(cancel||!d.moved){const recording=gestureRecorder.cancel();if(recording)host.recordTime?.(recording.time);gesture.cancel();}else{const take=gestureRecorder.finish();if(take)gesture.preview([take]);gesture.commit();}if(!cancel)host.inspectTarget?.(d);}catch(e){toast(e.message,true);}lastStamp='';refresh();}
 overlay.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-handle]');if(!b||e.button!==0)return;const d=descriptors.find(d=>d.id===b.dataset.handle);if(!d)return;e.preventDefault();e.stopPropagation();pause();chosen=d.id;if(d.node)select(d.node);if(d.kind==='backdrop')environment.show(d.targetId);const c=context(),override=host.resolved?.beginGesture(c,d);if(!override)gesture.begin();const doc=c.dimension===3?project().scene3d:project(),clip=doc.clips.find(x=>x.id===c.clip),duration=d.kind==='backdrop'?project().backdrop.duration:clip.duration;if(!override&&d.kind!=='decal'&&gestureRecorder.begin({...c,duration,fps:clip.fps??30,cues:clip.cues})){c.animate=true;gestureRecorder.capture(canvasEditCommands(project(),c,{...d,id:d.targetId,value:d.value}));}drag={...d,override,context:{...c,animate:gestureRecorder.take?true:d.kind==='backdrop'?environment.snapshot().record:c.animate},rect:overlay.getBoundingClientRect(),button:b,moved:false,start:[e.clientX,e.clientY]};overlay.setPointerCapture(e.pointerId);});
 overlay.addEventListener('pointermove',e=>{if(!drag)return;const d=drag;if(Math.hypot(e.clientX-d.start[0],e.clientY-d.start[1])<2&&!d.moved)return;d.moved=true;try{const at=[e.clientX-d.rect.left,e.clientY-d.rect.top],value=d.move(at),edit={...d,id:d.targetId,value};const atTime=gestureRecorder.at(),commands=canvasEditCommands(project(),{...d.context,...(atTime!==null?{time:atTime}:{})},edit);if(d.override)host.resolved.set(d.override.context,d.override.channel,value);else gesture.preview(gestureRecorder.capture(commands));if(atTime!==null)host.recordTime?.(atTime);d.button.style.left=at[0]+'px';d.button.style.top=at[1]+'px';d.button.title=d.label+' · '+(Array.isArray(value)?value.map(n=>n.toFixed(2)).join(', '):value.toFixed(2));}catch(error){finish(true);toast(error.message,true);}});
 overlay.addEventListener('pointerup',()=>finish());overlay.addEventListener('pointercancel',()=>finish(true));overlay.addEventListener('lostpointercapture',()=>finish(true));overlay.addEventListener('click',e=>{const b=e.target.closest('[data-background]');if(b){chosen='backdrop:'+b.dataset.background;environment.show(b.dataset.background);lastStamp='';refresh();}});
 window.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){e.preventDefault();finish(true);}},true);window.addEventListener('blur',()=>finish(true));
 let last=0;function tick(now){if(now-last>50){refresh();last=now;}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 return{snapshot:()=>({enabled,dragging:!!drag,handles:descriptors.map(({id,label,kind,xy,value})=>({id,label,kind,xy,value}))}),refresh};
}
