import {ProceduralAudio} from '../scene3d/core/audio.js';

// Explicit audition only. The same shuffled variation bags are retained across
// repeated Listen clicks; closing the shelf cancels scheduled cues and voices.
export function libraryAudition(){
 const players=new Map();let timers=[],generation=0,currentItem='';
 function stop(){generation++;for(const id of timers)clearTimeout(id);timers=[];for(const {audio}of players.values())audio.stop();}
 function play(item){stop();if(currentItem!==item.id){for(const {audio}of players.values())audio.dispose();players.clear();currentItem=item.id;}const token=generation;for(const event of item.packet?.events??[]){if(!event.audio)continue;const definition=item.packet.audioLibraries[event.audio.library];if(!definition)continue;const key=item.id+':'+event.audio.library,signature=JSON.stringify(definition);let entry=players.get(key);if(entry?.signature!==signature){entry?.audio.dispose();entry={signature,audio:new ProceduralAudio(definition)};players.set(key,entry);}entry.audio.unlock();const fire=()=>{if(generation===token)entry.audio.cue(event.audio.cue,(event.audio.strength??1)*(event.amount??1));};if(event.audio.cue){if(event.time===0)fire();else timers.push(setTimeout(fire,event.time*1000));}}if(item.packet?.events.some(e=>e.type==='beam'&&e.audio)){const start=performance.now(),tick=setInterval(()=>{if(generation!==token)return;const time=(performance.now()-start)/1000,active=new Map();for(const e of item.packet.events){const age=time-e.time;if(e.type==='beam'&&e.audio&&age>=0&&age<e.duration){const charge=e.charge??1.45,fire=age>=charge;active.set(item.id+':'+e.audio.library,{state:fire?e.audio.fire:e.audio.charge,age:fire?age-charge:age/charge*(e.audio.chargeDuration??charge)});}}for(const [key,entry]of players){const value=active.get(key);entry.audio.sync(value?.state??'',value?.age??0);}if(time>item.packet.duration+.1)clearInterval(tick);},1000/60);timers.push(tick);}return item.packet?.duration??0;}
 return{play,stop,snapshot:()=>[...players.values()].map(e=>({events:[...e.audio.events],variants:[...e.audio.variants].map(([cue,v])=>({cue,index:v.last})),state:e.audio.context?.state,bed:e.audio.state})),dispose(){stop();for(const {audio}of players.values())audio.dispose();players.clear();}};
}
