import {mergeActionEdits} from './actions.js';
import {validateAudioLibrary,validateEffectLibrary} from '../scene3d/core/library-validation.js';
import {animationTime,presentationTime,validateCues} from '../fx/presentation.js';
import {ensureFX,validateFX} from '../fx/schema.js';

const copy=x=>structuredClone(x),check=(v,m)=>{if(!v)throw Error('Library: '+m);};
const displayAt=(clip,at)=>presentationTime({...clip,duration:Math.max(clip.duration,at+(clip.cues??[]).reduce((n,c)=>n+c.duration,0)+1)},at);
const audioBindingValid=(lib,e)=>!!lib&&(e.type==='sound'?!!lib.cues?.[e.audio.cue]:e.type==='beam'?[e.audio.charge,e.audio.fire].every(state=>typeof state==='string'&&Object.hasOwn(lib.states,state)):true);
const documentFor=(p,d)=>d===3?p.scene3d:p;
const eventList=(clip,d)=>d===3?clip.events:clip.cues??[];
export const isEventSource=item=>['effects','sounds'].includes(item?.category);
export function captureEvents(p,{dimension,category,clip,eventIds,emitterIds,audio}){
 const doc=documentFor(p,dimension);check(doc,'create a scene first');const source=doc.clips.find(c=>c.id===clip);
 let events;
 if(audio){const lib=doc.audioLibraries?.[audio.library]??p.scene3d?.audioLibraries?.[audio.library];check(lib?.cues?.[audio.cue],'choose an existing sound cue');const duration=Math.max(.1,...lib.cues[audio.cue].map(c=>(c.delay??0)+(c.duration??0)))*Math.max(1,...lib.variation.duration);events=[{id:'sound',type:'sound',time:0,duration,amount:1,audio:copy(audio)}];}
 else{check(source,'choose a clip');const available=eventList(source,dimension);events=eventIds?eventIds.map(id=>{const e=available.find(e=>e.id===id);check(e,'source event was removed');return e;}):available.filter(e=>!e.controllerOwned&&e.enabled!==false&&(category==='sounds'?e.type==='sound':e.type!=='sound'));check(events.every(e=>!e.controllerOwned),'controller-owned effects belong to the action source');}
 const emitters=[];if(dimension===2&&category==='effects'){const available=(source.fx??p.fx)?.emitters??[],ids=new Set(emitterIds??[]);for(const id of ids){const e=available.find(e=>e.id===id);check(e,'source emitter was removed');for(const child of [e.stepEmit,e.deathEmit].filter(Boolean))ids.add(child);emitters.push(e);}}check(events.length||emitters.length,'select authored events or particle emitters');
 check(category!=='sounds'||events.every(e=>e.type==='sound'),'sound sources contain sound events only');
 const start=Math.min(...events.map(e=>e.time),...emitters.map(e=>displayAt(source,e.delay))),packet={events:events.map(e=>{const v=copy(e);delete v.librarySource;delete v.libraryOrigins;v.time-=start;return v;}),emitters:emitters.map(e=>{const v=copy(e);delete v.librarySource;v.delay=displayAt(source,e.delay)-start;return v;}),audioLibraries:{},effectLibraries:{},assets:[]};
 packet.duration=Math.max(.05,...packet.events.map(e=>e.time+e.duration),...emitters.map(e=>displayAt(source,e.delay+e.duration+e.life[1])-start));const assets=new Set(packet.emitters.map(e=>e.asset).filter(Boolean));
 for(const e of packet.events){if(e.audio){const lib=doc.audioLibraries?.[e.audio.library]??p.scene3d?.audioLibraries?.[e.audio.library];check(audioBindingValid(lib,e),'missing sound cue or charge/fire state');packet.audioLibraries[e.audio.library]=copy(lib);}if(e.effect){check(doc.effectLibraries?.[e.effect.library],'missing effect graph');packet.effectLibraries[e.effect.library]=copy(doc.effectLibraries[e.effect.library]);}for(const asset of [e.asset,e.impactAsset,e.contact?.asset].filter(Boolean))assets.add(asset);}
 for(const id of assets){const a=p.assets.find(a=>a.id===id);check(a,'missing effect artwork');packet.assets.push(copy(a));}return packet;
}
export function validateEventSource(item){
 const b=item.packet;check(b&&Array.isArray(b.events)&&b.events.length+(b.emitters?.length??0)>0&&b.events.length<=200,'invalid effect bundle');check(Number.isFinite(b.duration)&&b.duration>0&&b.duration<=600,'invalid effect duration');const ids=new Set();
 for(const e of b.events){check(typeof e.id==='string'&&!ids.has(e.id),'duplicate event ID');ids.add(e.id);check(Number.isFinite(e.time)&&e.time>=0&&Number.isFinite(e.duration)&&e.duration>0&&e.time+e.duration<=b.duration+1e-6,'invalid event interval');if(item.category==='sounds')check(e.type==='sound','sound source contains non-sound events');if(e.audio)check(audioBindingValid(b.audioLibraries?.[e.audio.library],e),'missing sound dependency');if(e.effect)check(b.effectLibraries?.[e.effect.library],'missing effect dependency');}
 for(const lib of Object.values(b.audioLibraries??{}))validateAudioLibrary(lib);for(const lib of Object.values(b.effectLibraries??{}))validateEffectLibrary(lib);
 if(item.dimension===2){validateCues({duration:b.duration,cues:b.events});const shell={assets:b.assets??[],joints:[]};ensureFX(shell).emitters=copy(b.emitters??[]);validateFX(shell);}else check(!b.emitters?.length,'2D emitters require the 2D renderer');
}
export function eventTargets(item){return [...new Set(item.packet.events.flatMap(e=>[e.node,e.joint,e.receiver].filter(Boolean)))];}
export function validateEventLinks(p){for(const dimension of [2,3])for(const clip of documentFor(p,dimension)?.clips??[])for(const [kind,entries]of [['events',eventList(clip,dimension)],['emitters',clip.fx?.emitters??[]]])for(const e of entries){const link=e.librarySource;if(!link)continue;const item=p.library?.items.find(i=>i.id===link.id);check(isEventSource(item)&&(item.dimension===dimension||item.category==='sounds'),'missing event source');check(Number.isInteger(link.index)&&item.packet[kind]?.[link.index],'missing source event');check(typeof link.instance==='string'&&link.baseline&&Number.isFinite(link.time)&&link.time>=0,'invalid bundle link');}}
function unique(list,base){let id=base,i=2;while(list.includes(id))id=base+'-'+i++;return id;}
function importDependencies(p,item,dimension){const doc=documentFor(p,dimension),maps={assets:{},audioLibraries:{},effectLibraries:{}};
 for(const kind of ['audioLibraries','effectLibraries']){doc[kind]??={};for(const [id,value]of Object.entries(item.packet[kind]??{})){const same=Object.entries(doc[kind]).find(([,v])=>JSON.stringify(v)===JSON.stringify(value));const dest=same?.[0]??(!Object.hasOwn(doc[kind],id)?id:unique(Object.keys(doc[kind]),item.id.slice(0,48)+'-'+kind+'-'+Object.keys(maps[kind]).length));if(!same)doc[kind][dest]=copy(value);maps[kind][id]=dest;}}
 for(const a of item.packet.assets??[]){const same=p.assets.find(v=>JSON.stringify(v)===JSON.stringify(a));const dest=same?.id??(!p.assets.some(v=>v.id===a.id)?a.id:unique(p.assets.map(v=>v.id),item.id.slice(0,48)+'-art-'+Object.keys(maps.assets).length));if(!same)p.assets.push({...copy(a),id:dest});maps.assets[a.id]=dest;}return maps;
}
function compileEvent(e,bindings,maps,time,id){const out=copy(e);out.id=id;out.time+=time;for(const key of ['node','joint','receiver'])if(out[key])out[key]=Object.hasOwn(bindings,out[key])?bindings[out[key]]:out[key];if(out.audio)out.audio.library=maps.audioLibraries[out.audio.library];if(out.effect)out.effect.library=maps.effectLibraries[out.effect.library];for(const key of ['asset','impactAsset'])if(out[key])out[key]=maps.assets[out[key]];if(out.contact?.asset)out.contact.asset=maps.assets[out.contact.asset];return out;}
export function eventInstances(p,item){const groups=new Map();for(const dimension of [2,3])for(const clip of documentFor(p,dimension)?.clips??[])for(const [kind,entries]of [['events',eventList(clip,dimension)],['emitters',dimension===2?clip.fx?.emitters??[]:[]]])for(const event of entries){const s=event.librarySource;if(s?.id!==item.id)continue;const key=dimension+':'+clip.id+':'+s.instance;let group=groups.get(key);if(!group){group={id:s.instance,name:item.name,dimension,clip:clip.id,events:[],emitters:[]};groups.set(key,group);}group[kind].push(event);}return [...groups.values()];}
function emitterValues(e,maps,time,id,ids,offset=[0,0],clip){const v=copy(e);v.id=id;v.delay=animationTime(clip,time+v.delay);v.x+=offset[0];v.y+=offset[1];if(v.asset)v.asset=maps.assets[v.asset];for(const key of ['stepEmit','deathEmit'])if(v[key])v[key]=ids[v[key]];return v;}
export function placeEvents(p,item,c){const dimension=c.dimension??item.dimension;check(dimension===item.dimension||item.category==='sounds','use the matching renderer for visual effects');const doc=documentFor(p,dimension),clip=doc?.clips.find(x=>x.id===c.clip);check(clip,'choose a destination clip');check(Number.isFinite(c.time??0)&&(c.time??0)>=0&&(c.time??0)<=clip.duration,'place inside the clip');const events=dimension===3?clip.events:clip.cues??(clip.cues=[]),start=c.time??0,bindings=copy(c.bindings??{});check(!events.some(e=>e.librarySource?.instance===c.instance),'duplicate effect instance');
 check(typeof c.instance==='string'&&/^[a-zA-Z0-9][\w.-]{0,63}$/.test(c.instance),'invalid effect instance ID');for(const [a,b]of Object.entries(bindings))check([a,b].every(v=>typeof v==='string'&&/^[a-zA-Z0-9][\w.-]{0,79}$/.test(v)&&!['__proto__','prototype','constructor'].includes(v)),'invalid target binding');
 const maps=importDependencies(p,item,dimension);for(let index=0;index<item.packet.events.length;index++){const id=c.instance+'-'+index;check(!events.some(e=>e.id===id),'duplicate event ID');const event=compileEvent(item.packet.events[index],bindings,maps,start,id);event.librarySource={id:item.id,revision:item.revision,instance:c.instance,index,bindings,time:start,baseline:copy(event)};events.push(event);}
 if(item.packet.emitters?.length){if(!clip.fx&&p.fx)clip.fx=copy(p.fx);const fx=ensureFX(clip),ids=Object.fromEntries(item.packet.emitters.map((e,i)=>[e.id,c.instance+'-emitter-'+i])),anchor=item.packet.emitters[0],offset=c.position?[c.position[0]-anchor.x,c.position[1]-anchor.y]:[0,0];for(let index=0;index<item.packet.emitters.length;index++){const source=item.packet.emitters[index],id=ids[source.id];check(!fx.emitters.some(e=>e.id===id),'duplicate emitter ID');const e=emitterValues(source,maps,start,id,ids,offset,clip);e.librarySource={id:item.id,revision:item.revision,instance:c.instance,index,bindings,time:start,offset,emitterIds:ids,baseline:copy(e)};fx.emitters.push(e);}}
 clip.duration=Math.max(clip.duration,start+item.packet.duration,...(clip.fx?.emitters??[]).map(e=>displayAt(clip,e.delay+e.duration+e.life[1])));return c.instance;
}
export function unlinkEvents(group){for(const e of [...group.events,...group.emitters])delete e.librarySource;}
export function updateEventInstances(p,item){const groups=eventInstances(p,item);for(const kind of ['events','emitters'])for(const group of groups){const clip=documentFor(p,group.dimension).clips.find(c=>c.id===group.clip),maps=importDependencies(p,item,group.dimension);for(const event of group[kind]){const link=event.librarySource,source=item.packet[kind][link.index];check(source,'source topology changed; capture a new source');const next=kind==='events'?compileEvent(source,link.bindings,maps,link.time,event.id):emitterValues(source,maps,link.time,event.id,link.emitterIds,link.offset,clip),current=copy(event);delete current.librarySource;const result=mergeActionEdits(link.baseline,current,next);result.librarySource={...link,revision:item.revision,baseline:copy(next)};const list=kind==='events'?eventList(clip,group.dimension):clip.fx.emitters;list[list.indexOf(event)]=result;clip.duration=Math.max(clip.duration,kind==='events'?result.time+result.duration:displayAt(clip,result.delay+result.duration+result.life[1]));}}}
export function eventPreview(p,item){const doc=documentFor(p,item.dimension),clip={id:unique(doc.clips.map(c=>c.id),'library-event-preview'),name:item.name,duration:Math.max(1,item.packet.duration+.4),loop:true,tracks:item.dimension===3?[]:{},...(item.dimension===3?{events:[]}:{fps:30,cues:[]})};if(item.dimension===2){if(p.fx)clip.fx=copy(p.fx);ensureFX(clip).emitters=[];}doc.clips.push(clip);placeEvents(p,item,{dimension:item.dimension,clip:clip.id,instance:'preview-event',time:.15});return{project:p,clip:clip.id};}
