import {constraintStrength,constraintValue} from '../constraints/model.js';
import {joystickChannels,sourceClipIds} from '../joysticks/model.js';
import {finalChannels,channelOverrides} from './resolved-channels.js';
import {animationTime} from '../fx/presentation.js';
import {influence} from '../motion-tools/core.js';
import {faceControlStack} from '../scene3d/core/facial-control.js';
export function propertyDrivers(project,{dimension=2,selected,clip:clipId,time=0,asset,shape,mode}={},runtime){const document=dimension===3?project.scene3d:project,clip=document?.clips.find(c=>c.id===clipId)??document?.clips[0],rows=[],add=(channel,owner,extra={})=>rows.push({channel,owner,...extra});if(!clip)return rows;const node=(dimension===3?document.nodes:project.joints).find(n=>n.id===selected);
 if(asset){const a=project.assets.find(a=>a.id===asset);for(const t of a?.vector?.tracks??[])if(!shape||t.shape===shape)add(t.channel,'Artwork keyframes',{end:a.vector.duration,detail:a.vector.loop?'Repeats with artwork':'Holds final key'});for(const b of project.appearance?.bindings??[])if(b.target.asset===asset&&(!shape||b.target.shape===shape))add(b.target.channel,'Style · '+(project.appearance.variants.find(v=>v.id===project.appearance.active)?.name??''),{detail:'Base colour; keyed colours take precedence'});return rows;}
 if(!node)return rows;if(dimension===2&&mode==='rig'){add('Transform','Rig rest pose',{detail:'Shared base; animation is not applied in Rig setup'});return rows;}if(dimension===2){if(clip.tracks[selected]?.length)add('Transform',clip.ik?.[selected]?'IK target keyframes':'Keyframes',{end:clip.duration});for(const [end,chain]of Object.entries(clip.ik??{}))if([end,chain.root,chain.mid].includes(selected))add('Position / rotation','IK chain',{detail:'Target: '+end,end:clip.duration});for(const e of clip.effects??[])if(e.enabled!==false&&e.joint===selected&&time>=(e.delay??0)&&time<(e.delay??0)+(e.span??clip.duration))add('Transform',e.type+' motion',{start:e.delay??0,end:(e.delay??0)+(e.span??clip.duration)});for(const t of clip.lightingTracks??[])if(t.node===selected)add(t.channel,'Light keyframes',{end:clip.duration});if(node.visual?.motion?.enabled)add('Transform','Secondary dynamics',{detail:'Layered over the sampled pose'});}
 else{for(const t of clip.tracks)if(t.node===selected)add(t.channel,t.controllerOwned?'Action controller':t.program?'Expression program':'Keyframes',{end:t.controllerOwned?undefined:clip.duration,detail:t.controllerOwned?'Releases at the controller state transition':undefined});const actor=runtime?.pipeline?.actors.get(selected);if(actor)for(const channel of actor.machine.writes??[])add(channel,'Controller · '+actor.machine.data.state,{detail:'Live state owns this channel until its transition'});for(const e of faceControlStack(clip.events,selected,time)){const c=e.faceControl??{open:'clip',tilt:'clip',gaze:[0,0],blink:false},remaining=e.time+e.duration-time;for(const channel of ['open','tilt','gaze','blink'])if(c[channel]!==undefined)add('eye.'+channel,e.name??e.id,{start:e.time,end:e.time+e.duration,blend:c.release??0,priority:c.priority??0,detail:c.release&&remaining<c.release?'Handing back to the independent face':'Overrides independent facial movement',control:{kind:'face',id:e.id}});}}
 if(dimension===2)for(const c of project.constraints??[])if(c.type==='followPath'&&c.node===selected&&constraintStrength(c,clip,time)>0){const extra={constraint:c.id,detail:'Target: '+(project.joints.find(j=>j.id===c.target)?.name??c.target)+' · '+Math.round(constraintStrength(c,clip,time)*100)+'% strength'};add('position','Follow Path constraint',extra);if(constraintValue(c,clip,time,'orient'))add('rotation','Follow Path constraint',extra);}
 if(dimension===2&&!sourceClipIds(project).has(clip.id))for(const j of project.joints)for(const [axis,a]of Object.entries(j.joystick?.axes??{}))if(a)for(const c of joystickChannels(project.clips.find(c=>c.id===a.clip)))if(c.node===selected)add(c.channel,'Joystick · '+j.name+' / '+axis.toUpperCase(),{detail:'Edit its source timeline or animate the joystick handle'});
 for(const group of ['layers','follow','constraints'])for(const tool of clip.tools?.[group]??[]){if(tool.joint!==selected&&!tool.joints?.includes(selected)&&!Object.hasOwn(tool.values??{},selected)&&![tool.chain?.root,tool.chain?.mid].includes(selected))continue;const weight=influence(tool,time,clip.duration);if(!weight)continue;add(group==='constraints'?(tool.type==='look'?'rotation':'position'):group==='follow'?'rotation':'Transform',tool.name??tool.type??group,{start:tool.start??0,end:tool.end??clip.duration,blend:tool.blend??0,detail:Math.round(weight*100)+'% influence',control:{kind:'tool',group,id:tool.id}});}
 for(const b of project.appearance?.bindings??[])if((b.target.kind=== (dimension===3?'node':'joint'))&&b.target.id===selected)add(b.target.channel,'Style · '+(project.appearance.variants.find(v=>v.id===project.appearance.active)?.name??'Project style'),{detail:'Base value before animation'});for(const t of finalChannels(clip,dimension===2?animationTime(clip,time):time,channelOverrides.values({dimension,clip:clip.id})))if(t.node===selected)add(t.channel,t.owner,{id:t.id,final:true,start:t.start,end:t.end,detail:'Final local output; original drivers continue underneath'});if(!rows.length)add('Transform',dimension===3?'Instance placement':'Rig rest pose',{detail:'No animation currently drives this selection'});return rows;}
export function applyOwnershipCommand(p,c){const doc=c.dimension===3?p.scene3d:p,clip=doc?.clips.find(x=>x.id===c.clip);if(!clip)throw Error('Missing ownership clip');if(c.op!=='ownership.handover')throw Error('Unknown ownership command');if(c.target.kind==='face'){const e=clip.events?.find(e=>e.id===c.target.id);if(!e?.faceControl&&!e?.lockFace)throw Error('This event has no facial ownership');e.faceControl??={open:'clip',tilt:'clip',gaze:[0,0],blink:false};for(const k of ['start','end','blend','priority'])if(c[k]!==undefined&&!Number.isFinite(c[k]))throw Error('Invalid handover');const end=c.end??e.time+e.duration;e.time=c.start??e.time;e.duration=end-e.time;if(c.blend!==undefined)e.faceControl.release=c.blend;if(c.priority!==undefined)e.faceControl.priority=c.priority;if(c.channels)for(const [key,enabled]of Object.entries(c.channels)){if(!['open','tilt','gaze','blink'].includes(key))throw Error('Unknown face channel');if(!enabled)delete e.faceControl[key];else e.faceControl[key]??=key==='blink'?false:'clip';}}else if(c.target.kind==='tool'){const tool=clip.tools?.[c.target.group]?.find(t=>t.id===c.target.id);if(!tool)throw Error('Missing motion tool');for(const key of ['start','end'])if(c[key]!==undefined)tool[key]=c[key];if(c.blend!==undefined)tool.blend=c.blend;}else throw Error('Unknown owner');}

// Map concrete inspector paths onto runtime channels rather than guessing from labels.
export function driversForField(rows,path,dimension=2){
 const channel=dimension===2&&['x','y','rotation','scaleX','scaleY'].includes(path)?path: path.replace(/\.\d+$/,'');
 const transform=dimension===2?['x','y','rotation','scaleX','scaleY'].includes(channel):['position','rotation','scale'].includes(channel);
 return rows.filter(r=>r.channel===channel||r.channel===path||transform&&(r.channel==='Transform'||r.channel==='Position / rotation'&&['x','y','rotation','position'].includes(channel)||r.channel==='position'&&['x','y'].includes(channel)||r.channel==='rotation'&&channel==='rotation'));
}
export function ownershipSource(row,context){
 if(row.constraint)return{kind:'constraint',id:row.constraint,...context};
 if(row.final)return {kind:row.owner==='Baked keys'?'track':'override',...context,channel:row.channel,id:row.id};
 if(row.control)return{kind:row.control.kind==='face'?'event':'tool',id:row.control.id,...context};
 if(/controller/i.test(row.owner))return{kind:'controller',...context};
 if(/Style/.test(row.owner))return{kind:'style',...context};
 if(/Artwork/.test(row.owner))return{kind:'artwork',...context,channel:row.channel};
 if(/keyframes|program/i.test(row.owner))return{kind:'track',...context,channel:row.channel};
 if(/IK|motion|dynamics/i.test(row.owner))return{kind:'motion',...context};
 return{kind:'rest',...context};
}
