import {appearanceState} from './appearance.js';
import {ProceduralAudio} from '../scene3d/core/audio.js';
import {validateAudioLibrary} from '../scene3d/core/library-validation.js';
export function soundDefaults({frequency=220,duration=.25,volume=.12,spread=.6}={}){if(![frequency,duration,volume,spread].every(Number.isFinite)||frequency<20||frequency>8000||duration<.02||duration>8||volume<0||volume>1||spread<0||spread>12)throw Error('Invalid sound controls');return{volume:.7,compressor:{threshold:-18,knee:20,ratio:4,attack:.004,release:.2},noise:{seconds:2,seed:31,multiplier:1664525,increment:1013904223},voice:{noiseRateBase:.9,noiseRateSpread:.2,noiseQ:.7,toneQ:.5,attack:.008,tail:.02,noiseOffset:.3,stopSmoothing:.02,stopTail:.08},variation:{semitones:[-spread,spread*.5,spread,0],tones:[.95,1.05,1,.98],pitchJitter:[-.05,.05],gain:[.92,1],duration:[.95,1.05],toneJitter:[.97,1.03],ring:[.9,1],phase:[0,6.28],pulse:[.98,1.02],drift:[.9,1.1],delay:[.95,1.05]},cueVariation:{repeatWindow:.1,repeatGain:.75,bassThreshold:140,tonePitchBase:.99,tonePitchSpread:.02,ringThreshold:500,minimumDelay:0,delayJitter:.005},cues:{play:[{kind:'tone',type:'sine',frequency,end:frequency*.6,duration,gain:volume,delay:0}]},states:{},beds:{}};}
export function validateSound(p){for(const lib of Object.values(p.audioLibraries??{}))validateAudioLibrary(lib);for(const c of p.clips)for(const e of c.cues??[])if(e.type==='sound'){const lib=p.audioLibraries?.[e.audio?.library]??p.scene3d?.audioLibraries?.[e.audio?.library];if(!lib?.cues[e.audio?.cue])throw Error('Sound cue needs an authored audio library and cue');}}
export function applySoundCommand(p,c){const doc=c.dimension===3?p.scene3d:p;if(!doc)throw Error('Create a scene first');if(c.op==='audio.library'){if(!/^[\w.-]{1,80}$/.test(c.id)||['constructor','prototype','__proto__'].includes(c.id))throw Error('Invalid sound library ID');validateAudioLibrary(c.value);doc.audioLibraries??={};doc.audioLibraries[c.id]=structuredClone(c.value);return c.id;}throw Error('Unknown sound command');}
export class ClipAudio{
 constructor(){this.entries=new Map();this.previous=-1e-6;this.clip='';}
 begin(clip,time=0){this.stop();this.clip=clip.id;this.previous=time-1e-6;}
 sync(project,clip,time,{audible=false}={}){if(!audible){this.stop();return;}if(this.clip!==clip.id||time<this.previous){this.stop();this.clip=clip.id;}for(const event of clip.cues??[]){if(event.type!=='sound'||event.enabled===false||event.time<=this.previous||event.time>time)continue;const b=event.audio,library=project.voiceOverrides?.[b.library]??appearanceState(project).variant?.voices?.[b.library]??b.library,definition=project.audioLibraries?.[library]??project.scene3d?.audioLibraries?.[library];if(!definition)continue;const signature=JSON.stringify(definition);let entry=this.entries.get(b.library);if(!entry||entry.signature!==signature){entry?.audio.dispose();entry={signature,audio:new ProceduralAudio(definition)};this.entries.set(b.library,entry);}entry.audio.unlock();entry.audio.cue(b.cue,(b.strength??1)*(event.amount??1));}this.previous=time;this.clip=clip.id;}
 stop(){for(const e of this.entries.values())e.audio.stop();this.previous=-1e-6;this.clip='';}
 dispose(){for(const e of this.entries.values())e.audio.dispose();this.entries.clear();}
}
