import test from 'node:test';
import assert from 'node:assert/strict';
import {visemeWeights,speechAt,validateSpeech} from '@shapeshift-labs/studio-core/speech';
import {execute,emptyProject} from '../fx/commands.js';
import {poseAt,identity,validateProject,bakeMotion} from '../runtime.js';
import {ProjectStore} from '../store.js';
import {applyCommand} from '../fx/commands.js';
import {timelineRows} from './timeline.js';
import {SpeechAudio} from './speech-audio.js';
function fixture(){const p=emptyProject('Speech test');p.clips[0].duration=6;p.clips[0].loop=false;p.assets=['closed','open'].map(id=>({id,src:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><circle cx="5" cy="5" r="4"/></svg>')}));p.joints.push({id:'mouth',name:'Mouth',parent:'root',rest:identity(),layer:1,sprite:{asset:'closed',width:10,height:10,pivotX:.5,pivotY:.5}});return execute(p,[{op:'speech.chunk',id:'hello',value:{src:'data:audio/wav;base64,AAAA',duration:1,cues:[{start:.1,end:.3,pose:'MBP'},{start:.3,end:.7,pose:'AI'}]}},{op:'speech.rig',id:'frog',value:{poses:{rest:{artwork:{mouth:'closed'}},MBP:{artwork:{mouth:'closed'}},AI:{artwork:{mouth:'open'},values:{mouth:{y:4,scaleY:1.2}}}}}},{op:'speech.place',id:'line',clip:'effect',chunk:'hello',rig:'frog',time:1}]).project;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('speech selects explicit artwork and smooths pose offsets without mutating rest artwork',()=>{const p=fixture(),c=p.clips[0];assert.equal(speechAt(p,c,1.2).artwork.mouth,'closed');assert.equal(speechAt(p,c,1.5).artwork.mouth,'open');near(poseAt(p,c,1.5).get('mouth').transform.y,4);near(poseAt(p,c,1.5).get('mouth').transform.scaleY,1.2);assert.equal(p.joints[1].sprite.asset,'closed');near(poseAt(p,c,2).get('mouth').transform.y,0);assert.equal(speechAt(p,c,1.9).artwork.mouth,'closed');});
test('coarticulation weights normalize and silence returns to rest',()=>{const cues=[{start:.1,end:.3,pose:'MBP'},{start:.3,end:.5,pose:'AI'}];for(let t=-.1;t<.8;t+=.001){const w=visemeWeights(cues,t);near(Object.values(w).reduce((a,b)=>a+b,0),1);assert.ok(Object.values(w).every(n=>n>=0&&n<=1));}assert.deepEqual(visemeWeights(cues,.9),{rest:1});});
test('rate and placement share cue timing, invalid edits roll back, undo/redo preserve dialogue',()=>{const s=new ProjectStore(fixture()),edit=c=>s.edit(p=>applyCommand(p,c));edit({op:'speech.place',id:'line',clip:'effect',chunk:'hello',rig:'frog',time:2,rate:2});assert.equal(speechAt(s.project,s.project.clips[0],2.25).artwork.mouth,'open');const before=JSON.stringify(s.project);assert.throws(()=>edit({op:'speech.place',id:'overlap',clip:'effect',chunk:'hello',rig:'frog',time:2.1}),/overlap/);assert.equal(JSON.stringify(s.project),before);s.undo();assert.equal(s.project.clips[0].dialogue[0].time,1);s.redo();assert.equal(s.project.clips[0].dialogue[0].time,2);validateProject(JSON.parse(JSON.stringify(s.project)));});
test('shared timeline retimes audio and visemes together and removes a chunk',()=>{const p=fixture();const row=timelineRows(p,{clip:'effect'}).find(r=>r.speech);const moved=execute(p,{op:'timeline.edit',clip:'effect',keys:[{row:row.id,id:'line'}],delta:1,scale:2,pivot:1}).project;assert.equal(moved.clips[0].dialogue[0].rate,.5);assert.equal(speechAt(moved,moved.clips[0],3).artwork.mouth,'open');const removed=execute(moved,{op:'timeline.edit',clip:'effect',keys:[{row:row.id,id:'line'}],remove:true}).project;assert.equal(removed.clips[0].dialogue.length,0);});
test('validation rejects bad cues, missing joints and out-of-range chunks',()=>{for(const mutate of [p=>p.speech.chunks.hello.cues[0].end=10,p=>p.speech.rigs.frog.poses.AI.artwork.bad='open',p=>p.clips[0].dialogue[0].time=6,p=>p.speech.chunks.hello.cues[0].pose='unknown']){const p=fixture();mutate(p);assert.throws(()=>validateSpeech(p),/Speech/);}});
function fake(){let decodes=0;const starts=[],stops=[];const ctx={currentTime:10,destination:{},resume:async()=>{},close:async()=>{},decodeAudioData:async()=>{decodes++;return{duration:1};},createGain:()=>({gain:{value:1},connect(){},disconnect(){}}),createBufferSource:()=>({playbackRate:{value:1},connect(){},disconnect(){},start(...args){starts.push({args,rate:this.playbackRate.value});},stop(){stops.push(1);}})};return{ctx,starts,stops,decodes:()=>decodes};}
test('recording scheduler uses seek offsets/rates, caches decode, and stops stale playback',async()=>{const p=fixture(),c=p.clips[0],f=fake(),audio=new SpeechAudio({contextFactory:()=>f.ctx,fetchAudio:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(2)})});await audio.start(p,c,1.5);assert.deepEqual(f.starts[0],{args:[10,.5,.5],rate:1});await audio.start(p,c,0);assert.deepEqual(f.starts[1].args,[11,0,1]);assert.equal(f.decodes(),1);c.dialogue[0].rate=2;await audio.start(p,c,1.25);assert.equal(f.starts[2].rate,2);near(f.starts[2].args[1],.5);audio.stop();assert.equal(audio.clock,null);assert.equal(f.stops.length,3);});
test('stopping while decode is pending prevents late speech',async()=>{const p=fixture(),f=fake();let finish;const gate=new Promise(r=>finish=r);const audio=new SpeechAudio({contextFactory:()=>f.ctx,fetchAudio:async()=>{await gate;return{ok:true,arrayBuffer:async()=>new ArrayBuffer(2)};}});const task=audio.start(p,p.clips[0],0);audio.stop();finish();await task;assert.equal(f.starts.length,0);});
test('baking motion keeps dialogue live without doubling speech offsets',()=>{const p=fixture(),c=p.clips[0],before=poseAt(p,c,1.5).get('mouth').transform.y;bakeMotion(p,c);near(poseAt(p,c,1.5).get('mouth').transform.y,before);assert.equal(c.dialogue.length,1);});
test('slow preview scales scheduled audio and chunk rate together',async()=>{const p=fixture(),f=fake(),audio=new SpeechAudio({contextFactory:()=>f.ctx,fetchAudio:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(2)})});await audio.start(p,p.clips[0],0,.5);assert.deepEqual(f.starts[0],{args:[12,0,1],rate:.5});audio.dispose();});

test('speech scales compose with authored scale and joint deletion prunes bindings',async()=>{const {removeJoint}=await import('../runtime.js');const p=fixture();p.joints[1].rest.scaleY=2;near(poseAt(p,p.clips[0],1.5).get('mouth').transform.scaleY,2.4);removeJoint(p,'mouth');assert.doesNotThrow(()=>validateProject(p));assert.deepEqual(p.speech.rigs.frog.poses.AI.artwork,{});});
test('portable exports embed linked recordings once without modifying the source',async()=>{const {portableProject}=await import('./project-transfer.js');const p=fixture();p.speech.chunks.hello.src='./hello.wav';p.speech.chunks.again=structuredClone(p.speech.chunks.hello);let fetches=0;const out=await portableProject(p,{baseURL:'https://example.test/studio/',fetcher:async url=>{assert.equal(url,'https://example.test/studio/hello.wav');fetches++;return{ok:true,blob:async()=>new Blob(['audio'])};},encode:async()=> 'data:audio/wav;base64,AAAA'});assert.equal(fetches,1);assert.equal(out.speech.chunks.hello.src,'data:audio/wav;base64,AAAA');assert.equal(p.speech.chunks.hello.src,'./hello.wav');});
