import {VISEMES,speechAt} from '@shapeshift-labs/studio-core/speech';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=s=>(s.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,40)||'speech')+'-'+crypto.randomUUID().slice(0,8);
export function mountSpeech({project,context,dispatch,toast,pause,seek,revision=()=>0}){
 const button=document.createElement('button');button.id='speech-open';button.textContent='Speech';document.getElementById('sound-open').after(button);
 const panel=document.createElement('aside');panel.id='speech-panel';panel.className='author-panel';panel.hidden=true;document.body.append(panel);let chunkId='',rigId='',audioFile=null;
 const $=id=>panel.querySelector('#'+id),json=v=>JSON.stringify(v,null,2),choices=(map,value)=>Object.entries(map??{}).map(([id,v])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(v.name??id)}</option>`).join('');
 function render(){const p=project(),c=context(),clip=p.clips.find(e=>e.id===c.clip),chunks=p.speech?.chunks??{},rigs=p.speech?.rigs??{};chunkId=chunks[chunkId]?chunkId:Object.keys(chunks)[0]??'';rigId=rigs[rigId]?rigId:Object.keys(rigs)[0]??'';
  panel.innerHTML=`<header><strong>Speech & mouth poses</strong><button data-close aria-label="Close speech">×</button></header>${c.dimension===3?'<p>Open a 2D puppet clip to author dialogue. The shared sampler can also be used by game code.</p>':`<p>Recorded chunks, timed mouth drawings and authored pose offsets. Audio and animation use the same chunk times.</p>
  <h3>1 · Voice chunk</h3><label>Chunk<select id="sp-chunk"><option value="">New chunk</option>${choices(chunks,chunkId)}</select></label><label>Name<input id="sp-name" value="${esc(chunks[chunkId]?.name??'New line')}"></label><label>Audio file<input id="sp-file" type="file" accept="audio/*"></label><small id="sp-file-state">${chunkId?'Existing audio is embedded or linked.':'Choose a recording; it is embedded when saved.'}</small><label>Timed visemes · seconds<textarea id="sp-cues" rows="7" spellcheck="false">${esc(json(chunks[chunkId]?.cues??[{start:.1,end:.25,pose:'MBP'},{start:.25,end:.65,pose:'AI'}]))}</textarea></label><p>Paste aligned cues from your voice pipeline. Each needs start, end and pose. An empty list plays audio with the rest pose; this tool does not transcribe recordings.</p><button id="sp-save-chunk">Save chunk</button>
  <h3>2 · Character binding</h3><label>Rig<select id="sp-rig"><option value="">New binding</option>${choices(rigs,rigId)}</select></label><label>Binding name<input id="sp-rig-name" value="${esc(rigs[rigId]?.name??'Character voice')}"></label><label>Mouth joint<select id="sp-joint">${p.joints.filter(j=>j.sprite).map(j=>`<option value="${esc(j.id)}">${esc(j.name??j.id)}</option>`).join('')}</select></label><button id="sp-template">Create mouth binding template</button><label>Pose bindings · JSON<textarea id="sp-binding" rows="12" spellcheck="false">${esc(json(rigs[rigId]??{attack:.035,release:.055,poses:{rest:{},MBP:{},AI:{},E:{},O:{},U:{},FV:{},L:{}}}))}</textarea></label><p>artwork maps joint IDs to registered asset IDs. values maps joints to x, y, rotation, scaleX or scaleY offsets (scale uses 1 as neutral). Map several visemes to one drawing with map. Only the strongest drawing is shown; transform values blend.</p><details><summary>Available artwork IDs</summary><p>${p.assets.map(a=>esc(a.id)+' — '+esc(a.name??a.id)).join('<br>')}</p></details><button id="sp-save-rig">Save binding</button>
  <h3>3 · Place on this clip</h3><label>Playback rate<input id="sp-rate" type="number" min=".25" max="4" step=".05" value="1"></label><label>Volume<input id="sp-gain" type="number" min="0" max="2" step=".05" value=".72"></label><button id="sp-add" ${chunkId&&rigId?'':'disabled'}>Add chunk at playhead</button><p>Clip length: ${clip?.duration??0}s. Chunks on the same rig cannot overlap.</p><div>${(clip?.dialogue??[]).map(e=>`<div class="sp-event"><button data-seek="${e.time}">${esc(chunks[e.chunk]?.name??e.chunk)} · ${e.time.toFixed(2)}s</button><button data-remove="${esc(e.id)}" aria-label="Remove ${esc(e.chunk)}">×</button></div>`).join('')}</div><output id="sp-active">Ready</output>`}`;
 }
 async function readAudio(file){if(file.size>15*1024*1024)throw Error('Use a chunk smaller than 15 MB');const bytes=await file.arrayBuffer(),ctx=new AudioContext();try{const buffer=await ctx.decodeAudioData(bytes.slice(0)),rate=60,count=Math.ceil(buffer.duration*rate),envelope=Array.from({length:count},(_,i)=>{let peak=0;for(let c=0;c<buffer.numberOfChannels;c++){const data=buffer.getChannelData(c);for(let s=Math.floor(i*buffer.sampleRate/rate);s<Math.min(data.length,Math.ceil((i+1)*buffer.sampleRate/rate));s++)peak=Math.max(peak,Math.abs(data[s]));}return +peak.toFixed(4);});const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read recording'));r.readAsDataURL(file);});return{src,duration:buffer.duration,envelope,envelopeRate:rate};}finally{await ctx.close();}}
 panel.onchange=e=>{if(e.target.id==='sp-chunk'){chunkId=e.target.value;audioFile=null;renderChunk();}if(e.target.id==='sp-rig'){rigId=e.target.value;const r=project().speech?.rigs?.[rigId];$('sp-rig-name').value=r?.name??'Character voice';$('sp-binding').value=json(r??{poses:{rest:{}}});}if(e.target.id==='sp-file'){audioFile=e.target.files[0];$('sp-file-state').textContent=audioFile?.name??'Choose a recording';}};
 function renderChunk(){const c=project().speech?.chunks?.[chunkId];$('sp-name').value=c?.name??'New line';$('sp-cues').value=json(c?.cues??[]);$('sp-file-state').textContent=c?'Existing recording selected.':'Choose a recording';$('sp-file').value='';$('sp-add').disabled=!(chunkId&&rigId);}
 panel.onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close')){panel.hidden=true;return;}try{
  if(b.id==='sp-save-chunk'){pause();b.disabled=true;const before=revision(),name=$('sp-name').value,cues=JSON.parse($('sp-cues').value),selectedChunk=chunkId,old=project().speech?.chunks?.[chunkId],audio=audioFile?await readAudio(audioFile):old;if(before!==revision())throw Error('Project changed while loading the recording. Save the chunk again.');if(!audio)throw Error('Choose an audio file');const id=selectedChunk||key(name);dispatch({op:'speech.chunk',id,value:{...audio,name,cues}});chunkId=id;audioFile=null;render();toast('Speech chunk saved');}
  if(b.id==='sp-template'){const joint=$('sp-joint').value,j=project().joints.find(j=>j.id===joint);if(!j)throw Error('Choose a mouth joint');$('sp-binding').value=json({attack:.035,release:.055,poses:Object.fromEntries(VISEMES.map(v=>[v,{artwork:{[joint]:j.sprite.asset},values:{}}]))});}
  if(b.id==='sp-save-rig'){pause();const id=rigId||key($('sp-rig-name').value);dispatch({op:'speech.rig',id,value:{...JSON.parse($('sp-binding').value),name:$('sp-rig-name').value}});rigId=id;render();toast('Speech binding saved');}
  if(b.id==='sp-add'){pause();dispatch({...context(),op:'speech.place',id:key('line'),chunk:chunkId,rig:rigId,rate:+$('sp-rate').value,gain:+$('sp-gain').value});render();}
  if(b.dataset.remove){pause();dispatch({...context(),op:'speech.remove',id:b.dataset.remove});render();}
  if(b.dataset.seek!==undefined){pause();seek(+b.dataset.seek);}
 }catch(error){toast(error.message,true);}finally{b.disabled=false;}};
 button.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)render();};
 const timer=setInterval(()=>{if(panel.hidden||!$('sp-active'))return;const c=context(),clip=project().clips.find(e=>e.id===c.clip);$('sp-active').textContent=speechAt(project(),clip,c.time).active.map(e=>`${e.chunk}: ${e.viseme} · ${e.time.toFixed(2)}s`).join(' / ')||'Rest / silence';},100);
 return{show(){panel.hidden=false;render();},hide(){panel.hidden=true;},snapshot(){const c=context();return speechAt(project(),project().clips.find(e=>e.id===c.clip),c.time);},dispose(){clearInterval(timer);panel.remove();button.remove();}};
}
