import test from 'node:test';import assert from 'node:assert/strict';
import {shapeRecipe,partDefaults,makeField,recipeBounds,traceField,meshField,meshOBJ,validateRecipe,sampleRecipe,validateBakedMesh} from './model.js';
import {sampleShape,vectorBake,animatedSVG,bakeTimes} from './bake.js';
import {svgParts} from './svg-import.js';
import {ProjectStore} from '../store.js';import {validateProject,identity} from '../runtime.js';import {applyCommand} from '../fx/commands.js';import {sampleVector,validateVector} from '../vector/model.js';import {createSceneSampler} from '../scene3d/animation.js';import {timelineRows,applyTimelineCommand} from '../authoring/timeline.js';
const project=()=>({format:'inkwell-puppet',version:1,name:'Shape lab test',assets:[],joints:[{id:'root',name:'Root',parent:null,layer:0,rest:identity()}],clips:[{id:'idle',name:'Idle',duration:2,fps:24,loop:true,tracks:{}}]}),near=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
function single(dimension=2,type='ball'){const r=shapeRecipe('test',dimension);r.parts=[{...partDefaults('a'),type}];r.tracks=[];return r;}
function bake(r,times=[0]){const bounds=recipeBounds(r),frames=times.map(t=>sampleShape(r,t,{bounds}));return{times,frames,...(r.dimension===2?{vector:vectorBake(r,frames,times)}:{})};}
test('SDF primitives have correct signs and smooth booleans merge, subtract and intersect',()=>{for(const dim of [2,3]){const r=single(dim);near(makeField(r)(.7,0,0),0);assert.ok(makeField(r)(0,0,0)<0);for(const type of ['box','capsule','ring']){r.parts[0].type=type;assert.ok(Number.isFinite(makeField(r)(.5,0,0)));}r.parts[0].type='ball';r.parts.push({...partDefaults('b'),radius:.3,operation:'subtract'});r.blend=0;assert.ok(makeField(r)(0,0,0)>0);assert.ok(makeField(r)(.5,0,0)<0);r.parts[1].operation='intersect';assert.ok(makeField(r)(.5,0,0)>0);}const r=shapeRecipe();r.tracks=[];r.blend=0;assert.ok(makeField(r)(0,0)>0);r.blend=1;assert.ok(makeField(r)(0,0)<0);});
test('metaball field adds influence and ignores Z in 2D',()=>{const r=single();r.mode='metaballs';near(makeField(r)(.7,0),0);r.parts.push({...partDefaults('b')});assert.ok(makeField(r)(.8,0)<0);near(makeField(r)(.8,0,100),makeField(r)(.8,0,0));});
test('2D contour extraction preserves holes and disconnected islands with bounded error',()=>{const r=single();r.blend=0;r.parts.push({...partDefaults('hole'),operation:'subtract',radius:.3});const field=makeField(r),rings=traceField(field,recipeBounds(r),128);assert.equal(rings.length,2);for(const ring of rings)for(const p of ring)assert.ok(Math.abs(field(...p))<.015);r.parts[1]={...partDefaults('other'),position:[2,0,0]};assert.equal(traceField(makeField(r),recipeBounds(r),128).length,2);assert.deepEqual(traceField(()=>1,{min:[-1,-1,0],max:[1,1,0],size:2},32),[]);});
test('3D extraction has finite outward normals and closed shared edges',()=>{const r=single(3),mesh=meshField(makeField(r),recipeBounds(r),20);validateBakedMesh(mesh);assert.ok(mesh.indices.length>100);const edges=new Map();for(let i=0;i<mesh.indices.length;i+=3)for(let j=0;j<3;j++){const a=mesh.indices[i+j],b=mesh.indices[i+(j+1)%3],key=a<b?a+':'+b:b+':'+a;edges.set(key,(edges.get(key)??0)+1);}assert.ok([...edges.values()].every(n=>n===2));for(let i=0;i<mesh.positions.length;i+=3){const p=mesh.positions.slice(i,i+3),n=mesh.normals.slice(i,i+3);assert.ok(p.reduce((s,v,j)=>s+v*n[j],0)>0);near(Math.hypot(...n),1);}assert.match(meshOBJ(mesh),/^#.*\nv /);assert.equal((meshOBJ(mesh).match(/^f /gm)??[]).length,mesh.indices.length/3);});
test('authored animation is stateless, deterministic and bounded for the whole motion',()=>{const r=shapeRecipe(),before=JSON.stringify(r),bounds=recipeBounds(r);for(const t of [0,1,2,1,0]){const sample=sampleRecipe(r,t);if(t===1)assert.deepEqual(sample.parts[1].position,[.1,.25,0]);for(const p of sample.parts)for(let i=0;i<2;i++)assert.ok(p.position[i]-p.radius>bounds.min[i]&&p.position[i]+p.radius<bounds.max[i]);}assert.equal(JSON.stringify(r),before);});
test('recipe commands support undo, retiming, JSON round trips and invalid-edit rollback',()=>{const store=new ProjectStore(project()),edit=c=>store.edit(p=>applyCommand(p,c));edit({op:'shapeLab.create',id:'blobs',dimension:3});edit({op:'shapeLab.key',id:'blobs',part:'a',channel:'radius',time:1,value:.9});edit({op:'shapeLab.settings',id:'blobs',values:{duration:4}});assert.equal(store.project.shapeLab.recipes[0].tracks.at(-1).keys[0].time,2);store.undo();assert.equal(store.project.shapeLab.recipes[0].duration,2);store.redo();validateProject(JSON.parse(JSON.stringify(store.project)));const before=JSON.stringify(store.project);assert.throws(()=>edit({op:'shapeLab.part',id:'blobs',part:'a',values:{radius:-1}}));assert.equal(JSON.stringify(store.project),before);});
test('2D animation bake preserves split/merge topology as editable opacity-swapped vectors',()=>{const r=shapeRecipe(),result=bake(r,[0,1,2]);validateVector(result.vector);assert.equal(result.vector.shapes.length,3);for(const [time,index]of [[0,0],[.99,0],[1,1],[1.99,1],[2,0]]){const visible=sampleVector(result.vector,time).filter(s=>s.opacity>0);assert.equal(visible.length,1);assert.equal(visible[0].id,'frame-'+index);}const xml=animatedSVG(result.vector);assert.equal((xml.match(/<animate /g)??[]).length,3);assert.match(xml,/calcMode="discrete"/);assert.match(xml,/fill-rule="evenodd"/);});
test('2D bake adds a separate SVG and clip, preserves source and supports undo/redo',()=>{const store=new ProjectStore(project()),r=shapeRecipe();store.edit(p=>applyCommand(p,{op:'shapeLab.create',id:r.id,value:r}));let output;store.edit(p=>output=applyCommand(p,{op:'shapeLab.bake',id:r.id,result:bake(r,[0,1,2])}));assert.ok(store.project.assets.find(a=>a.id===output.asset).vector);assert.equal(store.project.shapeLab.recipes[0].id,r.id);assert.equal(store.project.joints.length,2);store.undo();assert.equal(store.project.assets.length,0);store.redo();validateProject(JSON.parse(JSON.stringify(store.project)));});
test('3D bake inserts native meshes and step visibility keys with exactly one active frame',()=>{const p=project(),r=shapeRecipe('solid',3);r.resolution=16;applyCommand(p,{op:'shapeLab.create',id:r.id,value:r});const output=applyCommand(p,{op:'shapeLab.bake',id:r.id,result:bake(r,[0,1,2])});validateProject(p);const material=p.scene3d.materials.at(-1);assert.equal(material.shading,'svg');assert.equal(material.strokeStyle,'freehand');assert.equal(material.creases,false);assert.equal(material.palette[0],r.color);assert.equal(material.outlineUnits,'world');const sampler=createSceneSampler(p.scene3d);for(const [time,index]of [[0,0],[.5,0],[1,1],[1.5,1],[2,2],[0,0]]){const visible=sampler.sample(output.clip,time).nodes.filter(n=>n.type==='mesh'&&n.visible===true);assert.equal(visible.length,1);assert.ok(visible[0].id.endsWith('-'+index));}sampler.dispose();const row=timelineRows(p,{dimension:3,clip:output.clip}).find(r=>r.channel==='visible');assert.ok(row.boolean&&row.numericBoolean);applyTimelineCommand(p,{dimension:3,clip:output.clip,op:'timeline.edit',keys:[{row:row.id,time:0}],value:0});validateProject(p);applyCommand(p,{op:'scene3d.key',clip:output.clip,node:row.node,channel:'visible',time:0,value:.3,easing:'linear'});assert.throws(()=>validateProject(p),/visibility/);});
test('SVG outlines become signed regions and extruded 3D volumes with holes',()=>{const r=single(),v={viewBox:[0,0,100,100],shapes:[{id:'ring',name:'Ring',fill:'#fff',opacity:1,hidden:false,fillRule:'evenodd',commands:['M','L','L','L','Z','M','L','L','L','Z'],points:[0,0,100,0,100,100,0,100,30,30,70,30,70,70,30,70]}]};r.parts=svgParts(v);assert.equal(svgParts(v,[],3)[0].contours[0][0][1],1.5);validateRecipe(r);let f=makeField(r);assert.ok(f(0,0)>0);assert.ok(f(1,0)<0);r.dimension=3;f=makeField(r);assert.ok(f(1,0,0)<0);assert.ok(f(1,0,1)>0);assert.ok(f(0,0,0)>0);});
test('3D SVG projection is a filled silhouette and baking budgets reject oversized animation',()=>{const r=single(3);r.resolution=16;const frame=sampleShape(r,0,{projection:true});assert.equal(frame.rings.length,1);validateVector(vectorBake(r,[frame],[0]));r.duration=10;r.fps=30;assert.throws(()=>bakeTimes(r,true),/96/);assert.throws(()=>validateBakedMesh({positions:[Infinity,0,0],normals:[1,0,0],indices:[0,0,0]}));});
test('baked native mesh animations are reusable library characters',async()=>{const {libraryPreviewProject}=await import('../authoring/library.js'),p=project(),r=shapeRecipe('library-solid',3);r.resolution=12;applyCommand(p,{op:'shapeLab.create',id:r.id,value:r});const baked=applyCommand(p,{op:'shapeLab.bake',id:r.id,result:bake(r,[0,1,2])});applyCommand(p,{op:'library.capture',id:'solid-source',dimension:3,category:'characters',node:baked.node,name:'Merging solid'});const preview=libraryPreviewProject(p,p.library.items[0]);validateProject(preview.project);applyCommand(p,{op:'library.place',id:'solid-source',instance:'copy-solid',position:[3,0,0]});validateProject(p);const copy=p.scene3d.nodes.find(n=>n.id==='copy-solid'),clip=copy.librarySource.motion.bindings[baked.clip],sampler=createSceneSampler(p.scene3d),frame=sampler.sample(clip,1);assert.equal(frame.nodes.filter(n=>n.parent===copy.id&&n.type==='mesh'&&n.visible===true).length,1);sampler.dispose();});
