import {hybridWalkerProject} from './hybrid-walker.js';
import {mountMovementEditor} from './movement-editor.js';
import {mountTrackingEditor} from './tracking-editor.js';
import {emptyProcedural3D} from '@shapeshift-labs/studio-core/procedural3d/model';
import {primitiveWalkerScene,primitiveTrackingScene,primitiveSeekingScene} from '@shapeshift-labs/studio-core/procedural3d/builders';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountSceneProcedural(host){
 const button=document.createElement('button');button.id='s3-procedural-open';button.textContent='Procedural';host.panel.querySelector('header').append(button);
 const panel=document.createElement('aside');panel.className='s3-procedural';panel.hidden=true;host.panel.append(panel);
 const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./procedural3d/editor.css',document.baseURI).href;document.head.append(css);
 panel.innerHTML=`<header><strong>3D chains & contacts</strong><button data-close>×</button></header><p>Drive primitives, SVGs and puppet pieces with reaching, following or stepping chains.</p><details open><summary>Editable primitive walker</summary><label>Leg count<input data-legs type="number" min="4" max="16" step="2" value="8"></label><button data-study>Open 3D walker study</button><button data-hybrid-study>Open mesh & puppet walker</button><button data-tracking-study>Open head & eyes study</button><button data-seeking-study>Open target-following study</button></details><details open><summary>Add a chain</summary><label>Root object<select data-root></select></label><label>Target object<select data-target></select></label><label>Motion<select data-mode><option value="reach">Reach target</option><option value="follow">Follow target</option><option value="step">Step on terrain</option></select></label><label>Links<input data-count type="number" value="2" min="1" max="24"></label><label>Link spacing (metres)<input data-length type="number" value="1" min=".01" max="20" step=".1"></label><label>Primitive<select data-primitive><option>cylinder</option><option>box</option><option>cone</option></select></label><button data-add>Build editable links</button></details><details open><summary>Chain settings</summary><select data-chain aria-label="3D chain"></select><div data-chain-fields></div><button data-remove>Release chain</button></details><details><summary>Terrain primitives</summary><div data-terrains></div><button data-terrain-save>Use checked terrain</button></details><details><summary>Gait groups</summary><p>Legs in one group lift together. Groups take turns.</p><div data-groups></div><button data-gait-save>Apply groups</button></details><details><summary>Body support</summary><label>Body object<select data-body></select></label><div data-support-legs></div><label>Support up (world XYZ)<input data-up value="0, 1, 0"></label><label>Clearance (metres)<input data-height type="number" min="0" max="100" step=".1" value="1.6"></label><label>Response<input data-response type="number" min=".01" max="100" step="1" value="10"></label><label>Maximum tilt (degrees)<input data-tilt type="number" min="0" max="90" value="35"></label><button data-body-save>Support this body</button><button data-body-remove>Remove body support</button></details><p data-status role="status"></p>`;
 const $=name=>panel.querySelector('[data-'+name+']'),scene=()=>host.scene(),config=()=>scene()?.procedural??emptyProcedural3D();let chainId=null,bodyId=null,trackingControls,movementControls;
 const run=fn=>async()=>{try{host.pause();await fn();await host.refresh();refresh();$('status').textContent='Saved to the scene.';}catch(e){$('status').textContent=e.message;host.toast(e.message,true);}};
 const save=fn=>{const value=structuredClone(config());fn(value);return host.dispatch({op:'scene3d.settings',values:{procedural:value}});};
 const options=(value,blank='')=>(blank?`<option value="">${blank}</option>`:'')+scene().nodes.map(n=>`<option value="${esc(n.id)}" ${n.id===value?'selected':''}>${esc(n.name)} (${esc(n.id)})</option>`).join('');
 function refresh(){if(panel.hidden||!scene())return;trackingControls?.refresh();movementControls?.refresh();const p=config(),root=$('root').value,target=$('target').value;$('root').innerHTML=options(root||host.selected(),'Create a root marker');$('target').innerHTML=options(target,'Create a target marker');if(!p.chains.some(c=>c.id===chainId))chainId=p.chains[0]?.id;
  $('chain').innerHTML=p.chains.map(c=>`<option value="${esc(c.id)}" ${c.id===chainId?'selected':''}>${esc(c.id)}</option>`).join('');const c=p.chains.find(c=>c.id===chainId);
  $('chain-fields').innerHTML=c?`<label>Motion<select data-edit="mode">${['reach','follow','step'].map(m=>`<option ${m===c.mode?'selected':''}>${m}</option>`).join('')}</select></label><label>Root<select data-edit="root">${options(c.root)}</select></label><label>Target<select data-edit="target">${options(c.target)}</select></label><label>Knee direction (local XYZ)<input data-edit="pole" value="${(c.pole??[0,1,0]).join(', ')}"></label><label>Link lengths (metres)<input data-edit="lengths" value="${c.lengths.join(', ')}"></label><label>Piece length axis<select data-edit="axis">${['x','y','z'].map(a=>`<option ${a===(c.axis??'y')?'selected':''}>${a}</option>`).join('')}</select></label>${c.mode==='step'?[['Stride threshold','stepDistance',.35],['Foot lift','stepHeight',.3],['Step seconds','stepDuration',.25],['Overshoot','overshoot',.4],['Contact range','reach',5]].map(([label,key,fallback])=>`<label>${label}<input type="number" step=".05" data-edit="${key}" value="${c[key]??fallback}"></label>`).join('')+`<label>Contact direction (world XYZ)<input data-edit="direction" value="${(c.direction??[0,-1,0]).join(', ')}"></label><label>Foot orientation<select data-edit="footOrientation">${[['preserve','Keep artwork rotation'],['target','Turn toward target rotation'],['terrain','Align to terrain']].map(([value,label])=>`<option value="${value}" ${value===(c.footOrientation??'preserve')?'selected':''}>${label}</option>`).join('')}</select></label><label>Foot up axis (local XYZ)<input data-edit="footUp" value="${(c.footUp??[0,1,0]).join(', ')}"></label>`:''}<details><summary>Bind primitive, SVG or puppet pieces</summary><p>For puppet links, choose Fit to dimensions. Face camera around Y keeps a Y-axis link visible while retaining its endpoints.</p>${c.segments.map((id,i)=>`<label>Link ${i+1}<select data-link="${i}">${options(id)}</select></label>`).join('')}${c.joints?.length?`<label>Foot / end piece<select data-foot>${options(c.joints.at(-1))}</select></label>`:''}</details>`:'';
  $('terrains').innerHTML=scene().nodes.filter(n=>['box','sphere','cylinder','cone','plane'].includes(n.type)).map(n=>`<label class="check"><input type="checkbox" data-terrain value="${esc(n.id)}" ${p.terrains.includes(n.id)?'checked':''}>${esc(n.name)}</label>`).join('');
  const steps=p.chains.filter(c=>c.mode==='step'),groups=p.gaits.flatMap(g=>g.groups);$('groups').innerHTML=steps.map(c=>`<label>${esc(c.id)}<select data-group="${esc(c.id)}"><option value="0">Independent</option>${Array.from({length:8},(_,i)=>`<option value="${i+1}" ${groups.findIndex(g=>g.includes(c.id))===i?'selected':''}>Group ${i+1}</option>`).join('')}</select></label>`).join('');
  if(!scene().nodes.some(n=>n.id===bodyId))bodyId=p.bodies[0]?.node??host.selected();$('body').innerHTML=options(bodyId);bodyId=$('body').value;const b=p.bodies.find(b=>b.node===bodyId);$('support-legs').innerHTML=steps.map(c=>`<label class="check"><input type="checkbox" data-support-leg value="${esc(c.id)}" ${b?.chains.includes(c.id)?'checked':''}>${esc(c.id)}</label>`).join('');if(b){$('up').value=(b.up??[0,1,0]).join(', ');$('height').value=b.height;$('response').value=b.response??10;$('tilt').value=(b.maxTilt??.7)*180/Math.PI;}
 }
 const show=()=>{panel.hidden=false;refresh();};button.onclick=()=>panel.hidden?show():panel.hidden=true;$('close').onclick=()=>panel.hidden=true;
 const openStudy=async(kind='walker')=>{host.pause();await host.study(kind==='hybrid'?hybridWalkerProject(host.project()):kind==='seeking'?primitiveSeekingScene():kind==='tracking'?primitiveTrackingScene():primitiveWalkerScene({legs:Number($('legs').value)}));show();};$('study').onclick=run(()=>openStudy());$('hybrid-study').onclick=run(()=>openStudy('hybrid'));$('tracking-study').onclick=run(()=>openStudy('tracking'));$('seeking-study').onclick=run(()=>openStudy('seeking'));
 $('add').onclick=run(async()=>{chainId='chain-'+crypto.randomUUID().slice(0,6);await host.dispatch({op:'scene3d.procedural.build',values:{id:chainId,root:$('root').value||undefined,target:$('target').value||undefined,count:Number($('count').value),length:Number($('length').value),primitive:$('primitive').value,mode:$('mode').value}});});
 $('chain').onchange=()=>{chainId=$('chain').value;refresh();};$('body').onchange=()=>{bodyId=$('body').value;refresh();};
 panel.addEventListener('change',e=>{const el=e.target;if(el.dataset.edit)run(()=>save(p=>{const c=p.chains.find(c=>c.id===chainId),key=el.dataset.edit;c[key]=['pole','lengths','direction','footUp'].includes(key)?el.value.split(',').map(Number):['mode','root','target','axis','footOrientation'].includes(key)?el.value:Number(el.value);if(key==='mode'&&c.mode!=='step')c.footOrientation='preserve';}))();if(el.hasAttribute('data-foot'))run(()=>save(p=>{const c=p.chains.find(c=>c.id===chainId);c.joints[c.joints.length-1]=el.value;}))();if(el.dataset.link!==undefined)run(()=>save(p=>{p.chains.find(c=>c.id===chainId).segments[Number(el.dataset.link)]=el.value;}))();});
 $('remove').onclick=run(()=>save(p=>{p.chains=p.chains.filter(c=>c.id!==chainId);p.gaits=p.gaits.map(g=>({...g,groups:g.groups.map(a=>a.filter(id=>id!==chainId)).filter(a=>a.length)})).filter(g=>g.groups.length);p.bodies=p.bodies.map(b=>({...b,chains:b.chains.filter(id=>id!==chainId)})).filter(b=>b.chains.length);}));
 $('terrain-save').onclick=run(()=>save(p=>{p.terrains=[...panel.querySelectorAll('[data-terrain]:checked')].map(e=>e.value);}));
 $('gait-save').onclick=run(()=>save(p=>{const groups=Array.from({length:8},()=>[]);for(const el of panel.querySelectorAll('[data-group]'))if(Number(el.value))groups[Number(el.value)-1].push(el.dataset.group);p.gaits=groups.some(g=>g.length)?[{id:'gait',groups:groups.filter(g=>g.length)}]:[];}));
 $('body-save').onclick=run(()=>save(p=>{const chains=[...panel.querySelectorAll('[data-support-leg]:checked')].map(e=>e.value);p.bodies=[...p.bodies.filter(b=>b.node!==bodyId),{node:bodyId,chains,height:Number($('height').value),response:Number($('response').value),maxTilt:Number($('tilt').value)*Math.PI/180,maxOffset:3,up:$('up').value.split(',').map(Number)}];}));
 $('body-remove').onclick=run(()=>save(p=>{p.bodies=p.bodies.filter(b=>b.node!==bodyId);}));
 movementControls=mountMovementEditor(panel,{host,run,save,options,config});
 trackingControls=mountTrackingEditor(panel,{host,run,save,options,config});
 return {show,refresh,openStudy};
}
