import {featureCatalog,queryCatalog,expandRecipe} from '@shapeshift-labs/studio-core/catalog';
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults=r=>Object.fromEntries(Object.entries(r.inputSchema.properties).filter(([,v])=>Object.hasOwn(v,'default')).map(([k,v])=>[k,v.default]));
export function mountCatalogue(element,{siteRoot,onOpen,initial='',onSelect=()=>{}}){
 let selected=initial;const categories=[...new Set(featureCatalog.features.map(f=>f.category))];
 element.classList.add('feature-catalogue');
 element.innerHTML=`<header class="fc-heading"><div><p class="fc-eyebrow">SHAPESHIFT STUDIO · CORE + WEB</p><h1>What do you want to make?</h1><p>Explore every tool, find its requirements, and try an example.</p></div></header><div class="fc-search"><label>Find a feature<input type="search" aria-label="Find a feature" placeholder="Try lip sync, potion, mesh, export…"></label><label>Category<select aria-label="Feature category"><option value="">All categories</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><label>Available in<select aria-label="Feature scope"><option value="">Core + Web</option><option value="web">Web editor</option><option value="core">Core library</option></select></label></div><div class="fc-summary"><span role="status" aria-live="polite"></span><a href="${new URL('features/catalog.json',siteRoot)}" target="_blank" rel="noopener">Catalogue JSON</a><a href="${new URL('docs/features.md',siteRoot)}" target="_blank" rel="noopener">Full guide</a></div><div class="fc-layout"><nav aria-label="Features"></nav><article class="fc-detail" aria-label="Feature details"></article></div>`;
 const search=element.querySelector('input'),[category,scope]=element.querySelectorAll('select'),list=element.querySelector('nav'),detail=element.querySelector('article'),status=element.querySelector('[role=status]');
 function show(f){
  if(!f){detail.innerHTML='<h2>No matching features</h2><p>Try a broader term or clear the filters.</p>';return;}
  selected=f.id;onSelect(f.id);const recipes=featureCatalog.recipes.filter(r=>r.feature===f.id);
  detail.innerHTML=`<p class="fc-eyebrow">${esc(f.category)} · ${esc(f.scope.join(' + '))}</p><h2>${esc(f.title)}</h2><p class="fc-description">${esc(f.description)}</p><div class="fc-links">${f.panel&&onOpen?'<button data-open-tool>Open tool</button>':`<a href="${new URL('puppet-studio/index.html?features='+encodeURIComponent(f.id),siteRoot)}" target="_blank" rel="noopener">Open in Studio ↗</a>`}<a href="${esc(f.documentation)}" target="_blank" rel="noopener">Documentation ↗</a>${f.examples.map(ex=>`<a href="${new URL(ex.url,siteRoot)}" target="_blank" rel="noopener">${esc(ex.title)} ↗</a>`).join('')}</div><h3>Before you start</h3><ul>${f.requirements.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${f.limitations.length?`<h3>Supported limits</h3><ul>${f.limitations.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}${f.coreExports.length?`<details><summary>Use from Core · ${f.coreExports.length} imports</summary><pre>${esc(f.coreExports.map(p=>'@shapeshift-labs/studio-core'+p.slice(1)).join('\n'))}</pre></details>`:''}${f.commands.length?`<details><summary>Authoring commands · ${f.commands.length}</summary><p>Available through document.dispatch. Recipes below supply tested requests for common tasks.</p><pre>${esc(f.commands.join('\n'))}</pre></details>`:''}${(f.codeExamples??[]).map(ex=>`<h3>${esc(ex.title)}</h3><pre>${esc(ex.code)}</pre>`).join('')}${recipes.length?'<h3>Try it with an agent</h3><p>Build requests using your project IDs. Nothing runs until you explicitly dispatch them. Inputs are validated; the project store checks references and context.</p>':''}${recipes.map(r=>`<details class="fc-recipe" data-recipe="${r.id}"><summary>${esc(r.title)}</summary><ul>${[...r.requirements,...r.notes].map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>Offline: <code>npm run studio -- recipe ${esc(r.id)}</code></p><details><summary>Input schema · JSON Schema</summary><pre>${esc(JSON.stringify(r.inputSchema,null,2))}</pre></details><label>Recipe inputs<textarea aria-label="${esc(r.title)} inputs" spellcheck="false">${esc(JSON.stringify(defaults(r),null,2))}</textarea></label><button data-build>Build requests</button><button data-copy>Copy requests</button><p role="status" class="fc-recipe-status"></p><pre class="fc-requests">${esc(JSON.stringify(expandRecipe(r.id).requests,null,2))}</pre></details>`).join('')}`;
  detail.querySelector('[data-open-tool]')?.addEventListener('click',()=>onOpen(f));
 }
 function filter(){const result=queryCatalog({query:search.value,category:category.value||undefined,scope:scope.value||undefined});status.textContent=`${result.total} of ${featureCatalog.features.length} features`;list.replaceChildren();for(const f of result.features){const button=document.createElement('button');button.type='button';button.innerHTML=`<span>${esc(f.category)}</span><strong>${esc(f.title)}</strong>`;button.dataset.feature=f.id;button.setAttribute('aria-pressed',String(f.id===selected));button.onclick=()=>{for(const b of list.children)b.setAttribute('aria-pressed',String(b===button));show(f);detail.scrollTop=0;};list.append(button);}const current=result.features.find(f=>f.id===selected)??result.features[0];show(current);for(const b of list.children)b.setAttribute('aria-pressed',String(b.dataset.feature===selected));}
 detail.addEventListener('click',async event=>{const button=event.target.closest('[data-build],[data-copy]');if(!button)return;const box=button.closest('[data-recipe]'),status=box.querySelector('.fc-recipe-status');try{const requests=expandRecipe(box.dataset.recipe,JSON.parse(box.querySelector('textarea').value)).requests,text=JSON.stringify(requests,null,2);box.querySelector('.fc-requests').textContent=text;if(button.hasAttribute('data-copy')){await navigator.clipboard.writeText(text);status.textContent='Requests copied. No changes made.';}else status.textContent='Requests ready. No changes made.';}catch(error){box.querySelector('.fc-requests').textContent='';status.textContent=error.message;}});
 search.addEventListener('input',filter);category.addEventListener('change',filter);scope.addEventListener('change',filter);filter();
 return{focus:()=>search.focus(),select(id){selected=id;search.value='';category.value='';scope.value='';filter();}};
}
