import {activeSolo} from './model.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountSolos({project,context,revision,dispatch,pause,select,seek,toast,example}){
 const button=document.createElement('button');button.id='solos-open';button.textContent='Solos';document.getElementById('motion-tools').before(button);
 const panel=document.createElement('aside');panel.id='solos-panel';panel.className='author-panel';panel.setAttribute('aria-label','Solo groups');panel.hidden=true;document.body.append(panel);let stamp='';
 const style=document.createElement('style');style.textContent='#solos-panel .solo-choice{display:flex;align-items:center;gap:8px;flex-direction:row}#solos-panel .solo-choice input{width:auto;margin:0}.solo-radio{display:inline-block;padding:3px;cursor:pointer}';document.head.append(style);
 const options=(nodes,id)=>nodes.map(n=>`<option value="${esc(n.id)}" ${n.id===id?'selected':''}>${esc(n.name)}</option>`).join('');
 function run(c){try{pause();const a=context(),id=dispatch({node:a.selected,clip:a.clip?.id,time:a.time,...c});if(['solo.create','solo.wrap'].includes(c.op))select(id);stamp='';refresh();}catch(e){toast(e.message,true);}}
 function refresh(){if(panel.hidden)return;const a=context(),key=[revision(),a.dimension,a.selected,a.mode,a.time].join(':');if(stamp===key)return;stamp=key;const nodes=project().joints,n=nodes.find(n=>n.id===a.selected),children=nodes.filter(j=>j.parent===n?.id),siblings=nodes.filter(j=>j.parent===n?.parent),selected=n?.solo?activeSolo(n,a.mode==='rig'?null:a.clip,a.time):null,keys=a.clip?.soloTracks?.find(t=>t.node===n?.id)?.keys??[];
 panel.innerHTML=`<header><div><strong>Solo groups</strong><small>${a.mode==='rig'?'Rig defaults':'Hold keys · '+a.time.toFixed(2)+'s'}</small></div><button data-action="close" aria-label="Close Solos">×</button></header><button data-action="example">Load Solo example</button>${a.dimension!==2?'<p>Author Solos in a 2D rig. They also play in 3D puppet layers.</p>':`<p>A Solo shows one child branch at a time. Child groups can contain complete rigs, SVGs, or images.</p><label>Working on<select id="solo-owner">${options(nodes,n?.id)}</select></label>${n?.solo?`<h3>Active child</h3>${[{id:'',name:'None'},...children].map(child=>`<label class="solo-choice"><input type="radio" name="solo-child" data-child="${esc(child.id)}" ${child.id===(selected??'')?'checked':''}>${esc(child.name)}</label>`).join('')}<p>${a.mode==='rig'?'Select a child to change the default.':'Select a child to record an instant switch at the playhead.'} The rig default applies before the first key.</p><button data-action="disable">Convert to ordinary group</button><h3>Selection keys</h3>${keys.map(k=>`<div class="button-row"><button data-seek="${k.time}">${k.time.toFixed(3)}s · ${esc(nodes.find(n=>n.id===k.value)?.name??'None')}</button><button data-delete="${k.time}" aria-label="Delete Solo key">×</button></div>`).join('')||'<p>No keys in this clip.</p>'}<button data-action="timeline">Edit keys in Timeline</button>`:`<button data-action="enable" ${n?.sprite?'disabled':''}>Make this group a Solo</button>`}<section><h3>Wrap sibling pieces</h3><p>Select pieces under the same parent. Their transforms and animations are preserved.</p>${siblings.map(j=>`<label class="solo-choice"><input type="checkbox" data-wrap="${esc(j.id)}" ${j.id===n?.id?'checked':''}>${esc(j.name)}</label>`).join('')}<button data-action="wrap">Wrap in Solo</button><button data-action="create">Create empty Solo under selected item</button><p>Use a piece’s Parent field to move it into an existing Solo.</p></section>`}`;
 }
 panel.onchange=e=>{if(e.target.id==='solo-owner'){pause();select(e.target.value);stamp='';refresh();}};
 panel.onclick=async e=>{if(e.target.matches('[data-child]')){run({op:context().mode==='rig'?'solo.default':'solo.key',child:e.target.dataset.child||null});return;}const b=e.target.closest('button');if(!b)return;const action=b.dataset.action;if(action==='close')panel.hidden=true;if(action==='example'){await example();stamp='';refresh();}if(action==='wrap')run({op:'solo.wrap',children:[...panel.querySelectorAll('[data-wrap]:checked')].map(el=>el.dataset.wrap)});if(action==='create')run({op:'solo.create',parent:context().selected});if(action==='enable'||action==='disable')run({op:'solo.'+action});if(action==='timeline')document.getElementById('timeline-open').click();if(b.dataset.delete!==undefined)run({op:'solo.key',time:+b.dataset.delete,remove:true});if(b.dataset.seek!==undefined){pause();seek(+b.dataset.seek);stamp='';refresh();}};
 const show=()=>{panel.hidden=false;stamp='';refresh();};button.onclick=()=>panel.hidden?show():panel.hidden=true;setInterval(refresh,120);return{show,hide(){panel.hidden=true;}};
}
